- keras/callbacks.py
- tests/keras/test_callbacks.py
Google Doc: https://docs.google.com/document/d/1FvMlmW9diNaKJ988njcXEqb862kZUpGmLWzEvla3_FA/edit?usp=sharing
> New Callback: EarlyBaselineStopping

- keras/backend/cntk_backend.py
- keras/backend/tensorflow_backend.py
- keras/backend/theano_backend.py
- tests/keras/backend/backend_test.py
- tests/keras/layers/convolutional_test.py
This PR adds the missing `separable_conv1d` for Theano and CNTK.
> Add `separable_conv1d`

- tests/keras/applications/applications_test.py
This PR make MobileNet tests random to reduce CI build time.
> Make MobileNet tests random

- keras/backend/theano_backend.py
- keras/initializers.py
- tests/keras/backend/backend_test.py
- tests/keras/initializers_test.py
Alternative to #9957 for solving issue #8048
> Fix initializers

- docs/templates/getting-started/faq.md
Remove extra newline and add horizontal rule.
> Style fixes

- keras/applications/mobilenetv2.py
_inverted_res_block() and _first_inverted_res_block() are nearly the same. Merged them into one function
1. skip "Expand" part for 0 block
2. made layers names similar to original TF graph names
> Merge 2 functions together in applications MobileNetV2

- keras/backend/theano_backend.py
This PR cleans up preprocessing of `depthwise_kernel` for Theano.
- As-is: Two `dimshuffle`'s are redundantly performed, which may result in performance degradation.
- To-be: The two are integrated into a single `dimshuffle` with refactoring.
> Clean up preprocessing of `depthwise_kernel` for Theano

- docs/templates/applications.md
> Mobilenetv2 explanation 

- keras/engine/training.py
Just adding an explicit mention to Sequence in the fit_generator docs.
> Explicitly mention using a Sequence object in val

- keras/utils/multi_gpu_utils.py
**New Benchmark by in-place split (5% ~ 12% faster, and Reduce 400% data copy in  @total from host memory to GPU memory for batch inputs on 4 GPU):**
> Benchmark: keras.application.Resnet50 (NCHW; NVidia Tesla P100 x 4)
input_shape = 3x224x224, batch_size =  96 x 4: from 392(images/sec) => 417(images/sec)
input_shape = 3x299x299, batch_size =  64 x 4: from 229(images/sec) => 244(images/sec)
input_shape = 3x224x224, batch_size =   8 x 4: from 148(images/sec) => 163(images/sec)
> Benchmark: keras.application.InceptionV3 (NCHW; NVidia Tesla P100 x 4)
input_shape = 3x224x224, batch_size = 128 x 4: from 488(images/sec) => 526(images/sec)
input_shape = 3x299x299, batch_size =  96 x 4: from 270(images/sec) => 294(images/sec)
input_shape = 3x224x224, batch_size =   8 x 4: from 146(images/sec) => …
> In-place split to avoid inter-device duplication

- keras/backend/cntk_backend.py
This PR increases test coverages by factorizing CNTK pads for [the current](https://travis-ci.org/keras-team/keras/jobs/381949156) following missing lines:
```
keras/backend/cntk_backend.py              1524    192    87%
```
> Increase test coverages by factorizing CNTK pads

- keras/preprocessing/image.py
- tests/keras/preprocessing/image_test.py
This PR refactorizes ImageDataGenerator so that the random parameters of a transformation are generated separately from applying the transformation. The generation of the parameters happens in `get_random_transform()` function which outputs a dictionary of transformation parameters randomly chosen. The transform can then be applied in a new `apply_transform()` function.
My aim is to eventually enable more generalized usage for ImageDataGenerator; for example, transformation of segmentation coordinates in an image segmentation problem along with the image itself. Since this is going to be quite a big upgrade, I'm doing it in smaller steps at a time to be sure not to break anything too horribly. This refactorization is the first step.
Some design choices I have made here:
* Representing a …
> Refactor ImageDataGenerator

- keras/activations.py
Softplus docstring missing a parenthesis...
> Typo in docstring for softplus

- keras/preprocessing/image.py
> Handle capitalised extensions in list_pictures

- keras/applications/mobilenetv2.py
- tests/keras/applications/applications_test.py
This PR adds pooling options for MobileNetV2
> Add pooling options in MobileNetV2

- keras/layers/convolutional.py
* Add depth as the third dimension in docstring of
Conv3DTranspose in convolutional.py in keras.layers
> Improve the docstring of Conv3DTranspose

- tests/integration_tests/applications_test.py
This PR reduces tests for applications and is a follow-up of #10341.
> Reduce tests for applications

- docs/templates/applications.md
This PR fixes a version number, which is expected inaccurately by me :).
> Fix a version number

- docs/templates/getting-started/sequential-model-guide.md
A couple of variables are "used" in two examples without being defined. For consistency with other examples where auxiliary dimensions are defined, I think it would be better to explicitly assign them a value. I just used made up values, feel free to change to whatever makes more sense!
> Doc update

- tests/keras/engine/test_training.py
This PR add tests for inputs set dynamically, which is a follow-up of #10367. This PR will make CI cover the following:
```
keras/engine/training.py                    545     57    90%   580, 593, 629-632
```
|   | [Before](https://travis-ci.org/keras-team/keras/builds/391388966) |
|:-:|---|
| Python 2.7 + TF | 90.64% |
| Python 3.6 + TF | 90.54% |
| Python 2.7 + TH | 88.14% |
| Python 3.6 + TH | 88.09% |
| Python 2.7 + C | 87.97% |
| Python 3.6 + C | 87.93% |
> Add tests for inputs set dynamically

- keras/engine/training.py
> Fix small doc error (multiple outputs -> multiple inputs)

- keras/activations.py
- keras/losses.py
- keras/optimizers.py
- tests/test_documentation.py
Added : 
```
'keras.engine',
'keras.wrappers', 'keras.utils',
'keras.callbacks', 'keras.activations',
'keras.losses', 'keras.models', 'keras.optimizers'
```
To the documentation test. (Most of them were good! :tada: )
> Minor improvement documentation

- keras/engine/base_layer.py
- keras/engine/network.py
> docstring fixes

- keras/engine/training_generator.py
- tests/keras/test_callbacks.py
Fixes https://github.com/keras-team/keras/issues/10474
Attempt at reusing the validation enqueuer (I thought we were already doing that).
Not sure how to test this. Suggestion welcome.
> Reuse validation enqueuer

- examples/README.md
This PR adds the missing examples to the list of examples in _examples/README.md_.
> Add missing examples to examples/README.md

- keras/layers/core.py
Update `Conv2D` call to the Keras 2 API
Update `Conv2D` call to the Keras 2 API
- [n] This PR is backwards compatible [y/n]
> Update `Conv2D` call to the Keras 2 API

- examples/addition_rnn.py
- examples/babi_memnn.py
- examples/babi_rnn.py
- examples/cifar10_cnn.py
- examples/cifar10_cnn_capsule.py
- pytest.ini
Fix the line length for 5 files in `examples/` folder
> PEP8 fixed line length examples/

- keras/layers/convolutional.py
> Fix #10737

- keras/utils/conv_utils.py
- keras/utils/data_utils.py
- pytest.ini
> Improve keras/utils by enabling PEP8 501

- keras/engine/network.py
- keras/engine/sequential.py
- keras/engine/training_generator.py
I removed some variables, some unused, some redefined later on.
> Removed some unused variables.

- keras/layers/convolutional.py
I think this version is less error prone and more maintainable.
Maybe we could do some subclassing?
> Removed some code in the cropping layer by making use of python slices.

- keras/backend/tensorflow_backend.py
I was able to simplify this piece of code with the function `transpose_shape`.
> Some code refactoring using `transpose_shape` in tensorflow_backend.py.

- keras/backend/tensorflow_backend.py
> Some code refactoring using `transpose_shape` in tensorflow_backend.py. Part 3

- pytest.ini
- tests/keras/layers/convolutional_recurrent_test.py
- tests/keras/layers/convolutional_test.py
- tests/keras/layers/core_test.py
- tests/keras/layers/cudnn_recurrent_test.py
- tests/keras/layers/embeddings_test.py
- tests/keras/layers/normalization_test.py
- tests/keras/layers/wrappers_test.py
- tests/keras/legacy/interface_test.py
This PR is to enable PEP8 501 checks.
> Style fixes for enabling PEP8 501

- keras/applications/__init__.py
- keras/applications/densenet.py
- keras/applications/imagenet_utils.py
- keras/applications/inception_resnet_v2.py
- keras/applications/inception_v3.py
- keras/applications/mobilenet.py
- keras/applications/mobilenet_v2.py
- keras/applications/mobilenetv2.py
- keras/applications/nasnet.py
- keras/applications/resnet50.py
- keras/applications/vgg16.py
- keras/applications/vgg19.py
- keras/applications/xception.py
- keras/preprocessing/image.py
- keras/preprocessing/sequence.py
- tests/integration_tests/applications_test.py
See:
Original issue: https://github.com/keras-team/keras-applications/issues/28
keras_applications PR: https://github.com/keras-team/keras-applications/pull/29
keras_preprocessing PR: https://github.com/keras-team/keras-preprocessing/pull/40
> Integration with redesigned preprocessing & applications modules.

- docs/templates/layers/writing-your-own-keras-layers.md
"How to make a layer with multiple inputs/outputs?" is a question which is often asked on StackOverflow and in the github issues. 
There is no answer to it in the documentation.
#2364
#534
#3061
The layer makes zero sense, but I think the example is ok since it's really close to the first code example so readers can easily spot the differences.
> Added in the documentation an example of custom layer with multiple inputs and outputs.

- tests/keras/backend/backend_test.py
This PR is a follow-up on #10930. It removed tests which would be duplicated when running the travis build.
> Removed duplicated backend tests.

- examples/conv_filter_visualization.py
- examples/deep_dream.py
- examples/image_ocr.py
- examples/imdb_fasttext.py
- examples/imdb_lstm.py
- examples/lstm_text_generation.py
- examples/mnist_hierarchical_rnn.py
- examples/mnist_net2net.py
- examples/mnist_siamese.py
- examples/mnist_tfrecord.py
- examples/neural_doodle.py
- examples/neural_style_transfer.py
- pytest.ini
This PR is to enable PEP8 501 checks.
Especially, its for example code.
> Enable examples pep8

- .travis.yml
- docker/Dockerfile
Install cntk with pip. Merging this PR will also merge ##10834
See ##10834
> Used "pip install cntk" to simplify the installation of CNTK.

- tests/keras/backend/backend_test.py
- tests/keras/backend/reference_operations.py
This PR speeds up backend tests by removing redundant backend tests. The targets, which always been included in the slowest 20 test durations, are `test_elementwise_operations` and `test_nn_operations`.
This PR also cleans up old styles for backend tests including `assert_value_with_ref`, `return_results`, `shape_or_val`, and the related stuff with them. As a result, the `test_conv`, `test_depthwise_conv`, and `test_pool` are now much cleaner than before.
#10972
#10956
#10930
cc @gabrieldemarmiesse
> Speed up backend tests

- keras/layers/convolutional.py
By doing this, we can remove quite a lot of code. I think it will also increase the coverage. (maybe?)
A similar refactoring was done for the cropping layers.
The base class holds the `compute_output_shape` and `get_config` methods.
> Made a base class for ZeroPadding.

- examples/lstm_text_generation.py
unused args in **on_epoch_end** removed and softmax activation layer replace with args in dense layer.
> Update lstm text generation example

- tests/keras/backend/backend_test.py
- tests/keras/backend/reference_operations.py
Follow up on #11051. 
We want to avoid to duplicate backends tests.
@taehoonlee 
#11051
#11037
#10972
#10956
#10930
> Added in_train_phase and in_test_phase in the numpy backend.

- docs/templates/applications.md
This PR makes the performance table up-to-date.
> Revise the performance table for applications

- keras/layers/convolutional.py
This PR makes an abstract class for upsampling layers. Thus reducing the amount of code duplicate.
This PR is closely related to those past two ones for reference:
#10984
#10888
I made the base class. It was mostly copy pasting from the previous two PRs.
> Made an abstract class for upsampling.

- keras/backend/tensorflow_backend.py
- tests/keras/backend/backend_test.py
- tests/keras/backend/reference_operations.py
Improves documentation for `axis` argument (i.e. we should accept a list of integers as well).
> Support multiple axes for operations in TF backend

- tests/keras/backend/backend_test.py
This PR targets a refactoring of the backend tests, especially the handling of cntk functions which can be confusing (at least it was the case for me).
> Simplified the cntk backend tests and made them more readable.

- keras/backend/theano_backend.py
> [Refactoring] Removed code duplication in the theano backend.

- keras/engine/sequential.py
- tests/keras/test_sequential_model.py
Matches tf.keras behavior as of TF 1.11.0.
> [RELNOTES] Modify Sequential config to include model name (breaking change)

- keras/callbacks.py
- keras/utils/test_utils.py
- tests/keras/test_callbacks.py
Thanks @huyu398 for your work!
This PR is an update of #10609. See #10609 for a description of the issue.
Here is #10609 with modifications according to the review. 
I have tested the code locally on a windows and ubuntu machine. It worked in both.
>  Fixed the windows line endings in the CSVCallback.

- keras/datasets/boston_housing.py
Thanks @ozabluda for your work!
Update of #8330 according to review.
We should be able to close #8330 after this PR is merged.
Used a with statement instead of a close statement for robustness.
> Update of #8330 according to review.

- docs/templates/applications.md
This PR fixes incorrect minimum input size for applications.
- Line 274: VGG16
- Line 329: VGG19
- Line 441: InceptionV3
- Line 496: InceptionResNetV2
- Lines 623-: DenseNet
> Fix incorrect minimum input size for applications

- keras/legacy/interfaces.py
a little change to refactor lagacy/interfaces/interfaces.py
> refactor lagacy/interfaces

- keras/activations.py
- keras/backend/theano_backend.py
- tests/keras/activations_test.py
- tests/keras/backend/backend_test.py
This PR is an update of #10027 which I kinda broke. Sorry about it.
I moved the correctness test in the backend tests. I think it belongs there rather than in the activations tests.
> [updated] improve softmax implementation

- tests/keras/backend/backend_test.py
- tests/keras/backend/reference_operations.py
ones, zeros, zeros_like, ones_like
> add more variable initializers to numpy backend

- examples/addition_rnn.py
This PR improves the addition_rnn example's code and comments:
- added the docstring for `decode` method.
- changed "one hot" to "one-hot"
- changed "last hidden state of RNN" to "last output of RNN"
- passed `activation='softmax'` argument to the `Dense` layer and removed the `Activation` layer to make it more explicit where it is applied.
> Improve addition_rnn example's code and comments

- keras/engine/training.py
- keras/engine/training_arrays.py
Make fit_loop function easy read and understand.
> Refactor keras/engine/training.py and keras/engine/training_arrays.py

- docs/templates/layers/writing-your-own-keras-layers.md
> Fix typo in writing-your-own-keras-layers.md

- tests/keras/backend/backend_test.py
In travis, some tests were applied more than once. This PR makes sure that those tests are only ran once.
> De-duped some test functions.

- tests/keras/backend/backend_test.py
- tests/keras/backend/reference_operations.py
Credit goes to @danFromTelAviv  for his implementation in numpy of batch_dot.
@danFromTelAviv feel free to read this PR and comment if you see things which need changes.
@taehoonlee , I think you're the right person to ask for review. Thanks in advance.
#11068
> Added the batch_dot operation in the references_operations.py.

- docs/templates/applications.md
Update MobileNetV2 document invalid package
> Fix doc MobileNetV2 invalid package

- tests/keras/backend/backend_test.py
- tests/keras/backend/reference_operations.py
> Added the padding operations in reference_operations.py

- tests/keras/backend/backend_test.py
- tests/keras/backend/reference_operations.py
Everything is in the title.
#11068
> Added dropout to reference_operations.py

- keras/backend/cntk_backend.py
- pytest.ini
Reduced the line length of the code to 85 characters.
> Line length reduced to 85 characters for cntk_backend.py

- tests/keras/backend/backend_test.py
> Some tests were ran multiple times in backend_test.py. Fixed it.

- keras/backend/cntk_backend.py
- keras/backend/tensorflow_backend.py
- keras/backend/theano_backend.py
- tests/keras/backend/backend_test.py
I'm probably not doing this the right way, but I wanted to watch it fail on Travis (I'm sure I correctly installed only the Tensorflow backend locally).
Closes https://github.com/keras-team/keras/issues/11435.
> Support tensor arguments in clip.

- keras/callbacks.py
- tests/keras/test_callbacks.py
> Tensorboard to get gradients only for trainable weights - updated

- keras/backend/tensorflow_backend.py
- pytest.ini
> Enabled pep8 line length in the tensorflow backend.

- keras/engine/saving.py
1. rename argument: f as h5dict_instance
2. rename argument: f as groups
3. add some comments for save_weights_to_hdf5_group
> improve keras/engine/saving.py

- .travis.yml
> Removed matplotlib from travis because it's not used in the tests.

- keras/backend/numpy_backend.py
We need to make sure that the numpy backend is very readable since it's going to be displayed in the docs.
> Simplified the logic of reverse in the numpy backend.

- tests/keras/backend/backend_test.py
> Removed the variable BACKENDS as it is not used anymore.

- keras/backend/numpy_backend.py
- keras/backend/tensorflow_backend.py
> Added hard_sigmoid numpy implementation in the docs.

- .coveragerc
- .travis.yml
We now remove the file that we don't want rather than check all the backends one by one.
> Simplified travis build

- keras/backend/numpy_backend.py
- keras/backend/tensorflow_backend.py
Reworked on the implementation to make it more readable since it's user-facing code.
> Displaying the numpy relu in the docs.

- examples/neural_style_transfer.py
Minor edits in a comment and for improved formatting consistency.
> Change VGG16 to VGG19 an fix inconsistent float formatting.

- .travis.yml
> Simplifying the travis build

- keras/backend/tensorflow_backend.py
They are all simple function with a few lines of numpy.
> Added the numpy implementation of some small functions in the docs.

- keras/backend/tensorflow_backend.py
> fix small typos

- docs/autogen.py
> Add DepthwiseConv2D to online docs

- keras/backend/tensorflow_backend.py
- tests/keras/backend/backend_test.py
#11719 
- [n ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)
> Remove reduce sum impl in batch dot

- keras/backend/numpy_backend.py
- keras/backend/tensorflow_backend.py
- tests/keras/backend/backend_test.py
I add softsign function in numpy backend with a test.
> Add softsign function in numpy backend

- keras/layers/convolutional.py
Broken link updated from 
https://www.matthewzeiler.com/pubs/cvpr2010/cvpr2010.pdf 
to 
https://www.matthewzeiler.com/mattzeiler/deconvolutionalnetworks.pdf.
> the broken link updated

- docs/templates/getting-started/faq.md
- docs/templates/losses.md
- docs/templates/visualization.md
- keras/utils/__init__.py
Fixes #11959
- [n ] This PR requires new unit tests [y/n] (make sure tests are included)
- [y] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)
> Make model_to_dot available in keras.utils and update API

- docs/templates/applications.md
- docs/templates/getting-started/faq.md
This PR updates docs for ResNet variants.
> Update docs for ResNet variants

- keras/datasets/mnist.py
- tests/test_multiprocessing.py
This PR makes the file closing styles consistent.
> Make the file closing styles consistent

- keras/backend/cntk_backend.py
This PR cleans up untouchable lines in `separable_conv1d` of CNTK. The lines 1752-1760 cannot be touched because the ValueError in the line 1750 will always be raised (dilation_rate[0] is always 1 and dilation_rate[1] can be any integer). Thus, this PR removes the untouchable lines and moves the ValueError into the beginning for style consistency with `conv1d`, `conv2d`, and `conv3d`.
> Clean up untouchable lines in `separable_conv1d` of CNTK

- keras/backend/tensorflow_backend.py
Add numpy documentation like "{{np_implementation}}" in methods.
> Add numpy documentation

- keras/preprocessing/image.py
This fixes #11841. I will work on a follow-up PR on further documentations in keras-preprocessing.
> Fix #11841

- tests/keras/backend/backend_test.py
- tests/keras/engine/test_topology.py
This is a pull request to divide #12076 into multiple sub-PRs making it easier to review (the diff will be smaller).
#12076
> Used K.backend() instead of K._BACKEND.

- examples/variational_autoencoder.py
- examples/variational_autoencoder_deconv.py
- keras/engine/network.py
- keras/engine/sequential.py
- keras/engine/training_generator.py
- keras/utils/generic_utils.py
> Formatting fixes

- keras/utils/layer_utils.py
Current
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
model_1_input (InputLayer)   [(None, 128)]             0         
```
Proposed
```
_________________________________________________________________
Model: "part_of_speech_tagger"
Layer (type)                 Output Shape              Param #   
=================================================================
model_1_input (InputLayer)   [(None, 128)]             0
```
> Print the model name as part of layer_utils.print_summary

- keras/callbacks.py
- keras/engine/sequential.py
- keras/layers/core.py
- keras/layers/cudnn_recurrent.py
- keras/layers/embeddings.py
- keras/layers/local.py
- keras/layers/noise.py
- keras/layers/wrappers.py
- keras/optimizers.py
- keras/utils/data_utils.py
- tests/test_documentation.py
Improve `test_documentation` by making sure arguments of class init are in the class docstring
https://github.com/keras-team/keras/issues/12189
> Test init args in documentation

- keras/backend/cntk_backend.py
- tests/keras/backend/backend_test.py
Implement `update_sub` for CNTK backend function
#12162
- I am unable to find any tests for update functions in `backend_test.py`
> Add `update_sub` to CNTK backend

- .travis.yml
- docs/autogen.py
- tests/test_doc_auto_generation.py
> Added the possibility to specify the destination directory in autogen.py

- examples/conv_filter_visualization.py
Made the `conv_filter_visualization` example functional again and decreased the needed effort in actually running the program and changing simple parameters such as the desired layer or the number of steps and epochs. Overall it should be more readable and with that more understandable than before.
> Fixed conv_filter_visualization example

- examples/mnist_siamese.py
- [] This PR requires new unit tests [y/n] (make sure tests are included)
- [] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)
> Small change in mnist_siamese.py

- docs/mkdocs.yml
- examples/conv_filter_visualization.py
This PR adds MarkDown formatting to ```examples/conv_filter_visualization.py```.
Result:
> Added MarkDown formatting to examples/conv_filter_visualization.py

- docs/mkdocs.yml
- examples/imdb_cnn.py
This PR adds Markdown formatting to ```examples/imdb_cnn.py```.
Result:
> Added MarkDown formatting to examples/imdb_cnn.py

- docs/mkdocs.yml
- examples/conv_lstm.py
This PR adds Markdown formatting to ```examples/conv_lstm.py```.
Result:
> Added MarkDown formatting to examples/conv_lstm.py

- keras/backend/cntk_backend.py
Use native CNTK functions for `zeros_like` and `ones_like`
> Use native CNTK functions for zeros_like and ones_like

- keras/backend/common.py
Add type check when setting epsilon.
> Type check for `K.set_epsilon`

- keras/engine/training.py
See related issue
#12401 
- [Y] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
> Docs fix for Model

- keras/backend/cntk_backend.py
> Reuse `get_value` code inside `batch_get_value`

- keras/backend/cntk_backend.py
- tests/keras/backend/backend_test.py
Tests for `cumsum` and `cumprod` have been split for the time being
> K.cumsum for CNTK backend

- keras/activations.py
Update the docs for `tanh` and `sigmoid` functions [here](https://github.com/keras-team/keras/blob/c24d16af155e20976bdf61e468ba760408e676ff/keras/activations.py#L131) and [here](https://github.com/keras-team/keras/blob/c24d16af155e20976bdf61e468ba760408e676ff/keras/activations.py#L137) and also make the style uniform
> Update docs for some activations, make the style uniform

- LICENSE
The copyrights years were not up to date, hence, I changed them to the current year.
- [n] This PR is backwards compatible [y/n]
> Updated the copyright years

- examples/lstm_stateful.py
- keras/activations.py
- keras/engine/network.py
- keras/engine/training_utils.py
- keras/utils/test_utils.py
- keras/utils/vis_utils.py
This PR improves docstrings for consistency as Markdown format.
> Improve docs for consistency as Markdown format

- keras/backend/cntk_backend.py
- keras/backend/numpy_backend.py
- keras/backend/tensorflow_backend.py
- keras/backend/theano_backend.py
- tests/keras/backend/backend_test.py
This PR makes `eye` consistent over all the backends.
> Make `eye` consistent over all the backends

- keras/backend/cntk_backend.py
- tests/keras/backend/backend_test.py
This PR adds `cumprod` for CNTK.
> Add `cumprod` for CNTK

- keras/backend/cntk_backend.py
- keras/backend/tensorflow_backend.py
- keras/backend/theano_backend.py
- tests/keras/backend/backend_test.py
This PR adds `slice` for Theano and CNTK.
> Add `slice` for Theano and CNTK

- keras/backend/cntk_backend.py
- tests/keras/backend/backend_test.py
Implement functions `K.foldl` and `K.foldr` for CNTK
#12168
-[ ] This PR requires new unit tests [y/n] (make sure tests are included)
-[ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
-[x] This PR is backwards compatible [y/n]
-[ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)
> Implement `foldl` and `foldr` for CNTK #12168

- keras/backend/tensorflow_backend.py
This PR fixes `slice` of TF for enabling the sanity check to handle TF tensors.
#12539
#12548
> Fix `slice` of TF for enabling the sanity check to handle TF tensors

- examples/pretrained_word_embeddings.py
Use `np.fromstring` to read directly embedding values directly into an array
None
> Speed optimization

- keras/engine/base_layer.py
- keras/engine/training_arrays.py
- Using `dict.copy()` instead of importing `copy` library
- Faster list extension (see code)
None
> Minor optimisations

- keras/constraints.py
> fix a comment error for MaxNorm constraint

- README.md
> Updated README.md for windows users

- docs/README.md
Noticed some outdated source that hasn't been updated in the site ReadMe Doc.
> Refactor outdated official keras site doc.

- docs/templates/getting-started/functional-api-guide.md
I would try to be as explicit as possible in the first example of the functional API
> DOC: don't reuse names in introductory example

- keras/optimizers.py
- tests/keras/optimizers_test.py
Reverts keras-team/keras#12841
> Revert "Sync Keras optimizer with tf.keras optimizer"

- keras/losses.py
- tests/keras/losses_test.py
Adding MeanAbsoluteError, MeanAbsolutePercentageError, MeanSquaredLogarithmicError and BinaryCrossentropy loss classes.
n/a
- [ y] This PR requires new unit tests [y/n] (make sure tests are included)
- [ n] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
> Adding MeanAbsoluteError, MeanAbsolutePercentageError, MeanSquaredLogarithmicError and BinaryCrossentropy loss classes.

- keras/losses.py
- tests/keras/losses_test.py
Adding CategoricalCrossentropy and SparseCategoricalCrossentropy Loss classes
n/a
> Adding CategoricalCrossentropy and SparseCategoricalCrossentropy Loss classes

- keras/engine/saving.py
- keras/engine/training.py
- keras/engine/training_utils.py
- keras/losses.py
- keras/utils/generic_utils.py
- keras/utils/losses_utils.py
- keras/wrappers/scikit_learn.py
- tests/keras/engine/test_training.py
- tests/keras/losses_test.py
- tests/test_model_saving.py
Adding support for `Loss` instances in model compile.
n/a
> Adding support for `Loss` instances in model compile.

- keras/layers/convolutional.py
> correct DepthwiseConv2D docstring

- keras/backend/tensorflow_backend.py
In some special and useful cases, the num of classes is unknown (None).
> fine tune sparse_categorical_crossentropy

- examples/conv_filter_visualization.py
> Fixed a typo

- keras/backend/tensorflow_backend.py
- keras/metrics.py
- keras/utils/metrics_utils.py
- tests/keras/metrics_confusion_matrix_test.py
Adding TruePositives, TrueNegatives, FalsePositives, FalseNegatives metric classes.
n/a
> Adding TruePositives, TrueNegatives, FalsePositives, FalseNegatives metric classes.

- keras/metrics.py
- tests/keras/metrics_confusion_matrix_test.py
Add SpecificityAtSensitivity metric.
> Add SpecificityAtSensitivity metric.

- keras/engine/base_layer.py
> typo fixed

- keras/engine/base_layer.py
Fixed a logical error in the description of "Layer.compute_output_shape" method
> fix in "Layer.compute_output_shape" description

- docs/templates/getting-started/functional-api-guide.md
Fixes #12445 by adding data to the docs at [this link](https://keras.io/getting-started/functional-api-guide/#multi-input-and-multi-output-models) by modifying [here](https://github.com/keras-team/keras/blob/master/docs/templates/getting-started/functional-api-guide.md)
Refer #12445 
> Complete the docs by adding data to multi-input/output example

- keras/utils/data_utils.py
> Correct spelling mistake

- keras/engine/training_utils.py
`math_ops` changed to `K`
Issue: #13341
> fix #13341 math_ops to K

- keras/engine/training.py
Fixing typos in the docstrings
NA
> Fixing typos in the docstrings

- keras/layers/convolutional.py
- keras/layers/convolutional_recurrent.py
> Reverted space

- keras/layers/__init__.py
- keras/layers/convolutional.py
- keras/layers/convolutional_test.py
> add DepthwiseConv1D layer

- keras/mixed_precision/loss_scale_optimizer.py
- keras/mixed_precision/loss_scale_optimizer_test.py
PiperOrigin-RevId: 382409145
Cherry pick this into 2.6 release to avoid user confusion.
@reedwm and @mihaimaruseac
> Add more explicit error message for instance type checking of optimizer.

- keras/utils/layer_utils.py
Moved from https://github.com/tensorflow/tensorflow/pull/47439
> Make model summary wrap

- keras/applications/mobilenet_v3.py
- keras/distribute/distribute_strategy_test.py
- keras/engine/data_adapter.py
- keras/engine/sequential.py
- keras/engine/training_dataset_test.py
- keras/engine/training_utils_v1.py
- keras/feature_column/dense_features_v2_test.py
- keras/integration_test/preprocessing_test_utils.py
- keras/layers/merge.py
- keras/layers/multi_head_attention.py
- keras/layers/preprocessing/string_lookup.py
- keras/layers/preprocessing/text_vectorization_test.py
- keras/preprocessing/dataset_utils.py
minor fixing ```keras```:
- fixing comment spelling grammar
- fixing indentation
> minor fixing

- keras/models.py
- keras/models_test.py
Fix of the issue https://github.com/keras-team/keras/issues/14937
Including new test cases
> Fix clone_model to consider input_tensors

- keras/callbacks.py
Log the best epoch when restoring the best weights in early stopping.
> Log the best epoch when restoring the best weights in early stopping

- .devcontainer/devcontainer.json
- CONTRIBUTING.md
Modify the local env setup to support more operating systems.
Add the link to a list of supported editors and setup instructions.
> update contributing guide

- keras/layers/convolutional.py
- keras/layers/convolutional_test.py
#14958
This is my first try to solve this issue. I think we can do a prototype with Cropping1D and after when everything is perfect, copy the same pattern to Cropping2D, Cropping3D, etc.
Pls, give me your thoughts. @rmothukuru
> fix cropping layer return empty list if crop is higher than data shape

- keras/engine/training.py
- keras/utils/BUILD
- keras/utils/layer_utils.py
- keras/utils/layer_utils_test.py
Issue #15250. I am making this PR.
The changes have been made using the recursion approach. All the nested layers get summarized one by one.
> Print expanded nested layers feature in models.summary()

- keras/callbacks.py
Fix
[https://github.com/tensorflow/tensorflow/issues/44509](https://github.com/tensorflow/tensorflow/issues/44509)
[https://github.com/keras-team/keras/issues/15138](https://github.com/keras-team/keras/issues/15138)
> adapt EarlyStopping auto mode to auc

- keras/layers/preprocessing/benchmarks/image_preproc_benchmark.py
The third time that I give you this PR.
If there are any other questions,I will change.
> The latest update.Hope it can suit you

- keras/engine/training.py
- keras/utils/vis_utils.py
@fchollet
Changes wrt. PR #15291 and issue #15291.
> Fixed and added ValueError for `plot_model`, `model_to_dot` and `model.summary()`

- keras/datasets/cifar10.py
- keras/datasets/cifar100.py
This is a really minor typo I noticed today while reading the CIFAR-10 description and thought to make a quick PR fixing it.
> Fix a minor typo in CIFAR-10 and CIFAR-100 description

- keras/layers/convolutional.py
- keras/layers/convolutional_test.py
This is the solution for the `Cropping2D` layer, following the same way we did in  #14970
@fchollet  @mattdangerw
> Fix cropping2D empty list #15325

- keras/layers/convolutional.py
- keras/layers/convolutional_test.py
- keras/layers/local.py
- keras/layers/local_test.py
Please see #14894. Reopening due to merge issues in the last PR. Changes were previously approved by @fchollet.  
/auto Closes #14887, closes #15333.
> Reopening #48000, #48491, #48610 from tensorflow/tensorflow

- keras/activations.py
unnecessary casting and condition removed
> unnecessary casting and condition removed

- keras/layers/preprocessing/text_vectorization.py
here need to compare strings for equality not string memory address
> fix a bug: when use tf.keras.layers.TextVectorization layer to load model

- CONTRIBUTING.md
There are a number of things to keep in mind when contributint
Keras applications. This provides a checklist of things we will
look for from contributors.
> Update the contribution guide to include a applications section

- CONTRIBUTING.md
Just few typos I spotted while reading the contribution guide.
> Fixing typos.

- keras/losses.py
Correcting the formula in documentation of MAPE and also adding a note about using epsilon in denominator.
Fixes #15599
> Updating the documentation of MAPE

- keras/preprocessing/image_dataset.py
- keras/preprocessing/image_dataset_test.py
- keras/preprocessing/text_dataset.py
- keras/preprocessing/text_dataset_test.py
- keras/preprocessing/timeseries.py
- keras/preprocessing/timeseries_test.py
I made a change in `timeseries_dataset_from_array` so that users can have a choice to make batches or not do.
It solves #15645.
> Adding a choice not to make batches in `timeseries_dataset_from_array`

- keras/backend.py
The phase cached by backend._GRAPH_LEARNING_PHASES  is a tf.Tensor with attribute 'graph'.
There is a circular reference between key 'graph' and attribute 'graph'.
So we need use a weakref.ref to refer to the tensor phase here.
Otherwise, it would lead to memory leak.
> fix backend _GRAPH_LEARNING_PHASES graph circular reference.

- keras/layers/dense_attention.py
- keras/layers/wrappers_test.py
> Implement compute_output_shape for BaseDenseAttention

- keras/engine/training.py
- keras/preprocessing/text_dataset.py
Fixed a minor spelling error and a grammar mistake in the doc strings.
> Fixed minor typos

- .gitignore
- README.md
Also fix a small typo in the README.
> Add .DS_Store to .gitignore for macOS users

- keras/engine/data_adapter.py
> Fix typos in data_adapter.py

- keras/dtensor/BUILD
- keras/dtensor/__init__.py
- keras/dtensor/initializers_test.py
- keras/dtensor/layers_test.py
- keras/dtensor/layout_map_test.py
- keras/dtensor/metrics_test.py
- keras/dtensor/mnist_model_test.py
- keras/dtensor/optimizers_test.py
- keras/dtensor/test_util.py
- keras/dtensor/utils_test.py
- keras/optimizers/optimizer_experimental/BUILD
- keras/tools/pip_package/BUILD
- keras/tools/pip_package/create_pip_helper.py
PiperOrigin-RevId: 438858608
PiperOrigin-RevId: 439676157
> Cherrypick Keras DTensor related updates into keras 2.9

- keras/engine/training.py
- keras/engine/training_test.py
Closes https://github.com/keras-team/keras/issues/16397
See issue for description.
Let me know if I should add anything.
> Fix prediction with structured output

- keras/engine/base_layer.py
Added reference to the resource variable.
Fixes: https://github.com/tensorflow/tensorflow/issues/49614
> Add reference to resource variables.

- keras/regularizers.py
See issue https://github.com/keras-team/keras/issues/16518
> Fix OrthogonalRegularizer to implement the (1,1) matrix norm

- keras/layers/convolutional/base_conv.py
Fix #16570
As discussed in https://github.com/keras-team/keras/issues/16570#issuecomment-1134948727 /cc @reedwm
> Fix mixed precision serialization of group convs

- keras/utils/timeseries_dataset.py
Update alias to standard name.
From `tf.keras.preprocessing.timeseries_dataset_from_array` to `tf.keras.utils.timeseries_dataset_from_array`
> Update standard name

- keras/utils/vis_utils.py
- keras/utils/vis_utils_test.py
Relevant issue: https://github.com/keras-team/keras/issues/15795
> Fix error when labels contains brackets when plotting model

- keras/applications/applications_test.py
- keras/applications/nasnet.py
Fixes #16791.
Thank you to [ryukinlika](https://github.com/ryukinlika) who found the issue and identified an appropriate fix.
> Fix NASNet input shape computation

- keras/benchmarks/distribution_util.py
- keras/benchmarks/eager_microbenchmarks_test.py
- keras/benchmarks/layer_benchmarks/layer_benchmarks_test_base.py
- keras/benchmarks/layer_benchmarks/run_xprof.py
- keras/benchmarks/model_components_benchmarks_test.py
- keras/benchmarks/saved_model_benchmarks/saved_model_benchmark_util.py
Used Flynt python tool to update the f-string method on all possible files of the benchmarks folder.
> Updated f-string method

- keras/layers/preprocessing/string_lookup.py
- keras/layers/preprocessing/text_vectorization.py
> added an encoding parameter to TextVectorization layer

- keras/applications/mobilenet.py
- keras/applications/mobilenet_v2.py
- keras/applications/nasnet.py
The API docs for multiple pages in keras.applications are not rendered properly, see the tables on:
https://www.tensorflow.org/api_docs/python/tf/keras/applications/nasnet
https://www.tensorflow.org/api_docs/python/tf/keras/applications/mobilenet_v2
https://www.tensorflow.org/api_docs/python/tf/keras/applications/mobilenet
Fixes https://github.com/keras-team/keras/issues/16727
> Incorrectly rendered table

- keras/utils/image_utils.py
Update 
1. `tf.keras.preprocessing.image.array_to_img` to `tf.keras.utils.array_to_img`
2.  `tf.keras.preprocessing.image.img_to_array` to  `tf.keras.utils.image.img_to_array`
3. tf.keras.preprocessing.image.load_img to `tf.keras.utils.load_img`
> Update `tf.keras.preprocessing.image*` to `tf.keras.utils*`

- keras/utils/layer_utils_test.py
- keras/utils/text_dataset_test.py
This PR uses the `with` statement and the `.join` function to make the code more Pythonic and Succinct.
> [Refactoring] making the code more Succinct  and Pythonic

- keras/layers/rnn/lstm.py
Similar [#16921](https://github.com/keras-team/keras/pull/16921).
> Fix Value Error for Units of tf.keras.layers.LSTM

- keras/layers/rnn/simple_rnn.py
Fixes [#16902](https://github.com/keras-team/keras/issues/16902). Thank you!
> Fix Value error for Units of tf.keras.layers.SimpleRNN

- keras/layers/rnn/gru.py
> Fix Value error of tf.keras.layers.GRU

- keras/layers/convolutional/conv1d.py
- keras/layers/convolutional/conv2d.py
- keras/layers/convolutional/conv3d.py
> Update conv layer docs to reflect lack of CPU support for channels_first

- keras/layers/rnn/lstm.py
Fixed Broken link of paper jozefowicz15  et al at line 92
> Fixed Broken link of paper jozefowicz15  et al

- keras/callbacks.py
- keras/callbacks_test.py
following the feature requests as described in:
https://github.com/keras-team/keras/issues/16793#issuecomment-1246065854
and after approval I am submitting this PR.
Thanks.
> EarlyStopping add initial warm-up #16793

- keras/applications/convnext.py
- keras/applications/regnet.py
Fixes issue https://github.com/keras-team/keras/issues/16990
As mentioned in the comments, RegNet also has this issue so added a fix for both.
> Fixes ConvNeXt and RegNet when input_tensor is given

- keras/optimizers/optimizer_experimental/optimizer.py
- keras/optimizers/optimizer_experimental/optimizer_test.py
> Cherrypick for cl/482011499: Throw error on deprecated fields.

- keras/layers/preprocessing/image_preprocessing.py
Changed .format to f-string for better readability and performance as per PEP 498
> Changed .format to f-string for better readability

- keras/optimizers/optimizer_v2/gradient_descent.py
Updated the broken link for Sutskever et al., 2013 in documentation.
> Updated broken link

- keras/engine/training_test.py
- keras/mixed_precision/loss_scale_optimizer.py
> Cherrypick pull request #17225 from lgeiger:fix-mixed-precision-ema

- keras/optimizers/optimizer_experimental/sgd.py
Update the broken link for `Sutskever et al., 2013` in `sgd.py`
> Update broken link

- README.md
Fix the 404 page not found for the Keras functional API
> Update README.md to fix wrong links

- CONTRIBUTING.md
The language in the CONTRIBUTING.md file of the repository has been significantly improved, making it more clear and more concise for potential contributors. The changes include the use of simpler language, improved formatting and organization, and the inclusion of more detailed instructions and guidelines. The changes will help to ensure that contributions are of high quality and meet the standards of the repository. Overall, the improved language in the CONTRIBUTING.md file will greatly enhance the usability and accessibility of the repository, and will ultimately benefit the entire community.
> Improved the CONTRIBUTING.md file

- keras/utils/data_utils.py
Updated Docs string with new apis .
Old  api- tf.keras.preprocessing.sequence.pad_sequences 
New api - tf.keras.utils.pad_sequences
> Updated Docs string of doc_utils.py with new apis

- keras/layers/attention/multi_head_attention.py
Update the MHA docstrings to use 4-space indents.
No changes except for spaces and line breaks.
> Update MHA docstrings

- keras/utils/text_dataset.py
Update the text_dataset.py docstrings to use 4-space indents.
No changes except for spaces and line breaks.
> Update docstrings in text_dataset

- keras/utils/timeseries_dataset.py
- keras/utils/timeseries_dataset_test.py
Fixes https://github.com/keras-team/keras/issues/17392
> Fix timeseries_dataset_from_array counts when sequence_stride > 1

- keras/layers/preprocessing/string_lookup.py
I have added a URL of the TextVectorization API in the StringLookup Layer page so that users can easily look at and experiment with the API.
> Added a link to the TextVectorization API Reference Page.

- keras/optimizers/legacy/optimizer_v2.py
- keras/optimizers/legacy/optimizer_v2_test.py
Closes https://github.com/tensorflow/tensorflow/issues/58973
> OptimizerV2: Allow deepcopy

- CONTRIBUTING.md
- README.md
Added a section to address the security practices and to report security vulnerability found in keras.  Guiding users to use the same steps followed for Tensorflow repo.
Fixes: https://github.com/keras-team/keras/issues/17459
> Update security section.

- keras/layers/preprocessing/text_vectorization.py
> grammar corrections

- keras/layers/reshaping/up_sampling2d.py
> Unifying interpolation selection

- keras/optimizers/optimizer.py
Added a missing space in one of the ValueErrors raised.
> Add a missing space

- keras/engine/training.py
> [keras/engine/training.py] Standardise docstring usage of "Default to"

- keras/feature_column/dense_features.py
> [keras/feature_column/dense_features.py] Standardise docstring usage of "Default to"

- keras/datasets/imdb.py
> [keras/datasets/imdb.py] Standardise docstring usage of "Default to"

- keras/backend.py
> [keras/backend.py] Standardise docstring usage of "Default to"

- keras/layers/activation/leaky_relu.py
> [keras/layers/activation/leaky_relu.py] Standardise docstring usage of "Default to"

- keras/engine/training_v1.py
> [keras/engine/training_v1.py] Standardise docstring usage of "Default to"

- keras/layers/activation/relu.py
> [keras/layers/activation/relu.py] Standardise docstring usage of "Default to"

- keras/layers/locally_connected/locally_connected2d.py
> [keras/layers/locally_connected/locally_connected2d.py] Standardise docstring usage of "Default to"

- keras/applications/mobilenet.py
> [keras/applications/mobilenet.py] Standardise docstring usage of "Default to"

- keras/applications/inception_v3.py
> [keras/applications/inception_v3.py] Standardise docstring usage of "Default to"

- keras/engine/data_adapter.py
> [keras/engine/data_adapter.py] Standardise docstring usage of "Default to"

- keras/applications/imagenet_utils.py
> [keras/applications/imagenet_utils.py] Standardise docstring usage of "Default to"

- keras/layers/attention/additive_attention.py
> [keras/layers/attention/additive_attention.py] Standardise docstring usage of "Default to"

- keras/engine/functional.py
> [keras/engine/functional.py] Standardise docstring usage of "Default to"

- keras/layers/attention/multi_head_attention.py
> [keras/layers/attention/multi_head_attention.py] Standardise docstring usage of "Default to"

- keras/layers/attention/additive_attention.py
- keras/layers/attention/attention.py
- keras/layers/attention/base_dense_attention.py
- keras/layers/attention/multi_head_attention_test.py
This PR updates the indentation level of the docstrings to 4 spaces for the files located in layers/attention.
> Update indentation level - layers/attention

- keras/layers/activation/elu.py
- keras/layers/activation/leaky_relu.py
- keras/layers/activation/prelu.py
- keras/layers/activation/relu.py
- keras/layers/activation/softmax.py
- keras/layers/activation/thresholded_relu.py
This PR changes the indentation level of the docstrings to 4 spaces for the files located in `layers/activation`.
> Update indentation level - layers/activation

- keras/layers/preprocessing/image_preprocessing_test.py
> [keras/layers/preprocessing/image_preprocessing_test.py] Standardise docstring usage of "Default to"

- keras/optimizers/adam.py
> [keras/optimizers/adam.py] Standardise docstring usage of "Default to"

- keras/optimizers/legacy/adam.py
> [keras/optimizers/legacy/adam.py] Standardise docstring usage of "Default to"

- keras/utils/dataset_utils.py
> [keras/utils/dataset_utils.py] Standardise docstring usage of "Default to"

- keras/utils/feature_space.py
> [keras/utils/feature_space.py] Standardise docstring usage of "Default to"

- keras/optimizers/nadam.py
> [keras/optimizers/nadam.py] Standardise docstring usage of "Default to"

- keras/saving/serialization_lib.py
> [keras/saving/serialization_lib.py] Standardise docstring usage of "Default to"

- keras/metrics/base_metric.py
> [keras/metrics/base_metric.py] Standardise docstring usage of "Default to"

- keras/optimizers/schedules/learning_rate_schedule.py
> [keras/optimizers/schedules] Standardise docstring usage of "Default to"

- keras/layers/reshaping/cropping2d.py
- keras/layers/reshaping/cropping3d.py
- keras/layers/reshaping/flatten.py
- keras/layers/reshaping/up_sampling2d.py
- keras/layers/reshaping/up_sampling3d.py
- keras/layers/reshaping/zero_padding2d.py
- keras/layers/reshaping/zero_padding3d.py
> [keras/layers/reshaping] Standardise docstring usage of "Default to"

- keras/optimizers/legacy/adadelta.py
- keras/optimizers/legacy/adagrad.py
- keras/optimizers/legacy/adam.py
- keras/optimizers/legacy/ftrl.py
- keras/optimizers/legacy/gradient_descent.py
- keras/optimizers/legacy/optimizer_v2.py
- keras/optimizers/legacy/rmsprop.py
- keras/optimizers/legacy_learning_rate_decay.py
> [keras/optimizers/legacy] Standardise docstring usage of "Default to"

- keras/layers/rnn/base_conv_lstm.py
- keras/layers/rnn/conv_lstm1d.py
- keras/layers/rnn/conv_lstm2d.py
- keras/layers/rnn/conv_lstm3d.py
- keras/layers/rnn/gru.py
- keras/layers/rnn/legacy_cells.py
- keras/layers/rnn/lstm.py
> [keras/layers/rnn] Standardise docstring usage of "Default to"

- keras/applications/mobilenet_v3.py
> [keras/applications/mobilenet_v3.py] Standardise docstring usage of "Default to"

- keras/__init__.py
- keras/tools/pip_package/setup.py
Increase the release version for keras 2.13 from 2.13.0 to 2.13.1
> Increase the version number for keras 2.13

- keras/metrics/accuracy_metrics.py
- keras/metrics/base_metric.py
- keras/metrics/confusion_metrics.py
- keras/metrics/iou_metrics.py
- keras/metrics/probabilistic_metrics.py
- keras/metrics/regression_metrics.py
> [keras/metrics] Standardise docstring usage of "Default to"

- keras/layers/regularization/spatial_dropout2d.py
- keras/layers/regularization/spatial_dropout3d.py
> [keras/layers/regularization] Standardise docstring usage of "Default to"

- keras/models/cloning.py
- keras/models/sharpness_aware_minimization.py
> [keras/models] Standardise docstring usage of "Default to"

- keras/estimator/__init__.py
> [keras/estimator] Standardise docstring usage of "Default to"

- keras/legacy_tf_layers/base.py
- keras/legacy_tf_layers/migration_utils.py
- keras/legacy_tf_layers/variable_scope_shim.py
> [keras/legacy_tf_layers] Standardise docstring usage of "Default to"

- keras/engine/base_layer.py
- keras/engine/base_layer_utils.py
- keras/engine/base_layer_v1.py
- keras/engine/base_preprocessing_layer.py
- keras/engine/data_adapter.py
- keras/engine/functional.py
- keras/engine/input_layer.py
- keras/engine/training.py
- keras/engine/training_v1.py
> [keras/engine] Standardise docstring usage of "Default to"

- keras/metrics/probabilistic_metrics.py
It's better to demonstrate those metrics using classification losses in the docs.
> Update example losses @ probabilistic_metrics.py

- keras/utils/io_utils.py
typo in "keras.utils.disable_interactie_logging()"
should be 
"keras.utils.disable_interactive_logging()"
> typo in disable_interactie_logging

- README.md
Not sure about the timeline bit? We can just axe that if preferred.
> Update readme with more package info

- keras/backend/tensorflow/optimizer.py
- keras/backend/tensorflow/optimizer_distribute_test.py
The unit test has been updated to not unwrap the raw tf.Variable to mimic the production code behavior.
Also fix distributed_apply_weight_decay which was discovered during unit test fix.
> Fix TF optimizer with distribution strategy.

- keras/trainers/epoch_iterator.py
This PR removed the import of TF in trainer for other backends, which partially resolves the GPU memory issue when using the PyTorch backend.
We may consider removing `tf.available` as it is a sanity check that TF is installed before importing TF when using other backends.
In most of the cases, we should just avoid importing TF no matter TF is installed or not.
> Avoid importing TF in trainer with other backends

- examples/keras_io/vision/latent_walk.py
> Add "A walk through latent space with Stable Diffusion" to multi backend keras

- keras/kokoro/github/ubuntu/gpu/build.sh
- keras/kokoro/github/ubuntu/gpu/tensorflow/continuous.cfg
- keras/kokoro/github/ubuntu/gpu/tensorflow/presubmit.cfg
Adds GPU CI for Continuous and Presubmit.  Once we have it working for TensorFlow, will setup for JAX and PyTorch.
> Adds GPU CI for TensorFlow

- keras/trainers/data_adapters/__init__.py
> Generalize tf and torch dataset check in case path is not strict prefix

- keras/kokoro/github/ubuntu/gpu/jax/continuous.cfg
- keras/kokoro/github/ubuntu/gpu/jax/presubmit.cfg
- keras/kokoro/github/ubuntu/gpu/torch/continuous.cfg
- keras/kokoro/github/ubuntu/gpu/torch/presubmit.cfg
Creates trigger files.  Will update the `build.sh` in separate PR to work for JAX and Torch.
> Add JAX and Torch GPU Test setup

- keras/callbacks/backup_and_restore_callback_test.py
- keras/kokoro/github/ubuntu/gpu/build.sh
> Fix BackupRestore Test for TensorFlow GPU CI

- keras/kokoro/github/ubuntu/gpu/build.sh
- keras/metrics/reduction_metrics_test.py
* Now that Embedding Test is fixed, uncomment TF GPU Test
* Fix code format
> Fix format and uncomment TF GPU embedding test

- requirements-jax-cuda.txt
- requirements-tensorflow-cuda.txt
- requirements-torch-cuda.txt
- requirements.txt
I think that was the plan we decided on
https://github.com/keras-team/keras/pull/18566
but didn't make it into that PR in time
> Pin tf-nightly

- keras/kokoro/github/ubuntu/gpu/build.sh
- keras/kokoro/github/ubuntu/gpu/jax/continuous.cfg
- keras/kokoro/github/ubuntu/gpu/jax/presubmit.cfg
- keras/kokoro/github/ubuntu/gpu/tensorflow/continuous.cfg
- keras/kokoro/github/ubuntu/gpu/tensorflow/presubmit.cfg
- keras/kokoro/github/ubuntu/gpu/torch/continuous.cfg
- keras/kokoro/github/ubuntu/gpu/torch/presubmit.cfg
> Add Torch, JAX GPU CI

- keras/kokoro/github/ubuntu/gpu/build.sh
- keras/layers/convolutional/conv_transpose_test.py
- keras/layers/pooling/average_pooling_test.py
- keras/layers/pooling/max_pooling_test.py
- keras/ops/nn_test.py
Replaces TensorFlow with Numpy expected results.
Test to verify it fixes Torch GPU `nn_test.py` correctness.
> Replace `Tensorflow` with `numpy` for `nn_test`

- keras/saving/saving_lib.py
- keras/utils/file_utils.py
These extend off of #18579, adding more path normalization for full coverage in saving_lib.py.
> Add additional path separator normalization

- keras/layers/layer.py
- keras/ops/operation.py
- keras/saving/saving_lib_test.py
- keras/saving/serialization_lib.py
This PR includes some saving library battle tests, ensuring proper error coverage.
> Expand battle test coverage for saving library

- examples/keras_io/timeseries/timeseries_anomaly_detection.py
> Fixed typo timeseries_anomaly_detection.py

- .github/workflows/nightly.yml
@fchollet - Once its merged, please run the action manually.  Thanks.
> Use PyPa Action to upload

- .github/workflows/actions.yml
- .github/workflows/nightly.yml
Uninstall `keras` installed via TensorFlow from `requirements.txt`
> Uninstall pypi keras from TF in GitHub Actions

- keras/optimizers/adafactor.py
> Fixed typo in adafactor.py

- examples/keras_io/generative/pixelcnn.py
- examples/keras_io/tensorflow/generative/neural_style_transfer.py
updated imports and ops
git diff - https://github.com/keras-team/keras/pull/18632/commits/fd690c3473a0c064d5f82cf74fcfac761a9f49eb
> Keras io example : PixelCNN

- integration_tests/import_test.py
When the subprocess of testing imports and basic workflow runs and errors out, the main process still exit with code 0, which would not fail the CI.
This PR will make the CI fail when the subprocess fails.
This PR should be merged after #18655, which fixes the current breakages.
> ensure the main process raise an exception when the subprocess fails

- keras/ops/nn_test.py
This should address the test coverage in https://github.com/keras-team/keras/pull/18671#issuecomment-1775712652.
> Add unit test for sync batch norm under distribution strategy.

- integration_tests/tf_distribute_training_test.py
- keras/optimizers/loss_scale_optimizer.py
This is trying  to address https://github.com/keras-team/keras/issues/18666
Please note that this fix put backend specific logic into common loss scale optimizer. Let me know if you would like me to create a backend subclass for tensorflow only loss scale optimizer.
> Fix the loss scale optimizer for tf.distribute.

- examples/keras_io/tensorflow/structured_data/movielens_recommendations_transformers.py
Upgrade Keras to the Latest Version and Adapt the Code for Compatibility
In this commit, I have upgraded the Keras library to its latest version to take advantage of new features and improvements. Additionally, I have made necessary code modifications to maintain the previous functionality while utilizing the updated Keras API.
Key Changes:
Upgraded Keras to version 3.0
Updated deprecated Keras functions to their latest equivalents.
Tested the code to verify that it functions correctly with the new Keras version.
These changes aim to keep our project up to date with the latest tools and technologies while preserving the integrity of our existing functionality.
> Add movielens recommendation with keras 3.0

- keras/backend/jax/distribution_lib.py
This will be the final change for multi-worker support of data+model distribution.
See the multi-process testing in cl/578919156
> Add data input distribution for model+data parallel.

- keras/layers/convolutional/conv_transpose_test.py
- keras/ops/nn_test.py
> fix tests for channels_first

- keras/backend/jax/numpy.py
- keras/backend/numpy/numpy.py
- keras/backend/tensorflow/numpy.py
- keras/backend/torch/numpy.py
- keras/ops/numpy.py
- keras/ops/numpy_test.py
Added wrapper for `numpy.diff` (no `prepend` / `append` args) and other backend implementations.
> added diff op

- .github/workflows/actions.yml
- .github/workflows/nightly.yml
References the `actions.yml` in `nightly` as a dependency and removes the copy of the format, tests in `nightly.yml`.  This will align with how we do in `keras-nlp`.
> Remove duplicate in nightly github action

- .github/workflows/actions.yml
- .github/workflows/nightly.yml
Reverts keras-team/keras#18757 to resolve #18767
> Revert "Remove duplicate in nightly github action"

- keras/trainers/data_adapters/py_dataset_adapter_test.py
Instead of hardcoded 8 secs, we can verify the speed-up by comparing identical dataset with different settings in `PyDataset`
This might reduce false alarms in case the server accidentally runs slowly.
> Improve speedup test in `py_dataset_adapter`

- keras/activations/activations.py
- keras/layers/attention/grouped_query_attention.py
- keras/layers/convolutional/separable_conv1d.py
- keras/metrics/confusion_metrics.py
- keras/ops/core.py
- keras/ops/nn.py
Surfaced some minor inconsistencies in docstring after running them through a parser while working on the keras R package.
> Minor docstring fixes

- keras/backend/torch/numpy.py
This PR has fixed the GPU CI breakage introduced by #18816
> Fix torch's `sort` with cuda

- CONTRIBUTING.md
- README.md
Note: a number of sections were copied from the [`tf-keras` contributing guide](https://github.com/keras-team/tf-keras/blob/master/CONTRIBUTING.md).
> Added contributing guide as `CONTRIBUTING.md`.

- keras/regularizers/regularizers_test.py
I have added the assert condition for the test and it passes successfully
> [TODO] : Complete test for orthogonal regularizer

- keras/callbacks/reduce_lr_on_plateau.py
- keras/utils/audio_dataset_utils_test.py
- keras/utils/image_dataset_utils_test.py
- keras/utils/text_dataset_utils_test.py
> Use floating point numbers instead of integer when expected

- keras/backend/tensorflow/numpy.py
- keras/ops/numpy_test.py
Fix #18890 
The corresponding test has been added.
> Fix `ops.tril` and `ops.triu` with tensorflow backend

- keras/trainers/compile_utils.py
- keras/trainers/compile_utils_test.py
Fix #18970
The corresponding test has been added and can only be passed after this PR.
> Fix compiled crossentropy

- .gitignore
- keras/backend/tensorflow/optimizer.py
- keras/optimizers/adam_test.py
- keras/optimizers/base_optimizer.py
Fix for the issue described in https://github.com/keras-team/keras/issues/18985
> Fix `clipnorm` for TF models with `Embedding` layer(s).

- keras/utils/tracking.py
- keras/utils/tracking_test.py
> chore: override item removal methods in tracking

- keras/backend/common/variables_test.py
- keras/layers/preprocessing/discretization.py
- keras/layers/preprocessing/discretization_test.py
Unit test
- For sparse inputs in the Discretization layer (It's test_sparse_output now)
Typo
- "tf" should be "tensorflow"
- "DicretizationTest" should be "DiscretizationTest"
credit: @AlvaroMaza
> Implement a new unit test and correct some typos.

- keras/backend/tensorflow/numpy.py
- keras/ops/numpy_test.py
* Use a new way to handle them.
* Add a new unit test.
Fix: https://github.com/keras-team/keras/issues/19043 and https://github.com/keras-team/keras/issues/19045
> Rewrite triu and tril in tensorflow backend

- keras/layers/core/dense_test.py
- keras/layers/core/embedding_test.py
Add tests for enabling LORA on a Dense layer.
Add tests for enabling LORA on Embedding layer
> Add tests for  enabling LORA on a Dense and Embedding layer

- keras/ops/math.py
- keras/ops/math_test.py
> fix and add tests for /ops/math.py

- keras/backend/common/keras_tensor.py
- keras/backend/jax/numpy.py
- keras/backend/numpy/numpy.py
- keras/backend/tensorflow/numpy.py
- keras/backend/torch/numpy.py
- keras/metrics/accuracy_metrics.py
- keras/ops/numpy.py
- keras/ops/operation_utils.py
- keras/ops/operation_utils_test.py
This is for consistency with the NumPy API.
> Rename `ops.reshape` argument from `new_shape` to `newshape`.

- keras/trainers/data_adapters/array_data_adapter.py
Updated `ArrayDataset` to handle full batches at a time to avoid collating batches of size 1.
See https://github.com/keras-team/keras/issues/19120
The benchmark provided in the issue was run both on CPU and GPU, performance is back to what it was in 3.0.2.
> Fix performance regression for ArrayDataAdapter with Torch backend.

- benchmarks/model_benchmark/bert_benchmark.py
- examples/demo_jax_distributed.py
Fixed a few typos in the documentation, please do the needful.
Thank you!
> Fixing typos in doc

- keras/callbacks/tensorboard.py
There are more cleanups to come. Also I think there are some issue for the current TB callbacks (probably introduced when we port them from tf_keras)
> Minor cleanup for the unnecessary tf.summary.record_if(True) (no_op)

- keras/layers/preprocessing/category_encoding.py
- keras/layers/preprocessing/category_encoding_test.py
Weights tensor has to be a keyword argument unless we rework the tf_preprocessing layer class.
> Add weights param to category_encoding

- keras/backend/jax/distribution_lib.py
- keras/backend/jax/distribution_lib_test.py
> Fix typo in keras.distribution.initialize

- keras/layers/convolutional/base_depthwise_conv.py
- keras/layers/convolutional/base_separable_conv.py
- keras/layers/convolutional/conv_test.py
- keras/layers/convolutional/conv_transpose_test.py
- keras/layers/convolutional/depthwise_conv_test.py
- keras/layers/convolutional/separable_conv_test.py
This PR updates tests to precisely match detailed error messages using regex, enhancing test reliability.
> Check raised regex in convolutional tests

- examples/demo_jax_distributed.py
- guides/custom_train_step_in_jax.py
- guides/custom_train_step_in_tensorflow.py
- guides/custom_train_step_in_torch.py
- guides/writing_a_custom_training_loop_in_torch.py
- keras/backend/common/backend_utils.py
- keras/backend/common/variables.py
- keras/backend/numpy/nn.py
- keras/backend/tensorflow/nn.py
- keras/backend/tensorflow/numpy.py
- keras/backend/torch/nn.py
- keras/callbacks/swap_ema_weights.py
- keras/datasets/reuters.py
- keras/distribution/distribution_lib.py
- keras/layers/convolutional/conv_transpose_test.py
- keras/layers/layer.py
- keras/layers/preprocessing/discretization.py
- keras/layers/preprocessing/integer_lookup.py
- keras/layers/preprocessing/string_lookup.py
- keras/layers/preprocessing/text_vectorization.py
- keras/legacy/saving/saving_utils.py
- keras/metrics/metrics_utils.py
- keras/utils/argument_validation.py
- keras/utils/io_utils.py
- keras/utils/nest.py
> Fix typos in multiple files

- requirements-jax-cuda.txt
- requirements-tensorflow-cuda.txt
- requirements-torch-cuda.txt
- requirements.txt
Pin to TF 2.16 since its now general Release
> Pin to TF 2.16

- keras/backend/torch/random.py
Fixes https://github.com/keras-team/keras/issues/19288
> Fix `draw_seed` causing device discrepancy issue during `torch`'s symbolic execution

- keras/testing/test_case.py
Fixes https://github.com/keras-team/keras/issues/19292
> Fix TestCase.run_layer_test for multi-output layers

- .github/workflows/actions.yml
> downgrade codecov to v3

- .github/workflows/actions.yml
Resolves #19264 
Previous updates didn't work because I have been mistakenly updating the codecov setting for Keras.applications.
This one updates the setting for Keras.
> update codecov setting

- integration_tests/numerical_test.py
Resolves #19267.
All numerical issues are fixed.
Add `BatchNormalization` to `numerical_tests.py`.
Also test weights, predict, evaluate, in addition to training history.
> Change the numerical test to be more comprehensive.

- keras/dtype_policies/dtype_policy.py
- keras/dtype_policies/dtype_policy_test.py
Fix #19383
Corresponding tests have been added.
> Fix `DTypePolicy` serialization

- keras/export/export_lib.py
- keras/export/export_lib_test.py
In the current JAX export, while the variables are exported as `tf.Variable`s, these `tf.Variable`s are not at all connected to the graph. Instead, all the weights of the variables are inlined in the graph as constants.
As a consequence:
- The export is almost twice the size it should be
- One easily runs into the 2GB limit for the graph size with models with a lot of parameters
- Models that use RNGs in inference mode fail to export with a "leak" error.
This PR fixes the issues above by creating a stateless function, jax2tf converting it and binding the variables to the function in a `tf.function` wrapper. This follows the pattern documented at https://github.com/google/jax/blob/main/jax/experimental/jax2tf/README.md#saved-model-with-parameters .
Also:
- Fixed an issue where with the JAX …
> Fix variables binding in JAX export.

- keras/saving/saving_lib.py
I think this was just straggler code from a previous refactor.
> Remove dead code in saving lib

- keras/ops/function_test.py
I have added tests for model serialization and empty inputs and outputs in function in `ops/function_test.py`
> Add tests for model serialization and empty inputs/outputs in function

- keras/metrics/accuracy_metrics_test.py
Enhance test coverage for `keras/metrics/accuracy_metrics.py` by addressing untested lines reported by `codecov`
> Enhance Testing Coverage for `keras/metrics/accuracy_metrics.py`

- keras/metrics/f_score_metrics_test.py
Enhance test coverage for `keras/metrics/f_score_metrics.py` by addressing untested lines reported by `codecov`
> Enhance Testing Coverage for `keras/metrics/f_score_metrics.py`

- keras/export/export_lib.py
- keras/export/export_lib_test.py
- Make the batch size dynamic for `model.export()` in the same way that it is with `ExportArchive`.
- Add support for non batch size dynamic dimensions for JAX. Previously, all dynamic dimensions where assumed to be the batch size, which only works for dimension 0.
Also added support for passing `polymorphic_shapes` in `jax2tf_kwargs`. This allows having constraints between dynamic dimensions. This allows easy control of dimensions without having the user call `jax2tf` by hand outside of `ExportArchive`.
> Add support for dynamic dimensions with model export.

- keras/backend/common/variables.py
> Add docstrings for `KerasVariable` #19266

- keras/ops/numpy.py
- keras/ops/numpy_test.py
> Add symbolic shape to nonzero

- keras/ops/math_test.py
I have added missing tests for `ops/math.py`
and 
I have suggested #19494
> Add missing tests for `ops/math.py`

- keras/src/saving/serialization_lib.py
- keras/src/saving/serialization_lib_test.py
fixes https://github.com/keras-team/keras/issues/19561
> Ellipsis Serialization and tests

- keras/src/backend/mlx/numpy.py
Added tensordot by using `mlx.core.tensordot(...)` function.
Note: I added `median()` implementation but I removed it because it will be better to add it in a different PR.
> Added tensordot

- keras/src/layers/core/embedding.py
Related to https://github.com/keras-team/keras-nlp/pull/1591
Mainly, this PR reduces quantization error by choosing `output_dim` as reduced axis because, typically, `input_dim` is larger than `output_dim`.
> Reduce int8 quantization error for `Embedding` layer

- .github/workflows/actions.yml
- .github/workflows/nightly.yml
- shell/api_gen.sh
* Output format changes when running `./shell/api_gen.sh`.
* Lint the users code before running API Gen.
> output format changes and errors in github

- keras/src/backend/mlx/math.py
- keras/src/backend/mlx/numpy.py
The `median` function has successfully passed all 30 test cases 
```Python
======================================= test session starts ========================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.4.0
rootdir: /content
plugins: anyio-3.7.1
collected 30 items                                                                                 
test_median.py ..............................                                                [100%]
======================================== 30 passed in 0.35s ========================================
```
Here’s a summarized overview of the tests performed on the `median` function:
- **Basic Functionality**: Tested the function's ability to calculate the median of single-dimensional arrays without altering the …
> Implement missing functions in mlx backend

- keras/src/models/cloning.py
- keras/src/models/cloning_test.py
- keras/src/ops/function.py
@martin-gorner PTAL. What would you test it on?
> Implement custom layer insertion in clone_model.

- requirements-jax-cuda.txt
- requirements-tensorflow-cuda.txt
- requirements-torch-cuda.txt
- requirements.txt
Reverts keras-team/keras#19654
> Revert "Bump the python group with 2 updates"

- keras/src/backend/tensorflow/numpy.py
- keras/src/ops/numpy.py
- keras/src/ops/operation_utils.py
Note that this fix will replace a different fix in Keras-nlp that addresses the same issue https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/src/backend/ops.py#L26
> Fix static shape for `take_along_axis` with Tensorflow.

- keras/src/layers/normalization/layer_normalization.py
Fix bug in `LayerNormalization` with `rms_scaling` set to `True`.
Fixes #19642
> Fix bug in layernorm with rms_scaling=True

- keras/src/backend/jax/numpy.py
- keras/src/layers/convolutional/conv1d.py
- keras/src/layers/convolutional/conv1d_transpose.py
- keras/src/layers/convolutional/conv2d.py
- keras/src/layers/convolutional/conv2d_transpose.py
- keras/src/layers/convolutional/conv3d.py
- keras/src/layers/convolutional/conv3d_transpose.py
- keras/src/layers/convolutional/depthwise_conv1d.py
- keras/src/layers/convolutional/depthwise_conv2d.py
- keras/src/layers/convolutional/separable_conv1d.py
- keras/src/layers/convolutional/separable_conv2d.py
- keras/src/layers/pooling/average_pooling1d.py
- keras/src/layers/pooling/average_pooling2d.py
- keras/src/layers/pooling/average_pooling3d.py
- keras/src/layers/pooling/max_pooling1d.py
- keras/src/layers/pooling/max_pooling2d.py
- keras/src/layers/pooling/max_pooling3d.py
- keras/src/ops/numpy_test.py
Additionally, fix the formatting error
> Fix dtype test for `trace`

- keras/src/dtype_policies/__init__.py
- keras/src/dtype_policies/dtype_policy_test.py
- keras/src/ops/operation_test.py
These tests should prevent the future breakages.
Also, add support for `DTypePolicy` in `keras.dtype_policies.get`
> Add more tests for `DTypePolicy`

- keras/src/backend/mlx/numpy.py
This PR contributes to #19571 and implements arctan2 that was merged into mlx.
> Added arctan2 operation

- keras/src/backend/mlx/linalg.py
Add implementation for ops - qr, cholesky, svd, inv
> mlx - linalg ops

- keras/src/layers/normalization/layer_normalization.py
> Fix `LayerNormalization.get_config`

- keras/src/layers/core/lambda_layer.py
> Fix TypeError in `Lambda.from_config`

- keras/src/ops/core.py
> doc: `ops.slice`

- keras/src/layers/normalization/unit_normalization.py
Added missing closing bracket and exact output value in example code after replicating the code.
> corrected the example code in unit_normalization.py

- keras/src/initializers/__init__.py
- keras/src/initializers/random_initializers_test.py
- keras/src/layers/rnn/gru.py
- keras/src/layers/rnn/gru_test.py
Fix #19828 
Just two simple fixes. Tests have been added.
> Fix the compatibility issues of `Orthogonal` and `GRU`

- keras/api/_tf_keras/keras/ops/image/__init__.py
- keras/api/ops/image/__init__.py
- keras/src/backend/jax/image.py
- keras/src/backend/numpy/image.py
- keras/src/backend/tensorflow/image.py
- keras/src/backend/torch/image.py
- keras/src/ops/image.py
- keras/src/ops/image_test.py
These two functions are useful for image prerpocessing and augmentation
Most of the implementations are inspired by:
https://github.com/google-deepmind/dm_pix
EDITED:
Decrease the values of `atol` in `keras/src/ops/image_test.py`. They were set too high.
> Add `rgb_to_hsv` and `hsv_to_rgb`

- keras/src/metrics/reduction_metrics.py
- keras/src/metrics/reduction_metrics_test.py
This would cause dynamic shapes to not work properly with the Tensorflow backend.
> Fix for broadcast in metrics reduction.

- keras/src/backend/torch/core.py
> resolve torch device placement issue for associative_scan

- keras/src/backend/jax/image.py
- keras/src/backend/numpy/image.py
- keras/src/backend/tensorflow/image.py
- keras/src/backend/torch/image.py
- keras/src/layers/preprocessing/center_crop_test.py
- keras/src/layers/preprocessing/resizing_test.py
- keras/src/utils/image_utils.py
Addresses #19723, #19725 
Also added test cases to verify that the erroring code mentioned in the above issue now works. Thanks!
> address zero division in crops

- keras/src/backend/tensorflow/random_test.py
> Fix TF's GPU CI

- keras/src/layers/attention/multi_head_attention.py
- keras/src/layers/attention/multi_head_attention_test.py
> More robust MHA errors for mismatched shapes

- keras/src/trainers/trainer.py
Added details and a more complete example of how to use custom metrics.
Also corrected inaccurate statement about the tracking of custom metrics.
> Updated docstring for `Model.compute_metrics()`.

- keras/src/models/model_test.py
- keras/src/trainers/compile_utils.py
There are some edge cases that current `CompileLoss` will fail:
```python
from keras import Input
from keras import models
x = np.random.rand(8, 3)
y1 = np.random.rand(8, 1)
y2 = np.random.randint(0, 2, (8, 1))
inputs = layers.Input(shape=(3,), name="input_a")
output = layers.Dense(1, name="output")(inputs)
model = models.Model(inputs, {"output_a": output, "output_b": output})
init_weights = model.get_weights()
model.compile(
optimizer="sgd",
loss={
"output_a": "mean_squared_error",
"output_b": "binary_crossentropy",
},
)
model.fit(x, (y1, y2), batch_size=2, epochs=1, shuffle=False)
class MyModel(models.Model):
def __init__(self):
inputs = Input(shape=(3,), name="inputs")
outputs = layers.Dense(1, name="a")(inputs) …
```
> Simplify and improve `CompileLoss`

- keras/src/backend/tensorflow/optimizer.py
- keras/src/backend/tensorflow/optimizer_distribute_test.py
- keras/src/backend/tensorflow/trainer.py
- keras/src/ops/nn_test.py
- requirements.txt
We are getting some reports form customers that this is breaking TPUStrategy runs.
We don't have a nice minimal repro yet, will work on that next week! But going to roll this back for now while we figure it out.
> Rollback tf distribute change

- keras/src/ops/nn.py
- keras/src/ops/nn_test.py
Fixing issue [#20021](https://github.com/keras-team/keras/issues/20021), if tuple axis case on softmax function should be fixed.
If not, feel free to comment on this, and give me a feedback. :)
> Fixing issue #20021: Unexpected result on keras.ops.nn.softmax when running with tuple axis

- keras/src/layers/core/einsum_dense.py
- keras/src/layers/core/einsum_dense_test.py
Fix https://github.com/keras-team/keras-nlp/issues/1705
The root cause is that we need to restore the proper shape of `kernel_scale` for dequantization to merge lora weights in qlora. Currently, the tests do not catch this issue. A new test with the same config as `Gemma` has been added.
I have verified that `Gemma`, `Gemma2` and `PaliGemma` work with the fix in this PR:
```python
import keras
from keras_nlp import models
init_kwargs = [
{
"vocabulary_size": 20,
"num_layers": 2,
"num_query_heads": 4,
"num_key_value_heads": 1,
"hidden_dim": 16,
"intermediate_dim": 32,
"head_dim": 4,
"layer_norm_epsilon": 1e-6,
},
{
"vocabulary_size": 20,  # 256128
"num_layers": 2,  # 46
"num_query_heads": 4,  # 32
"num_key_value_heads": 2,  # 16
"hidden_dim": 16,  # …
```
> Fix QLoRA saving/loading

- keras/src/layers/layer.py
- keras/src/layers/layer_test.py
> Add clear deprecation error message for add_metric()

- keras/src/backend/tensorflow/optimizer.py
- keras/src/backend/tensorflow/optimizer_distribute_test.py
- keras/src/backend/tensorflow/trainer.py
- keras/src/ops/nn_test.py
- keras/src/trainers/trainer_test.py
- requirements.txt
Re-revert #19969 & fixing issue #20045
> Reland tf distribute fix

- keras/src/layers/convolutional/conv2d.py
- keras/src/layers/convolutional/conv3d.py
Updated Conv2D and Conv3D description. Fixes: [#20052](https://github.com/keras-team/keras/issues/20052)
> 2D CNN's and 3D CNN's description update. 

- keras/src/layers/preprocessing/rescaling.py
- keras/src/layers/preprocessing/rescaling_test.py
> Add numpy `scale` and `offset` support to `Rescaling`

- keras/src/backend/jax/distribution_lib.py
We should raise an error if the number of model replicas (batch dim) is not divisible by the number of processes because otherwise, the splitting fails (we don't support padding).
> Improve error handling in distribution lib

- keras/src/applications/densenet.py
Updated default classes values in Densenet documentation. Fixes [#20184](https://github.com/keras-team/keras/issues/20184)
> Updated classes details in Densenet Documentation

- .devcontainer/devcontainer.json
Updated devcontainer.json to include `pip install -r requirements.txt` to speed up future contributions and cut back on the commands required to remember after instantiating a dev container for future contributors!
> [#20238] updated devcontainer to include pip install

- keras/src/models/model.py
- keras/src/models/model_test.py
This PR adds public APIs to set and get model variables.
> Add public APIs for model variables

- keras/src/backend/tensorflow/numpy.py
`N`, `M` and `k` can now be tensors and not just ints, which is useful when these parameters come from dynamic dimensions in a shape.
> Reimplement `eye` op on TF to support tensors as inputs.

- keras/src/layers/convolutional/depthwise_conv2d.py
Modifying existing example code
> Modified example in DepthwiseConv2D file

- keras/src/backend/common/tensor_attributes.py
WeakKeyDictionary is really what we wanted for this, but the issue is that tensors are not hashable and can't be used as keys.
By making values weakly referenced, we can run in two issues:
- After a mask is set, typically nothing keeps a reference to the mask, so if garbage collection happens, all masks are likely lost.
- After a tensor used as key is garbage collected, nothing notifies WeakValueDictionary because the id is just an id an not connected to the tensor object, so the key/value pair is not removed from the dictionary. When the id is reused, a random tensor can get paired with a random preexisting mask.
This fix uses finalizers to be notified that a tensor is garbage collected to clear its mask.
> Fix `set_tensor_attr` bug related to garbage collection.

- keras/src/testing/test_case.py
Fix for https://github.com/keras-team/keras/issues/20118
> Preserve tuple type in json dump/load

- keras/src/layers/activations/activation.py
Passing Python list directly to the keras layer object in Example from activation.py is throwing Value error.  Fixed the error by passing tensor as a input. Here is the [gist](https://colab.sandbox.google.com/gist/LakshmiKalaKadali/caefd982bfff4ff6c4139784236c3a17/quickstart_colab.ipynb#scrollTo=F3hV2zfCb7Nu).
Thank You
> Fixed the Value error in Example from activation.py

- keras/src/activations/activations_test.py
- keras/src/ops/nn.py
I found some typographical errors in the test cases and API description examples, so I corrected them.
> correct misspelling and test case

- keras/src/trainers/trainer.py
Clearly documented what all the options are for `x` and all the implications for other arguments.
Also made the documentation more consistent between the arguments and between `fit`, `evaluate` and `predict`.
> Tweaked documentation of `Model`'s `fit`, `evaluate` and `predict`.

- keras/src/callbacks/tensorboard.py
This bug caused batch level metrics and evaluation metrics to all be reported for step 0, which would not show a graph.
Epoch level metrics, were not affected by this bug.
The fix was tested manually on a training run.
> Fix steps for `TensorBoard` callback for evaluation and batch metrics.

- keras/src/initializers/__init__.py
- keras/src/initializers/random_initializers_test.py
- keras/src/layers/core/dense.py
- keras/src/layers/core/einsum_dense.py
- keras/src/layers/core/embedding.py
Fix #19767
This PR also simplified the int8 weights assignment during quantization.
> Add support for direct tensor as initializer

- keras/src/callbacks/backup_and_restore.py
- keras/src/callbacks/backup_and_restore_test.py
- keras/src/utils/file_utils.py
Fixes https://github.com/keras-team/keras/issues/20463
> Double backup

- keras/src/layers/preprocessing/image_preprocessing/center_crop.py
- keras/src/layers/preprocessing/image_preprocessing/center_crop_test.py
I implemented the transform_bounding_boxes method to handle center cropping. 
Could you please review my code and let me know if there are any corrections or improvements needed?
here is [gist](https://colab.research.google.com/drive/1LQEOczv4WLYycS5UnhkXMlZH02CRPSI2?usp=sharing)
> implement transform_bounding_boxes for center_crop

- keras/src/metrics/reduction_metrics.py
Fixes rendering issue here https://keras.io/api/metrics/metrics_wrappers/#mean-class
> Fix rendering issue

- keras/src/models/functional_test.py
Test was counting warnings, but some other components can throw unrelated warnings.
This makes sure we only count the warnings we're looking for.
> Make test resilient to spurious warnings.

- keras/src/ops/core.py
- keras/src/ops/core_test.py
`convert_to_tensor(x, sparse=False)` is the API to densify sparse tensors. When used in that manner, the input is already a backend tensor. For this scenario, it makes sense to support symbolic tensors so that one can build a functional model using `convert_to_tensor`.
Also improved the documentation of `convert_to_tensor`.
> Add support for symbolic tensors to `convert_to_tensor`.

- keras/src/layers/preprocessing/image_preprocessing/random_translation.py
- keras/src/layers/preprocessing/image_preprocessing/random_translation_test.py
I have implemented the transform_bounding_boxes method to support random zoom functionality. 
Please let me know if any corrections are needed.
here is [gist](https://colab.research.google.com/drive/1LQEOczv4WLYycS5UnhkXMlZH02CRPSI2?usp=sharing)
> implement transform_bounding_boxes for random_translation

- keras/src/metrics/regression_metrics.py
Multiple Example Title has removed in metrics cosineSimilarity method.
> Multiple Example Title has been removed

- keras/api/_tf_keras/keras/ops/__init__.py
- keras/api/_tf_keras/keras/ops/numpy/__init__.py
- keras/api/ops/__init__.py
- keras/api/ops/numpy/__init__.py
- keras/src/backend/jax/numpy.py
- keras/src/backend/numpy/numpy.py
- keras/src/backend/tensorflow/numpy.py
- keras/src/backend/torch/numpy.py
- keras/src/ops/numpy.py
- keras/src/ops/numpy_test.py
> Add diagflat op

- keras/api/_tf_keras/keras/layers/__init__.py
- keras/api/layers/__init__.py
- keras/src/layers/__init__.py
- keras/src/layers/preprocessing/image_preprocessing/equalization.py
- keras/src/layers/preprocessing/image_preprocessing/equalization_test.py
@fchollet 
[collab](https://colab.research.google.com/drive/1qqvSbHoMBYjZoM_aVwiwchnHFYtRdCMJ?usp=sharing)
> Add Equalization Layer

- keras/src/metrics/iou_metrics.py
Multiple Example title has been removed in OneHotIoU file.
> Multiple Example title has been removed in OneHotIoU

- keras/src/layers/preprocessing/text_vectorization_test.py
Trying to address TODO:
```python
```
I think this PR covers most basic functionalities.
> [TextVectorization Layer] Added tests for testing the funtionality

- keras/api/_tf_keras/keras/layers/__init__.py
- keras/api/layers/__init__.py
- keras/src/layers/__init__.py
- keras/src/layers/preprocessing/image_preprocessing/mix_up.py
- keras/src/layers/preprocessing/image_preprocessing/mix_up_test.py
I have implemented MixUp image processing. If this implementation is acceptable, I can proceed to add the corresponding test cases.
here is my [gist](https://colab.research.google.com/drive/1lpFMvyqN5pFNxdtAjr8pOMpJS_kezkvm?usp=sharing)
> Add implementations for mix_up

- keras/src/backend/jax/distribution_lib.py
- keras/src/distribution/distribution_lib.py
Remove `DO NOT USE` from the top of distribution_lib files as the Jax backend is supported.
> Update `distribution_lib` files docstrings

- keras/src/layers/preprocessing/image_preprocessing/mix_up.py
I corrected an issue where the data_format argument was not passed to the super().__init__() method.
> Correct bug for MixUp initialization.

- keras/api/_tf_keras/keras/layers/__init__.py
- keras/api/layers/__init__.py
- keras/src/layers/__init__.py
- keras/src/layers/preprocessing/image_preprocessing/random_hue.py
- keras/src/layers/preprocessing/image_preprocessing/random_hue_test.py
I have implemented the RandomHue image processing feature. Please let me know if any further corrections or improvements are required.
here is my [gist](https://colab.research.google.com/drive/1WrdTiyBvOCWFERooeKE5ddT-Y_HctKAA?usp=sharing)
> Add implementations for random_hue

- keras/src/layers/preprocessing/image_preprocessing/random_hue.py
I have updated the code with the following changes:
1. Modified the example to ensure it works seamlessly on the Keras platform.
2. Adjusted the invert implementation to apply different weights to each sample in the batch, enabling more diverse augmentations.
> Update example and logic for random_hue

- keras/api/_tf_keras/keras/layers/__init__.py
- keras/api/layers/__init__.py
- keras/src/layers/__init__.py
- keras/src/layers/preprocessing/image_preprocessing/random_grayscale.py
- keras/src/layers/preprocessing/image_preprocessing/random_grayscale_test.py
@fchollet 
[colab](https://colab.research.google.com/drive/1qqvSbHoMBYjZoM_aVwiwchnHFYtRdCMJ?usp=sharing)
> Add RandomGrayscale Layer

- keras/src/layers/preprocessing/image_preprocessing/random_hue.py
> Fix Randomhue

- keras/src/layers/rnn/gru.py
The simplified implementation, which used the same recurrent dropout masks for all the previous states didn't work and caused the training to not converge with large enough recurrent dropout values.
This new implementation is now the same as Keras 2. Note that recurrent dropout requires "implementation 1" to be turned on.
Fixes https://github.com/keras-team/keras/issues/20276
> Fix recurrent dropout for GRU.

- keras/src/utils/model_visualization.py
Fixes #20681 
Feel free to add your suggestions!
> Change the import order of pydot and its older forks

- keras/api/_tf_keras/keras/layers/__init__.py
- keras/api/layers/__init__.py
- keras/src/layers/__init__.py
- keras/src/layers/preprocessing/image_preprocessing/random_color_degeneration.py
- keras/src/layers/preprocessing/image_preprocessing/random_color_degeneration_test.py
I have implemented the RandomColorJitter image processing feature. Please let me know if any further corrections or improvements are required.
here is my [gist](https://colab.research.google.com/drive/1SbOuNDMJuP_IanVZ17VQrbFFGqhrFkds?usp=sharing)
> Add random_color_degeneration processing layer

- keras/src/backend/common/variables.py
- keras/src/backend/tensorflow/distribute_test.py
- keras/src/layers/layer.py
- keras/src/optimizers/base_optimizer.py
Fix #20695 
Fix #20698 
Fix #20699 
Fix #20700 
In this PR, the aggregation behavior is now consistent with `tf_keras`.
(I'm not sure how to test this using `tf.distribute`)
> Fix the aggregation in the codebase

- keras/src/saving/serialization_lib.py
Not all of their symbols are exported.
> Fix serialization of domain packages.

- keras/src/metrics/iou_metrics.py
removed example title in metrics.BinaryIoU class
> Multiple Example Title has been removed in metrics.BinaryIoU

- keras/src/backend/mlx/math.py
This just implements fft for the mlx backend, contributing to #19571
> mlx fft implementation

- keras/api/_tf_keras/keras/layers/__init__.py
- keras/api/layers/__init__.py
- keras/src/layers/__init__.py
- keras/src/layers/preprocessing/image_preprocessing/random_invert.py
- keras/src/layers/preprocessing/image_preprocessing/random_invert_test.py
I have implemented the RandomInvert image processing feature. Please let me know if any further corrections or improvements are required.
here is my [gist](https://colab.research.google.com/drive/1LjfUet6Dd-N4QG8EIF9yYkchjxwJfgYZ?usp=sharing)
> Add random_invert layer

- keras/src/backend/mlx/nn.py
This relates to #19571 
The tests look good! All tests are passing for `keras/src/layers/rnn` now too
> `mlx.nn.conv` implementation

- keras/src/backend/jax/trainer.py
this change will allow users to customize what happens in the step function while being able to use existing metrics update logic without needing to duplicate it
> extract metrics update logic into a helper method

- keras/src/layers/preprocessing/image_preprocessing/random_zoom.py
Update fill_mode argument default value in RandomZoom class Fixed [#20794](https://github.com/keras-team/keras/issues/20794)
> Update fill_mode argument default value in RandomZoom class

- keras/src/visualization/plot_image_gallery.py
* Add `y_true`, `y_pred` and `label_map` arguments for plotting ImageClassification tasks scenario using `plot_image_gallery` method.
> provided y_true or y_pred add labels for plot image gallery method

- keras/src/backend/jax/trainer.py
The state sharding is leaked at the end of `fit`, `evaluate` and `predict`. The values are not reused if `fit`, `evaluate` and `predict` is called again.
> Clear JAX state sharding after `fit`, `evaluate` and `predict`.

- keras/src/layers/preprocessing/image_preprocessing/random_perspective.py
This PR ensures the exposed APIs convert the inputs to the tensors.
> Fix Torch GPU CI

- keras/src/backend/tensorflow/linalg.py
The error occurred while using the map() and solve() methods with a TensorFlow dataset. To resolve this issue, I modified the source code accordingly.
here is my [gist](https://colab.research.google.com/drive/1dt5Kgx-bhALHkdMjbebVYAogyqkLPFp9?usp=sharing)
> [Fix] solve method on linalg

- keras/src/backend/openvino/excluded_concrete_tests.txt
- keras/src/backend/openvino/numpy.py
**Details:** It serves as exemplar for opensource community who will contribute to OpenVINO backend via good-first-issues.
cc, @fchollet, could you please review?
> [OpenVINO backend] Support numpy.amax and numpy.amin

- keras/src/models/sequential.py
Before:
```
def pop(self, rebuild=True):
"""Removes the last layer in the model."""
```
After:
```
def pop(self, rebuild=True):
"""Removes the last layer in the model.
Args:
rebuild: `bool`. Whether to rebuild the model after removing
the layer. Defaults to `True`.
Returns:
layer: layer instance.
"""
```
> docs: add params to Sequential.pop docstring

- keras/api/_tf_keras/keras/ops/image/__init__.py
- keras/api/ops/image/__init__.py
- keras/src/backend/jax/image.py
- keras/src/backend/numpy/image.py
- keras/src/backend/tensorflow/image.py
- keras/src/backend/torch/image.py
- keras/src/ops/image.py
- keras/src/ops/image_test.py
I have implemented the perspective_transform method using NumPy and TensorFlow. If this concept and implementation prove to be applicable, I can proceed with adding support for Torch and JAX as well.
here is my [gist](https://colab.research.google.com/drive/1GhIKYjaeaYP4-B-mWvh98rM3MK5b3lzc?usp=sharing)
> Add perspective_transform for ops

- keras/src/metrics/reduction_metrics.py
Fixes internal tests broken by https://github.com/keras-team/keras/pull/20782
> Fix mean metrics to allow dict/list inputs

- keras/api/_tf_keras/keras/ops/image/__init__.py
- keras/api/ops/image/__init__.py
- keras/src/backend/jax/image.py
- keras/src/backend/numpy/image.py
- keras/src/backend/tensorflow/image.py
- keras/src/backend/torch/image.py
- keras/src/ops/image.py
- keras/src/ops/image_test.py
I have implemented the gaussian_blur method for ops. If any corrections or improvements are needed, please let me know.
Additionally, I referred to this [implementation](https://pytorch.org/vision/0.16/generated/torchvision.transforms.functional.gaussian_blur.html) for reference.
You can find my implementation in this [gist](https://colab.research.google.com/drive/11ks-MB4rBW6gvt-FmAzVWLMsBCAwW58c).
> Add gaussian_blur for image

- keras/src/backend/jax/image.py
- keras/src/layers/preprocessing/image_preprocessing/random_gaussian_blur.py
I have updated the RandomGaussianBlur layer to utilize the gaussian_blur method from the image layer. If any additional corrections are required, please feel free to let me know.
here is my [gist](https://colab.research.google.com/drive/1ECBkK4aLhtyDgIAw_U1OEYXZKaL4Fj86?usp=sharing)
> Update the RandomGaussianBlur layer to utilize the image layer method

- keras/src/layers/preprocessing/image_preprocessing/resizing.py
- keras/src/layers/preprocessing/image_preprocessing/resizing_test.py
Sometimes we need `antialias` to be consistent with the numerics.
> Add `antialias` to `layers.Resizing` and add more tests.

- keras/src/legacy/saving/legacy_h5_format_test.py
- keras/src/legacy/saving/saving_utils.py
Fix legacy model saving & reloading with axis argument in its layer.
Might fix #20963.
> fix legacy model saving & reloading with axis argument in its layer

- keras/src/backend/jax/nn.py
- Flash attention was not being called on TPU because of a if condition that skipped it
- the condition has been fixed also the implementation has been updated to fix the dimension of q,k and v
> Fix flash attention TPU error

- keras/src/backend/jax/nn.py
- keras/src/backend/numpy/nn.py
- keras/src/backend/tensorflow/nn.py
- keras/src/backend/torch/nn.py
- keras/src/ops/nn.py
The attn_logits_soft_cap is only available in JAX TPU backend. I am adding the optional arg to enable that
> Add optional arg for attention logits soft cap for jax tpu backend

- keras/src/backend/numpy/image.py
I've replaced the JAX version of jax.image.resize with a NumPy-based implementation that closely mirrors the original behavior. Please review the updated code and let me know if any further corrections or improvements are needed.
> Removed jax dependency from numpy image layer

- keras/src/backend/openvino/excluded_concrete_tests.txt
- keras/src/backend/openvino/numpy.py
**Details:** Support numpy exp and expand_dims
> [OpenVINO Backend] Support numpy exp and expand_dims

- keras/src/backend/openvino/excluded_concrete_tests.txt
- keras/src/backend/openvino/numpy.py
- pytest.ini
@rkazants, could you please review it?
> [Good First Issue][Keras 3 OpenVINO Backend]: Support numpy.dot operation #29119

- keras/src/backend/tensorflow/image.py
- keras/src/backend/torch/image.py
- keras/src/ops/image_test.py
I fixed typos in the TensorFlow implementation and added a test case.
> Fix typos and add a test case for elastic_transform

- keras/api/_tf_keras/keras/layers/__init__.py
- keras/api/layers/__init__.py
- keras/src/backend/tensorflow/image.py
- keras/src/layers/__init__.py
- keras/src/layers/preprocessing/image_preprocessing/random_elastic_transform.py
- keras/src/layers/preprocessing/image_preprocessing/random_elastic_transform_test.py
I have implemented the RandomElasticTransform image processing feature. Please let me know if any further corrections or improvements are required.
Here is my [gist](https://colab.research.google.com/drive/11ZHPpNYZ_WctRlggDuxAwJQpMLiVxWtb?usp=sharing)
> Add RandomElasticTransform layer

- keras/src/backend/tests/device_scope_test.py
- keras/src/backend/torch/core.py
Fixes #21052 and #19376 for the torch backend.
> Add support for torch tensors on meta device

- keras/api/_tf_keras/keras/losses/__init__.py
- keras/api/losses/__init__.py
- keras/src/losses/losses.py
- keras/src/losses/losses_test.py
Adding a new loss that helped me to fight some noisy datasets in the past.
Details:
https://arxiv.org/abs/1805.07836
> feat: add Categorical Generalized Cross Entropy (GCE) loss

- keras/src/backend/tests/device_scope_test.py
> Fix torch gpu tests

- keras/src/saving/saving_lib.py
This PR defers the creation of the H5 entry group until `__setitem__` is called, preventing the creation of empty groups.
For example, previously unused `vars` will be removed in this PR.
Backward compatibility is maintained by using an empty dictionary for unmatched paths.
> Remove the empty H5 groups in `H5IOStore`

- keras/src/optimizers/muon.py
- keras/src/optimizers/muon_test.py
I'm the author of [#21037](https://github.com/keras-team/keras/commit/717a64a3a467d4ee19dd9314e8e2402593d826bd), and I found that I made a mistake in this document. I'll just revise it again.
> fix muon document

- keras/src/backend/torch/core.py
Resolves https://github.com/keras-team/keras/issues/21096
Haven't added a unit test for this. Let me know if we want to.
> Fix scatter_update bug for torch

- keras/src/layers/layer.py
- keras/src/models/functional_test.py
When constructing a Functional model with a global dtype policy, a spurious `Cast` operation would appear in the graph before each layer. This cast is part of the layer `__call__` method and should not appear separately.
> Fix Functional model graph under global dtype policy.

- keras/src/backend/tensorflow/sparse.py
Fixes https://github.com/keras-team/keras/issues/21069
> Add support for dynamic dimensions for ops handling `tf.IndexedSlices`.

- keras/src/testing/test_case.py
Adds the expected/actual output shapes/dtypes in the failure message.
Also greatly simplifies the code by using `keras.tree`.
> Add details when `TestCase.run_layer_test` output verification fails.

- requirements-common.txt
- requirements.txt
We also want it for cuda installations.
> Add pre-commit to the common requirements file

- .github/workflows/actions.yml
- .github/workflows/nightly.yml
They have been broken for a month
> Fix nightly releases

- keras/src/utils/file_utils.py
- keras/src/utils/file_utils_test.py
Recognize /tfhub as a remote location.
> Recognize /tfhub as a remote location.

- keras/src/metrics/confusion_metrics.py
> Updated confusion_metrics.py

- keras/src/backend/openvino/excluded_concrete_tests.txt
- keras/src/backend/openvino/numpy.py
@rkazants 
I removed the reciprocal to another PR.
> [OpenVINO Backend] support reciprocal

- keras/src/backend/openvino/excluded_concrete_tests.txt
- keras/src/backend/openvino/numpy.py
Hi @rkazants 
I’ve updated ```ops.stack``` to support tuples, which is needed for my GSoC project to enable pipelines.
Could you please review the changes when you have a moment?
Thank you!
> [OpenVINO Backend] update ops.stack to support tuples

- keras/src/metrics/confusion_metrics.py
Modified compile() API in tf.keras.metrics.SpecificityAtSensitivity.
> Modified confusion_metrics.py

- keras/src/callbacks/model_checkpoint.py
- keras/src/callbacks/monitor_callback.py
Check for `self.best is None` when printing logs.
> Fix callback

- keras/src/backend/openvino/core.py
Hi @rkazants ,
Supporting `__rpow__` for `OpenVINOKerasTensor`, which is needed for my GSoC project.
Could you please review it?
> [OpenVINO Backend] support __rpow__ for OpenVINOKerasTensor

- keras/src/layers/normalization/layer_normalization.py
- keras/src/layers/normalization/layer_normalization_test.py
- keras/src/ops/nn.py
~This will likely break SD3 numerics~
> Raise warning when rms_scaling = True

- keras/src/layers/rnn/rnn.py
reported here -  https://fusion2.corp.google.com/invocations/ed2b0baf-40ff-482b-bc33-3d4eac5a0463/targets/%2F%2Fthird_party%2Fpy%2Fkeras:src%2Flayers%2Frnn%2Fbidirectional_test_jax/tests
> Fix numpy upgrade error 

- keras/src/layers/reshaping/flatten.py
- keras/src/layers/reshaping/flatten_test.py
With TensorFlow, when both the batch size and some other dimensions are dynamic, we need to use the dynamic batch size that comes from `ops.shape` instead of None / -1, otherwise there are two Nones / -1s passed to `ops.reshape`.
Fixes https://github.com/keras-team/keras/issues/21380
> Add support for multiple dynamic dimensions to `Flatten` layer on TF.

- keras/src/distribution/distribution_lib.py
- keras/src/trainers/data_adapters/__init__.py
It is assumed that the data is already pre-sharded across hosts.
If `distribution.auto_shard_dataset` is `True` but the input dataset isn't a tf.data.Dataset, will error out as before. Setting `auto_shard_dataset` to `False` will allow any dataset type to be used.
Unfortunately we can't add a test for this in OSS since we don't have a multi-process test fixture.  However, this was tested internally.
> Support non-tf.data.Dataset instances in multi-host setting.

- keras/src/backend/openvino/core.py
@rkazants 
I encountered problems when multiplying booleans while enabling the pipelines.
> [OpenVINO backend] supporting mul with bools

- keras/src/layers/preprocessing/image_preprocessing/rand_augment.py
- keras/src/layers/preprocessing/image_preprocessing/rand_augment_test.py
Fix for [keras-team/keras#21169](https://github.com/keras-team/keras/issues/21169)
- Modified the logic to update the sample image processing algorithm dynamically for each batch during TensorFlow graph execution.
> Fix RandAugment behavior in tf graph mode

- keras/src/export/openvino.py
> [OpenVINO backend] fix openvino model exported names to match keras names

- keras/src/saving/saving_lib.py
Also update error message which was inaccurate.
> Bug fix with serialization when walking through operations.

- keras/src/saving/saving_lib.py
- keras/src/version.py
Patch release with a small fix
> Version bump 3.11.1

- keras/src/version.py
> update version number

- keras/src/layers/preprocessing/integer_lookup.py
> Fix the `vocabulary_dtype` in `keras.layers.IntegerLookup()`

- keras/src/backend/tensorflow/rnn.py
- keras/src/layers/rnn/gru_test.py
> Fix GRU with return_state=True on tf backend with cuda

- .gemini/styleguide.md
Borrowed content from here - https://github.com/keras-team/governance/blob/master/keras_api_design_guidelines.md
> Create styleguide.md for keras

- keras/src/layers/preprocessing/normalization.py
> Fix the Doc of the combination relation in func `keras.layers.Normalization()`

- keras/api/_tf_keras/keras/ops/__init__.py
- keras/api/_tf_keras/keras/ops/nn/__init__.py
- keras/api/ops/__init__.py
- keras/api/ops/nn/__init__.py
- keras/src/backend/jax/nn.py
- keras/src/backend/jax/rnn.py
- keras/src/backend/numpy/nn.py
- keras/src/backend/openvino/nn.py
- keras/src/backend/tensorflow/nn.py
- keras/src/backend/torch/nn.py
- keras/src/ops/nn.py
- keras/src/ops/nn_test.py
By https://github.com/keras-team/keras/issues/20046
This is an unfold implementation; the API and documentation were referenced from [PyTorch’s version](https://docs.pytorch.org/docs/stable/generated/torch.nn.Unfold.html#unfold).  
At present we only supply backends for JAX, TensorFlow and PyTorch.  
A NumPy implementation has been finished, but its performance would be poor
Finally, I am not able to use  OpenVINO.
> Add unfold op
