keras/backend/tensorflow/numpy.py
When ensuring consistent dtype inference across backends, I found that several tf's numpy ops, such as `cos`, `exp`, `log` and others, incorrectly promote bfloat16 to float64 or uint* to int*.
Currently, our approach involves casting back to the expected dtype. However, this is suboptimal, particularly for `mixed_bfloat16` training, as the intermediates might consume a large amount of memory.
To address this issue, we can replace the tfnp ops with native ops which are more bfloat16-friendly.
=> Revisit tf's numpy api

keras/layers/reshaping/reshape.py, keras/layers/reshaping/reshape_test.py
When using `-1` for one of the dimensions and a dynamic batch size, with the Tensorflow backend, in non eager mode, this would result in Tensors with a `None` dimension where the `-1` was. This is because the `reshape` op does not treat the batch size specially and therefore has no way to determine what goes to the batch dimension vs. the `-1` dimension.
To fix this, we resolve the `-1` to an actual number at build time since the layer knows that the batch dimension is untouched.
Note that this bug would not affect the JAX and PyTorch backends because we inject a fake batch size when needed.
=> Fix for layers.Reshape when using -1 and a dynamic batch size.

keras/backend/jax/numpy.py, keras/backend/numpy/numpy.py, keras/backend/tensorflow/numpy.py, keras/backend/torch/numpy.py, keras/backend/torch/random.py, keras/ops/numpy.py, keras/ops/numpy_test.py
In addition to the applying `backend.result_type`:
- Remove TODO strings in tf's numpy api because there is no particular preference for using tfnp over plain TF APIs (https://github.com/keras-team/keras/pull/18787#pullrequestreview-1734998900)
- Try the best to prevent incorrect bfloat16 promotion
Currently, the status of ops applied `backend.result_type` is as follows (has fully covered A-M):
<details>
</details>
=> Apply `backend.result_type` to `einsum`, `expand_dims`, `flip`, `floor`, `full_like`, `hstack`, `is*`, `meshgrid` and `moveaxis`

keras/backend/jax/distribution_lib.py, keras/backend/jax/distribution_lib_test.py
The https://github.com/keras-team/keras/commit/3d147bed1e7e25ff84b129374784aaf2aabe1ae8 was using the jax.Device.device_kind incorrectly. The jax.Device.device_kind will contain extra information like "tpu v3" or "Tesla V100-SXM2-16GB", which can't be used to parse the type. We should use `platform` instead.
Also adding tests to cover the device conversion logic.
Please also see internal cl in cl/584064211  for tpu in single and multi-process test.
=> Fix the device conversion logic for keras.distribute.list_devices()

keras/testing/test_case.py
This is unimportant, just made this change while debugging a KerasNLP failure so though I would port here as well.
Makes error messages much more readable when things go wrong.
=> Use set comparisons for serialization errors

keras/layers/reshaping/reshape.py, keras/layers/reshaping/reshape_test.py
PR https://github.com/keras-team/keras/pull/18792 broke the case when value for -1 cannot be calculated statically.
=> Fix regression in Reshape layer when using -1.

keras/ops/math_test.py
a pull request to add tests to `keras/ops/math_test.py` 
This update targets the `Qr` and `ExtractSequences `classes, focusing on:
1. QR operation initialization and error handling.
2. Low-rank input and undefined dimension management for Qr.
3. Initialization and functionality tests for ExtractSequences.
=> Add tests in `keras/ops/math.py`

keras/layers/attention/additive_attention_test.py, keras/layers/attention/attention.py, keras/layers/attention/attention_test.py
The API `keras.layers.Attention` implementation has this below line `noise_shape=self.noise_shape` that fails since attention layer has no attribute `noise_shape`. Since this argument passed to the function `backend.random.dropout()` which has  default value set as `None`.So we can set `noise_shape=None` to make it works.
Fixes #18754
=> Set noise_shape to None in attention.py

keras/metrics/reduction_metrics_test.py
For my first commit to Keras, I picked a simple one, addressing two small TODO items in reduction_metrics_test.py.
I believe what the comment "# TODO: Check save and restore config" meant is that an object (Sum or Mean) must be re-constructed from config, and be tested. 
Please let me know if I misunderstood the requirements, or otherwise made any mistakes.
=> Add save and restore config tests to address TODO items.

keras/backend/jax/numpy.py, keras/backend/numpy/numpy.py, keras/backend/tensorflow/numpy.py, keras/backend/torch/numpy.py, keras/ops/numpy.py, keras/ops/numpy_test.py
Addresses #18730 . I've adopted the jax convention of defaulting dtype to the original in the case of ints, rather than integer type promotion as is the numpy/tensorflow/torch approach.
=> added dtype arg to cumsum/cumprod, fixes inconsistency bug

keras/backend/jax/numpy.py, keras/backend/numpy/numpy.py, keras/backend/tensorflow/numpy.py, keras/backend/torch/numpy.py, keras/layers/normalization/unit_normalization.py, keras/layers/preprocessing/normalization.py, keras/ops/numpy.py, keras/ops/numpy_test.py
This PR has addressed the dtype inference for these ops with python `int` and `float` numbers.
The manually casting in the layer implementation from the previous PR can now be removed.
This should enhance UX when implementing new layers to support mixed precision training.
=> Improve dtype inference of `add`, `divide`, `maximum`, `minimum`, `multiply` and `subtract` when using python native dtypes

keras/layers/convolutional/base_conv.py, keras/layers/convolutional/base_depthwise_conv.py, keras/layers/convolutional/base_separable_conv.py, keras/layers/convolutional/conv1d.py, keras/layers/convolutional/conv2d.py, keras/layers/convolutional/conv2d_transpose.py, keras/layers/convolutional/conv3d.py, keras/layers/convolutional/conv3d_transpose.py, keras/layers/convolutional/depthwise_conv1d.py, keras/layers/convolutional/depthwise_conv2d.py, keras/layers/convolutional/separable_conv1d.py, keras/layers/convolutional/separable_conv2d.py
"Updating the args documentation of padding='same' for all convolutional layers.
Reference issue #15703.
Reference PRs #15771 closed due to stale.
The documentation for padding in all conv layers listed above states that, "" ""same"" results in padding with zeros evenly to the left/right or up/down of the input such that output has the same height/width dimension as the input."". This seems incorrect as it is true only when `strides=1`. Hence update the same.
=> Change Conv layers Doc string wrt padding.

keras/backend/jax/numpy.py, keras/backend/numpy/numpy.py, keras/backend/tensorflow/numpy.py, keras/backend/torch/numpy.py, keras/ops/numpy.py, keras/ops/numpy_test.py
Added `constant_values` kwarg to `ops.pad`. This argument is ignored if `mode != 'constant'`, which is different to `numpy` which raises.
=> Added constant_values support to pad

keras/layers/layer.py, keras/layers/layer_test.py
Fixes a bug in the current implementation whereby layers only look 1-child deep for layer losses.
=> Fixed layer.losses such that it recurses into sublayer losses

keras/backend/tensorflow/image.py, keras/layers/preprocessing/random_zoom_test.py
RandomZoom would lose the tensor shape when using with TF backend.
The multiple `None` dims would error out when used combined with the `Flatten` layer.
This PR simply adds back the shape in the underlying ops of TF backend.
=> Bug fix for TF backend using random zoom with flatten

keras/ops/numpy.py
The documentation for the `indices_or_sections` argument appeared twice.
=> Fix glitch in documentation for the `split` operation.

keras/backend/tensorflow/core.py, keras/backend/tensorflow/numpy.py, keras/backend/tensorflow/sparse.py, keras/backend/tests/compute_output_spec_test.py, keras/ops/numpy.py, keras/ops/operation_utils.py
Most Tensorflow sparse operation lose the static shape because the shape is only propagated using the `dense_shape` property, which is a tensor and is dynamic.
This is a workaround for this issue to allow static shape to be propagated as expected with Keras ops.
=> Add support for Tensorflow SparseTensors: preserve static shapes.

keras/backend/jax/trainer.py, keras/backend/numpy/trainer.py, keras/backend/tensorflow/trainer.py, keras/backend/torch/trainer.py, keras/trainers/trainer_test.py
This pull request introduces the `stop_evaluating` and `stop_predicting` attributes available for callbacks, allowing users to halt the evaluation and prediction loops.
The existing `stop_training` attribute makes it possible to interrupt the training loop based on custom criteria in callbacks. However, similar capabilities are not available for the evaluation and prediction loops. The introduction of `stop_evaluating` and `stop_predicting` attributes extends this functionality, allowing users to use callbacks to stop these loops.
1. **Added `stop_evaluating` attribute:**
- Enables users to interrupt the evaluation loop based by marking is as `True` in a callback.
2. **Added `stop_predicting` attribute:**
- Provides the ability to halt the prediction loop based by marking is as `True` in …
=> Adding stop_evaluating and stop_predicting attributes for Callbacks

keras/trainers/data_adapters/py_dataset_adapter.py, keras/trainers/data_adapters/py_dataset_adapter_test.py
The second of two very small issues I ran into trying to run an existing code base on keras 3. This allows the `PyDataset.__getitem__` method to return a dict of tensors, which is a valid way to supply inputs as `Model(inputs={...})` and very convenient for formatting complex inputs. We could add checks in the case of a dict to make sure the batch is not deeply nested, and doesn't contain other invalid objects. This was just a minimal fix.
=> support dict items in PyDataset

keras/backend/common/variables.py, keras/layers/core/input_layer_test.py
One of two very small issues I ran into trying to run an existing code base on keras 3. This allows passing a tuple of numpy (or any other valid) int types to `Input(shape=...)`. I am preloading some data to generate the model shape on the fly, and the lib I'm using to wrangle that data happens to output shape as numpy ints.
=> support numpy int dtypes in shapes

.github/dependabot.yml
Fixes https://github.com/keras-team/keras/issues/18833.
This PR sets up dependabot to update the GitHub Actions used in workflows and the pinned Python dependencies in the requirements files.
Dependabot is set up to send a single monthly PR updating all the dependencies in each ecosystem at once. As a preview, here are the PRs I received on my fork:
- https://github.com/pnacht/keras/pull/1 updating the GitHub Actions
- https://github.com/pnacht/keras/pull/2 updating the Python dependencies
For the Python dependencies, it:
- updates the patch-version-pinned `torch` and `torchvision` in `requirements-torch-cuda.txt`
- It also updates `tf-nightly` and `tf-nightly-cpu` to the latest nightly build. If you'd rather not have this update automatically (due to potential breakages), let me know and …
=>  Add dependabot to update GHA and Python deps

keras/backend/tensorflow/rnn.py
Regression caused by #18610 
Fixes #18854 .  Also verified it doesn't re-introduce the masking issue - #18397
Wrapping check of `inputs_supported` in `tf.function` takes 200+ ms on each call.  Without this check LSTM layer returns results in 15ms/step for imdb keras.io example.  If we don't wrap it in `tf.function`, that causes masking issue since we are comparing python bool from `cudnn_supported` with TF symbolic tensor from `inputs_supported`.
This check on `inputs_supported` may not be necessary?
Colab testing the fix: https://colab.research.google.com/drive/1EFFINfOGp-htUvLZu_oK5aCzOWFNwTfS?usp=sharing
=> Fix LSTM performance on TF Backend

keras/activations/activations.py, keras/backend/jax/nn.py, keras/backend/numpy/nn.py, keras/backend/tensorflow/nn.py, keras/backend/torch/nn.py, keras/ops/nn.py, keras/ops/nn_test.py
This PR:
- add `hard_swish` to `ops.nn` to ensure consistency for all activation functions in the codebase
- add dtype inference tests for `hard_sigmoid` and `hard_swish`
I plan to add more dtype inference tests for `ops.nn`.  I think we can focus on float types for these ops, as it's uncommon to use them with integer types.
Is it a good idea (adding more tests / skipping integer types for `ops.nn`)?
=> Add `hard_swish` to `ops.nn` and dtype tests for `hard_swish` and `hard_sigmoid`

keras/models/model.py, keras/saving/saving_api.py, keras/saving/saving_api_test.py
close #18864 
I reviewed the history of past commits and merged them into keras.saving.save_model().
And I removed model.save() and modified it to just call keras.saving.save_model().
=> Reduce redundancy on saving model

keras/export/export_lib.py, keras/export/export_lib_test.py
Previously, JAX release 0.4.16 was incompatible with stable TF versions. However, this has recently been fixed, and JAX export can now be used again.
=> Remove versioning restrictions for export from JAX backend

keras/layers/convolutional/conv2d_transpose.py
Fixed the doc bug in channels_last shape description from
`(batch_size, channels, height, width)` 
to 
`(batch_size, height, width, channels)`
to avoid confusion among users.
Fixes #18910
=> Fix the doc bug in channels_last shape in conv2d_transpose.py

keras/export/export_lib.py
This PR checks whether the installed packages for JAX and TF both can access the GPU when JAX with GPU is being used for export.
If TF is CPU-only, the export API will prevent the usage of JAX-native serialization, allowing cross-device compatibility, but at the expense of performant serving from the exported artifact.
=> Fix jax2tf device incompatiblity for Export

keras/layers/normalization/batch_normalization.py, keras/layers/normalization/batch_normalization_test.py
Proposed solution for the bug reported in https://github.com/keras-team/keras/issues/18759
Prior to this, masking was not effective in batch normalization layers. This approach pulls weighted_moments and divide_no_nan logic into batch_normalization using core operations so that masking will work with any back-end instead of just tensorflow.
Open to suggestions.
=> Add masking to BatchNormalization

keras/backend/torch/random.py, keras/random/random_test.py
Fixes #18920 for Torch on GPU.  Move to Device before doing math with another tensor that's using `convert_to_tensor`.
=> Fixes Torch GPU Test for Binomial and Beta Distribution

keras/layers/convolutional/conv2d.py, keras/layers/convolutional/conv3d.py, keras/layers/convolutional/conv3d_transpose.py, keras/layers/convolutional/depthwise_conv2d.py, keras/layers/convolutional/separable_conv2d.py
Stumbled upon some inconsistencies in the docs for conv layers, e.g. Conv2d, which currently states
> `"channels_last"` corresponds to inputs with shape `(batch_size, channels, height, width)`
which seems wrong, especially since a bit further down, it mentions
> Input Shape: If `data_format="channels_last"`: A 4D tensor with shape: `(batch_size, height, width, channels)`
Similar inconsisties exist for other conv layers, namely conv3d, conv3d_transpose, depthwise_conv2d, separable_conv2d.
So here's a simple Doc Fix to get the documentation for the `data_format` argument to conv layers in line with the expected input shape.
=> Fix descrepancies in Conv Module docstrings regarding data_format

keras/random/seed_generator.py, keras/random/seed_generator_test.py
KerasCV serialization tests were failing from 
```
TypeError: Cannot serialize object <keras.src.random.seed_generator.SeedGenerator object at 0x7fe3582b5610> of type <class 'keras.src.random.seed_generator.SeedGenerator'>. To be serializable, a class must implement the get_config() method.
```
https://github.com/keras-team/keras-cv/actions/runs/7175074758/job/19537736102?pr=2232
=> add get_config() to SeedGenerator

keras/optimizers/adafactor.py, keras/optimizers/adafactor_test.py
Adafactor would crash when using variables with 2 dimensions or more with most backends. It would work with the TensorFlow backend because `TensorShape` allows adding an int.
=> Fix Adafactor when variables have 2 dimensions or more.

keras/backend/tensorflow/numpy.py, keras/backend/tensorflow/sparse.py, keras/ops/numpy.py, keras/ops/numpy_test.py
This is in preparation for JAX support of sparse tensors.
Added explicit support for `ops.isfinite`. This op is used by optimizers (`LossScaleOptimizer`) with sparse gradients. Somehow, `tf.isfinite` works out of the box with `tf.IndexedSlices` but this change makes the support explicit.
Removed support for `ops.mod` and `ops.floor_divide`. These ops are not used with sparse tensors in any context right now; support was incomplete with TensorFlow and there is no support for them in JAX for JAXSparse tensors.
=> Tweaks to TensofFlow support for SparseTensor/IndexedSlices.

keras/trainers/data_adapters/py_dataset_adapter.py
Multiprocessing import needs to import multiprocessing.dummy.
This has worked up until now due to an import in tensorflow, which will soon no longer be available here.
=> Update multiprocessing import in py_dataset_adapter.py

keras/applications/nasnet.py
This was the issue raised at the time of `Keras 3 code base` migration from `keras-team/keras-core` to `keras-team/keras`. I was told to recreate the pull request if the issue is not fixed after the migration.
issue was: keras-team/tf-keras#142
=> default value for input_shape when include_top is provided has False.

keras/layers/layer.py, keras/layers/layer_test.py
Previously, those were not returned with "return_losses=True". In the same line, we now get the regularizer object from the respective module.
=> Return regularization losses in stateless_call.

keras/layers/reshaping/cropping2d.py, keras/layers/reshaping/cropping3d.py
The API Cropping2D has an argument cropping which can take either int or tuple of 2 tuple of ints.
If we provide -ve values when passed as tuple like `cropping = ( (-1,-1), (-1,-1) )` then this API raises exception like below which is intended.
> ValueError: The `1st entry of cropping` argument must be a tuple of 2 integers. Received 1st entry of cropping=(-1, -1), including values {-1} that do not satisfy `value >= 0`
However if we given -ve int value like `cropping = -1`, then there is no exception and generating unintended output.
Internally this -ve value being converted into tuple from below code.
https://github.com/keras-team/keras/blob/c3d269b308b40314e8e128a7116a7f3fdf0ca212/keras/layers/reshaping/cropping2d.py#L60
After converting to tuple there is no validation that this API …
=> Validate cropping arg value for -ve ints

keras/backend/tensorflow/rnn.py
This allows the static shape to propagate in RNNs in the case when the number of time steps is fixed and known at build time.
Fixes #18941.
=> Fix for https://github.com/keras-team/keras/issues/18941

keras/backend/tensorflow/optimizer.py, keras/optimizers/base_optimizer.py, keras/optimizers/optimizer_test.py
Currently, the initial state of `_model_variables_moving_average` is INCORRECT when using tensorflow backend.
This bug will also cause the model weights become all zeros, regardless of the initializer used.
This PR fixes the bug by using `tf.cond` to overwrite `_update_model_variables_moving_average` in `TFOptimizer`.
The new test `test_ema_with_model_fit` can only be passed after this PR.
Before this PR, the trained model weights will be very small, even though they should be close to 1. (initialized by 1 and `ema_momentum=0.9999`)
Actually, the bug was identified during the implementation of the idea proposed in #18949
=> Fix EMA when using tensorflow backend

keras/layers/reshaping/cropping1d.py, keras/layers/reshaping/cropping1d_test.py, keras/layers/reshaping/cropping2d.py, keras/layers/reshaping/cropping2d_test.py, keras/layers/reshaping/cropping3d.py, keras/layers/reshaping/cropping3d_test.py
The cropping layer APIs like Cropping2D,Cropping3D and Cropping1D, have cropping parameter which should be smaller than the input(or image) size. This is validating like below.
https://github.com/keras-team/keras/blob/4a4a139c7aada9f4495620e5a1c5f7ef20d84395/keras/layers/reshaping/cropping2d.py#L94-L102
But the error description above states cropping should be `greater` than input which actually should be `smaller` than input. Reference [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/b27ecffe8781337f36dafa35dc7c5791/cropping_exception_error.ipynb) for demo.
=> Correct the Error description in cropping layer APIs

keras/backend/tensorflow/numpy.py, keras/backend/torch/numpy.py, keras/ops/numpy_test.py
It's a common use case to use a tensor to split another tensor.
This PR addresses the incompatibility issue of using a tensor input as `indices_or_sections` in `ops.split` for tensorflow and torch.
It is worth noting that I have implemented a more robust solution for tensorflow backend, supporting XLA compilation for tensor input of `indices_or_sections`.
The corresponding test `test_split_with_jit_in_tf` has been added.
=> Fix `ops.split` in torch and tensorflow

keras/backend/jax/trainer.py, keras/backend/torch/trainer.py, keras/trainers/data_adapters/tf_dataset_adapter.py, keras/trainers/data_adapters/torch_data_loader_adapter.py
There are two major improvements:
1. Utilize shared memory to convert tensor to numpy (`TFDatasetAdapter` and `TorchDataLoaderAdapter`)
2. Introduce `JAXEpochIterator` with prefetching to achieve speed-up
3. Add prefetching to `TorchEpochIterator` to achieve speed-up
The result:
JAX:
|Methods|Training speed||
|-|-|-|
|Current implementation|147ms/step||
|`np.asarray`|137ms/step|-6.8%|
|`np.asarray` + prefetching|128ms/step|-12.3%|
Torch:
|Methods|Training speed||
|-|-|-|
|Current implementation|223ms/step||
|`np.asarray`|214ms/step|-4.0%|
|`np.asarray` + prefetching|203ms/step|-9.0%|
The standalone script (tested with RTX4070):
```python
import torch  # noqa:F401 dummy import to prevent segmentation fault
import keras
from keras import backend …
```
=> Add `JAXEpochIterator` and speed up `get_numpy_iterator`

keras/backend/tensorflow/numpy.py, keras/metrics/confusion_metrics_test.py, keras/ops/nn_test.py, keras/ops/numpy_test.py
https://github.com/keras-team/keras/issues/18947
Some ops would only work properly if `enable_numpy_behavior` was on. This reimplements these ops using standard tf operations.
=> Remove reliance on Tensorflow enable_numpy_behavior for some ops.

keras/backend/jax/numpy.py, keras/backend/numpy/numpy.py, keras/backend/tensorflow/numpy.py, keras/backend/torch/numpy.py, keras/ops/numpy.py, keras/ops/numpy_test.py
tf ops should be less buggy and more battle-tested. Some `tf.cond` used by `tfnp.*` could also be eliminated.
In addition, this PR adds dtype inference for `floor_divide`, which was missing before.
The following are left to be `tfnp.*` because they are much more complex to implement using native tf ops:
- max
- average
- copy
- cross
- diag
- diagonal
- diff
- linspace
- logspace
- min
- moveaxis
- roll
- swapaxes
- take
- take_along_axis
- trace
- tri
- eye
=> Replace `tfnp` with native tf ops wherever possible

keras/layers/rnn/lstm.py
Fix [#18958](https://github.com/keras-team/keras/issues/18958)
=> Fix `inplace operation` in LSTM when using torch backend

keras/backend/torch/trainer.py
PR #18991 update to `trainer.py` caused regression in keras-cv test - 
```
def to_device(d):
>       return torch.as_tensor(d, device=get_device())
```
E       UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:212.)
/opt/miniconda3/envs/keras-cv3/lib/python3.9/site-packages/keras/src/backend/torch/trainer.py:512: UserWarning
================================================= short test summary info …
=> Use  `convert_to_tensor` when moving to device for numpy

requirements-tensorflow-cuda.txt, requirements-torch-cuda.txt
* Use Cuda 12.1 for Torch to align with TF and Jax.  Also, aligns torch install with that of Colab that uses `torch+cu121` packages.
* Remove `extra-url` for TensorFlow as its no longer required.
=> Update Cuda Reqs to align Cuda versions

keras/layers/preprocessing/discretization_test.py, keras/utils/numerical_utils.py
Update `utils/numerical_utils.py` to support input shapes with a rank greater than two.
when the output_mode is  `multi_hot`, `one_hot`, or `int`
Compatible with all backends: TensorFlow, JAX, and PyTorch.
Credit to: @ixig and @mattdangerw
=> Allow rank > 2 for input shapes in numerical_utils

keras/layers/preprocessing/category_encoding.py, keras/layers/preprocessing/hashed_crossing.py, keras/layers/preprocessing/hashing.py, keras/layers/preprocessing/integer_lookup.py, keras/layers/preprocessing/string_lookup.py, keras/layers/preprocessing/text_vectorization.py, keras/layers/preprocessing/text_vectorization_test.py, keras/utils/backend_utils.py
Fixes - 
1. TextVectorization layer: local variable 'outputs' referenced before assignment error on some instances in the call method of TextVectorization. 
2. allow output_sequence_length when ragged is True - #18576 
Abstracted repeated use of `convert_to_tensor` on preprocessing layer outputs for non-TF backends into common utility in backend.
FYI: @SasankYadati.  I had made the change for issue #1 independently and then noticed that you had similar issue in #18980, so combined that issue also into this PR.  Hope that's OK.
=> Text Vectorization Preprocessing Layer - Fixes

keras/backend/common/variables.py
This fix is using TensorShape's [as_list() method](https://www.tensorflow.org/api_docs/python/tf/TensorShape#as_list) to prevent downstream issues whenever TensorShape contains Dimension objects (which sometimes happen for legacy reasons).
This ensures that the resulting shape will only contain int/None items (and no Dimension objects) in any case.
=> Fix TensorShape bug in tensorflow backend

keras/utils/numerical_utils.py
Replace deprecated `keras.backend.categorical_crossentropy` with `keras.ops.categorical_crossentropy` in the docs.
=> Redirect deprecated function call

keras/metrics/confusion_metrics.py
I think "binary_crossentropy" is more appropriate for those metrics.
=> Update docstrings of confusion_metrics.py

keras/ops/operation_utils.py
Currently, the operation util `compute_conv_output_shape`, doesn't throw an exception given an unknown type of `padding`. Conv layers dependent on this util throw an unknown exception
`UnboundLocalError: local variable 'output_spatial_shape' referenced before assignment`
To reproduce:
```
import keras
layer = layers.Conv2D(64, kernel_size=(3, 3),
strides=(3, 3),
padding=(1, 1), use_bias=True)
inputs = keras.random.uniform((1, 224, 224, 3))
out = layer(inputs)
```
Which can be fixed using this patch.
=> raise exception on unknown padding for conv

keras/backend/jax/core.py, keras/backend/jax/trainer.py, keras/backend/numpy/trainer.py, keras/backend/tensorflow/core.py, keras/backend/tensorflow/trainer.py, keras/backend/torch/trainer.py, keras/layers/normalization/batch_normalization_test.py, keras/trainers/data_adapters/array_data_adapter.py, keras/trainers/data_adapters/array_data_adapter_test.py, keras/trainers/data_adapters/data_adapter.py, keras/trainers/data_adapters/data_adapter_utils.py, keras/trainers/data_adapters/generator_data_adapter.py, keras/trainers/data_adapters/generator_data_adapter_test.py, keras/trainers/data_adapters/py_dataset_adapter.py, keras/trainers/data_adapters/py_dataset_adapter_test.py, keras/trainers/data_adapters/tf_dataset_adapter.py, keras/trainers/data_adapters/tf_dataset_adapter_test.py, keras/trainers/data_adapters/torch_data_loader_adapter.py, keras/trainers/data_adapters/torch_data_loader_adapter_test.py, keras/trainers/epoch_iterator.py, keras/trainers/epoch_iterator_test.py
- Added `get_jax_iterator` and `get_torch_dataloader` to all `DataAdapter`s.
- `GeneratorDataAdapter` and `PyDatasetAdapter` can now consume tensors from any backend (added support for JAX and Torch). As a result, any combination of input format is supported by these two `DataAdapter`s.
- Made `DataAdapter`s unit tests similar.
- Fixed gap where `shuffle="batch"` was not implemented (used a global shuffle) for the numpy iterator.
- `GeneratorDataAdapter` no longer peeks twice at the first element.
- Removed the concept of `return_type` in `EpochIterator` since it is now always "auto".
- Each backend has a subclass of `EpochIterator` (this is not new), which is now in charge of retrieving the correct iterator for the backend.
- This prevents the double conversion that was happening in some …
=> All DataAdapters can now create a native iterator for each backend.

keras/backend/config.py
Useful for llms! The tradeoff in precision can often be worth it in memory constrained environments, and unlike float16, does not have the same overflow/underflow issues during training.
=> Allow bfloat16 as default dtype

CONTRIBUTING.md
In `CONTRIBUTING.md`, `pytest` was repeated twice in the first code block of `Run tests` (i.e. `pytest pytest keras/losses/losses_test.py` fails but `pytest keras/losses/losses_test.py` doesn't).
Apologies if I missed something, I was just comparing it to tf-keras `CONTRIBUTING.md`.
=> Fix repeat pytest in CONTRIBUTING.md

keras/backend/torch/numpy.py, keras/ops/numpy_test.py
The implementation of min() with torch backend is not working properly. For eg if list of axis passed the reduction is not happening. Changed the implementation like torch.numpy.max function which is working fine.
Attached https://colab.research.google.com/gist/SuryanarayanaY/9b28fd5fa5837d11d660550caa13eea0/19064.ipynb for demo of same.
Fizes #19064
=> Change implementation of numpy.min() of torch backend

keras/layers/pooling/average_pooling2d.py, keras/layers/pooling/average_pooling3d.py, keras/layers/pooling/base_global_pooling.py, keras/layers/reshaping/up_sampling2d.py, keras/layers/reshaping/up_sampling3d.py
I have found the inconsistency in `data_format` across these layers while building a model zoo library.
This PR should improve the UX for developers who want to support both `channels_last` and `channels_first` for their models.
=> Let backend determine the data format by setting `data_format=None`

keras/backend/torch/numpy.py, keras/ops/numpy_test.py
At present the behaviour of  API `keras.ops.take` with Torch backend is different and incorrect compared to TF and Jax.
This is specifically when input `x.ndim=2` and `axis = None` where x is not flattened by default with axis=None.
Hence changed the implementation and added test case to verify.
Shall fix #18984
=> Correct keras.ops.take behaviour with axis=None

integration_tests/numerical_test.py
To ensure the `numerical_test`, compares between Keras 3 and Keras 2,
we use `tf_keras` for Keras 2.
=> Fix the numerical_test by using `tf_keras` instead of `tensorflow.keras`

keras/trainers/data_adapters/py_dataset_adapter_test.py
Removed the parts of the test that were invalid. We were using libraries (TensorFlow, JAX, Torch) in multiple threads or multiple processes in a way that is not supported. This was causing issues with CUDA.
=> Fix for `py_dataset_adapter_test` on GPU.

keras/backend/jax/core.py, keras/backend/numpy/core.py, keras/backend/tensorflow/core.py, keras/backend/torch/core.py, keras/layers/core/dense.py, keras/layers/core/einsum_dense.py, keras/layers/layer.py, keras/saving/saving_api_test.py, requirements-common.txt, setup.py
Currently attempting to save or load weights in bfloat16 will fail. There may be better ways to do this, but the approach jax and tf seem to take is to use the `ml-dtypes` library to get a bfloat16 dtype that will work with numpy.
This is further compounded by the h5py format, which saves bfloat16 as a void type. This implementation currently just assumes any two byte void type is bfloat16, which seems a bit hacky. Quite possibly a better way to do this.
=> Attempt to add support for saving/loading bfloat16

keras/layers/attention/attention.py, keras/layers/attention/attention_test.py
**The Issue:**
In the previous implementation, if `v_mask` was set to `None` and `use_causal_mask` was `True`, the method encountered a `ValueError`. 
This issue arose because the method attempted to perform operations with a `None` value, which is not compatible with the expected tensor operations.
**The Enhancement:**
The modified implementation introduces a more robust handling mechanism for such scenarios:
1. Handling `None` for `v_mask` with Causal Mask: When `use_causal_mask` is `True`, the method now correctly generates a causal mask regardless of whether `v_mask` is `None`. 
3. Handling `None` for `v_mask` without Causal Mask: If `use_causal_mask` is `False`, and `v_mask` is `None`, the method safely returns `None`.
=> Fix for `_calculate_score_mask` in Attention Layer

integration_tests/numerical_test.py, keras/backend/torch/nn.py
Fix #19073
The deviation from the Keras 2 numerics is because of the following:
* The `moments` op used `mean.detach()`, which cut off the gradients for the mean, which is useful since it backprops to the inputs to the batch norm, from which the mean is computed from.
* The same reason that we should not detach the mean and variance in the `batch_normalization` op.
We had to change the torch `batch_normalization` op to a plain implementation instead of calling the fused op of `torch.nn.functional.batch_norm()` since it cannot run without calling `mean.detach()` and pass the detached mean to it, which cuts off the gradients.
In `torch.nn.BatchNorm2d`, the implementation is not mathematically equivalent to the Keras implementation. They call the fused op with `training=True`, and let the op …
=> Fix wrong gradients for torch batch_norm and moments

keras/backend/jax/math.py, keras/backend/numpy/math.py, keras/backend/tensorflow/math.py, keras/backend/torch/math.py, keras/ops/math.py, keras/ops/math_test.py
Related to #19070 
The `norm` in jax and torch is the same as numpy's `norm`.
However, significant modifications are required for tensorflow to match the output of the other backends.
=> Add `ops.math.norm`

keras/applications/mobilenet.py
Found when converting/exposing your entire codebase:
```sh
$ python -m pip install python-cdd==0.0.99rc20  # Or a newer version!
$ python -m cdd exmod -m keras --emit class -r -o build/keras 
```
Which failed to re-`ast.parse` the output because it produces:
```py
class _conv_block(object):
"""
Adds an initial convolution layer (with batch normalization and relu6).
:cvar inputs: Input tensor of shape `(rows, cols, 3)` (with `channels_last` data format) or (3, rows, cols) (with `channels_first` data format). It should have exactly 3 inputs channels, and width and height should be no smaller than 32. E.g. `(224, 224, 3)` would be one valid value.
:cvar filters: Integer, the dimensionality of the output space (i.e. the number of output filters in the convolution).
:cvar alpha: controls the …
```
=> [keras/applications/mobilenet.py] `_conv_block` & `_depthwise_conv_block` now conformed to 'Google style docstrings' format

keras/backend/jax/core.py, keras/ops/core_test.py
`ops.scatter_update` throws an exception with the JAX backend. 
To reproduce:
```
import os
os.environ['KERAS_BACKEND'] = 'jax'
adjacency_matrix = ops.zeros((12))
indices = [[0],[1], [3]]
updates = ops.ones(shape=(3))
adjacency_matrix = ops.scatter_update(adjacency_matrix, indices, updates)
```
This patch can fix this error.
=> bug fix in scatter update for jax backend

keras/backend/jax/math.py, keras/backend/numpy/math.py, keras/backend/tensorflow/math.py, keras/backend/torch/math.py, keras/ops/math.py, keras/ops/math_test.py
Adds the inverse error function (`erfinv`) function to the supported ops. It's widely used in statistics, probability and numerical applications, complements the `erf` op which is available and is easily implemented since it's already supported by all backends.
=> Add `erfinv` op

keras/utils/progbar.py
We need to explicitly cast `avg` to float otherwise, training has some issues with the torch backend when the default dtype is `bfloat16`.
=> Cast avg to float in progbar

keras/backend/jax/math.py, keras/backend/numpy/math.py, keras/backend/tensorflow/math.py, keras/backend/torch/math.py, keras/ops/math_test.py
This PR remove the redundant computation in #19099 by using native `tf.linalg.norm`.
It also includes the dtype tests for `norm`.
If I'm available, I will add more tests for other operators in `math`.
=> Refactor tf's `norm` and apply `result_type` to `norm`

keras/backend/jax/core.py, keras/backend/jax/numpy.py, keras/backend/jax/sparse.py, keras/backend/tensorflow/numpy.py, keras/backend/tests/compute_output_spec_test.py, keras/layers/core/dense_test.py, keras/layers/core/embedding_test.py, keras/layers/core/identity.py, keras/layers/merging/merging_test.py, keras/layers/reshaping/flatten_test.py, keras/layers/reshaping/permute_test.py, keras/ops/core_test.py, keras/ops/numpy.py, keras/ops/numpy_test.py, keras/optimizers/optimizer_sparse_test.py, keras/testing/test_case.py, keras/trainers/trainer_test.py, keras/utils/jax_utils.py
Add support for sparse tensors with the JAX backend.
This is experimental since JAX support for sparse tensors itself is experimental.
This support has the following limitation:
- Only the BCOO format is fully supported and tested. Other formats are untested and only supported for some use cases.
- Not all combinations of `n_batch`, `n_sparse` and `n_dense` are supported. What is tested is:
- all sparse (equivalent to `tf.SparseTensor`)
- `n_sparse == 1` and the rest is dense (equivalent to `tf.IndexedSlices`)
- The the embedding layer / the `take` op is not optimized (densifies inputs).
- Gradients obtained from sparse inputs are not sparse.
Also:
- Fixed a bug with TensorFlow sparse support for `squeeze` when `axis` is negative.
- `run_layer_test` can now take a tuple of input shapes.
=> Add support for sparse tensors with the JAX backend.

keras/callbacks/model_checkpoint.py
When we use `F1_score` with `average=None` as monitor for Model checkpoint and the model is of multi-class classification problem then the metric returns f1_score of each class. In such scenario if save_best_only=True passed to ModelCheckpoint then it will raise an error due to ambiguity. 
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`
If we set `save_best_only=False` which is default then there is no problem with model checkpointing. Hence I am proposing to fall back to `save_best_only=False` mode and display it as user warning for such case instead raising an exception.
Attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/dd8a9494d77508b52f116d42dc68406b/f1_score_error_fix.ipynb) for the same with testing the …
=> When monitor metric size >1 fallback to save_best_only=False in ModelCheckpoint

keras/ops/core.py, keras/ops/core_test.py
While adding tests for `keras/ops/core.py`, I caught a bug in the `_check_output_spec` method 
Previously, the method would raise an `AttributeError` when trying to access the `dtype` attribute of `false_fn_spec` if it was `None`.
The fix involves adding a check at the beginning of the `_check_output_spec` method to return `True` only if both `true_fn_spec` and `false_fn_spec` are `None`. If only one of them is `None`, the function will return `False`, preventing the `AttributeError`.
The updated unit tests in `core_test.py` confirm that the fix works as expected. All tests now pass successfully.
=> Fix AttributeError in `_check_output_spec` Method of `keras.ops.core.Cond` Class" + Add tests

keras/testing/test_case.py
Some TensorFlow sparse operations are not supported with XLA. This change turns off jit compilation for sparse tensor tests with the TensorFlow backend. This reverts it to what it was before https://github.com/keras-team/keras/pull/19109
=> Fix TensorFlow sparse tests on GPU.

keras/backend/jax/numpy.py
The `broadcast_to` Op with Jax backend expects Array as input and fails when it is a Tensor like `tf.Tensor` or a `KerasVariable`.
I am proposing to explicit conversion to numpy array before passing it to `jax.numpy.broadcast_to`.
Shall fixes #19116 .
=> Fix bug in broadcast_to Op with Jax backend when keras variable as input

keras/trainers/data_adapters/generator_data_adapter.py, keras/trainers/data_adapters/generator_data_adapter_test.py, keras/trainers/data_adapters/tf_dataset_adapter.py, keras/trainers/data_adapters/tf_dataset_adapter_test.py, keras/trainers/trainer_test.py
- `TFDatasetAdapter.get_jax_iterator()` now converts `tf.SparseTensor`s to JAX `BCOO`s.
- `GeneratorDataAdapter` can now take `tf.SparseTensor`s, JAX `BCOO`s or `scipy.sparse` tensors and output either `tf.SparseTensor`s or JAX `BCOO`s.
=> Add TFDatasetAdapter and GeneratorDataAdapter sparse support for JAX.

keras/ops/operation.py
Because it is an f-string, curly braces need to be escaped.
=> Fixed formatting that preventing error message from printing.

keras/backend/jax/trainer.py, keras/callbacks/callback.py
This PR fix the CI by adding`self._jax_state_synced=True` in `__init__`.
Additionally, it utilizes the new `self._get_jax_state` for `*_on_batch` and updates the logic behind `self.jax_state_sync` to avoid `if not self._jax_state_synced`
=> Add `self._jax_state_synced` in `__init__` in jax's trainer

keras/backend/jax/core.py, keras/backend/numpy/core.py, keras/backend/tensorflow/core.py, keras/backend/torch/core.py, keras/ops/core.py, keras/ops/core_test.py
Previously, we had the following support for loop vars:
- jax and tensorflow support nest structures (dicts/tuples) in a tuples
- torch and numpy support only flat tuples
With this change, we support any nested structure. If loops vars is a loop or tuple, args as passed positionally.
Alternatively, we could:
- demand the toplevel be a tuple/list, with nested structure inside
- pass any structure through unaltered (never pass args positionally). this is the jax approach, and IMO it's the cleanest, but to get there we would need to break compat.
=> Support nested structures in while loops

keras/backend/common/dtypes_test.py
This pull request aims to introduce additional unit tests for the `keras.backend.common.dtypes` module, with a focus on the `_resolve_weak_type`  and the `_least_upper_bound`. 
In the process of enhancing the test suite, particularly for `_least_upper_bound`, I encountered specific challenges that I wish to report and seek assistance with.
While enhancing the test suite for the `_least_upper_bound` , I encountered challenges in creating test for 
```python
else:
raise ValueError(
f"Internal Type Promotion error: {nodes} do not have a unique "
f"least upper bound on the specified lattice; options are {LUB}. "
"This is an unexpected error in Keras's internal logic; "
"please report it to the maintainers."
)
```
https://github.com/keras-team/keras/blob/master/keras%2Fbackend%2Fcommon%2Fdtypes …
=> Add unit tests to `backend/common/dtypes_test.py`

keras/ops/numpy.py
Found when converting/exposing your entire codebase:
```sh
$ python -m pip install python-cdd==0.0.99rc22  # Or a newer version!
$ python -m cdd exmod -m keras --emit sqlalchemy_hybrid -r -o build/keras 
```
It fails because it parses out this:
```py
{   'default': 'xy',
'doc': 'Cartesian (`"xy"`, default) or matrix (`"ij"`) indexing of output.',
'typ': 'Literal["xy"]'}
```
Instead of this:
```py
{   'default': 'xy',
'doc': 'Cartesian (`"xy"`, default) or matrix (`"ij"`) indexing of output.',
'typ': 'Literal["xy", "ij"]'}
```
BTW: Sending this two-line one-file PR because when I tried whole codebase upgrade-to-non-adhoc-syntax it was not merged: #18786
=> [keras/ops/numpy.py] Use a more standard docstring format for `meshgrid`

keras/utils/summary_utils.py
Models are getting bigger! Let's adapt our summary so we can avoid ellipsizing summary for layers/sub-models with up to 10B parameters. In KerasNLP/KerasCV this comes up when we have a model that wraps a backbone, which can have billions of parameters. An ellipsized count is not readable, you can't tell the number of training digits. 
Not exactly sure on spacing. For sequential, I just made the whole summary 4 chars bigger (as the width is much smaller than functional anyway), For functional, I stole width from the `Connected to` column, as I would claim parameters count is more important.
Here's a quick demo:
https://colab.research.google.com/gist/mattdangerw/96bded8af054649caae8ec4cba8f0942/summaries.ipynb
=> Show billions of parameters in model summary

requirements-jax-cuda.txt
Fix the JAX version for GPU CI.  Added a TODO to see if the cuda version can be updated.
Log: https://source.cloud.google.com/results/invocations/c60e0c47-9e68-42ce-b67e-2f685ab476c9/log
=> Fix JAX GPU CI Cuda error by fixing JAX version

keras/metrics/reduction_metrics.py, keras/metrics/reduction_metrics_test.py
The new behavior is similar to Keras 2 i.e. `tf.math.divide_no_nan`.
=> Fix for `keras.metrics.Mean` when the sum of weights is negative.

keras/export/export_lib.py, keras/export/export_lib_test.py
This PR makes sure the default variable collections are wrapped as TF variables on the JAX backend, preventing variables from being embedded as constants.
Additionally, I've added a basic test for registering a custom endpoint using jax2tf conversion from the JAX backend.
=> Wrap JAX export variables in TF variable, add test for JAX with TF function endpoint

keras/ops/numpy.py
I fixed a typo in the keras/ops/numpy.py file on line 668 (issue #19168): lenght -> length
Do not hesitate to tell me if I have to modify something else... :blush:
=> #19168: Fix a typo

.github/dependabot.yml
Disable AutoUpdate of JAX GPU by Dependabot.
Followup to #19161.
=> Disable Dependabot auto-update for JAX GPU

keras/backend/jax/trainer.py, keras/backend/tensorflow/trainer.py, keras/backend/torch/trainer.py, keras/trainers/data_adapters/tf_dataset_adapter.py, keras/trainers/data_adapters/torch_data_loader_adapter.py, keras/trainers/data_adapters/torch_data_loader_adapter_test.py
Fixes https://github.com/keras-team/keras/issues/19156
The `IterableDataset` can optionally implement `__len__`.
=> Add support for `IterableDataset` to `TorchDataLoaderAdapter`.

keras/ops/math.py, keras/ops/nn.py, keras/ops/nn_test.py
$L_p$ Normalization is a popular operation available in both PyTorch and TensorFlow. Having it in Keras 3.0 would be a great addition. This PR will add the `normalize()` ops,
$$
v' = \frac{v}{\max(\lVert v \rVert_p, \epsilon)}
$$
This operation is widely used in the community; for example, `OpenAI-CLIP` or `Google-SigLIP` uses `l2_normalization` in their encoder embeddings.
* PyTorch: https://pytorch.org/docs/stable/_modules/torch/nn/functional.html#normalize
* TensorFlow: https://www.tensorflow.org/api_docs/python/tf/linalg/normalize
=> Add `normalize` ops

keras/backend/jax/numpy.py
This PR fixes the TypeError that occurs when certain ops do not retrieve the `value` from `KerasVariable` when using jax backend.
colab to reproduce the error:
[https://colab.research.google.com/drive/1LeIIJsj29K3uI2t2dXmd0yhHCCkKeHj4?usp=sharing](https://colab.research.google.com/drive/1LeIIJsj29K3uI2t2dXmd0yhHCCkKeHj4?usp=sharing) 
```bash
Argument '<KerasVariable shape=(1, 2, 3), dtype=float32, path=test_layer_4/variable_4>' of type <class 'keras.src.backend.jax.core.Variable'> is not a valid JAX type.
Arguments received by TestLayer.call():
• inputs=jnp.ndarray(shape=(10, 2, 3), dtype=float32)
```
The solution is to add `convert_to_tensor` in these ops.
=> Add `convert_to_tensor` in certain ops in JAX

keras/backend/numpy/linalg.py
A use of keras is to be able to run models with the numpy backend without have to install PyTorch. Since keras 3.0.5 this does not work.
This is due to #19143 by @frazane.
This PR fixes that, so that the numpy backend only requires the `numpy` and `jax[cpu]`.
Run anything with the numpy backend without having torch installed.
```
python3.11/site-packages/keras/src/backend/numpy/__init__.py:3: in <module>
from keras.src.backend.numpy import linalg
python3.11/site-packages/keras/src/backend/numpy/linalg.py:6: in <module>
from keras.src.backend.torch.core import convert_to_tensor
python3.11/site-packages/keras/src/backend/torch/__init__.py:17: in <module>
from keras.src.backend.torch import core
python3.11/site-packages/keras/src/backend/torch/core.py:6: in <module>
import torch
E …
```
=> Numpy backend requires torch

keras/layers/preprocessing/text_vectorization.py, keras/layers/preprocessing/text_vectorization_test.py
Resolves a deserialisation issue when `ngrams` is set to a tuple in `TextVectorization` layer. Closes #19180.
=> Fix(preprocessing): resolve `ValueError` for `ngrams` tuple

keras/ops/image.py, keras/ops/image_test.py
This PR will add `crop_images` image ops as discussed here (https://github.com/keras-team/keras/issues/18489). This will perform similar task as `tf.image.crop_to_bounding_box` but with some extra functionalities.
To-Do:
=> Add `ops.image.crop_images`

.kokoro/github/ubuntu/gpu/build.sh
`psutil` gets installed as part of general requirements.txt. But sometimes, it takes a while to install all dependencies and background log reader starts its job. When it happens, it causes the CI to fail since `psutil` is not yet installed. So, install `psutil` in the beginning so we don't have this failures that occur sometimes.
```
Downloading tf_nightly-2.16.0.dev20240209-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (589.8 MB)
Downloading nvidia_cublas_cu12-12.3.4.1-py3-none-manylinux1_x86_64.whl (412.6 MB)
Downloading nvidia_cuda_cupti_cu12-12.3.101-py3-none-manylinux1_x86_64.whl (14.0 MB)
Downloading nvidia_cuda_nvcc_cu12-12.3.107-py3-none-manylinux1_x86_64.whl (22.0 MB)
Downloading nvidia_cuda_nvrtc_cu12-12.3.107-py3-none-manylinux1_x86_64.whl (24.9 MB)
Downloading …
```
=> Adds psutil deps for CI Log Reader

keras/backend/common/variables.py, keras/layers/core/dense.py, keras/layers/core/einsum_dense.py, keras/layers/core/embedding.py, keras/layers/layer.py, keras/layers/layer_test.py, keras/optimizers/base_optimizer.py, keras/utils/tracking.py
`_untrack_variable` is necessary when performing in-place operations on variables, such as changing the dtype.
A unit test is also included.
I think it would be beneficial to expose `constraint` and `regularizer` for `KerasVariable`:
- This prevents improper assignment to these attrs, which could lead to runtime error (and may be challenging to debug).
- This should enhance the development UX.
This PR is also a preparation for adding `quantize` to `Layer` and `Quantizer` classes for `KerasVariable`.
=> Add `_untrack_variable` to `Layer` and explicitly define `constraint` and `regularizer` to `KerasVariable`

.github/workflows/actions.yml, .github/workflows/config/mlx/keras.json, integration_tests/import_test.py, keras/backend/common/variables.py, keras/backend/mlx/__init__.py, keras/backend/mlx/core.py, keras/backend/mlx/image.py, keras/backend/mlx/layer.py, keras/backend/mlx/math.py, keras/backend/mlx/nn.py, keras/backend/mlx/numpy.py, keras/backend/mlx/random.py, keras/backend/mlx/rnn.py, keras/backend/mlx/trainer.py, keras/layers/layer.py, keras/models/model.py, keras/trainers/trainer_test.py, requirements.txt
This PR adds an MLX (https://github.com/ml-explore/mlx) backend as mentioned also in #18901 .
A lot of things are still missing but my initial goal was to be able to pass the trainer and backend tests as well as train a small MLP. The backend is implemented by porting things either from the Jax backend or the PyTorch backend where appropriate.
The following is an excerpt from the MNIST training example that runs fine with the MLX backend on my M2 air.
```python
model = keras.Sequential(
[
keras.Input(shape=input_shape),
layers.Dense(1024, activation="relu"),
layers.Dense(1024, activation="relu"),
layers.Dense(num_classes, activation="softmax"),
]
)
model.summary()
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(x_train, y_train, …
```
=> Adds initial support for an MLX backend

keras/backend/torch/numpy.py, keras/ops/numpy_test.py
I just discovered a private api `torch._int_mm` for performing int8xint8->int32 matmul
However, it comes with strict conditions to perform:
1. both inputs must have int8 dtype
2. both inputs must be 2d
3. x1.shape must be [>16, >= 16 and a multiplier of 8]
4. x2.shape must be [>= 16 and a multiplier of 8, multiplier of 8]
Nevertheless, it could still be valuable to include.
The performance report (using the code from #19137 )
```python
elif backend.backend() == "torch":
import torch
torch.set_float32_matmul_precision("high")
jit_network = torch.compile(network)
```
```bash
TOPS/TFLOPS
===================================
dim    |     int8     fp16     fp32
-----------------------------------
256    |     0.23     0.51     0.49
512    |     1.52     3.26     3.21
1024   |    11.98    25.34 …
```
=> Support `torch._int_mm` in torch's `ops.matmul`

keras/layers/normalization/spectral_normalization.py, keras/layers/regularization/alpha_dropout.py, keras/layers/rnn/rnn.py, keras/testing/test_case.py
Added the training argument to `TestModel.call` so that `training=True` is actually passed to the layer during the training test.
This uncovered some issues:
- `SpectralNormalization` had an `if` that should have been a `ops.cond`. https://github.com/keras-team/keras/issues/19183
- `AlphaDropout` should have been using `ops.shape`.
- The dropout mask for `StackedRNNCells` was not constructed with the correct size.
=> Fix `test_case.run_layer` which was not training with `training=True`.

keras/backend/common/variables.py, keras/backend/common/variables_test.py, keras/export/export_lib_test.py
This PR additionally special-cases JAX dimension expressions (at tracing time) from being blocked by dtype and shape standardization in Keras.
**NOTE:** The test for unknown JAX dimensions in shape and dtype standardization is not reproducible outside of the export API. (This is because SavedModel export triggers JAX tracing, which produces the JAX _DimExpr for which we special-case.) As a result, I have deleted the associated test, as it is covered in `export_lib_test.py`.
=> Add workflow test for multiple unknown JAX dimensions

requirements-jax-cuda.txt, requirements-tensorflow-cuda.txt, requirements-torch-cuda.txt, requirements.txt
Now that RC0 is released, pin to TF 2.16 RC0 instead of Nightly.
Spectral Norm test is failing on the Master as well for TF GPU Backend.
=> Update CI to TF 2.16 RC0

keras/utils/dataset_utils.py, keras/utils/image_dataset_utils.py
I added a verbose arg to `index_directory` function in utils/dataset_utils.py and to `image_dataset_from_directory` function  in utils/image_dataset_utils.py to control/remove prints when using `image_dataset_from_directory.`
=> Remove prints from image dataset from directory

keras/saving/object_registration.py
Found when converting/exposing your entire codebase:
```sh
$ python -m pip install python-cdd==0.0.99rc32  # Or a newer version!
$ python -m cdd exmod -m keras --emit sqlalchemy_hybrid -r -o build/keras 
```
It fails because it parses out this:
```py
{   'doc': 'Dictionary of `{name: object}` pairs.',
'typ': 'Mapping[name, object]'}
```
Instead of this:
```py
{   'doc': 'Dictionary of `{name: object}` pairs.',
'typ': 'Mapping[str, object]'}
```
PS: Not sure if `object` is the best narrowing of the target type. If it's not tell me the right, e.g., `Callable`.
BTW: Sending this one-line one-file PR because when I tried whole codebase upgrade-to-non-adhoc-syntax it was not merged: #18786
=> [keras/saving/object_registration.py] Set `CustomObjectScope` dictionary arg type to `str` rather than `name`

keras/backend/tensorflow/linalg.py, keras/layers/normalization/spectral_normalization_test.py, keras/ops/linalg.py, keras/ops/linalg_test.py
- On the Tensorflow backend, reimplemented all cases for `ops.linalg.norm` instead of sometimes relying on `tf.linalg.norm`. `tf.linalg.norm` sometimes fails to compile on XLA or returns tensors with no shape. Note that there is not special op used by `tf.linalg.norm`.
- Added more test cases for `ops.linalg.norm`:
- vector norms are now also tested with 2 dimensional inputs
- axis as a tuple of 2 values is tested
- many more cases of invalid combinations of rank / ord / axis are verified
=> Fix for TF XLA compilation error for `SpectralNormalization`.

keras/random/random.py
I noticed that the `@keras_export` decorator was missing from the `random.binomial` and `random.beta` functions which is causing issues when importing these functions from the `random` module.
=> Decorate `binomial` and `beta` functions with `keras_export`

keras/backend/jax/numpy.py, keras/backend/numpy/numpy.py, keras/backend/tensorflow/numpy.py, keras/backend/torch/numpy.py, keras/ops/numpy.py, keras/ops/numpy_test.py
jax:
use `preferred_element_type="int32"` to enable int8xint8->int32 in `einsum`
tf:
add custom ops for 2 subscripts below to replace `tf.einsum` with `tf.matmul` in order to enable int8xint8->int32 format:
- "abcde,afce->acdbf"
- "abc,dce->abde"
other backends:
just align the dtype conversion with jax and tf.
However, I'm not sure how to benchmark them, and currently, I don't see much improvement by using int8 `einsum` compared to float32/bfloat16 `einsum` in jax and tf backends.
=> Enable int8xint8->int32 `einsum`

keras/backend/common/backend_utils.py, keras/backend/jax/numpy.py, keras/backend/numpy/numpy.py, keras/backend/tensorflow/numpy.py, keras/backend/torch/numpy.py, keras/ops/numpy.py, keras/ops/numpy_test.py, keras/ops/operation_utils.py, keras/ops/operation_utils_test.py
In this PR:
- Introduces `canonicalize_axis`, `standardize_axis_for_numpy` and `to_tuple_or_list` and utilizes them to standardize the code across all backends
- Add support for multiple axes in `expand_dims` and `squeeze` (especially in tensorflow and torch)
(BTW, this PR will further help to reduce the redundancy of quantization computation)
EDITD:
`pytest.warns(None)` has been replaced by `warnings.catch_warnings(record=True)` as suggested in https://github.com/scipy/scipy/issues/15186
This should fix the failed unit tests.
=> Refactor `axis` logic across all backends and add support for multiple axes in `expand_dims` and `squeeze`

keras/utils/image_dataset_utils.py, keras/utils/image_dataset_utils_test.py
I'm not really sure how to do this but I've noticed that there is no easy way to use padding with image_dataset_from_directory. So I added an analogous argument to crop_to_aspect_ratio. I'm not sure about the behaviour when both padding and croping are set to true so I just raise an error.
=> Add pad_to_aspect_ratio arg to image_dataset_from_directory

.github/workflows/actions.yml, integration_tests/numerical_test.py
Resolves #19216.
Add numerical test to the CI to catch more bugs.
=> add numerical test to CI

keras/trainers/data_adapters/data_adapter_utils.py
Quite a simple fix:
`tuple or list` returns `tuple` so the current check amounts to `isinstance(x, tuple)` when clearly it is intended to also check for `list`.
You can quickly verify this with the following example in any interactive python shell:
```py3
>>> x = [1, 2, 3]
>>> isinstance(x, tuple or list)
False
>>> isinstance(x, (tuple, list))
True
```
=> Fix `isinstance` check for tuple input in `pack_x_y_sample_weight`

keras/backend/jax/random.py
jax.random.shuffle API is deprecated and is replaced with [jax.random.permutation](https://jax.readthedocs.io/en/latest/_autosummary/jax.random.permutation.html).
Fixes: https://github.com/keras-team/keras/issues/19271
=> Update jax random shuffle API

keras/distribution/distribution_lib.py
Hey, excited about Keras 3 and trying out its distributed training, thanks for your work! I found a parameter name typo in `keras.distribution.initialize`.
=> fix typo in `keras.distribution.initialize` (`proceed_id` -> `process_id`)

keras/backend/common/stateless_scope.py, keras/backend/tensorflow/core.py
When variables are passed to stateless calls (`stateless_call`, `stateless_update`, `stateless_apply`), unwrap them to extract their value so that the mapping from variable to value in `StatelessScope` points to a value. This is to prevent an infinite recursion when performing operations (e.g. `__add__`) in a stateless scope.
Also fix issue where casting a `tf.SparseTensor` would lose the shape. The optimization in `ops.cast` is what revealed the stateless calls bug.
=> Unwrap variable values in all stateless calls.

keras/ops/nn.py, keras/ops/nn_test.py
=> Fix `keras.ops.softmax` for the tensorflow backend

.github/workflows/actions.yml
Resolves #19264 
We may need to add the secret to the repo if it is not there yet.
The tests running here are fine.
Let's merge it to see if it works on the master branch.
=> add token to codecov

keras/backend/tensorflow/optimizer.py, keras/optimizers/optimizer_sparse_test.py
This should have been added along with `scatter_add` and `scatter_sub` as part of https://github.com/keras-team/keras/pull/18692 as it was added in the super class: https://github.com/keras-team/keras/blob/master/keras/optimizers/base_optimizer.py#L222
Fixes https://github.com/keras-team/keras/issues/19281
=> Add Tensorflow support for variable `scatter_update` in optimizers.

keras/backend/tensorflow/core.py, keras/backend/tensorflow/layer.py, keras/backend/tensorflow/numpy.py, keras/backend/tensorflow/trainer.py, keras/export/export_lib.py, keras/models/cloning.py, keras/ops/core_test.py, keras/utils/tracking.py, keras/utils/tree.py, keras/utils/tree_test.py, requirements-common.txt, setup.py
Related to #18442 
Related to #18614 
This PR refactors `keras.utils.tree` to use `optree` instead of `dm-tree`
- Exports APIs (`is_nested`, `flatten`, `unflatten_as`, `map_structure`, `map_structure_up_to`, `assert_same_structure`, `pack_sequence_as`, `lists_to_tuples`) with the path `keras.utils.tree.*`
- Add docstrings (mostly borrowed from `dm-tree` and `tf.nest`)
- Adds unit tests
- Eliminates `tf.nest` in the codebase (excluding legacy code)
I have verified that exported APIs should meet the requirements of keras_cv and keras_nlp
=> Replace `dm-tree` with `optree`

keras/trainers/data_adapters/data_adapter_utils.py, keras/trainers/data_adapters/generator_data_adapter.py, keras/trainers/data_adapters/generator_data_adapter_test.py, keras/trainers/data_adapters/py_dataset_adapter.py, keras/trainers/data_adapters/py_dataset_adapter_test.py, keras/trainers/data_adapters/torch_data_loader_adapter.py, keras/trainers/data_adapters/torch_data_loader_adapter_test.py
The shape for the `tf.TensorSpec` for the `tf.Dataset` is determined by inspecting several batches and keeping dimensions that are common.
Fixes https://github.com/keras-team/keras/issues/19124
=> Allow tensors in `tf.Dataset`s to have different dimensions.

keras/dtype_policies/__init__.py, keras/dtype_policies/dtype_policy.py, keras/dtype_policies/dtype_policy_test.py
Fixes issue for KerasCV where we use `uint8` for dtype.  Set to `FloatDtypePolicy` to get past the quantization dtype policy error. Tested locally with KerasCV to verify the fix.
=> Set dtype policy for uint8

keras/dtype_policies/dtype_policy.py, keras/layers/attention/attention.py, keras/layers/attention/attention_test.py
Fixes #19257 by using Value dim shape for `compute_output_shape` of Attention layer.
=> Use Value dim shape for Attention compute_output_shape

keras/layers/reshaping/up_sampling2d.py
When the `data_format` is `"channels_first"` the rows and columns are mentioned as `2,3` but this logic will not hold good when the input is transposed like below, which results in input to have `rows,col as 1,2` always for both `channel_first` and `channel_last` 
https://github.com/keras-team/keras/blob/5bc8488c0ea3f43c70c70ebca919093cd56066eb/keras/layers/reshaping/up_sampling2d.py#L150-L151
This fixes the incorrect shape computation of `new_shape` when the `interpolation` is not `"nearest"`
Fixes: https://github.com/keras-team/keras/issues/19261
Fixes: https://github.com/keras-team/keras/issues/19153
Working Gist by subclassing layer. https://colab.sandbox.google.com/gist/sachinprasadhs/3b9ea7d2b3bbb4f31c9b2eacce86cf2c/upsampling.ipynb
=> Fix output shape for channels_first

keras/utils/jax_layer.py, keras/utils/jax_layer_test.py, requirements.txt
- `JaxLayer` can wrap any JAX model defined by a function.
- `FlaxLayer` is a subclass of `JaxLayer` that can wrap a Flax module.
=> Add `JaxLayer` and `FlaxLayer` to wrap JAX/Flax modules as layers.

keras/utils/jax_layer.py
TensorFlow Nightly failed on import of Keras since `jax` becomes a requirement due to import.
```
+ /tmp/tmp.yijSXl7avZ/bin/python3 -c 'import sys; import tensorflow as tf; sys.exit(0 if "keras" in tf.keras.__name__ else 1)'
File "/tmp/tmp.yijSXl7avZ/lib/python3.12/site-packages/tensorflow/python/util/lazy_loader.py", line 147, in _initialize
import keras  # pylint: disable=g-import-not-at-top
^^^^^^^^^^^^
File "/tmp/tmp.yijSXl7avZ/lib/python3.12/site-packages/keras/__init__.py", line 8, in <module>
from keras import _tf_keras
File "/tmp/tmp.yijSXl7avZ/lib/python3.12/site-packages/keras/_tf_keras/__init__.py", line 1, in <module>
from keras._tf_keras import keras
File "/tmp/tmp.yijSXl7avZ/lib/python3.12/site-packages/keras/_tf_keras/keras/__init__.py", …
```
=> Move Jax import to conditional

keras/utils/jax_layer_test.py, requirements-jax-cuda.txt, requirements-tensorflow-cuda.txt, requirements-torch-cuda.txt
`flax` is missing in the `requirements-[backend]-cuda.txt`
`@pytest.mark.skipif` has been also included to skip `flax`-related tests if the absence of `flax` is intentional
=> Fix gpu CI by adding `flax` in the requirements

keras/saving/saving_lib.py, keras/saving/saving_lib_test.py
I'm working on getting https://github.com/adriangb/scikeras and one of the needed features is being able to pickle models (e.g. for `GridSearchCV`). This is the first step for this, I can follow up with a PR to implement `Model.__reduce__` although that is not strictly necessary (it can be implemented via `copyreg.pickle` in SciKeras).
Since saving already worked with a file-like object internally I just had to refactor the logic into `_fileobj` methods making this a pretty straightforward change.
=> Allow save_model/load_model to accept a file-like object

keras/layers/core/dense.py, keras/layers/core/dense_test.py, keras/layers/core/einsum_dense.py, keras/layers/core/einsum_dense_test.py
This PR updates the logic in `build` to directly add int8 weights if `dtype_policy` is a QuantizedDTypePolicy
Additionally, I have moved the logic about quantization to the bottom of the class.
=> Update `build` in `Dense` and `EinsumDense` for `QuantizedDTypePolicy`

keras/backend/torch/core.py, keras/ops/core.py, keras/ops/core_test.py
With little bit of tweaking of the syntax, now its possible to have custom gradients for all three - JAX, PyTorch and TensorFlow.
Sorry if I don't know, tho I added the unit tests, I don't know how to run to test it.
Example of syntax:
Here's the rough notebook testing it:
- https://colab.research.google.com/gist/abhaskumarsinha/5486857bacd9adb78a32ed29aee3f580/keras-autograd.ipynb
- https://colab.research.google.com/drive/1PbnHsZMWBLHXzOtrzwTLc6GQMAO_EwZb?usp=sharing
I believe custom addition of function and their custom gradient definitions would enable the users to implement complex layers and operations even if that isn't available in other frameworks. It could also help them work with custom data structures like - complex numbers, non metric spaces or probabilistic spaces.
Example …
=> Custom Gradients

keras/initializers/random_initializers.py, keras/layers/preprocessing/random_crop.py
This fixes edge case scenario when `seed=0`.
According to the existing implementation for `seed=0`, `self.seed = seed or random.make_default_seed()` evaluates to 
`0 or random.make_default_seed()` which forces the seed value from  `random.make_default_seed()` and invalidate this logic for `0` input.
Fixes: https://github.com/keras-team/keras/issues/19361
=> fix seed value when seed=0

keras/layers/merging/dot.py
Fixed the type checking for layers merging condition to accept list input as well.
For the initial `model.get_config()` `input_shape[0]` is a `tuple` 
```python
{'module': 'keras.layers',
'class_name': 'Dot',
'config': {'name': 'dot',
'trainable': True,
'dtype': 'float32',
'axes': 1,
'normalize': False},
'registered_name': None,
'build_config': {'input_shape': [(None, 10), (None, 10)]},
'name': 'dot',
```
But the `input_shape[0]` type gets changed to `list` when the model is saved and loaded back.
```
{
"module":"keras.layers",
"class_name":"Dot",
"config":{
"name":"dot",
"trainable":true,
"dtype":"float32",
"axes":1,
"normalize":false
},
"registered_name":"None",
"build_config":{
"input_shape":[
[
"None",
10
],
[
"None",
10
]
]
},
"name":"dot", 
```
Fixes: …
=> Fix type check for input

keras/backend/tensorflow/numpy.py, keras/layers/core/dense_test.py, keras/layers/core/einsum_dense_test.py, keras/ops/numpy_test.py
We need these new subscripts to utilize int8,int8->int32 `einsum` for backprop in #19356 
```python
inputs_grad = ops.einsum(
self._custom_gradient_equation, upstream, float_kernel
)
```
To find out all of these subscripts:
```python
import re
from keras.backend.tensorflow.numpy import _normalize_einsum_subscripts
currently_supported_subscripts = [
"a,b->ab",
"ab,bc->ac",
"abc,cd->abd",
"abcd,abed->abce",
"abcd,adbe->acbe",
"abcd,aecd->acbe",
"abcd,aecd->aceb",
"abc,cde->abde",
"abc,dce->abde",
"abcd,cde->abe",
"abcde,aebf->adbcf",
"abcde,afce->acdbf",
]
def custom_gradient_subscripts(equation):
dot_replaced_string = re.sub(r"\.\.\.", "0", equation)
split_string = re.match(
"([a-zA-Z]+),([a-zA-Z]+)->([a-zA-Z]+)", dot_replaced_string
)
if split_string is not None:
input_spec = …
```
=> Add more manual implementations for TF's `einsum`

keras/saving/saving_lib_test.py
When running tests locally, it would add an untracked file to git.
So changing it to use a temporary directory.
=> only save to temp directories in tests

keras/trainers/trainer.py, keras/trainers/trainer_test.py
Related to #19267.
Before this fix, when returning a list from `model.evaluate()`, it would always sort the value by the metric names,
not respecting the order of the metrics configed by the user in `model.compile()`.
Added a test to ensure the behavior.
Before the fix, the test fails.
After the fix, the test passes.
=> Bug fix, model.evaluate return metrics in order.

keras/backend/jax/trainer.py, keras/backend/numpy/trainer.py, keras/backend/tensorflow/trainer.py, keras/backend/torch/trainer.py, keras/trainers/trainer.py, keras/trainers/trainer_test.py
Related to #19267 .
This fixes one of the numerical differences between Keras 3 & Keras 2.
The loss was averaged across multi batches without considering whether it is a full batch or not.
The last batch contains less examples, should be averaged dividing the actual number of samples..
Used `sample_weights` argument in `Mean.update_state()`.
So the `Mean` class would average it considering the number of samples.
Extracted a backend agnostic function to avoid confusion to the readers as it is not the same as the `sample_weights` set by the user.
Added 2 tests, which fail before the change, but succeed after the change.
=> fix bug for numerical difference in losses

keras/utils/sequence_utils_test.py
For function `keras.utils.pad_sequences`, it says
sequences: List of sequences (each sequence is a list of integers).
but floats here also work. This commit add test for float type
Modifications to the function itself and document may involve API stability, so no changes have been made, further consideration may be needed
=> Add `dtype=float32` to PadSequencesTest

keras/layers/core/dense.py, keras/layers/core/dense_test.py, keras/layers/core/einsum_dense.py, keras/layers/core/einsum_dense_test.py, keras/layers/core/embedding.py, keras/layers/core/embedding_test.py
This PR includes:
1. Add `quantize` to Embedding layer
2. Prevent quantization of subclasses for Dense, EinsumDense and Embedding
3. Improve `quantized_call` for training speed in EinsumDense
|model|quantized|`compute_dtype`|training speed (before/this pr)|peak memory usage (before/this pr)|
|-|-|-|-|-|
|GPT2|int8|float32|112ms / 106ms|3.994GB / 4.066GB|
|GPT2|int8|bfloat16|88ms / 82ms|2.745GB / 2.728GB|
=> Add `quantize` to Embedding

keras/layers/preprocessing/center_crop.py
The `CentreCrop` layer expects `input_shape` to be a non-nested tuple(or list) of size 3 (unbatched) or size 4 (batched). Since `input_shape` not inferring from the inputs passed to the layer, user can pass any value like nested list or nested tuple or and it will give output shape which is not expected.
Proposed a check for input_shape validation. May please review.
Might fix #19372.
=> Fix CentreCrop compute_output_shape

keras/export/export_lib.py
Per our discussion @fchollet, removing this duplicate wrapping.
=> Remove duplicate variable wrapping for JAX export

keras/backend/common/variables.py, keras/backend/common/variables_test.py, keras/layers/layer.py, keras/layers/layer_test.py, keras/layers/normalization/batch_normalization.py, keras/layers/normalization/batch_normalization_test.py, keras/layers/normalization/layer_normalization.py, keras/layers/normalization/layer_normalization_test.py
Individual autocasting to the wieghts is possible to configure in Keras2 using the option called `experimental_autocast`
https://github.com/keras-team/tf-keras/blob/master/tf_keras/engine/base_layer.py#L608
In fact, this missing feature could lead to inconsistent behavior for `BatcnNormalization` and `LayerNormalization` between Keras2 and Keras3.
This PR is also related to the upcoming fp8 training.
(`amax_history` and `scale` are set and utilized in `float32` if I'm not mistaken)
cc @kaixih
=> Reintroduce the option for autocasting to individual weights

keras/layers/preprocessing/category_encoding.py, keras/layers/preprocessing/category_encoding_test.py
Currently the `CategoryEncoding` layer outputs shape and its `compute_output_shape` method not rendering same outputs. The behaviour is same across all backends. Fixed three cases where there is difference.
Please note that the behaviour is different wrt Keras2 but same across all three backends with Keras3. Hence the fix is inline with Keras3 outputs and `compute_output_shape` function changed to match the actual output shapes.
The behaviour in Keras3 across all backends with and without fix replicated in the attached  [tf-gist,](https://colab.sandbox.google.com/gist/SuryanarayanaY/bfd84b3f37080f3ab9db8bf611bb4ac8/64392_keras3_tf_tested.ipynb) [torch-gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/88d4237009aa344315cd5a0628dc707e/64392_keras3_torch_tested.ipynb) & …
=> fix compute_output_shape in CategoryEncoding layer

keras/layers/rnn/dropout_rnn_cell.py
Fix typo for the the `recurrent dropout` implementation to use `recurrent_dropout` instead of `dropout`.
recurrent_dropout has no effect in the below usage as per existing implementation.
`layer = keras.layers.SimpleRNN(10, recurrent_dropout=0.5)` 
Fixes: https://github.com/keras-team/keras/issues/19395
=> Fix dropout for recurrent dropout

keras/utils/jax_layer.py, keras/utils/jax_layer_test.py
The code samples had typos.
Also removed in incorrect comment in tests, the export is fully tested.
=> Fix `FlaxLayer` docstring.

keras/backend/common/dtypes.py, keras/backend/common/dtypes_test.py, keras/backend/common/variables.py, keras/backend/common/variables_test.py, keras/backend/torch/core.py, keras/ops/core_test.py, keras/ops/math_test.py, keras/ops/nn_test.py, keras/ops/numpy_test.py
This PR:
- Centralizes the dtype-related variables into `keras.backend.common.dtypes`
- Uses `tuple` instead of `list` for dtype string initialization to prevent future overwriting.
- Introduces `float8_e4m3fn` and `float8_e5m2` for the upcoming fp8 training
- Adds a simple test for `ops.cast` of `float8_*`
It is worth noting that `dtypes.result_type` will intentionally fail when encountering `float8_*` because there are no implicit conversions from `float8_*` to other dtypes. (following the same rule as in JAX)
=> Refactor dtypes and add float8_* dtypes

keras/ops/numpy.py, keras/saving/serialization_lib_test.py
Please take a look, I had trouble loading a model that did things like this:
kernel_output = keras.layers.Concatenate()(
[ 
kernel(input[:, 2*other:2*other+2] - input[:, 2*ref:2*ref+2]) 
for ref in range(n)
for other in range(n) 
if other != ref 
])
=> ops/numpy.py: support key as list in GetItem

keras/losses/__init__.py, keras/losses/losses.py, keras/losses/losses_test.py
Adds Dice class/function implementation to losses.
=> feat(losses): add Dice loss implementation

keras/utils/summary_utils.py
When the `custom function` is passed as a `print_fn` the existing implementation will error out since `line_break` will not be provided in the custom function and it has no action for custom function.
This fix will check if the `print_fn` is from the below logic then pass the argument `line_break` else call `print_fn` without argument `line_break`
```
if not print_fn and not io_utils.is_interactive_logging_enabled():
print_fn = io_utils.print_msg
```
https://github.com/keras-team/keras/blob/6c591d7d34c3ffaa50e805fd75c83d9c2a23414f/keras/utils/summary_utils.py#L137C1-L138C38
Fixes: https://github.com/keras-team/keras/issues/19371
=> Fix print_fn for custom function

keras/layers/rnn/bidirectional.py, keras/layers/rnn/bidirectional_test.py
The `compute_output_shape` trying to add list and tuples of shapes while calculating the output_shape with `return_state=True` and `merge_mode='concat'`. This will cause the TypeError like below.
```
TypeError: Exception encountered when calling Bidirectional.call().
can only concatenate list (not "tuple") to list
```
May Fixes #19328
=> Fix compute_output_shape in  bidirectional.py

keras/backend/jax/numpy.py, keras/backend/numpy/numpy.py, keras/backend/tensorflow/numpy.py, keras/backend/torch/numpy.py, keras/ops/numpy.py, keras/ops/numpy_test.py
Adds support for `ops.correlate` implementing `np.correlate` for all backends.
=> feat(ops): support `np.correlate`

keras/export/export_lib.py, keras/export/export_lib_test.py
- Aliases are used to refer to `tf.function`s that may have multiple concrete functions.
- `jax2tf_kwargs` can be used to control the lowering that is performed by `jax2tf.convert`.
=> Add support for aliases and finer control over `jax2tf` in export.

keras/backend/jax/numpy.py
The JAX bug with `axis=None` and `keep_dims=True` is fixed.
=> Fix `quantile` and `median` for JAX backend with jax 0.4.26.

keras/losses/__init__.py
Binary and categorical focal crossentropy losses are not added to `ALL_OBJECTS_DICT` in `keras/losses/__init__.py` and therefore the following would raise a ValueError 
```python
losses.get("binary_focal_crossentropy")
```  
This PR imports the binary and categorical focal crossentropy classes and functions and adds them to `ALL_OBJECTS` (and, consequently, to `ALL_OBJECTS_DICT`)
=> Update keras/losses/__init__.py to include Binary and Categorical Focal Crossentropy

keras/metrics/reduction_metrics.py
This patch makes sure the `sample_weights` are on the default device. Before, it can happen that `sample_weights` are on CPU while values are on GPU (unless the `sample_weights` were moved to GPU by a dataloader, for example).
Note that the `y_true` are moved to the default device already during metric computation; for example https://github.com/keras-team/keras/blob/d4f23eac3a9469646a070129d723a532fdb07090/keras/metrics/accuracy_metrics.py#L9-L10 or https://github.com/keras-team/keras/blob/d4f23eac3a9469646a070129d723a532fdb07090/keras/metrics/f_score_metrics.py#L159-L160
I understand that a corresponding issue, reproducible example and a suitable test would be the ideal way to proceed, but unfortunately, my current time constraints only allow me to create this pull-request.
=> Fix a crash with PyTorch backend when using `weighted_metrics` with a GPU.

keras/layers/core/embedding.py
The python example in `Embedding` layer class uses Keras2 code snippet that has  `input_length` arg. This will raise an below with keras3. 
`Unrecognized 'input_length' keyword arguments passed to Embedding 
`
In keras3 we don't need this arg as it will automatically inferred from the input passed. Alternatively we can pass `input_shape`as kwarg. I proceeded with first approach.
Fixes #19282.
=> Fix example code in embedding.py

keras/backend/numpy/random.py, keras/backend/tensorflow/random.py, keras/backend/torch/random.py, keras/layers/regularization/alpha_dropout_test.py, keras/layers/regularization/dropout_test.py, keras/layers/regularization/gaussian_dropout.py, keras/layers/regularization/gaussian_dropout_test.py, keras/layers/regularization/gaussian_noise.py, keras/layers/regularization/gaussian_noise_test.py, keras/random/random_test.py
Fixes #19437 
This PR fixes the issue when setting `dtype` in `keras.random.*` and the corresponding implementations in `keras.layes.*`
A rigorous test has been also included.
=> Fix dtype inconsistency in `keras.random`

keras/models/functional.py, keras/models/model.py, keras/models/sequential.py
Fixes #19152 (credit to @marcelo-souzaf)
Related to #19453 
This PR addresses incorrect type annotations for `Model`, `Sequential` and `Functional`
The root cause is the overridden `__new__`
I'm using VSCode to demonstrate:
|Class|Before|After|
|-|-|-|
|`Model`| ![3](https://github.com/keras-team/keras/assets/20734616/c52628ea-62cc-493a-a270-3c974f4825bd) | ![6](https://github.com/keras-team/keras/assets/20734616/df1f0a74-5996-4362-8609-43d4da551103) |
|`Sequential`| ![1](https://github.com/keras-team/keras/assets/20734616/844bf74c-da49-4f95-b8f8-ba241e00299c) | ![4](https://github.com/keras-team/keras/assets/20734616/57489cd2-c7c6-4c6a-a477-e96712f5518e) |
|`Functional`| ![2](https://github.com/keras-team/keras/assets/20734616/b62ed5ca-13a0-42e3-88dd-6a840f25004d) | …
=> Fix type annotation for `Model`, `Sequential` and `Functional`

keras/activations/activations.py
Current implementation of `hard_sigmoid` op  in Keras3 is inline with `torch` and `jax` whereas Keras2 it is different. But documentation still shows Keras2 implementation. Changing the documentation accordingly to suit current implementation.
Might Fix TF #[65381](https://github.com/tensorflow/tensorflow/issues/65381)
=> Doc bug fix for hard_sigmoid op

keras/backend/jax/numpy.py, keras/ops/numpy.py, keras/ops/numpy_test.py
Support for TensorFlow backend for sparse tensors was added in https://github.com/keras-team/keras/commit/5f9b8befffd2fae6e0a074867dddfc01fcfea31c
This adds:
- symbolic support
- JAX support
- units tests for symbolic, TensorFlow and JAX
=> Add full `bincount` and `digitize` sparse support.

keras/backend/tensorflow/distribution_lib.py
`distribution_lib.list_device(device_type=None)` would return CPU devices instead of returning GPU/TPU devices if available. This makes the behavior of `device_type=None` consistent with the JAX implementation and also consistent with the docstring.
Fixes `testing.tensorflow_uses_gpu()`.
=> Fix for `distribution_lib.list_device()` for TensorFlow backend.

keras/optimizers/base_optimizer.py, keras/optimizers/optimizer_test.py
=> Fix issue with using a callable as a learning rate

keras/ops/nn_test.py
I have added some tests for untested lines in `ops/nn.py` 
and
I will investigate this failed test later (another PR) 
TODO: Currently, when using the `one_hot` function with an invalid `axis` parameter, the error is directly thrown by the backends.
```
def test_one_hot_with_invalid_axis_raises_value_error(self):
x = np.array([[0, 1], [1, 2]])
num_classes = 3
invalid_axis = 5
expected_error_message = (
f"axis must be -1 or between \\[0, {len(x.shape)}\\), but "
f"received {invalid_axis}."
)
with self.assertRaisesRegex(ValueError, expected_error_message):
knn.one_hot(x, num_classes=num_classes, axis=invalid_axis)
```
=> Add missing tests `ops/nn.py`

keras/backend/jax/image.py, keras/backend/numpy/image.py, keras/backend/tensorflow/image.py, keras/backend/torch/image.py, keras/ops/image.py, keras/ops/image_test.py
=> Added `rgb_to_grayscale`

keras/backend/tensorflow/core.py, keras/backend/tensorflow/sparse.py, keras/ops/numpy_test.py, keras/trainers/data_adapters/array_slicing.py
What was crashing was `tf.sparse.to_dense`, which was called by `convert_to_numpy`, which was called by `assertAllClose`.
Special handling is needed on GPU to densify sparse tensors that represent a scalar.
Also found a simpler way to create empty (i.e. with 0 dimensions) tensors.
=> Workaround for Tensorflow unit test crash on GPU.

keras/ops/image.py, keras/ops/image_test.py
This PR addresses a 
`TypeError: MapCoordinates.__init__() missing 1 required positional argument: 'order'`
in `MapCoordinates` by adding a default `order=1` in the constructor. 
Also,
tests for uncovered areas in `ops/image.py` are also included for better coverage.
---
**Note:**
We default to `order=1` for linear interpolation, which is generally more commonly used in many applications  and preferred choice due to its smoother results than order=0 (nearest neighbor).
---
**Changes Made:**
- Added default `order=1` to `MapCoordinates` constructor.
- Included tests for uncovered areas in `ops/image.py`.
=> Fix `MapCoordinates` class and Add Tests for Uncovered Areas in `keras/ops/image.py`

keras/backend/jax/nn.py
Ref: https://jax.readthedocs.io/en/latest/notebooks/thinking_in_jax.html#numpy-lax-xla-jax-api-layering
`jax.numpy` implicitly promotes arguments to allow operations of mixed data types, while `jax.lax` does not. If using `jax.lax` directly, it is advised to do explicit type promotion. Because the core functions in nn.py are the backbone for various model edge cases, it is better to use a safer operand.
=> Update nn.py to use jnp.add rather than + operand.

keras/losses/__init__.py, keras/losses/losses.py, keras/losses/losses_test.py
Add [Tversky](https://arxiv.org/abs/1706.05721) loss implementation.
=> feat(losses): add Tversky loss implementation

keras/layers/layer.py, keras/layers/layer_test.py, keras/trainers/trainer.py
- added `Layer.metrics` to return all metrics owned by the layer and its sub-layers recursively.
- `Layer.metrics_variables` now returns variables from all metrics recursively, not just the layer and its direct sub-layers.
- `Model.metrics` now returns all metrics recursively, not just the model level metrics.
- `Model.metrics_variables` now returns variables from all metrics recursively, not just the model level metrics.
- added test coverage to test metrics and variables 2 levels deep.
This is consistent with the Keras 2 behavior and how `Model/Layer.variables` and `Model/Layer.weights` work.
=> Models and layers now return owned metrics recursively.

keras/layers/preprocessing/category_encoding_test.py, keras/layers/preprocessing/hashing_test.py, keras/layers/preprocessing/index_lookup.py, keras/layers/preprocessing/index_lookup_test.py, keras/layers/preprocessing/normalization_test.py, keras/layers/preprocessing/random_brightness.py, keras/layers/preprocessing/random_brightness_test.py
1: 
In this PR , I have added tests for keras/layers/preprocessing:
`keras/layers/preprocessing/category_encoding_test.py`
`keras/layers/preprocessing/hashing_test.py`
`keras/layers/preprocessing/index_lookup_test.py`
`keras/layers/preprocessing/normalization_test.py`
---
2 :
This PR corrects the error attribute names in the `RandomBrightness` layer, changing `_value_range_VALIDATION_ERROR` to `_VALUE_RANGE_VALIDATION_ERROR`. This ensures that the proper error messages are displayed when `value_range` parameter validations fail.
---
=> Fix `RandomBrightness`, Enhance `IndexLookup` Initialization and Expand Test Coverage for `Preprocessing Layers`

keras/src/backend/jax/trainer.py, keras/src/backend/numpy/trainer.py, keras/src/backend/tensorflow/trainer.py, keras/src/backend/torch/trainer.py, keras/src/trainers/trainer.py, keras/src/trainers/trainer_test.py
This works the same way as in Keras 2, whereby the metrics are returned directly from the logs if the set of keys doesn't match the model metrics.
=> Added metrics from custom `train_step`/`test_step` are now returned.

README.md, api_gen.py
Use Temp Dir and Abs path in `api_gen.py`
=> Use temp dir and abs path in `api_gen.py`

keras/src/backend/jax/optimizer.py, keras/src/backend/tensorflow/optimizer.py, keras/src/backend/torch/optimizers/torch_parallel_optimizer.py, keras/src/optimizers/adadelta.py, keras/src/optimizers/adafactor.py, keras/src/optimizers/adagrad.py, keras/src/optimizers/adam.py, keras/src/optimizers/adamax.py, keras/src/optimizers/adamw.py, keras/src/optimizers/base_optimizer.py, keras/src/optimizers/ftrl.py, keras/src/optimizers/lion.py, keras/src/optimizers/nadam.py, keras/src/optimizers/optimizer_test.py, keras/src/optimizers/rmsprop.py, keras/src/optimizers/sgd.py
Ref implementation:
https://github.com/google/flax/pull/3623
We should use `ops.maximum` for gradient accumulation with `overwrite_with_gradient=True` variables.
This PR also fixes a potential bug in gradient accumulation where directly using `self._accumulated_gradients` may mismatch with the filtered `grads` in the code path.
The new test `test_overwrite_with_gradient_with_gradient_accumulation` can only pass after the changes.
EDITED:
Fix all optimizers arguments hint by including `loss_scale_factor` and `gradient_accumulation_steps`:
|Before|After|
|-|-|
|![before1](https://github.com/keras-team/keras/assets/20734616/bf3f4690-870e-46f9-87f9-416b8da6416c)|![before](https://github.com/keras-team/keras/assets/20734616/96c2d87b-0711-4277-8b53-b78532ce64ce)|
=> Fix gradient accumulation when using `overwrite_with_gradient` during float8 training

.kokoro/github/ubuntu/gpu/build.sh
Since code is now moved to `keras/src`, the ignore file paths for pytest also needs to be updated. This was done for GitHub action tests, but also needed to be done for GPU test runs.
=> Fix CI: Update code path in ignore path

.github/workflows/stale-issue-pr.yaml
1. Added condition to run only on main repo and skip forked repo.
2. Added 500 operations per run, so that issues and PRs will not be skipped during the run.
=> Add operations per run

keras/src/layers/core/dense.py, keras/src/layers/core/dense_test.py, keras/src/layers/core/einsum_dense.py, keras/src/layers/core/einsum_dense_test.py, keras/src/layers/core/embedding.py, keras/src/layers/core/embedding_test.py, keras/src/layers/layer.py
This PR prevents incorrect usage of `quantize` on the layer with different quantization modes.
```python
from keras import models
model = models.Sequential([layers.Input(shape=[16]), layers.Dense(32)])
model.quantize("int8")
model.quantize("float8")  # <- will succeed with the current codebase
```
This PR also replaces the original error msg with a more informative one:
```bash
ValueError: Layer 'dense' is already quantized with dtype_policy='int8_from_float32'. Received: mode=float8
```
=> Fix incorrect usage of `quantize`

keras/backend/exports.py, keras/backend/mlx/core.py, keras/backend/mlx/nn.py, keras/backend/mlx/numpy.py, keras/backend/mlx/trainer.py
Implemented `batch_normalisation`, `divide_no_nan`  and few fixes for imports.
=> implement batch_normalization

keras/src/backend/jax/numpy.py, keras/src/backend/tensorflow/linalg.py, keras/src/backend/tensorflow/math.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/tensorflow/random.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Mainly, this PR removes the dependency on `tfnp`.
I've tried to eliminate the usage of `tf.cond` in some important ops such as `take_along_axis`.
Additionally, support for negative indices has been added and tested for both `take` and `take_along_axis`, especially for tensorflow and torch backends.
EDITED:
- Add `__init__` both for `Tri` and `Eye` for consistency with convention of `k` and `dtype`
=> Remove the dependency on `tensorflow.experimental.numpy` and support negative indices for `take` and `take_along_axis`

keras/src/backend/jax/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py
- The TensorFlow implementation was missing `convert_to_tensor`
- The sparse annotation was unnecessarily applied twice
- Now `abs` calls `absolute` in all backends
Also fixed TensorFlow `ops.select`.
=> Make `ops.abs` and `ops.absolute` consistent between backends.

keras/src/models/model.py, keras/src/models/model_test.py
https://github.com/keras-team/keras/issues/19554
Implements some basic unit tests for pickling on top of one of the existing parameterized tests.  I think this gets pretty good coverage across cases.
There might be some weird edge cases where reloading fails, but I think this is fine in that pickling isn't really useful as  a long term storage solution - just a short term way to transfer some info between workers.
Open to ideas about better approaches here - this is just the best I could come up with.
=> Add pickle support for Keras model

keras/src/layers/core/einsum_dense.py, keras/src/layers/core/einsum_dense_test.py
Actually, this is a bug introduced by my previous PR...
I've added the unit tests for this and the specified equations are retrieved from Gemma.
=> Fix the bug in `_int8_call` of `EinsumDense`

keras/src/backend/mlx/numpy.py
Currently, MLX does not have a bultin `median(...)` function so I implemented it by using `mx.sort(...)` and `mx.take(...)`.
=> Implemented `median(...)` function.

keras/src/backend/mlx/numpy.py
Align `mlx/numpy.py` with other implementations. There were some missing params which are added.
=> mlx - add mx.round and fix numpy args

keras/src/utils/tracking.py
super() calls python's builtin list class.
As per Python docs: 
```python
list.insert(i, x)
```
"Insert an item at a given position. The first argument is the index of the element before which to insert, so a.insert(0, x) inserts at the front of the list, and a.insert(len(a), x) is equivalent to a.append(x)."
https://docs.python.org/3/tutorial/datastructures.html
=> list insert requires index

keras/src/datasets/imdb.py
Convert return type imdb.load_data to Numpy array. Currently X_train and X-test returned as list. Tested [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/f8132ac0b80cadf0c65ed4f74ee092c3/19596.ipynb).
Fixes #19596
=> Convert return type imdb.load_data to np array

requirements-jax-cuda.txt, requirements-tensorflow-cuda.txt, requirements.txt
=> pin torch < 2.3.0 (pre-release ver) to resolve 'Parameter' object has no attribute 'fget'

.github/workflows/stale-issue-pr.yaml
With latest version of stale. Cache management is required actions write permission to update the cahce in next run.
=> Provide write permission to action for cache management.

keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/losses/losses.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
This PR:
- Ensure dtype inference for `ctc_loss` across all backends
- Add `ctc_loss` to numpy backend
- Add `ctc_decode` (including both `"greedy"` and `"beam_search"` strategies) to numpy backend
- Add `"greedy"` strategy for `ctc_decode` to torch backend
- Reduce the number of import lines by using `keras.src.backend`
Furthermore, we can simply utilize `tf.nn.gelu` instead of a custom implementation since we have already removed the usage of `enable_numpy_behavior`
=> Refactor CTC APIs

requirements-common.txt
The new `api_gen.py` requires namex to be at `0.0.8`.
It errors out with `0.0.7`.
=> update the namex version requirements

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
@fchollet 
Sorry Last PR got messed up!
=> Add `PSNR` API

keras/src/backend/torch/core.py
Running with MPS used to require this flag since the feature was experimental. It has since graduated to stable in PyTorch (see https://pytorch.org/docs/stable/notes/mps.html).
We can go ahead and remove the flag check. Fix #19436.
=> Remove `PYTORCH_ENABLE_MPS_FALLBACK` flag requirement for mps

keras/src/ops/image.py
Error when an image of dtype `float16` is used in `nn.ops.image.extract_patches`
[Colab link](https://colab.research.google.com/drive/1y41vpFs6Cd4NHmSY6IRmU53PXgl_SAFE?usp=sharing)
Fixed it.
=> Making extract_patches compatible with images of dtype float16 along with float32

keras/src/trainers/data_adapters/__init__.py, keras/src/trainers/data_adapters/py_dataset_adapter.py, keras/src/trainers/data_adapters/py_dataset_adapter_test.py
`PyDataset` now uses the `num_batches` property instead of `__len__` to support `None`, which is how one indicates the dataset is infinite. Note that infinite datasets are not shuffled.
Fixes https://github.com/keras-team/keras/issues/19528
Also added exception reporting when using multithreading / multiprocessing. Previously, the program would just hang with no error reported.
=> Add support for infinite `PyDataset`s.

keras/src/trainers/data_adapters/array_data_adapter_test.py, keras/src/trainers/data_adapters/generator_data_adapter_test.py, keras/src/trainers/data_adapters/py_dataset_adapter.py, keras/src/trainers/data_adapters/py_dataset_adapter_test.py, keras/src/trainers/data_adapters/tf_dataset_adapter_test.py, keras/src/trainers/data_adapters/torch_data_loader_adapter_test.py
There is no use case for using an iterator for a different backend than the current backend.
=> Speed up `DataAdapter` tests by testing only the current backend.

keras/src/backend/mlx/math.py, keras/src/backend/mlx/trainer.py
Adds support for `math.erfinv` on MLX backend.
=> feat(math): support erfinv on mlx

keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Specifies `NonZero` output type with related test coverage.
=> fix(ops): specify `NonZero` output dtype and add test coverage

keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/losses/losses.py, keras/src/losses/losses_test.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
1. Compute `label_length` by counting non-`mask_index` elements in `losses.CTC`
2. Fix a bug in greedy decoding
3. Fix a bug where TF's beam search decoding didn't respect `mask_index`
4. Update the argument so that `mask_index` defaults to `0` which is consistent with `losses.CTC`
The unit tests have been updated.
I've also verified that this example will be compatible with Keras3 after the PR:
https://keras.io/examples/vision/handwriting_recognition/
|Backend|Training Speed|Validation Loss (at epoch=10)|
|-|-|-|
|tensorflow|~53ms/step|2.9052|
|jax|~9ms/step (super fast...)|2.9896|
- `tensorflow`, `ops.ctc_decode(strategy="beam_search")` at epoch=10:
- `jax`, `ops.ctc_decode(strategy="greedy")` at epoch=10:
=> Fix `ops.ctc_decode`

keras/src/dtype_policies/dtype_policy.py, keras/src/layers/layer_test.py, keras/src/layers/normalization/spectral_normalization_test.py, keras/src/testing/test_case.py
Fix #19629
1. Ensure the same rule applies for np arrays in autocasting (`self.dtype_policy.convert_input`)
2. Introduce `self.assertDType` in `TestCase` (should be useful for any dtype checks)
=> Ensure the same rule applies for np arrays in autocasting

keras/src/backend/tensorflow/nn.py, keras/src/ops/nn_test.py
=> support conv3d on cpu for TF

requirements-common.txt, setup.py
When installing keras with `pip install -U keras` the [`packaging`](https://pypi.org/project/packaging/) package is not installed.
Its parsing features are however used with 
```python
from packaging.version import parse
```
in `keras/src/backend/torch/trainer.py` and `keras/src/utils/torch_utils.py`, which leads to a `ModuleNotFoundError`.
This PR adds the `packaging` package to `requirements-common.txt` and `setup.py`.
=> add packaging requirement

keras/src/export/export_lib.py, keras/src/export/export_lib_test.py, keras/src/layers/layer.py
The code computing the `call` signature was not going through the structure correctly.
Also tweaked tracking in `Layer` class:
- the first attribute set was not tracked.
- `TrackedDict` does not play nice with `jax2tf`/JAX so `_build_shapes_dict` is not tracked.
=> Fix bug in `model.export()` when inputs in a structure.

requirements.txt
`tensorflow-cpu` is not available for macOS, hence switch to `tensorflow`
=> switch tensorflow for macOS

keras/src/layers/preprocessing/string_lookup.py
The string lookup layer outputs int64 dtype when `output_mode` is `one_hot` or `multi_hot` or `count`. But the documentation example shows the output as `float32` instead of `int64`. Hence Updating the same.
Fixes #19660 .
=> Update python example dtype in string_lookup.py

keras/src/layers/convolutional/conv1d.py, keras/src/layers/convolutional/conv1d_transpose.py, keras/src/layers/convolutional/conv2d.py, keras/src/layers/convolutional/conv2d_transpose.py, keras/src/layers/convolutional/conv3d.py, keras/src/layers/convolutional/conv3d_transpose.py, keras/src/layers/convolutional/depthwise_conv1d.py, keras/src/layers/convolutional/depthwise_conv2d.py, keras/src/layers/convolutional/separable_conv1d.py, keras/src/layers/convolutional/separable_conv2d.py, keras/src/layers/pooling/average_pooling1d.py, keras/src/layers/pooling/average_pooling2d.py, keras/src/layers/pooling/average_pooling3d.py, keras/src/layers/pooling/max_pooling1d.py, keras/src/layers/pooling/max_pooling2d.py, keras/src/layers/pooling/max_pooling3d.py
This change adds an extra newline character after the `Input shape:` and `Output shape:` sections for docstrings with nested bullet points. This ensures the correct markdown translation on the keras.io website for the convolution and pooling layers which have these bullet points right after these section headings. 
**Screeenshot of issue for MaxPooling2D from the keras.io website:**
The markdown translation logic in the keras-io repo for docstrings requires an additional \n character. Some layers such as the ConvLSTM and GlobalAveragePooling already do this correctly in their docstrings. This change replicates the correct structure for the docstrings of the pooling and conv layers which have this rendering issue
**Screenshot of MaxPooling2D after the fix:**
=> Fix for rendering issues with Keras Layers API Documentation (Convolution and Pooling layers)

keras/src/layers/layer.py, keras/src/layers/merging/base_merge.py, keras/src/layers/merging/concatenate.py, keras/src/layers/merging/maximum.py, keras/src/layers/merging/merging_test.py, keras/src/layers/merging/minimum.py, keras/src/layers/merging/multiply.py
- Fixed bug where base `Layer` class was not handling masking with input structures correctly, which affected all merge layers.
- Fixed bug where the zeros outside of the mask were still used to compute the output of the merge layer (affected `Maximum`, `Minimum` and `Multiply`).
- Fixed bug where the output mask was not computed correctly (affected all merge layers).
- Fixed bug where `Concatenate` layer was not broadcasting the mask correctly.
Fixes https://github.com/keras-team/keras/issues/18416
=> Fix masking in merge layers.

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/ops/__init__.py, keras/src/backend/jax/core.py, keras/src/backend/numpy/core.py, keras/src/backend/tensorflow/core.py, keras/src/backend/torch/core.py, keras/src/ops/core.py, keras/src/ops/core_test.py
Related to #19519
Originally, `tf.scan` stacks the output of the `f` as the final output and doesn't support the separated `carry` throughout the loop iterations.
I've reimplemented `scan` for tensorflow backend to align with the behavior of `jax.lax.scan`.
However, the current implementation requires that the output (`y`) of `f` must have the same shape/dtype as `carry`. This is not required in other backends.
=> Add `scan` op

keras/src/dtype_policies/dtype_policy.py, keras/src/dtype_policies/dtype_policy_test.py, keras/src/layers/core/dense.py, keras/src/layers/core/dense_test.py, keras/src/layers/core/einsum_dense.py, keras/src/layers/core/einsum_dense_test.py, keras/src/layers/core/embedding.py, keras/src/layers/core/embedding_test.py
This PR fixes unexpected dtype policy changes when quantization fails.
For example, the current codebase will output `False` in the following snippet:
```python
layer = layers.Embedding(10, 16)
layer.build()
x = np.random.randint(0, 9, size=(1, 3))
original_dtype_policy = layer.dtype_policy
try:
layer.quantize("float8")  # Will fail
except:
pass
print(original_dtype_policy == layer.dtype_policy)  # False
```
With this PR, the output will be `True`.
=> Fix unexpected dtype policy changes when quantization fails

keras/src/backend/tensorflow/core.py, keras/src/ops/core_test.py
With the TensorFlow backend, when passing a `RaggedTensor`, the dynamic shape returned by `tf.shape` is an object that raises an exception when a ragged dimension is accessed. We catch it and leave the dimension as `None`.
=> Fix `ops.shape()` for `tf.RaggedTensor`.

keras/src/utils/torch_utils.py
The PR consists of a tiny addition in docs to let the user know that `TorchModuleWrapper`, as the name sounds is not a Wrapper to Wrap any arbitrary code into Keras with any backend, but rather a different feature enabling integration of PyTorch custom layers to Keras when running PyTorch backends.
I'll try to write basic wrappers for actual code conversion if that is possible and try checking the extent by which complex models can be easily integrated into Keras, being backend invariant.
Thank You.
=> Improved docs to bring in clarity.

keras/src/applications/mobilenet_v3.py
Fixes #19689
I opted to add a `name` arg to fix the issue since it's a similar pattern in other `keras.applications` models (updated: see conversation below). An alternative way is to use `keras.src.utils.naming.uniquify` internally.
=> Add `name` to MobileNetV3 to allow multiple instances in one model

keras/src/dtype_policies/__init__.py, keras/src/ops/operation.py
- Subclasses of `Operation` / `Layer` which override `__init__` and use the `dtype` parameter don't expect a `dict`. We deserialize the `DTypePolicy` in `from_config`.
- The auto `get_config` feature would break when a `DTypePolicy` was passed to the constructor of any `Operation` or `Layer` subclass not implementing `get_config`.
=> Tweaks for serialization of DTypePolicy in ops/layers.

keras/src/export/export_lib.py, keras/src/export/export_lib_test.py
The export now supports subclasses of `Model` for which the `call` method takes more than one input argument. Note that it is required for the model class to implement a `build` method with a signature that matches the `call` method.
=> Fix export for subclass models with multiple inputs.

keras/src/backend/torch/nn.py
Hello,
As I was using an Apple M2 computer, I discovered a tiny bug in keras.ops.one_hot with the torch backend (on MPS device): the line `output = where(expand_dims(x, axis=-1) >= 0, output, 0)` raises the error "expected scalar type long long but found int", since in this setup the last "0" is automatically converted to an int (int32) instead of a long (int64), as opposed to  most backends/devices.
The proposed fix solves this issue (and still works with other backends/devices).
=> Fix one_hot for torch backend (MPS device)

keras/src/ops/operation.py
As of #19728, Operation.from_config() has been overriding the dtype field in the passed config dict.
There doesn't seem to be an explicit contract that from_config doesn't modify the config argument, but this seems to be the case in practice, and this behaviour has broken some code on an internal repo.
=> Don't mutate passed config dict in Operation.from_config()

keras/src/layers/preprocessing/hashed_crossing.py, keras/src/layers/preprocessing/hashing.py, keras/src/layers/preprocessing/index_lookup.py, keras/src/layers/preprocessing/text_vectorization.py, keras/src/utils/tf_utils.py
It turns out `tf_backend.convert_to_tensor` does not support on-GPU Torch tensors. This also removes the need for some late import.
=> Re-introduce `tf_utils.ensure_tensor` in preprocessing layers.

keras/src/dtype_policies/__init__.py, keras/src/ops/operation.py, keras/src/ops/operation_test.py
We should use `dtype_policies.serialize` to serialize the `DTypePolicy` in `Operation`. A simple test has been added to verify this.
A note has been added in `from_config` to indicate that when overriding `from_config`, users should deserialize the `dtype` if needed.
=> Fix `dtype` serialization

keras/src/backend/tensorflow/numpy.py, keras/src/ops/numpy_test.py
Fix #19772 
- Remove redundant `backend.convert_to_numpy` in tests
- Add tests for `num` as a tensor
=> Fix the `linspace` bug when `num` is a tensor in the tensorflow backend

keras/src/backend/jax/image.py, keras/src/backend/numpy/image.py, keras/src/backend/tensorflow/image.py, keras/src/backend/torch/image.py, keras/src/ops/image.py, keras/src/ops/image_test.py
As titled.
This should follow the convention of `keras.layers`:
Leave `data_format` as `None`, and if not specified, set it to the value of `keras.config.image_data_format`.
Additionally, the logic of `pad_images` and `crop_images` have been updated to support `data_format`. With this PR, we can also process unknown shapes in `pad_images` (similar to `ops.pad`).
However, it is impossible to support fully unknown shapes in `crop_images`.
=> Leave `data_format` as `None` in `keras.ops.images` and add `data_format` support to `pad_images` and `crop_images`

keras/src/layers/preprocessing/string_lookup.py, keras/src/layers/preprocessing/string_lookup_test.py
Currently keras.layers.StringLookup fails when Vocabulary is a Tensor. This will raise below error.
`AttributeError: 'StringLookup' object has no attribute 'encoding'
`
This is self.encoding declared after super class constructor call. Fixed the same and added a test case.
Fixes #19770
=> Fix bug in StringLokkup when vocab is a tensor

keras/src/layers/preprocessing/feature_space_test.py, keras/src/layers/preprocessing/normalization.py, keras/src/layers/preprocessing/tf_data_layer.py, keras/src/ops/linalg_test.py, keras/src/utils/backend_utils.py
The tests failed because we had the weights on torch gpu in `tf.data` pipeline.
To address this, I have introduced `convert_weight` in `TFDataLayer` to convert the weights of the layer to the correct backend setting.
(Currently, only `Normalization` needs this)
Additionally, loosen the tolerance in `linalg_test.py` to prevent random test failures.
With this PR, I can pass the failed tests on the master branch for all backends using GPU.
=> Add a conversion mechanism in `TFDataLayer` to better support different backends in `tf.data`

keras/src/layers/core/lambda_layer.py
The `output_shape` of a `keras.layers.Lambda` will be serialized as a list if it's originally a tuple.
After deserialization, it doesn't come back.  It works fine until a function call is made here:
https://github.com/keras-team/keras/blob/master/keras/src/layers/core/lambda_layer.py#L110
=> Fix `output_shape` deserialization in Lambda Layer (#19776)

keras/src/backend/numpy/nn.py, keras/src/layers/preprocessing/category_encoding_test.py, keras/src/ops/nn_test.py, keras/src/utils/numerical_utils.py
Make the behavior consistent across all backends.
=> Fix `CategoryEncoding` generates output with 1 additional dimension in all backends except NumPy (#19724)

keras/src/layers/reshaping/permute.py
By adding a third column in `dims` in the example, we avoid the misconception that the tuple could mean the exchange of the given pair, i.e. `(2, 3)` meaning to exchange the second and third column.
=> Make example in documentation more obvious

keras/src/utils/backend_utils.py, keras/src/utils/backend_utils_test.py
We should trigger an error when attempting to perform numpy's ops in a non-numpy backend via `DynamicBackend`. The current codebase disregards `self._backend` and defaults to use `keras.src.backend.*`.
=> Fix `DynamicBackend`

keras/src/models/functional.py, keras/src/models/functional_test.py, keras/src/models/sequential.py, keras/src/models/sequential_test.py, keras/src/ops/function.py, keras/src/ops/function_test.py
Fix #19792
As titled.
To enable this, we can simply add `compute_output_shape` to `Sequential` and `Functional`.
The added unit test verifies this.
(I also encountered this issue when building the project https://github.com/james77777778/keras-image-models)
=> Enable `Sequential` and `Functional` model to be used as a submodel

keras/src/models/model.py
Accidentally found that the log I added to `Functional.__init__` was printed twice.
=> perf: remove a redundant call to `Functional.__init__`

keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py
This allows passing `atol` and `rtol`. Should work under all backends.
I haven't found my way around the test suite yet. Is there a good place to implement a unit test for this?
=> Propagate kwargs through `keras.ops.isclose`

keras/src/backend/jax/math.py
Microbenchmarks are here [1]. Seems to be faster on CPU, GPU, TPU. Also XLA is sometimes able to dedup everything before k is referenced when it's called multiple times with different ks. This results in nice gains for retrieval applications with multiple top k metrics.
[1] https://gist.github.com/Hilly12/85460873d9786924159f2377f320df48
=> Faster in_top_k implementation for Jax backend

keras/src/tree/dmtree_impl.py, keras/src/tree/tree_test.py, keras/src/utils/module_utils.py, requirements-common.txt
i encountered an issue where below code snippet doesn't work and later found that the issue is specific to dmtree:
```
import keras
input1 = keras.layers.Input(shape=(32,))
input2 = keras.layers.Input(shape=(32,))
added = keras.layers.Add()([input1, input2])
```
throws exception
```
File "/home/haohuanw/Documents/keras/keras/src/layers/merging/base_merge.py", line 102, in build
if not isinstance(input_shape[0], (tuple, list)):
TypeError: 'NoneType' object is not subscriptable
```
then found the issue was due to a small bug in `dmtree::is_nested()`. i then also expand to make sure both tree implementation is tested in ci. it also discovered 2 subtle differences between optree and dmtree.
additional help needed: is `requirements-common.txt` the right place for adding the test deps?
=> fixing dmtree.is_nested() and parameterized tree test

keras/src/metrics/metric.py, keras/src/metrics/metric_test.py
This allows it to surface variables from metrics nested at any depth.
Previously, metrics within metrics within metrics would not have their variables tracked in JAX, causing them to not be updated.
=> `Metric.variables` is now recursive.

keras/src/utils/file_utils.py
refer to:
https://github.com/python/cpython/blob/48f9d3e3faec5faaa4f7c9849fecd27eae4da213/Lib/urllib/request.py#L259-L264
Http response without a `Content-Length` header will cause `total_size = -1`
https://github.com/keras-team/keras/blob/efaaf85e19113400f23462cbafcef433cd95ad9c/keras/src/utils/file_utils.py#L279-L286
Line 280 is bypassed, so line 285 will be executed instead. `current` will be set to `self.progbar.target`, which is `None`.
=> Fix `get_file` when the HTTP response has no `Content-Length` header

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/ops/__init__.py, keras/src/backend/jax/core.py, keras/src/backend/numpy/core.py, keras/src/backend/tensorflow/core.py, keras/src/backend/torch/core.py, keras/src/ops/core.py, keras/src/ops/core_test.py
This op should be useful and functions the same as `jax.lax.switch`
=> Add `ops.switch`

keras/src/tree/tree_test.py, requirements-common.txt
For consistency, use `absl.testing.parameterized` instead of `parameterized` for `tree_test.py` since that is used for all other tests.
It's one less dependency. It also says `optree` or `dmtree` in each test name.
=> Use `absl.testing.parameterized` for `tree_test.py`.

keras/src/layers/normalization/batch_normalization.py
This PR fixes #19818 by adding a more descriptive message to the mask mismatch exception in batch normalization.
Before:
After (Highlighted for clarity):
=> Make batch norm mask shape error more descriptive

keras/src/backend/jax/trainer.py, keras/src/backend/numpy/trainer.py, keras/src/backend/tensorflow/trainer.py, keras/src/backend/torch/trainer.py, keras/src/trainers/trainer.py, keras/src/trainers/trainer_test.py
This allows models to perform different computations during training and evaluation. For instance, some expensive to compute metrics can be skipped during training and only computed during evaluation.
Note that backwards compatibility with overrides that do not have the `training` argument is maintained.
=> Add `training` argument to `Model.compute_loss()`.

keras/src/metrics/accuracy_metrics.py, keras/src/metrics/accuracy_metrics_test.py, keras/src/metrics/reduction_metrics.py, keras/src/metrics/reduction_metrics_test.py
- `reduce_to_samplewise_values` would not reduce `sample_weights` correctly because the number of dimensions of `values` was checked.
- `reduce_to_samplewise_values` needs to explicitely broadcast `sample_weights`. Before, it was implicitly broadcast in the multiplication with `values`. However, the explicit broadcast is needed for the computation of `num_samples` for the averaging to be correct. This causes a bug when `sample_weights` is of rank 2 or more and a broadcast happens when doing the multiplication. This logic existed in `tf_keras`: https://github.com/keras-team/tf-keras/blob/master/tf_keras/metrics/base_metric.py#L508
- `Accuracy` and `BinaryAccuracy` were doing a mean reduction too early, before multiplying by `sample_weights`. This matters when the rank of `sample_weights` …
=> Fix bugs with `Mean`, `Accuracy` and `BinaryAccuracy` metrics.

keras/src/backend/numpy/core.py, keras/src/backend/numpy/numpy.py, keras/src/layers/core/dense_test.py, keras/src/layers/core/einsum_dense_test.py
It only acts as a pass-through to support the forward pass.
This might be useful if we want to perform inference for the quantized model using the numpy backend.
=> Add `custom_gradient` (a pass-through) for the numpy backend

keras/src/layers/layer.py, keras/src/layers/layer_test.py
i am debugging a variable naming issue that i found out when upgrading from v3.0.1 -> v3.3.3. the situation i observed is that the variable name random "restarts" in nested layers and i am able to root cause to https://github.com/keras-team/keras/commit/b53b4d being the culprit when keras is trying to fix another naming issue for lora.
with the ability to cache `_parent_path` on the first `name_scope` open with `current_path()`, the `_parent_path` will be set to empty string when `self.add_weight()` is being called in init function since the scope name stack will always be empty when construct layers. then, during build, since `_parent_path` is being set to an empty string resulted name will only contain the immediate layer name and thus causing the variable name to restart.
here is a …
=> fix variable name when add in init function

keras/src/layers/preprocessing/hashed_crossing.py
This pull request is a minor documentation fix, so I don't create an issue for this.
For some reason, there is an unclosed backtick the in layer.HashedClossing docstring and this breaks the code formatting of the online documentation.
Before fix:
After fix:
=> Fix code formatting error in docstring

setup.py
Otherwise it seems like it is dragged into the distribution.
At least it does in our release process at conda-forge
xref: https://github.com/conda-forge/keras-feedstock/issues/91
=> Exclude benchmarks directory from distribution

keras/src/utils/summary_utils.py, keras/src/utils/summary_utils_test.py
Fix #19535 
Besides `layer._inbound_nodes`, we can also use `layer._build_shape_dict` to get the output shapes.
With this PR, we can try our best to show the output shape of the custom model subclassed from `keras.Model`
```python
import keras
class MyModel(keras.Model):
def __init__(self):
super().__init__()
self.dense1 = keras.layers.Dense(4, activation="relu")
self.dense2 = keras.layers.Dense(2, activation="softmax")
self.unbuilt_dense = keras.layers.Dense(1)
def build(self, input_shape):
self.dense1.build(input_shape)
input_shape = self.dense1.compute_output_shape(input_shape)
self.dense2.build(input_shape)
def call(self, inputs):
x = self.dense1(inputs)
return self.dense2(x)
m = MyModel()
m.build((None, 2))
m.summary()
```
```bash
Model: "my_model" …
```
=> Improve `Model.summary`

keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Currently when int is given as input for dims in the ops.tile for torch backend, it throws an error `TypeError: tile(): argument 'dims' must be tuple of ints, not int`
Fixes: https://github.com/keras-team/keras/issues/19877
=> Fix torch.tile for int

keras/src/backend/torch/layer.py, keras/src/layers/layer_test.py
this pr fixes a regression observed in torch distributed training with v3.3.3. when wrapping keras model with DDP, it resulted in errors like below:
```
[rank1]:   File "/home/hwang/.cache/bazel/_bazel_hwang/456a88c8103b63576563cc0e1d65d843/execroot/nuro/bazel-out/k8-opt/bin/learning/behavior/lambda_model/mpi_run.runfiles/nuro/external/pypi__torch_2_3_0_cu121_x86_64/torch/nn/parallel/distributed.py", line 798, in __init__
[rank1]:     _verify_param_shape_across_processes(self.process_group, parameters)
[rank1]:   File "/home/hwang/.cache/bazel/_bazel_hwang/456a88c8103b63576563cc0e1d65d843/execroot/nuro/bazel-out/k8-opt/bin/learning/behavior/lambda_model/mpi_run.runfiles/nuro/external/pypi__torch_2_3_0_cu121_x86_64/torch/distributed/utils.py", line 269, in …
```
=> Fix torch distributed training

keras/src/losses/__init__.py, keras/src/losses/losses.py, keras/src/losses/losses_test.py
This PR allows users to set the `dtype` for `Loss`. Previously, it was only configurable via `keras.backend.set_floatx()`.
=> Add `dtype` argument to all losses and export `CTC`

keras/api/_tf_keras/keras/dtype_policies/__init__.py, keras/api/dtype_policies/__init__.py, keras/src/dtype_policies/__init__.py, keras/src/dtype_policies/dtype_policy.py, keras/src/dtype_policies/dtype_policy_map.py, keras/src/dtype_policies/dtype_policy_map_test.py, keras/src/dtype_policies/dtype_policy_test.py, keras/src/layers/attention/multi_head_attention.py, keras/src/layers/attention/multi_head_attention_test.py, keras/src/layers/core/dense.py, keras/src/layers/core/einsum_dense.py, keras/src/layers/core/embedding.py, keras/src/layers/layer.py, keras/src/layers/layer_test.py, keras/src/ops/operation.py
ORIGINAL FROM #19783
Sorry for the inconvenience.
I have tried to implement the idea mentioned by @mattdangerw :
https://github.com/keras-team/keras-nlp/pull/1612
I think this idea is clean and only requires some small changes to support mixing dtype policies into subclasses.
In general, `DTypePolicyMap` is similar to `LayoutMap` as it contains a dict to record the (layer name, policy) pair.
The limitations / overheads of using `DTypePolicyMap`:
- Each layer must have a unique name (`auto_name` might fail)
- Some extra logic needs to be added in `get_config` for the top class (ex: `Backbone` in KerasCV and KerasNLP)
The basic usage  (adding quantization support for `MultiHeadAttention`):
<details>
```python
import keras
from keras import dtype_policies
import numpy …
```
=> Introduce `DTypePolicyMap`

keras/src/dtype_policies/dtype_policy.py, keras/src/dtype_policies/dtype_policy_map.py, keras/src/dtype_policies/dtype_policy_test.py, keras/src/layers/core/dense.py, keras/src/layers/core/dense_test.py, keras/src/layers/core/einsum_dense.py, keras/src/layers/core/einsum_dense_test.py, keras/src/layers/core/embedding.py, keras/src/layers/core/embedding_test.py, keras/src/layers/layer.py, keras/src/layers/layer_test.py, keras/src/ops/operation.py
This PR is a small but important fix.
We should ensure that the `dtype` argument passed to `Layer` is a str when it is a `FloatDTypePolicy` in config for backward compatibility.
Otherwise, it will break the downstream project like KerasNLP. (Currently, master branch should break it.)
EDITED:
It would be a good idea to replace `is_quantized` with `quantization_mode` in `DTypePolicy`.
Now, `quantization_mode` returns `None` if the policy is not quantized. This behavior matches `Layer`.
=> Fix `dtype` argument passed to `Layer` when it is a `FloatDTypePolicy` in config

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/ops/__init__.py, keras/src/ops/core.py
This is strangely missing from the `ops` module. The current way to use `dtype`s would be to call `tensor.dtype` directly, but this is dangerous territory for a multi-backend library, and also confusing to users when the `ops` module specifically exists to avoid calling tensor methods directly.
Example use case:
```py3
x = keras.ops.zeros((32, 2))
t = keras.ops.full((keras.ops.shape(x)[0], 1), t, dtype=keras.ops.dtype(x))
```
Slightly nasty: the output from this will not compare equal to the actual dtype of the tensor for all backends:
```py3
x = keras.ops.zeros(())
keras.ops.dtype(x) == x.dtype
```
However, I don't think this is an issue, as all use cases will either relate a dtype to a hard-coded value (where users can use a string) or one inferred from a tensor (where users can just …
=> Add `keras.ops.dtype`

keras/src/export/export_lib.py, keras/src/export/export_lib_test.py
Modification of non-trainable variables were not reflected in the `tf.Variable`s for exported JAX models. In particular, this caused random functions to use the same seed on every call.
This change binds the non-trainable variables of the model in the exported function.
=> Fix for JAX exported model not updating non-trainable variables.

keras/src/export/export_lib_test.py, keras/src/layers/preprocessing/tf_data_layer.py, keras/src/utils/jax_utils.py
During export, the `tf.function` wrapping the `jax2tf` function is traced. In this scenario, we're in a JAX tracing scope within a Tensorflow graph. `TFDataLayer` now detects this correctly.
Also improved `jax_utils.is_in_jax_tracing_scope()`: there are multiple tracer array classes that all extend `jax._src.core.Tracer`.
=> Fix JAX export support of `TFDataLayer`.

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/ops/__init__.py, keras/src/backend/jax/core.py, keras/src/backend/numpy/core.py, keras/src/backend/tensorflow/core.py, keras/src/backend/torch/core.py, keras/src/ops/core.py, keras/src/ops/core_test.py
Fix #19708
With this PR, we can run the following example that @yifengshao might find useful:
```python
import keras
data = np.random.randn(3, 128, 128)
data = ops.convert_to_tensor(data)
def fft2(x):
return ops.fft2((ops.real(x), ops.imag(x)))
data_fft = ops.map(fft2, data)
print(data_fft[0].shape, data_fft[1].shape)  # (3, 128, 128) (3, 128, 128)
```
I have improved `tf.map_fn` to automatically infer the `fn_output_signature`
=> Add `ops.map`

keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
`nonzero` returns a tuple of N 1D integer tensors, one per dimension in the input.
Also changed `nonzero` unit tests to be more interesting by actually exercising the case where there are zeros.
=> Fix `ops.Nonzero.compute_output_spec()`.

keras/src/utils/dataset_utils.py, keras/src/utils/dataset_utils_test.py
Fixes https://github.com/keras-team/keras/issues/19797
Also:
- remove conversion to `np.array` since ealier check verifies inputs are `np.array`.
- improved verification in the `np.array` case to check the type of all the elements, not just the first one.
- removed code related to `dict`s, which are not supported as top-level structure.
- refactored tests as parameterized tests.
=> `keras.utils.split_dataset` now supports nested structures in dataset.

keras/src/export/export_lib.py, keras/src/export/export_lib_test.py
Fixes #19913 
a simple repro from the original issue with minor changes:
```
import keras
class SomeModel(keras.Model):
def __init__(self, output_channels: int):
super().__init__()
self.output_channels = output_channels
self.fc1 = keras.layers.Dense(256, activation="relu")
self.fc2 = keras.layers.Dense(
self.output_channels * 2,
bias_initializer="ones",
kernel_initializer="zeros",
)
def build(self, input_shape):
super().build(input_shape)
self.fc1.build(input_shape)
fc1_out = self.fc1.compute_output_shape(input_shape)
self.fc2.build(fc1_out)
def call(self, inputs):
features = self.fc1(inputs)
return self.fc2(features)
class SomeParentModel(keras.Model):
def __init__(self, *args, **kwargs):
super().__init__(*args, **kwargs)
self.fx = SomeModel(20)
def call(self, …
```
=> Fix `export_lib.make_tensor_spec`

keras/src/dtype_policies/__init__.py, keras/src/dtype_policies/dtype_policy.py, keras/src/dtype_policies/dtype_policy_map.py, keras/src/dtype_policies/dtype_policy_map_test.py, keras/src/dtype_policies/dtype_policy_test.py, keras/src/layers/layer_test.py, keras/src/ops/operation.py
This PR silently deprecates the usage of `FloatDTypePolicy`. In the future, we could completely remove `FloatDTypePolicy`.
The reason is that we allow integer types for `DTypePolicy` (most commonly in preprocessing layers). This makes `FloatDTypePolicy` feel out of place:
```python
from keras import dtype_policies
policy = dtype_policies.DTypePolicy("int32")
print(policy)  # <FloatDTypePolicy "int32">
```
`FloatDTypePolicy` was initially introduced to distinguish between non-quantized and quantized policies.
However, we now have `quantization_mode` to indicate the status.
=> Internally, replace `FloatDTypePolicy` with `DTypePolicy`

keras/src/backend/tensorflow/random.py, keras/src/random/random_test.py
`if tf.rank(*)` will fail if we want to use `random.beta` within a `TFDataLayer`
=> Fix compatibility of `random.beta` in `tf.data`

keras/src/saving/saving_lib.py, keras/src/saving/saving_lib_test.py
Should fix #19921
The root cause is that #19852 will incorrectly duplicate `*.weights.h5` in `save_model`.
And we should consider falling back to the original behavior if the system is read-only in `load_model`.
Sorry for the inconvenience!
=> Fix `save_model` and `load_model`

keras/src/random/random_test.py, keras/src/saving/saving_lib.py, keras/src/saving/saving_lib_test.py, keras/src/testing/test_case.py
This PR fixes the GPU CI of torch backend.
Additionally, this PR utilizes `tempfile` in `_save_model_to_fileobj` and `_load_model_from_fileobj` for better file handling, preventing race conditions when multiple processes try to save and load the model.
A test for OSError (read-only system) has also been included.
EDITED:
I have added a test to verify concurrent loading as mentioned in #19924 by @WeichenXu123
=> Fix GPU CI and improve `save_model` and `load_model`

keras/src/backend/common/keras_tensor.py, keras/src/backend/common/keras_tensor_test.py, keras/src/dtype_policies/dtype_policy.py, keras/src/ops/core.py, keras/src/ops/function.py
This PR should improve consistency when using `KerasTensor`
=> Prevent setting attributes on `KerasTensor`

keras/src/backend/tensorflow/numpy.py, keras/src/ops/numpy_test.py
Fix #19919
The tests for `tf.function(jit_compile=True)` have been included.
=> Fix `ops.tril` and `ops.triu` for tensorflow backend

keras/src/backend/jax/__init__.py, keras/src/backend/jax/core.py, keras/src/backend/numpy/__init__.py, keras/src/backend/numpy/core.py, keras/src/backend/tensorflow/__init__.py, keras/src/backend/tensorflow/core.py, keras/src/backend/tensorflow/random.py, keras/src/backend/torch/__init__.py, keras/src/backend/torch/core.py, keras/src/random/seed_generator.py, keras/src/random/seed_generator_test.py
seeing below error on running tensorflow distributed training with multiple workers. the issue being seed state getting broadcasted is in a dtype that tensorflow doesn't support:
```
Exception encountered: ''Value for attr 'T' of uint32 is not in the list of allowed values: bool, float, half, double, int32, int64
; NodeDef: {{node CollectiveBcastSend}}; Op<name=CollectiveBcastSend; signature=input:T -> data:T; attr=T:type,allowed=[DT_BOOL, DT_FLOAT, DT_HALF, DT_DOUBLE, DT_INT32, DT_INT64]; attr=group_size:int; attr=group_key:int; attr=instance_key:int; attr=shape:shape; attr=communication_hint:string,default="auto"; attr=timeout_seconds:float,default=0; is_stateful=true; is_distributed_communication=true> [Op:CollectiveBcastSend]''
```
this pr introduces a seed dtype function to customize …
=> configure random seed dtype based on backend

keras/src/losses/loss.py, keras/src/losses/loss_test.py, keras/src/losses/losses.py, keras/src/metrics/metric.py, keras/src/metrics/metric_test.py
Fix #19932
Now the logic for parsing the `dtype` argument is the same across `Layer`, `Loss` and `Metric`.
=> Improve consistency of the `dtype` argument across `Layer`, `Loss`, and `Metric`.

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/ops/__init__.py, keras/src/backend/common/backend_utils.py, keras/src/backend/jax/core.py, keras/src/backend/numpy/core.py, keras/src/backend/tensorflow/core.py, keras/src/backend/torch/core.py, keras/src/ops/core.py, keras/src/ops/core_test.py
Addresses #19904, adds `associative_scan` support for all backends. 
This is my first time contributing, so would greatly appreciate any feedback or something I may be missing (and would be more than happy to apply them)! Thanks!
=> add associative_scan

keras/src/trainers/trainer.py
https://github.com/keras-team/keras/blob/24ffc7cadb0e54a56d77527a0b9e47053dfebc97/keras/src/trainers/trainer.py#L1004-L1010
In `Trainer.fit()`, there's a call to `self._symbolic_build()` before training.
It consumes one extra piece of data which may be unexpected behavior if the amount of data is calculated.
Only the JAX and Torch backends are affected.
Closes #19929
=> Fix `Trainer._symbolic_build`

keras/src/backend/jax/numpy.py, keras/src/ops/numpy_test.py
JAX has an unreleased change https://github.com/google/jax/pull/21441 that make it so that `int`s and `bool`s are no longer promoted to floats by `floor` and `ceil`.
Our current implementation follows the Numpy promotion rule, i.e. `int`s and `bool`s are promoted to floats. Therefore:
- updated unit tests, which use `jax.numpy` as the reference.
- updated our JAX implementation of `floor` and `ceil` (note that `ceil` would already cast).
=> Fix for a change in JAX's promotion rules for `floor` and `ceil`.

.kokoro/github/ubuntu/gpu/build.sh
Enabling `distribution_lib_test` to ensure we continuously test our distribution logic. We need this more than before as with larger Gemma models, there is a higher interest in distributed training and inference.
=> Enable distribution test

keras/src/distribution/distribution_lib.py
Just came across some minor typo in the code example that results in an error as the string is not closed.
=> Fix docstring: typo for setting environment variables

keras/src/layers/core/dense.py, keras/src/layers/core/dense_test.py, keras/src/layers/core/einsum_dense.py, keras/src/layers/core/einsum_dense_test.py, keras/src/layers/core/embedding.py, keras/src/layers/core/embedding_test.py, keras/src/layers/layer.py
Related to https://github.com/keras-team/keras-nlp/pull/1670
The logic could be further simplified if we could call `super().quantize` in subclasses.
A minor simplification in the tests for quantization is also included.
=> Add `type_check` for `quantize`

keras/src/backend/common/keras_tensor.py, keras/src/backend/common/variables.py, keras/src/backend/common/variables_test.py, keras/src/backend/exports.py, keras/src/backend/torch/core.py, keras/src/random/seed_generator.py
This should fix #19952 and #19846
I have found that the built-in ops of `keras.Variable` behave differently compared to `keras.ops.*`.
This PR resolves it, and the corresponding tests have been included.
An example of the newly introduced built-in ops:
```python
import keras
optimizer = keras.optimizers.SGD(learning_rate=0.12345)
print(optimizer.learning_rate)  # <KerasVariable shape=(), dtype=float32, path=SGD/learning_rate>
print(keras.ops.convert_to_numpy(optimizer.learning_rate))  # 0.12345
print(round(optimizer.learning_rate, ndigits=3))  # tf.Tensor(0.123, shape=(), dtype=float32)
print(int(optimizer.learning_rate))  # 0
print(float(optimizer.learning_rate))  # 0.12345000356435776
```
EDITED:
Also fix the hint for `keras.Variable`
|Before|After|
|-|-| …
=> Improve `keras.Variable`'s dtype consistency and add `__int__`, `__float__` and `__round__`

keras/src/backend/torch/core.py, requirements-jax-cuda.txt, requirements-tensorflow-cuda.txt, requirements-torch-cuda.txt, requirements.txt
Fix #19602
Fix #19765 
I just figured out the solution for the previously failed tests. Let's see if we can pass all the tests now.
cc @haifeng-jin 
EDITED:
All tests have passed!
Some thoughts:
- `torch.compile` easily fails to resolve `@property` and `isinstance`
- The speedup of `jit_compile=True` is still not significant in the torch backend.
=> Remove upperbound for torch version

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/ops/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
This is commonly used for spline transformations.
=> Add keras.ops.searchsorted

guides/training_with_built_in_methods.py, keras/src/backend/tensorflow/trainer.py, keras/src/trainers/data_adapters/data_adapter.py, keras/src/trainers/data_adapters/py_dataset_adapter.py, keras/src/trainers/epoch_iterator.py, keras/src/trainers/epoch_iterator_test.py
Addresses issue #19749 
I wanted to double-check a couple of things, though: 
1. `on_epoch_end` and `on_epoch_begin` are for `PyDataset` and not for other backend-specific datasets.
2. The user is responsible for making these callbacks thread-safe and free of side effects. I made a [notebook](https://colab.research.google.com/drive/1LPQRLw0ujJkPZF_VScZ0zxuAe2YUzB2t?usp=sharing) to demonstrate this.
e.g. if the user were to shuffle the dataset at the end of each epoch, there is a chance that the dataset is shuffled twice, as demonstrated in the notebook. 
I implemented `on_epoch_begin()` based on the above understanding. But if that's a misunderstanding please let me know and would be happy to fix! Thanks!
=> add on_epoch_begin for dataset

keras/src/backend/jax/distribution_lib.py
The current `_to_jax_device()` implementation assumes that in `jax.devices` devices are sorted by id but specific order is not guaranteed.
Example output with 2 processes with 4 devices each:
```
[
TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0),
TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1),
TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0),
TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1),
TpuDevice(id=2, process_index=1, coords=(1,0,0), core_on_chip=0),
TpuDevice(id=3, process_index=1, coords=(1,0,0), core_on_chip=1),
TpuDevice(id=6, process_index=1, coords=(1,1,0), core_on_chip=0),
TpuDevice(id=7, process_index=1, coords=(1,1,0), core_on_chip=1),
]
```
=> Fix `_to_jax_device()`

keras/src/backend/tensorflow/random.py, keras/src/backend/tensorflow/random_test.py
src/samplers/top_k_sampler_test.py to run into a compilation error:
```
(OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_FLOAT, Tseed=DT_INT64, output_dtype=DT_INT64){{node while/stateless_categorical/StatelessMultinomial}}
```
=> Cast random.categorical seed to int32 in TF backend

keras/src/backend/numpy/math.py, keras/src/backend/tensorflow/math.py, keras/src/backend/torch/math.py, keras/src/ops/math.py, keras/src/ops/math_test.py
`tf.unsorted_segment_*` is actually able to handle n dimension segment_ids but all other backends and `tf.segment_*` doesn't support this case. this pr adds an actual validation check to let user know about the requirements.
in addition to above, i also:
1. reduced boilerplate code in numpy and torch implementation
2. fixed numpy and torch's segment_max initialization state handling issue
3. reduced boilerplate code for segment reduction in unit tests and test for more cases.
=> fixing segment_max edge cases and add more exception handling

keras/src/backend/torch/nn.py, keras/src/layers/pooling/average_pooling_test.py, keras/src/ops/nn_test.py
I might be missing something, but whatever custom logic we had for torch average pooling appears to be broken, and the common function we have to compute same padding on torch seems to fix it.
Fixes #19721
=> Fix torch average pooling

keras/api/_tf_keras/keras/optimizers/__init__.py, keras/api/optimizers/__init__.py, keras/src/optimizers/lamb.py, keras/src/optimizers/lamb_test.py
This PR adds the Lamb optimizer described in the paper "Large Batch Optimization for Deep Learning: Training BERT in 76 minutes" (https://arxiv.org/abs/1904.00962)
The optimizer was previously implemented by the authors of the paper in the tensorflow_addons repository (https://github.com/tensorflow/addons) which is deprecated.
I was interested in this optimizer and opened an issue before. It is available here: https://github.com/keras-team/keras/issues/19965
I compared its output against `tensorflow_addons.optimizers.LAMB` and behavior is identical **only if `weight_decay=0.0`**. This is because the implementation in tensorflow_addons couples weight decay to the optimization procedure (as did previous implementations of Adam, see https://arxiv.org/abs/1711.05101 for details)
When looking …
=> add lamb optimizer

integration_tests/dataset_tests/cifar100_test.py
I found that test case failed on "cifar100_test.py".
Because of type mismatching on y_train and y_test, it failed. and I changed the dtype to match with current y data.
I tested it on windows wsl, and if this problem is just related in my local configuration, plz let me know.
=> Change dtypes for test_dtypes test case.

keras/src/models/sequential.py, keras/src/models/sequential_test.py, keras/src/utils/summary_utils.py
Fix #19982
This PR also fixes `.summary()` when there is a built `Functional`/`Sequential` model as the first layer of a `Sequential` model
=> Extend support to `Sequential._maybe_build` for functional/sequential models

keras/src/backend/jax/distribution_lib.py, keras/src/trainers/data_adapters/array_data_adapter.py, keras/src/trainers/data_adapters/array_data_adapter_test.py, keras/src/trainers/data_adapters/array_slicing.py, keras/src/trainers/data_adapters/data_adapter.py, keras/src/trainers/data_adapters/data_adapter_utils.py, keras/src/trainers/data_adapters/generator_data_adapter.py, keras/src/trainers/data_adapters/generator_data_adapter_test.py, keras/src/trainers/data_adapters/py_dataset_adapter_test.py, keras/src/trainers/data_adapters/tf_dataset_adapter.py, keras/src/trainers/data_adapters/tf_dataset_adapter_test.py, keras/src/trainers/data_adapters/torch_data_loader_adapter.py, keras/src/trainers/data_adapters/torch_data_loader_adapter_test.py
- Slicing and splitting is more efficient with Numpy arrays on CPU than JAX arrays on CPU.
- Converting to `jax.Array` sends them to the first device by default, which is incorrect in the case of distribution and slows down distribution.
Also
- Keep JAX BCOO tensors on CPU within data adapters.
- Use `np.split` instead of `jax.numpy.split` in distribution_lib per the JAX distribution guide.
=> Use Numpy arrays in data adapters for JAX backend.

integration_tests/dataset_tests/imdb_test.py
Correct failed test case on ImdbLoadDataTest
Since, x_train,x_test are implicitly declared as np.array in source code below,
I think the x_train, x_test type should be changed from list to np.ndarray in test code.
- keras/src/datasets/imdb.py
```
def load_data(
path="imdb.npz",
num_words=None,
skip_top=0,
maxlen=None,
seed=113,
start_char=1,
oov_char=2,
index_from=3,
**kwargs,
):        
....
x_train, y_train = np.array(xs[:idx], dtype="object"), labels[:idx] 
x_test, y_test = np.array(xs[idx:], dtype="object"), labels[idx:]
```
=> Correct test case for ImdbLoadDataTest

keras/src/backend/jax/optimizer.py, keras/src/backend/tensorflow/optimizer_distribute_test.py, keras/src/optimizers/base_optimizer.py, keras/src/optimizers/optimizer_test.py
Fix https://github.com/keras-team/keras/issues/19990
Removes unnecessary (wrong) weight decay and gradient clipping during gradient accumulation. The will be applied only before actual variable update.
To make gradient accumulation work in the same way as "large batch" real number of iterations was hidden under property.
This is done because a lot of optimizers use it during gradient estimation in update_step.
=> Fix gradient accumulation

keras/src/backend/tensorflow/nn.py, keras/src/ops/nn_test.py
Using tensor.device will fail for a symbolic tensor.
Fixes #19991
=> Fix conv + channel_first + tensorflow + CPU

keras/src/layers/rnn/rnn.py
It seems that without handling the case that it has length as 1, it would be working as the same manner.
However, if there is another specific reason or special case that this code is needed, feel free to comment here and let me know. :)
=> Remove duplicated code from rnn.py

keras/src/losses/loss.py, keras/src/losses/loss_test.py, keras/src/metrics/metric.py, keras/src/metrics/metric_test.py
There is a regression after #19937 where, when users set a global dtype policy such as "mixed_float16" or "mixed_bfloat16", the `dtype` is wrongly set in `Loss` and `Metric`.
It should follow `keras.config.floatx()` as stated in the docstrings.
=> Revert to the original default behavior of `dtype` in `Loss` and `Metric`

keras/src/ops/nn_test.py
Fixing [test case failed on torch gpu ci](https://github.com/keras-team/keras/pull/20022#issuecomment-2241951918) reported by @james77777778 .
=> Fix test_softmax_correctness_with_axis_tuple test case failed on torch gpu ci.

guides/training_with_built_in_methods.py, keras/src/metrics/metric_test.py, keras/src/metrics/reduction_metrics.py
Fixes #20012 
Only tensorflow backend has this problem.
source: https://github.com/tensorflow/tensorflow/blob/7f950f32717fa53b4265e92a181e7e9e3d1eb6a6/tensorflow/python/eager/pywrap_tensor.cc#L316-L339
=> Fix `reset_state` for some metrics

keras/src/backend/jax/trainer.py, keras/src/distribution/distribution_lib.py
- Lazily compute the layout using the first batch and re-use it. This speeds up host to device transfers which were slowed down by creating a new mesh and sharding each time. `jax.device_put` is still pretty slow so longer term it might be worth looking into packing features with a similar layout so there's fewer device puts.
- Allow turning sharding across processes off in the distribution API. This allows doing `dataset.shard(index)` followed by `dataset.batch(per_process_batch_size)` which enables scaling up to larger batch sizes.
Before:
After:
=> Faster host to device transfer on Jax backend

keras/src/backend/jax/math.py, keras/src/backend/numpy/math.py, keras/src/ops/math_test.py
Fix #19995
The performance will be slightly slower, but it should be acceptable.
|Before|After||
|-|-|-|
|10.842s|11.063s|+2%|
Benchmark script:
```python
import functools
import timeit
import jax
from keras.src.backend.jax.math import in_top_k
logits = jax.random.uniform(jax.random.key(42), shape=(32, 128, 50))
labels = jax.random.randint(
jax.random.key(42), shape=(32, 128), minval=0, maxval=50
)
@functools.partial(jax.jit, static_argnames=["k"])
def jit_in_top_k(logits, labels, k=5):
return in_top_k(labels, logits, k=k)
print(jit_in_top_k(logits, labels, k=5).mean())
print(timeit.timeit(lambda: jit_in_top_k(logits, labels, k=5)))
```
Additionally, improve numpy's `top_k` which had significantly poor performance due to double sorting (or even more times of sorting...)
=> Fix jax's `in_top_k` and numpy's `top_k`

keras/src/ops/nn.py, keras/src/ops/nn_test.py
Similar with [#20021](https://github.com/keras-team/keras/issues/20021),
On log_softmax function, also has the same issue.
It couldn't pass the below test case that check the sum of all the exponential values should be 1.0.
So, I fixed the logic on log_softmax function also.
```
def test_log_softmax_correctness_with_axis_tuple(self):
input = np.array([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])
combination = combinations(range(3), 2)
for axis in list(combination):
result = keras.ops.nn.log_softmax(input, axis=axis)
normalized_sum_by_axis = np.sum(
np.exp(ops.convert_to_numpy(result)), axis=axis
)
self.assertAllClose(normalized_sum_by_axis, 1.0)
```
=> Fix log_softmax logic for tuple axis

keras/src/backend/common/variables.py, keras/src/backend/common/variables_test.py
To keep compatibility with previous Tensorflow implementations, we can return variable value after assignment.
Specifically, this impacts porting Tensorflow Federated to Keras 3, see https://github.com/google-parfait/tensorflow-federated/blob/0ca2550e62ca7728e5e9a45edca1feedc6bc065f/tensorflow_federated/python/learning/models/functional.py#L528 which depends on returning the value after an `assign`.
Overhead should be minimal and I could see this being useful for finding the value after an `assign_add` or `assign_sub`.
Fix #19997.
=> Return value on KerasVariable assignment

keras/src/layers/reshaping/zero_padding1d.py, keras/src/layers/reshaping/zero_padding1d_test.py
Add `data_format` parameter to `ZeroPadding1D`. Parameter is available for 2D and 3D layers.
Fix #19984
=> Zero pad 1D data format parameter

keras/src/backend/torch/core.py
Issue: `convert_to_numpy` fails for XLA tensors in the torch backend.
Solution: Call `.cpu()` on any tensor that's not already a CPU tensor.
=> Support torch `convert_to_numpy` for all devices

keras/src/callbacks/callback.py
I couldn't find self.validation_data param's usage on callback class, and found that self.params has no initial value unlike self._model.
So, I removed self.validation_data, and add initial value as None for self.params
=> Remove non-used param & add initial value for callback.py

keras/src/callbacks/model_checkpoint.py, keras/src/callbacks/reduce_lr_on_plateau.py, keras/src/utils/sequence_utils.py
Numpy 2.0 deprecates part of their namespace, see https://numpy.org/doc/stable/numpy_2_0_migration_guide.html for all details.
Keras is affected by `np.Inf` -> `np.inf` and `np.unicode_` -> `np.str_`.
=> Migrate numpy namespace to numpy 2.0

keras/src/backend/common/variables.py, keras/src/backend/tensorflow/core.py
`tf.Variable` allows passing a callable instead of an initial value. We now use a callable when the initializer passed to the Keras `Variable` is a callable. This defers the materialization of the full initial value, which is unnecessary when tracing for instance.
=> Let Tensorflow call the initializer of variables when callable.

keras/src/backend/jax/distribution_lib.py, keras/src/backend/jax/distribution_lib_test.py, keras/src/distribution/distribution_lib.py
This PR fixes these issues:
1. There was a bug that `distribute_data_input()` put the entire data on the first device when there was only one process.
2. `distribute_data_input()` and `distribute_dataset()` in `DataParallel` didn't work in the multi-process environment.
=> Fix Data+Model Distribution Issues

keras/src/quantizers/quantizers.py, keras/src/quantizers/quantizers_test.py
I encountered an issue with dtype in `abs_max_quantize` when trying to quantize KerasNLP models using `bfloat16` setting.
The root cause is that the computed `scale` might be float32 instead of bfloat16 in some backends (at least, JAX) using a non-CUDA env.
cc @mattdangerw
=> Fix dtype issue in `abs_max_quantize`

keras/src/layers/preprocessing/feature_space.py, keras/src/layers/preprocessing/feature_space_test.py, keras/src/layers/preprocessing/text_vectorization.py
Since we can provide custom preprocessors to features of FeatureSpace, trying to adapt to data  a TextVectorization preprocessing layer, with vocabulary provided, raises `ValueError`:
For example the code bellow:
```
vocabulary = ['a', 'b', 'c', 'd']
preprocessor = TextVectorization(vocabulary=vocabulary, output_mode='int', output_sequence_length=5)
feature_space = FeatureSpace(
features={'example': FeatureSpace.feature(dtype='string', output_mode='int', preprocessor=preprocessor)},
output_mode='dict')
ds = tf.data.Dataset.from_tensor_slices({'example': tf.constant(['a b', 'b', 'c', 'd', 'bfr cdvew xas'])})
feature_space.adapt(ds)
for sample in ds:
print(feature_space(sample))
```
raises:
```
File ".../lib/python3.11/site-packages/keras/src/layers/preprocessing/index_lookup.py", line 586, …
```
=> Do not adapt TextVectorization preprocessor if provided with vocabulary  in FeatureSpace. 

keras/src/layers/rnn/conv_lstm.py, keras/src/layers/rnn/dropout_rnn_cell.py
Implemented dropout and recurrent dropout in `ConvLSTMCell` with the same approach as in Keras 2.
Fixes https://github.com/keras-team/keras/issues/20063
=> Added dropout support in `ConvLSTMCell`.

keras/src/backend/torch/trainer.py
I ran into this issue, so I fixed it. My linter is showing many more possibly undefined references in the trainer objects for all backends, so maybe these are due for a general cleanup.
=> Fix unbound local error in torch backend when a call to `train_step` generates no training logs

keras/src/backend/jax/trainer.py, keras/src/backend/numpy/trainer.py, keras/src/backend/tensorflow/trainer.py, keras/src/backend/torch/trainer.py
Fixes #20104 .
`_pythonify_logs()` treat `logs` as dict: https://github.com/keras-team/keras/blob/933579d3c4a585f236982d05d3a74921f9567415/keras/src/trainers/trainer.py#L931
`on_test_batch_end()` `on_test_end()` same: https://github.com/keras-team/keras/blob/933579d3c4a585f236982d05d3a74921f9567415/keras/src/callbacks/callback_list.py#L114
`_get_metrics_result_or_logs()` process `logs` if it's a dict, or return it as is.
and finally: https://github.com/keras-team/keras/blob/933579d3c4a585f236982d05d3a74921f9567415/keras/src/backend/tensorflow/trainer.py#L356
=> Fix default value of `logs` in Trainer

keras/src/metrics/accuracy_metrics.py, keras/src/metrics/accuracy_metrics_test.py
`BinaryAccuracy` metric asserts that threshold is in [0, 1]. But this is not the legacy BinaryAccuracy behaviour in TensorFlow 2.15 (and below) and in torcheval metrics, where threshold is not limited to [0, 1]. This behaviour is useful when `y_pred` are logits and not probabilities.
This PR proposes to remove the assertion on threshold value.
Edit: This change could be extended to `FBetaScore` metric that has the same assertion on the threshold.
=> Remove threshold limits in BinaryAccuracy()

keras/src/backend/jax/numpy.py
The current implementation of `keras.ops.divide_no_nan` is non differentiable in Jax and returns `nan` gradients. This can be verified with the following code:
```
>>> x1 = jnp.array(1, dtype=jnp.float32)
>>> x2 = jnp.array(0, dtype=jnp.float32)
>>> jax.grad(keras.ops.divide_no_nan)(x1, x2)
Array(nan, dtype=float32)
```
The fix is to prevent `jnp.divide` from returning `inf` by using an additional `jnp.where` call. More details on how to prevent `nan` gradients when using `jnp.where` can be found  [here](https://jax.readthedocs.io/en/latest/faq.html#gradients-contain-nan-where-using-where) in the Jax documentation.
=> Fix divide_no_nan jax op to be differentiable

keras/src/utils/file_utils.py, keras/src/utils/file_utils_test.py
This PR improves KerasNLP model loading time internally.
=> Add `/readahead` to the list of recognized remote paths

keras/src/backend/tensorflow/core.py, keras/src/ops/core_test.py
tf.cond allows raw bool value as `pred` only outside tf.functions (model.compile(jit_compile=True)).
To work with this issue there is a smart_cond op, which allows raw boolean values in any context and in case of raw booleans can build much simpler graph.
The code is ported from keras V2 https://github.com/keras-team/tf-keras/blob/master/tf_keras/utils/control_flow_util.py#L106
See failing (without this PR) example in test.
=> TF cond with plain bool's

keras/src/backend/tensorflow/linalg.py, keras/src/backend/torch/linalg.py, keras/src/ops/linalg_test.py
=> Fix `svd` with `compute_uv=False`

keras/src/models/functional.py, keras/src/models/functional_test.py
Fix https://github.com/keras-team/keras/issues/20119
=> Fix functional model output type after deserialization

keras/src/ops/core.py, keras/src/ops/core_test.py
=> Fix `ops.stop_gradient` for `KerasTensor`

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
I need `left_shift` and `right_shift` in some cases.
After implementing them, I realized that it might be useful to add these bitwise ops.
=> Add bitwise ops

keras/src/backend/jax/numpy.py
Apparently, `jax<0.4.24` doesn't support `bitwise_*_shift` and `bitwise_invert`, which caused the CI to fail:
https://github.com/google/jax/commit/4e55086dfb73976002e3ede8d16bd92458324ae0
Actually, there are just aliases of `*_shift` and `invert`.
=> Fix JAX's `bitwise_*_shift` and `bitwise_invert`

keras/src/trainers/data_adapters/py_dataset_adapter.py, keras/src/trainers/data_adapters/py_dataset_adapter_test.py
Fixes https://github.com/keras-team/keras/issues/20032
*Issue:* with multithreading/multiprocessing on, and with an infinite `PyDataset`, the `on_epoch_end` callback was stopping the Enqueuer thread at the end of the first epoch. On the second epoch, the `EpochIterator` would run out of data, creating an empty (0 step) epoch. On the third epoch, the `EpochIterator` would call `get_*_iterator()` again, therefore creating a brand new Enqueuer restarting from the beginning.
*Desired Behavior:* each epoch should take `steps_per_epoch` items from the `PyDataset`. The indices queried should continue increasing epoch after epoch with no gaps and no repetition.
*Why Unit Tests Didn't Catch This:* Unit tests where not calling `on_epoch_end` or `on_epoch_begin`.
*Fix:* refactored code so that:
- …
=> Allow infinite `PyDataset`s to use multithreading/multiprocessing.

keras/src/ops/numpy_test.py
I forgot to replace the unsupported jnp ops in `numpy_test.py`...
I've checked the entire codebase to ensure compatibility.
=> Fix `numpy` dtype CI

keras/src/testing/test_case.py
Some layers may require (and ) missed dtypes like uint8 for images. E.g.:
```python
class MyCustomImageLayer(layers.Layer):
def __init__(self, **kwargs):
super().__init__(**kwargs)
self.input_spec = InputSpec(ndim=4, axes={-1: 3}, dtype="uint8")
```
=> Allow more dtypes in layer test

keras/src/models/functional.py, keras/src/models/model.py, keras/src/models/sequential.py
When using subclassing of `Model` (`Functional` and `Sequential` are affected, but we generally don't subclass them), the return object type is forced to be `Model`, which might be incorrect.
```python
from keras import models
from keras.src.models import Functional
from keras.src.models import Sequential
class MyModel(models.Model):
def __init__(self, **kwargs):
inputs = layers.Input((4,))
outputs = layers.Dense(8)(inputs)
super().__init__(inputs, outputs, **kwargs)
class MyFunctional(Functional):
pass
class MySequential(Sequential):
pass
model = MyModel()
model = MyFunctional()
model = MySequential()
```
||Before|After|
|-|-|-|
|`MyModel`|![image](https://github.com/user-attachments/assets/68fe4f21-d251-4e32-a746-2702e2d8b74e)|![image](https://github.com/user-att …
=> Fix `typing.cast` when using subclassing

keras/src/ops/operation.py
https://github.com/keras-team/keras/issues/20155
This PR allows using hasattr() on node attributes, without raising an error.
=> _get_node_attribute_at_index() raising AttributeError instead of ValueError

keras/src/utils/model_visualization.py
As I understood, when only pydot library is installed without graphviz, check_graphviz method should return false.
However, when I tested it on latest version of pydot==3.0.1, I found that it shows error as below.
```
AttributeError: module 'pydot' has no attribute 'InvocationException'
```
So, I changed this error to PydotException, so that I could get a message that advice to install graphviz.
=> Update pydot exception to match latest version

keras/src/trainers/compile_utils.py
Currently, when CompileLoss is [called](https://github.com/keras-team/keras/blob/4bf1d80fb994ca8e6bebc679b05d124fb294764c/keras/src/trainers/compile_utils.py#L613) (e.g. by `model.fit(...)`) but not yet built, it will internally call its [_filter_unused_inputs](https://github.com/keras-team/keras/blob/4bf1d80fb994ca8e6bebc679b05d124fb294764c/keras/src/trainers/compile_utils.py#L586) method twice:
- a [first time](https://github.com/keras-team/keras/blob/4bf1d80fb994ca8e6bebc679b05d124fb294764c/keras/src/trainers/compile_utils.py#L502) inside `self.build(y_true, y_pred)`
- a [second time](https://github.com/keras-team/keras/blob/4bf1d80fb994ca8e6bebc679b05d124fb294764c/keras/src/trainers/compile_utils.py#L618) inside the `call` itself
This is not only redudant, but most importantly can …
=> Fix duplicated filtering in CompileLoss when not built

keras/src/backend/tensorflow/trainer.py, keras/src/backend/tensorflow/trainer_test.py
The problem occurs when Model.predict() returns a sparse matrix.
Example code:
```python
import keras
class SparseLayer(keras.layers.Layer):
def __init__(self, **kwargs):
super().__init__(**kwargs)
def call(self, inputs):
return inputs
#return tf.sparse.to_dense(inputs)
n_batches = 4
input_shape = (3, 3)
indices = np.array([[0, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0]])
batch_input = tf.sparse.SparseTensor(dense_shape=(n_batches, *input_shape),
indices=indices,
values=tf.constant([1, 1, 1, 1], dtype=tf.dtypes.float32))
model_input = keras.Input(shape=input_shape, batch_size=1, sparse=True)
sparselayer = SparseLayer()(model_input)
model = keras.Model(inputs=model_input, outputs=sparselayer)
output_call = model(batch_input)
print('output_call', …
```
=> Added SparseTensor check on convert_to_np_if_not_ragged.

keras/src/models/functional.py, keras/src/models/functional_test.py
There are several issues related to mismatched inputs structure:
- #20166
- #20136
- #20086
and more...
As a result, it would be beneficial to add a warning for users.
Ultimately, we might want to raise an error when a mismatch occurs. Otherwise, it could lead to subtle issues if the inputs have the same shape and dtype, as the computation could be incorrect even though the code runs.
=> Add a warning for mismatched inputs structure in `Functional`

keras/src/legacy/saving/legacy_h5_format.py, keras/src/saving/saving_lib_test.py
Fixes: https://github.com/keras-team/keras/issues/20147
> So, I investigated it a bit and the problem is the keras.layers.Normalization layer, which is not finalized.
> This is because keras.layers.Normalization has two weights loaded from the file, adapted_mean and adapted_std, but these are not used directly when making a prediction.
> What is used directly are two variables, **which are not added as weights**, called mean and std, that are updated whenever finalize_state() is called.
> 
> And this is the problem. Theoretically, whenever loading weights from a file, finalize_state() should be called by load_own_variables().
> But load_own_variables() is called only with the new saving API, when the weights are saved in the format ".weights.h5", while the efficientnet weights have the …
=> Calling finalize_state() when loading legacy h5 weights

keras/src/utils/model_visualization.py
When running model_visualization_test, I found that there's failed test case,and it shows error as below.
- keras/integration_tests/model_visualization_test.py"
```
plot_model(model, "nested-functional.png", expand_nested=True)
"dot" with args ['-Tpng', '/tmp/tmpv2ec_hvt'] returned code: -6
stdout, stderr:
b''
b"failed at node 380[1]\ndot: maze.c:313: chkSgraph: Assertion `np->cells[1]' failed.\n"
AssertionError: "dot" with args ['-Tpng', '/tmp/tmpv2ec_hvt'] returned code: -6
```
An error occurred because some edges represent destinations that do not exist on the dot.
So, I added the logic to remove this kind of edge from dot.
=> Correct failed test case for model_visualization_test.py

keras/src/datasets/cifar10.py, keras/src/datasets/cifar100.py
The modifications to `get_file`, and removing the deprecated `untar` need an extra directory name to be accessed.
Other possible solutions were provided by myself an others in the linked Issue.
I did a demo here: [Colab](https://colab.research.google.com/gist/ghsanti/284e8b5012dba741ba6929c1aaf8e30c/print.ipynb), also tested on Windows.
The commit that produced the issue [seems to be this one](https://github.com/keras-team/keras/commit/dcefb139863505d166dd1325066f329b3033d45a).
Maybe @ashep29 or @mehtamansi29 have an opinion.
Note that it's just one commit, somehow VSCode managed to duplicate it.
Closes #20180
=> fix: upload cifar10 and cifar100 datasets

keras/src/trainers/trainer.py, keras/src/trainers/trainer_test.py
Fix #20188
The root cause is that we might have unbuilt (and unusable) metrics with a nested trainer.
The solution is to clear these metircs and skip them when calling `self.metrics` in the newly instantiated trainer.
=> Fix the metrics issue in a nested trainer

keras/src/export/export_lib.py, keras/src/models/model.py
When exporting a Keras model into a TF SavedModel, the current output is like this:
```
The following endpoints are available:
* Endpoint 'serve'
inputs (POSITIONAL_OR_KEYWORD): ...
training (POSITIONAL_OR_KEYWORD): ...
mask (POSITIONAL_OR_KEYWORD): ...
Output Type:
...
Captures:
* Huge list of variables, usually in this form: TensorSpec(shape=(), dtype=tf.resource, name=None) *
```
This can be quite overwhelming when you have to export models many times.
This PR adds a parameter that allows choosing whether to print all the variables when exporting.
=> Added parameter 'verbose' when exporting TF SavedModel

integration_tests/model_visualization_test.py
I've updated the model_visualization_test to be compatible with pytest. 
Additionally, I included assertion logic to verify that the file exists and implemented a cleanup process to remove PNG files after running pytest. If this approach is acceptable, I plan to extend these changes to all methods in model_visualization_test.
=> Add the logic to assert and remove files after running test

keras/src/trainers/trainer.py, keras/src/trainers/trainer_test.py
#20197 caused an `AttributeError` if the nested `Trainer` wasn't compiled beforehand.
This PR adds placeholders to fix the issue and simplify the logic in `compile` and `_clear_previous_trainer_metrics`
cc @mattdangerw
=> Fix and improve the mechansim for removing metrics in `Trainer`

keras/src/models/sequential.py, keras/src/models/sequential_test.py
=> Replace `ValueError` with `AttributeError` in `Sequential`'s property

keras/src/losses/losses.py
The example mentioned for the Keras API binarycrossentropy was failing with the error **AttributeError: 'list' object has no attribute 'shape'**.
```python
>>> y_true = [0, 1, 0, 0]
>>> y_pred = [-18.6, 0.51, 2.94, -12.8]
>>> bce = keras.losses.BinaryCrossentropy(from_logits=True)
>>> bce(y_true, y_pred)
AttributeError: 'list' object has no attribute 'shape'
```
It works if we change the input from list to arrays.
```python
>>> y_true = np.array([0, 1, 0, 0])
>>> y_pred = np.array([-18.6, 0.51, 2.94, -12.8])
>>> bce = keras.losses.BinaryCrossentropy(from_logits=True)
>>> bce(y_true, y_pred)
<tf.Tensor: shape=(), dtype=float32, numpy=0.8654580116271973>
```
=> Fixing example code for binarycrossentropy in losses.py file

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/ops/__init__.py, keras/src/ops/core.py, keras/src/ops/core_test.py
Code and comments are adopted from TF https://github.com/tensorflow/tensorflow/blob/v2.17.0/tensorflow/python/ops/math_ops.py#L1086
But i don't know if copyright should be marked somehow.
=> SaturateCast op

keras/src/saving/saving_api.py
Follow-up PR after https://github.com/keras-team/keras/pull/19854 fixing `load_model` when trying to load a model from the Hugging Face Hub.
At the moment (`keras==3.5.0`), running the following snippet
```py
import os
os.environ["KERAS_BACKEND"] = "torch"
import keras
model = keras.saving.load_model("hf://Wauplin/densenet_121_example")
```
fails with 
```
File "/home/wauplin/projects/huggingface_hub/az.py", line 10, in <module>
model = keras.saving.load_model("hf://Wauplin/densenet_121_example")
File "/home/wauplin/projects/huggingface_hub/.venv310/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 179, in load_model
file_utils.copy(filepath, local_path)
File "/home/wauplin/projects/huggingface_hub/.venv310/lib/python3.10/site-packages/ke …
```
=> Fix load_model from hf:// preset

integration_tests/model_visualization_test.py
To verify the model's structure, I added a method that parses the model into a dictionary and included an assert statement to validate it. 
Additionally, I assigned fixed names to each layer in the model to ensure consistency when referencing them.
=> Add assert statement to check model structure on model_visualization_test

keras/src/applications/densenet.py, keras/src/applications/resnet.py, keras/src/applications/xception.py
Updated documentation for DenseNet, Xception and ResNet to mirror MobileNet's classes callout for default to 1000.
=> [#20144] updated documentation for DenseNet, Xception, and ResNet

keras/src/layers/preprocessing/feature_space_test.py
There was a problem with checking the backend (the `()` were forgotten), and hence the condition always evaluated to False.
=> Fix test `test_output_mode_dict`

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
`ops.trunc` is required for the future implementation of int4 quantization
=> Add `ops.trunc`

keras/src/metrics/accuracy_metrics.py, keras/src/utils/dataset_utils.py
Since in Numpy we have `dtype('float64') == None`, type comparison should be done using `is` or `isinstance`.
```python
a = np.array([1.1, 2.2])
print(a.dtype) # prints dtype('float64')
print(a.dtype == None) # prints True
```
This PR fixes that in `accuracy_metrics`.
=> Canonical type comparison

keras/src/backend/tensorflow/image.py, keras/src/layers/preprocessing/resizing.py, keras/src/ops/core.py, keras/src/ops/image.py, keras/src/ops/image_test.py
1. Drop resized image casting in TF backend: Jax/Numpy have no such casting
2. Fix convertion to original dtype for TF/Jax/Numpy backends:
- TF and Jax return resized image in `float32`
- If original dtype is integer, we should round it before cast
- If interpolation done with high-degree polynom, values can overcome source dtype range (e.g. [0; 255] for `uint8`), so we should make saturating cast
=> Fix image resize conversion to original dtype

keras/src/layers/normalization/unit_normalization.py
Enhanced the compute_output_shape method by adding validation for input shape types and axis bounds. The method now ensures that input_shape is either a list or tuple, and that all axis values are within the valid range of input dimensions. This provides clearer error handling and prevents potential issues during shape computation.
Reason for the Change: Previously, the compute_output_shape method did not validate the input shape type or check if the specified axes were within bounds. This could lead to ambiguous or delayed errors during dynamic execution when invalid input shapes or out-of-bound axes were used, leading to confusion for the user. 
The updated validation improves robustness by catching these issues earlier in the process, providing more informative error messages to the …
=> Solving issue #20221

keras/src/layers/normalization/batch_normalization.py, keras/src/layers/normalization/group_normalization.py, keras/src/layers/normalization/layer_normalization.py
Added validation checks in Group, Layer, Batch Normalization layers for the compute_output_shape function to ensure that no issues like #20221 arises again.
=> added validation checks in Group, Layer, Batch Normalization layers

keras/src/layers/normalization/batch_normalization.py, keras/src/layers/normalization/layer_normalization.py
When implementing SD3, I found that `LayerNormalization` is numeric unstable when dtype is set to `float16`.
This PR upcasts float16/bfloat16 to float32 for the computation.
I used `backend.result_type(..., "float32")` to handle higher precision dtypes, such as float64.
=> Fix numeric instability in `LayerNormalization`

keras/src/ops/image.py
I've found a typo in the documentation for the extract_patches function. It said (patches_height, patches_widht) instead of (patches_height, patches_width). 
My commit fixes that.
=> Fix typo in documentation for the extract_patches function.

keras/src/models/functional.py, keras/src/models/functional_test.py, keras/src/models/model_test.py, keras/src/models/sequential.py, keras/src/models/sequential_test.py
The `Model` class has a setter for `layers` to provide a more descriptive message on why this property cannot be changed. But it only applies to sub-class models as classes that override `layers` don't inherit it.
This adds a similar message for functional and sequential models.
=> Provide a setter for `layers` in `Sequential` and `Functional`.

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
I haven't check the performance yet, but I believe adding this operation will be beneficial since both torch and jax have optimized it in their codebases.
From a performance perspective, we should be able to replace `_compute_attention` in `MultiHeadAttention` with this op if the input shapes are strictly 4D.
EDITED:
It seems that CI is using `jax<=0.4.30` due to python version limitation. I implemented a pure numpy version of `dot_product_attention` for the unit tests.
For backends:
- jax: Uses `jax.nn.dot_product_attention` if available. Otherwise, adapts the impl from `jax==0.4.33`.
- numpy: Adapts the impl from `jax==0.4.31` (no customizable `vmap`)
- tensorflow: Adapts the impl from `jax==0.4.31` (no customizable `vmap`)
- torch: Uses …
=> Add `ops.nn.dot_product_attention`

keras/src/models/model_test.py, keras/src/trainers/compile_utils.py
Fix #20243 
Actually, #20243 works as expected in torch and jax backends without this PR. The underlying issue in TF backend has been resolved.
The root cause was that we used `pop` in `_filter_unused_inputs` within `CompileLoss`, which is not allowed in a jitted tf graph. The solution is to avoid modifying the incoming data.
A test has been added to verify the implementation.
=> Fix `CompileLoss` with undefined `loss` argument

keras/src/backend/tests/device_scope_test.py, requirements-jax-cuda.txt
Pin JAX version to 0.4.28. Previously it was set ot 0.4.23. Anything higher gives coredump in GPU Tests due to a change in how the Cuda libs are installed.
=> Fix jax cuda requirements

keras/src/backend/tests/device_scope_test.py
In JAX 0.4.28, `x.device` attribute doesn't exist. Its only introduced in more recent JAX releases. So `device_scope_test.py` fails for JAX CI. This PR should fix it.
=> fix device get for Jax CI

guides/transfer_learning.py
Update transfer learning guide for BatchNormalization and fine-tuning. Fixes [#20285](https://github.com/keras-team/keras/issues/20285)
=> Update "Transfer learning & fine-tuning(BM layer)" guide 

keras/src/layers/attention/additive_attention.py, keras/src/layers/attention/attention.py
Fix rendering issue in keras.io by making change from "Call Args:" to "Call arguments:" which is allowed docstring to render.
Fixes: https://github.com/keras-team/keras/issues/20297
=> Fix rendering issue

keras/src/backend/jax/core.py, keras/src/backend/torch/core.py, keras/src/ops/core_test.py
Passing a tensor to `ops.stop_gradient()` always works. However, passing a variable directly would work with the Tensorflow backend but fail with an obscure error message with the JAX backend and the Torch backend, requiring users to write `ops.stop_gradient(variable.value)`.
This makes it work directly with variables, which is a common use-case.
=> Allow `ops.stop_gradient()` to take a variable.

keras/src/activations/activations.py
"is define as" => "is defined as"
=> Fix a typo in a docstring in activations.py:

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/ops/__init__.py, keras/src/backend/jax/math.py, keras/src/backend/numpy/math.py, keras/src/backend/tensorflow/math.py, keras/src/backend/torch/math.py, keras/src/ops/math.py, keras/src/ops/math_test.py
This PR adds the `keras.ops.histogram()` operation to the source implementations and API.
```
import os
os.environ["KERAS_BACKEND"] = "jax"
import keras
input_tensor = np.array([1, 2, 3, 4, 5])
keras.ops.histogram(input_tensor)
```
Outputs:
```
(Array([1., 0., 1., 0., 0., 1., 0., 1., 0., 1.], dtype=float32),
Array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ], dtype=float32))
```
```
import os
os.environ["KERAS_BACKEND"] = "tensorflow"
import keras
input_tensor = np.array([1, 2, 3, 4, 5])
keras.ops.histogram(input_tensor)
```
Outputs:
```
(<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1])>,
<tf.Tensor: shape=(11,), dtype=float64, numpy=array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])>)
```
``` …
```
=> [Keras Ops] Add Histogram Operation

keras/src/trainers/trainer.py, keras/src/trainers/trainer_test.py
Currently if someone runs https://keras.io/examples/keras_recipes/reproducibility_recipes/, gets an error:
(PR for fixing recipe https://github.com/keras-team/keras-io/pull/1941)
```python
UnimplementedError: Graph execution error:
Detected at node gradient_tape/sequential_1/max_pooling2d_1_2/MaxPool2d/MaxPoolGrad defined at (most recent call last):
<stack traces unavailable>
GPU MaxPool gradient ops do not yet have a deterministic XLA implementation.
[[{{node gradient_tape/sequential_1/max_pooling2d_1_2/MaxPool2d/MaxPoolGrad}}]]
tf2xla conversion failed while converting __inference_one_step_on_data_2978[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.
[[StatefulPartitionedCall]] …
```
=> Disable XLA with TensorFlow determinisim

keras/src/initializers/initializer.py
Observed a few typos in the documentation and fixed those typos.
=> Fix typos in documentation Initializer

keras/src/backend/common/masking_test.py, keras/src/backend/common/tensor_attributes.py
There was a shortcut ignoring `None` values.
Also added unit tests to cover that masking cases.
=> Fix `set_tensor_attr` so that setting `None` clears the attribute.

keras/src/layers/attention/multi_head_attention.py, keras/src/layers/attention/multi_head_attention_test.py
Via #20324.
This assertion was added in #19973, however re: #20324 it seems overly restrictive. It was not covered by an existing test case.
=> Remove MultiHeadAttention assertion that last dims of Q and V need to be equal

keras/src/models/functional.py, keras/src/models/model_test.py
Currently, when loading a model instantiated from a custom `Model` subclass its config is not passed to it's constructor. This leads to some parameters not being restored.
Here is a snippet showing the behavior mentioned:
```py
class CustomModel(Model):
def __init__(self, *args, param=1, **kwargs):
super().__init__(*args, **kwargs)
self.param = param
def get_config(self):
base_config = super().get_config()
config = {"param": self.param}
return base_config | config
inputs = layers.Input((3,))
outputs = layers.Dense(5)(inputs)
model = CustomModel(inputs=inputs, outputs=outputs, param=3)
new_model = CustomModel.from_config(model.get_config())
print(new_model.param) # prints 1 currently i.e. default value of param
```
This PR proposes to fix this issue by passing config in …
=> Pass config to constructor when reviving custom functional model

keras/src/trainers/compile_utils.py
Last August, I suggested a simple workaround to avoid duplicated filtering in CompileLoss when not built (PR #20161), stressing in the description that the root cause was that [_filter_unused_inputs](https://github.com/keras-team/keras/blob/4bf1d80fb994ca8e6bebc679b05d124fb294764c/keras/src/trainers/compile_utils.py#L586) was modifying y_true/y_pred arguments in-place.
This PR suggests to undo the workaround, now that [_filter_unused_inputs](https://github.com/keras-team/keras/blob/acceb5a995b82a006bb174b396844afc9f1fd052/keras/src/trainers/compile_utils.py#L586) has been properly fixed [in this commit](https://github.com/keras-team/keras/pull/20296/commits/b9955ad204c0813d7a43392b76780c9ab39266d2) to not modify y_true/y_pred in-place anymore (PR #20296).
Without this PR (in Keras 3.6.0), …
=> Fix absence of filtering in CompileLoss when not built

keras/src/ops/numpy.py
If the dimensions of `pad_width` and `input` are not the same, other backends will throw a corresponding exception, but PyTorch can still work, which may result in an unrelated exception being raised.
Users may assume that the `pad_width = ((0, 0), (1, 2), (0, 0))` can be shortened to `pad_width = ((0, 0), (1, 2))`.
However, due to torch's use of reverse order, the latter will be processed to `((1, 2),)` (reversed and with higher dimensions removed).
https://github.com/keras-team/keras/blob/8e7843c9f8a3b3298730ab993fd6e6d7bf5c2b1c/keras/src/backend/torch/numpy.py#L1089
https://github.com/keras-team/keras/blob/8e7843c9f8a3b3298730ab993fd6e6d7bf5c2b1c/keras/src/backend/torch/numpy.py#L1096-L1097
=> Restrict the inputs of `ops.pad()`

keras/src/layers/core/embedding.py, keras/src/trainers/data_adapters/__init__.py
- Allow passing a custom dataset adapter - this is to enable enqueuing ID tensors to `TPUEmbedding` before converting them to Jax arrays and putting them on tensorcores.
- Small fix in `compute_output_shape` in embedding layer.
=> Allow passing custom dataset adapters.

keras/src/layers/normalization/spectral_normalization.py
Address comment here: https://github.com/keras-team/keras/issues/20309
According to @hertschuh, the `stop_gradient` call was removed since it wasn't available in the `keras.ops` package. This resulted in unstable behavior for the entire Spectral Normalization wrapper. `stop_gradient` is now present, and the fix (tested on a much larger problem) appears to have stabilized the behavior.
=> stop_gradient in SpectralNormalization wrapper

keras/src/losses/loss.py, keras/src/losses/loss_test.py
Since `sum_over_batch_size` actually is `mean`, `mean` option was added as equivalent of `sum_over_batch_size` to explicitly and clearly state what `sum_over_batch_size` does, under the expected name `mean`, while keeping `sum_over_batch_size` for backwards compatibility. See also https://github.com/keras-team/keras/issues/18818, where the problem with the current name is noted.
Also, why is done like this:
```
loss = ops.sum(values)
loss /= ops.cast(
ops.prod(ops.convert_to_tensor(ops.shape(values), dtype="int32")),
loss.dtype,
)
```
if there's the clearer and shorter keras mean?
`loss = ops.mean(values, axis=None, keepdims=False)`
Please take it, `sum_over_batch_size` is confusing, I already implemented `mean` when I realized it was already done under a different name. 
Edit: already …
=> Clarification: new mean option is synonym with sum_over_batch_size in loss function base class

.github/workflows/actions.yml, integration_tests/jax_custom_fit_test.py, integration_tests/tf_custom_fit_test.py, integration_tests/torch_custom_fit_test.py, keras/src/backend/numpy/trainer.py, keras/src/callbacks/callback_list.py, keras/src/trainers/trainer.py, keras/src/utils/python_utils.py
Fix #20371
The issue is resolved by applying `pythonify_logs` to all entry points in `CallbackList`.
Additionally, this PR moves the implementation of `pythonify_logs` to `keras.src.utils.python_utils` and adds integration tests for all backends.
=> Refactor `pythonify_logs` and add custom fit integration tests.

keras/src/layers/activations/softmax.py
This PR is raised to address the variable names mismatch in the example code.
=> Addressed variable names mismatch in example code in softmax.py

keras/src/backend/common/thread_safe_test.py, keras/src/backend/jax/__init__.py, keras/src/backend/jax/core.py, keras/src/backend/numpy/__init__.py, keras/src/backend/numpy/core.py, keras/src/backend/tensorflow/__init__.py, keras/src/backend/tensorflow/core.py, keras/src/backend/torch/__init__.py, keras/src/backend/torch/core.py, keras/src/callbacks/callback_list.py, keras/src/metrics/iou_metrics_test.py
- Added `IS_THREAD_SAFE` backend flag with an accompanying test.
- Disabled async callbacks for unsafe backends.
- Fixes https://github.com/keras-team/keras/issues/20382
=> Added `IS_THREAD_SAFE` backend flag

keras/src/callbacks/tensorboard_test.py, keras/src/losses/losses.py, keras/src/models/model_test.py, keras/src/trainers/compile_utils.py, keras/src/trainers/compile_utils_test.py, keras/src/tree/optree_impl.py
This pull request enhances loss configuration flexibility by allowing the use of a nested structure that mirrors the output structure to map outputs to loss functions. This enables training with structured losses that can be applied to any level of the output hierarchy such as individual tensors or nested structures of tensors.
Key features:
1. Flexibility to apply losses to both individual tensors (leaf nodes) and nested structures of tensors (intermediate nodes) in the output.
2. The entire subtree at a given node is passed to the corresponding loss function, allowing for custom loss calculations on structured data.
```python
import keras
from keras.src import tree
np.random.seed(0)
data_shape = (10, 2)
X = np.random.rand(*data_shape)
y1 = np.random.rand(*data_shape) …
```
=> Enable Structured Losses

keras/src/layers/normalization/group_normalization.py
Without fp32 casting getting `nan` loss in my custom model
=> Fix GroupNormalization compute dtype

keras/api/_tf_keras/keras/activations/__init__.py, keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/activations/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/activations/__init__.py, keras/src/activations/activations.py, keras/src/activations/activations_test.py, keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
I noticed that the CELU activation function is not currently supported in Keras, even though it is available in the Torch and JAX frameworks. To address this, I implemented the CELU layer logic for both TensorFlow and NumPy, while using the existing implementations for JAX and Torch.
If this approach seems acceptable, I would be happy to update ops.nn.py to include support for the CELU activation in the Keras backend as well.
[CeLU](https://arxiv.org/abs/1704.07483)
=> Add celu activation layer for each nn.py

.github/workflows/actions.yml, keras/src/backend/jax/trainer.py, keras/src/backend/numpy/trainer.py, keras/src/backend/tensorflow/distribute_test.py, keras/src/backend/tensorflow/trainer.py, keras/src/backend/torch/trainer.py, keras/src/trainers/epoch_iterator.py, keras/src/trainers/epoch_iterator_test.py, keras/src/trainers/trainer.py, keras/src/trainers/trainer_test.py
Fixes https://github.com/keras-team/keras/issues/20394
Fixes https://github.com/keras-team/keras/issues/20390
Fixes https://github.com/keras-team/keras/issues/20344
`TensorFlowTrainer` :
- Added usage of `iterator.get_next_as_optional()`, which enables `steps_per_execution` to exceed the previous limit of 32 while preventing `tf.errors.OutOfRangeError`
`EpochIterator` :
- Refactored to unify code base across different backends
- Fixed edge cases involving various combinations of `steps_per_epoch` and `steps_per_execution`
=> `EpochIterator`, `TensorFlowTrainer` : refactoring and fixes

keras/src/backend/tensorflow/numpy.py, keras/src/layers/convolutional/base_conv.py, keras/src/layers/convolutional/base_conv_transpose.py, keras/src/layers/convolutional/base_depthwise_conv.py, keras/src/layers/convolutional/base_separable_conv.py, keras/src/layers/convolutional/conv1d.py
Here is a demo how TF fuses BiasAdd kernel with MatMu/Conv* https://colab.research.google.com/drive/15TNcyvNcOCtvEFX8m-mA--W0MYK5bA6P?usp=sharing
The is no fusion if tf.add used instead.
To preserve behavior from Keras 2 (Dense and Conv* layers used tf.nn.bias_add), bias_add will be restored at backend level.
=> Allow some TF kernels fusion: tf.nn.bias_add as special case of tf.add

keras/api/_tf_keras/keras/activations/__init__.py, keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/activations/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/activations/__init__.py, keras/src/activations/activations.py, keras/src/activations/activations_test.py, keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
I noticed that the GLU activation function is not currently supported in Keras, despite its availability in the Torch and JAX frameworks. To address this gap, I implemented the GLU logic for both TensorFlow and NumPy, leveraging the existing implementations in JAX and Torch for consistency.
If this approach is acceptable, I can proceed by adding test cases to ensure the correctness of these implementations.
=> Add GLU activation

keras/src/saving/saving_lib_test.py, keras/src/saving/serialization_lib.py
- Serialization was not taking the registered name and package from the registry.
- Deserialization was selecting symbols by postfix as a fallback.
=> Fix serialization / deserialization.

keras/api/_tf_keras/keras/activations/__init__.py, keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/activations/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/activations/__init__.py, keras/src/activations/activations.py, keras/src/activations/activations_test.py, keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
Since Keras does not provide built-in support for the hard_tanh activation function, I implemented it using TensorFlow and NumPy backends, leveraging the existing implementations in JAX and Torch for consistency.
=> Add hard_tanh activation function

keras/src/backend/tensorflow/numpy.py
eb5c5ae broke Dense layers in TF1, since `.shape` returns a list of Dimensions which are unhashable types. Adding `.as_list()` enables this check in both TF1 and TF2.
```
{tf.constant([1, 2]).shape.as_list()[0],}
```
=> Patch to fix TF1 shape comparison in add function

keras/src/backend/numpy/numpy.py, keras/src/losses/loss.py, keras/src/losses/loss_test.py, keras/src/losses/losses.py, keras/src/losses/losses_test.py
Fix #19740
In some cases, normalizing loss values based on the sum of `sample_weight` can help stabilize the loss range. To maintain backward compatibility (including with `tf_keras`), a new reduction, `mean_with_sample_weight`, has been added to `Loss` to toggle this feature.
This change should also not impact existing config files.
Let me know if this sounds good. If so, I will add remaining tests for all losses.
=> Add `mean_with_sample_weight` reduction to `Loss`

keras/api/_tf_keras/keras/activations/__init__.py, keras/api/activations/__init__.py, keras/src/activations/__init__.py, keras/src/activations/activations.py, keras/src/activations/activations_test.py
Although an implementation for log_sigmoid already exists, it was not declared in activations.py. I have added it to activations.py and included corresponding test cases.
=> Add log_sigmoid activation

keras/src/backend/tensorflow/numpy.py
I missed this in #20413. Confirmed this fixes the issue in Colab.
=> Fix additional shape comparison for TF1 compatibility

keras/src/metrics/accuracy_metrics.py, keras/src/metrics/accuracy_metrics_test.py
to consume sorted IDs of top N categories instead of scores for all categories.
=> Add `from_sorted_ids` option to `SparseTopKCategoricalAccuracy`.

keras/src/saving/file_editor_test.py
Fixes the test failiure when the local folder is not writtable in test runs.
=> Use temporary folder for testing model saving in file editor

keras/src/utils/io_utils.py, keras/src/utils/io_utils_test.py
Fixes #19386 
The root cause is that `━` is not supported by CP125* encoding. We can replace it with `=` which aligns with Keras2 behavior.
Additionally, `print_msg` has been modified to encode and decode to the target encoding, providing a more robust approach.
=> Fix encoding issue

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/ops/__init__.py, keras/src/backend/jax/math.py, keras/src/backend/numpy/math.py, keras/src/backend/tensorflow/math.py, keras/src/backend/torch/math.py, keras/src/ops/math.py, keras/src/ops/math_test.py
Added implementation of `ifft2` to ops.
fixes #20437
=> adding `ifft2` method to ops

keras/src/trainers/data_adapters/py_dataset_adapter.py, keras/src/trainers/data_adapters/py_dataset_adapter_test.py, keras/src/trainers/epoch_iterator.py, keras/src/trainers/trainer_test.py
The issue was caused by the fact that the iterator was not fully consumed and `on_epoch_end` was not called.
Added an exception to catch this situation in the future.
Added a unit test to test `model.fit()` with all the combinations of data adapters.
=> Fix for https://github.com/keras-team/keras/issues/20425

keras/src/models/functional.py, keras/src/models/functional_test.py
Fix #20170
It should be acceptable to suppress warnings for mismatched tuples and lists in functional models, as the TF backend will automatically convert lists to tuples for input data.
=> Suppress warnings for mismatched tuples and lists in functional models

keras/src/backend/tensorflow/trainer.py, keras/src/trainers/trainer_test.py
Add low-level API parameter `unrolled_steps_per_execution` for `TensorFlowTrainer`.
This parameter specifies how many steps of the `step_per_execution` loop to unroll. Increasing this value can reduce kernel launch overhead, but will increase memory usage and compilation time.
Usage:
```python
model.unrolled_steps_per_execution = 4
model.fit(...)
```
The following example shows how this parameter can reduce GPU idling by reducing kernel launch delay when a model is trained using `step_per_execution = 4`, resulting in a 2x speedup.
With `unrolled_steps_per_execution = 1` (default value):
With `unrolled_steps_per_execution = 4`:
```python
import os
os.environ["KERAS_BACKEND"] = "tensorflow"
import tensorflow as tf  # For tf.data
import tensorflow_datasets as tfds
from keras.applications …
```
=> `TensorFlowTrainer`: Add low-level API `unrolled_steps_per_execution` parameter

keras/src/layers/preprocessing/image_preprocessing/random_flip.py, keras/src/layers/preprocessing/image_preprocessing/random_flip_test.py
I've implemented the transform_bounding_boxes method for random_flip.py. If you notice any areas that need improvement, please feel free to let me know. Thank you!
here is my [gist](https://colab.research.google.com/drive/1LQEOczv4WLYycS5UnhkXMlZH02CRPSI2?usp=sharing)
=> Implement transform_bounding_boxes for random_flip

keras/src/trainers/compile_utils.py, keras/src/trainers/compile_utils_test.py, keras/src/trainers/trainer_test.py
Fix for cases where the loss is partially defined over `y_pred`.
Example:
```python
inputs = keras.Input((2,))
x = keras.layers.Dense(3)(inputs)
model = keras.Model(inputs, [x, x, x])
model.compile(loss=["mse", None, None])
model.fit(x=np.random.random((320, 2)), y=np.random.random((320, 3)))
```
=> `CompileLoss`: fix for partially defined loss with different `y_pred` and `y_true` structures

keras/src/trainers/compile_utils.py, keras/src/trainers/compile_utils_test.py
Fixes #20343. Thanks to rivershah@ for pointing this out.
This changes CompileLoss metrics to report the values before weights are applied, which brings it in line with Keras 2 behavior.
=> Update CompileLoss to report unweighted metric values (breaking change)

keras/api/_tf_keras/keras/activations/__init__.py, keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/activations/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/activations/__init__.py, keras/src/activations/activations.py, keras/src/activations/activations_test.py, keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
Since Keras lacks built-in support for the hard_shrink activation function, I implemented it across TensorFlow, JAX, and NumPy, aiming to maintain consistency with existing implementations available in PyTorch.
=> Add hard_shrink activation function

keras/api/_tf_keras/keras/activations/__init__.py, keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/activations/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/activations/__init__.py, keras/src/activations/activations.py, keras/src/activations/activations_test.py, keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
Since Keras lacks built-in support for the tanh_shrink activation function, I implemented it across TensorFlow, JAX, and NumPy, aiming to maintain consistency with existing implementations available in PyTorch.
=> Add tanh_shrink activation

keras/src/layers/attention/multi_head_attention.py
Adding a required arg in `_compute_attention` broke a few implementations in KerasHub. This workaround should fix the bug.
- The value of `return_attention_scores` has to be the one passed in `call` arg. 
- Some of the MHA implementations in KerasHub subclass MHA, so introducing a required arg has broken those implementation
- This PR adds a `self._return_attention_scores` with a default value `False` and it set to the value passed in call, which in-turn called `_compute_attention`
=> remove arg `return_attention_scores` from `_compute_attention`

keras/api/_tf_keras/keras/initializers/__init__.py, keras/api/initializers/__init__.py, keras/src/initializers/__init__.py, keras/src/initializers/constant_initializers.py, keras/src/initializers/constant_initializers_test.py, keras/src/initializers/random_initializers.py, keras/src/initializers/random_initializers_test.py, keras/src/layers/preprocessing/stft_spectrogram.py
Fix #20483 
This PR renames `OrthogonalInitializer` to `Orthogonal` and `STFTInitializer` to `STFT` for name consistency and adds serialization tests to prevent future breakages.
This PR also adds a default value `side="real"` to support calls to `initializers.get("STFT")`
=> Improve the consistency of the names of initializers

keras/src/layers/attention/multi_head_attention.py, keras/src/layers/attention/multi_head_attention_test.py
This PR fixes an issue in KerasHub where the `attention_mask` could be incorrectly expanded.
A test has been added to prevent future breakages.
cc @divyashreepathihalli
=> Fix `attention_mask` computation in `MultiHeadAttention`

keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/layers/attention/multi_head_attention_test.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
I was experimenting with the new flash attention version of `dot_product_attention` and found it to be performant using jax backend.
For example, using SD3 medium to generate a 800x800 image on a RTX4070:
|flash attention|cost time|
|-|-|
|`False`|10.61s|
|`True`|5.45s|
However, the current implementation of `dot_product_attention` relies on users to decide whether to use flash attention, which can heavily depend on the backend.
This PR refactors the implementation by setting `flash_attention=None` to allow the backend to automatically detect availability. This change should be more user-friendly and improve maintainability IMO.
cc @divyashreepathihalli @hazemessamm
=> Refactor `dot_product_attention` to use flash attention when available

keras/src/losses/losses.py
The example mentioned for the Keras API binarycrossentropy was failing with the error AttributeError: 'list' object has no attribute 'shape'.
```python
>>> # Example 2: (batch_size = 2, number of samples = 4)
>>> y_true = [[0, 1], [0, 0]]
>>> y_pred = [[-18.6, 0.51], [2.94, -12.8]]
>>> # Using default 'auto'/'sum_over_batch_size' reduction type.
>>> loss = keras.losses.BinaryFocalCrossentropy(
gamma=3, from_logits=True)
>>> loss(y_true, y_pred)
```
It works if we change the input from list to arrays.
```python
>>> # Example 2: (batch_size = 2, number of samples = 4)
>>> y_true = np.array([[0, 1], [0, 0]])
>>> y_pred = np.array([[-18.6, 0.51], [2.94, -12.8]])
>>> # Using default 'auto'/'sum_over_batch_size' reduction type.
>>> loss = keras.losses.BinaryFocalCrossentropy(
gamma=3, …
```
=> Fixing example code for BinaryFocalCrossentropy in losses.py file

keras/api/_tf_keras/keras/activations/__init__.py, keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/activations/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/activations/__init__.py, keras/src/activations/activations.py, keras/src/activations/activations_test.py, keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
Since Keras lacks built-in support for the soft_shrink activation function, I implemented it across TensorFlow, JAX, and NumPy, aiming to maintain consistency with existing implementations available in PyTorch.
=> Add soft_shrink activation

keras/src/backend/jax/nn.py, keras/src/backend/torch/nn.py, keras/src/layers/attention/multi_head_attention_test.py, requirements-common.txt
=> Enhance the robustness of the flash attention check

requirements-common.txt
The coverage issue seems to be addressed now: https://github.com/keras-team/keras/pull/20495#issuecomment-2478787386
=> Unpin coverage

keras/src/layers/attention/multi_head_attention.py, keras/src/layers/attention/multi_head_attention_test.py
Made the compute_output_shape method more flexible; now _output_shape can be either an integer or a tuple (as previously required).
Fix discussed at the bottom of issue #19769
=> More flexible output_shape computation in keras.layers.MultiHeadAttention

keras/src/backend/jax/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/layers/attention/attention.py, keras/src/layers/attention/multi_head_attention.py, keras/src/layers/attention/multi_head_attention_test.py, keras/src/ops/nn.py
This PR modifies `enable_flash_attention` to set the value to `None`. This makes it more user-friendly by allowing the backend to decide whether to use flash attention.
The MHA tests have been also updated.
Additionally, a minor but crucial bug in `dot_product_attention` in tensorflow backend has been fixed. (identified by the updated test)
=> Fix tensorflow `_dot_product_attention_xla` and update `enable_flash_attention`

keras/api/_tf_keras/keras/activations/__init__.py, keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/activations/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/activations/__init__.py, keras/src/activations/activations.py, keras/src/activations/activations_test.py, keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
Since Keras lacks built-in support for the squareplus activation function, I implemented it across TensorFlow, PyTorch, and NumPy, aiming to maintain consistency with existing implementations available in Jax.
=> Add squareplus activation

keras/src/backend/tests/device_scope_test.py
This function was deprecated in JAX v0.4.32, and will soon be removed. `jax.default_backend()` is a drop-in replacement for `xla_bridge.get_backend().platform`.
=> Avoid call to deprecated xla_bridge.get_backend()

keras/api/_tf_keras/keras/config/__init__.py, keras/api/config/__init__.py, keras/src/backend/config.py, keras/src/layers/attention/attention.py, keras/src/layers/attention/grouped_query_attention.py, keras/src/layers/attention/grouped_query_attention_test.py, keras/src/layers/attention/multi_head_attention.py, keras/src/layers/attention/multi_head_attention_test.py
This PR introduces flash attention to GQA and moves the flash attention configs to `backend.config`.
The previous location of the flash attention configs was a bit weird IMO.
=> Introduce flash attention to GQA and move the flash attention configs to `backend.config`

keras/src/losses/losses.py
The example mentioned for the Keras API CategoricalCrossentropy was failing with the error AttributeError: 'list' object has no attribute 'shape'.
=> Fixing example code for CategoricalCrossentropy in losses.py file

keras/src/layers/attention/grouped_query_attention_test.py
=> Fix and update GQA tests

keras/src/layers/rnn/rnn.py
The documentation for the base class for recurrent layers (class `RNN` exported as `keras.layers.RNN`) incorrectly mentioned the call argument `sequences` as `inputs`. This PR corrects the argument's name in the documentation and updates the argument's description to align more closely with similar arguments in similar layers.
=> Fix incorrect argument name and update description in RNN documentation

keras/src/backend/numpy/image.py, keras/src/ops/core.py, keras/src/ops/core_test.py
`np.finfo` fails when encountering bfloat16. With `ml_dtypes`, we can improve compatibility.
=> Replace `np.iinfo` and `np.finfo` with `ml_dtypes`

keras/src/saving/saving_lib.py, keras/src/saving/saving_lib_test.py
Related to #20524
We should raise an error when `save_weights` or `load_weights` is called on an unbuilt model as the behavior is undefined
=> Raise an error when `save_weights` or `load_weights` is called on an unbuilt model

keras/src/callbacks/early_stopping.py, keras/src/callbacks/early_stopping_test.py
All values were already reset properly in `on_train_begin` except `best`.
Fixes https://github.com/keras-team/keras/issues/20521
=> Allow EarlyStopping to be reused between multiple `fit`s.

keras/src/optimizers/base_optimizer.py, keras/src/optimizers/optimizer_test.py
=> Fix `BaseOptimizer` to handle a mix of `tf.Variable` and `KerasVariable`

keras/src/backend/common/variables.py, keras/src/backend/tensorflow/core.py, keras/src/backend/tensorflow/distribute_test.py, keras/src/optimizers/loss_scale_optimizer.py
Fix #19891
The results from https://github.com/keras-team/keras/issues/19891#issue-2365146253 should be correct now:
```bash
ground truth: 0.43009480834007263
evaluate: 0.43009480834007263
post-fit output: 0.42891690135002136
```
=> Propagate the `aggregation` property when creating a `tf.Variable`

keras/src/layers/attention/multi_head_attention.py, keras/src/layers/attention/multi_head_attention_test.py, keras/src/utils/summary_utils.py, keras/src/utils/summary_utils_test.py
Fix the issue here:
https://github.com/keras-team/keras/pull/20002#discussion_r1855446457
We should avoid expose `output_shape` in MHA; otherwise, the `summary()` breaks in subclassed models.
Also, the logic of parsing `self._output_shape` has been simplified.
cc @nglehuy
=> Remove `output_shape` property in MHA

keras/src/models/cloning.py, keras/src/models/cloning_test.py
Changed `_clone_sequential_model` to work properly when using the `input_tensors` argument. Fixes #20549.
`keras.models.clone_model()` now checks for `input_tensors` in the right way and uses `input_tensors` shape and dtype in the clone as expected.
Also added tests for cloning Functional and Sequential (w./wo. explicit Input layer) models with defined `input_tensors`:
```
keras/src/models/cloning_test.py::CloneModelTest::test_input_tensors_cnn_functional
keras/src/models/cloning_test.py::CloneModelTest::test_input_tensors_cnn_sequential
keras/src/models/cloning_test.py::CloneModelTest::test_input_tensors_cnn_sequential_noinputlayer
```
=> Fix cloning of Sequential models w. input_tensors argument

keras/src/callbacks/model_checkpoint.py, keras/src/saving/saving_api.py
Update ModelCheckpoint support ".h5" and ".keras" both filetype support with with the save_weights_only=False
Fixes [#20490](https://github.com/keras-team/keras/issues/20490)
=> Update ModelCheckpoint support ".h5" support

.gitignore, keras/api/_tf_keras/keras/activations/__init__.py, keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/activations/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/activations/__init__.py, keras/src/activations/activations.py, keras/src/activations/activations_test.py, keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
PR for creating the sparsemax activation layer as requested in issue [#20554](https://github.com/keras-team/keras/issues/20554). 
[Original paper](https://arxiv.org/abs/1602.02068)
=> Addition of Sparsemax activation

keras/src/losses/losses.py, keras/src/losses/losses_test.py
https://github.com/keras-team/keras/issues/20487
=> Add parameter axis to tversky loss

keras/src/legacy/saving/legacy_h5_format.py, keras/src/legacy/saving/legacy_h5_format_test.py
=> FIX BUG in load_weights_from_hdf5_group_by_name" legacy_h5_format.py

keras/api/_tf_keras/keras/activations/__init__.py, keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/activations/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/activations/__init__.py, keras/src/activations/activations.py, keras/src/activations/activations_test.py, keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
Since Keras does not include built-in support for the threshold activation function, I implemented it using TensorFlow, JAX, and NumPy to ensure consistency with the implementation available in PyTorch. 
If adding this activation to Keras is acceptable, I am prepared to contribute further by modifying ops.py, activations.py, and adding corresponding test cases.
=> Add threshold activation

keras/src/random/random.py, keras/src/random/seed_generator.py
Following the discussion under #20569 this pull request contains a reformulation of the outdated doc concerning
the seed argument of all RNG functions. I also added a clarification to the SeedGenerator class documentation.
Resolves #20569
=> Random seed doc

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
I have also added support for n-d in the TensorFlow implementation, which was not included in the original version. Also only int64 and int32 are support in tensorflow implementation
we can include this implementation which is supported by all INT_DTYPES for tensorflow implementation, I have checked it passes all the tests WDYT?
```python
def unravel_index(x, shape):
x = tf.convert_to_tensor(x)
input_dtype = x.dtype
if x.ndim == 1:
coords = []
for dim in reversed(shape):
coords.append(tf.cast(x % dim, input_dtype))
x = x // dim
return tuple(reversed(coords))
x_shape = x.shape
coords = []
for dim in shape:
coords.append(tf.reshape(tf.cast(x % dim, input_dtype), x_shape))
x = x // dim
return tuple(reversed(coords))
```
@fchollet
=> Add unravel_index op

keras/src/backend/jax/__init__.py, keras/src/backend/jax/core.py
Makes the default `name_scope` in Jax backend use `jax.named_scope`. The layer name now shows up in profiles.
=> Add support for jax named scope.

keras/src/backend/common/variables.py, keras/src/backend/common/variables_test.py, keras/src/backend/jax/core.py, keras/src/backend/numpy/core.py, keras/src/regularizers/regularizers_test.py, keras/src/utils/tracking_test.py
- when the variable dtype is not specified, the dtype of the tensor/array passed as initializer is used instead of defaulting to `backend.floatx()`.
- with the JAX backend, don't needlessly create a copy of the initializer value, reuse it if possible
=> Better handling of variable creation with tensor as initializer.

keras/src/layers/layer.py, keras/src/layers/layer_test.py
#20562 causes issues in some downstream projects related to mask propagation.
The root cause is that `previous_mask` is retrieved after `__call__` but the mask might be removed during `__call__` to suppress warnings (ex: `MultiHeadAttention`). To fix it, we can cache the `previous_mask` before `__call__` and set it to the outputs.
cc @SamanehSaadat
=> Fix masking propagation when `_keras_mask` is unset during `call`

keras/src/trainers/trainer.py, keras/src/trainers/trainer_test.py
Fixes #20474 #20473
Credits to @TheMGGdev
I adopted the changes and added a test.
=> Fix the issue when using `Model.compile` multiple times

keras/src/backend/tensorflow/distribute_test.py, keras/src/backend/tensorflow/layer.py, keras/src/backend/tensorflow/trainer.py, keras/src/losses/loss.py, keras/src/trainers/trainer.py
Fix #19891 
Identified the root cause: the loss should be scaled when using a `MirroredStrategy`.
References:
- https://github.com/keras-team/tf-keras/blob/06e37bfe00c400dd0b993f12596b5f766d4a172d/tf_keras/engine/compile_utils.py#L228
- https://github.com/keras-team/tf-keras/blob/master/tf_keras/utils/losses_utils.py#L360
A correctness test has been added.
cc @SamanehSaadat @drasmuss
=> Fix loss scaling with `tf.distribute.MirroredStrategy` and `keras.regularizers`

keras/src/constraints/constraints_test.py
Release notes mention the following changes for Numpy 2.2:
* bool(np.array([])) and other empty arrays will now raise an error. Use arr.size > 0 instead to check whether an array has no elements.
=> Update for numpy 2.2 bool array changes

keras/src/backend/tensorflow/distribute_test.py, keras/src/backend/tensorflow/trainer.py, keras/src/losses/loss.py, keras/src/trainers/compile_utils.py
Follow-up to #20609
We need to unscale the loss value for metrics when using distributed strategies.
The test has been updated.
=> Unscale loss value in metrics in tensorflow

keras/src/models/functional.py, keras/src/models/functional_test.py
When a functional model built with `dict` and called with `list` as arguments, current implementation just raises warning. This is OK if the keys are ordered in the dict.
In my opinion when the keys are unordered it should raise a error. The below code should raise the Error instead of simple warning as All Users may not aware that Keras sorts the `dict` as per the keys. In below code while building the model keras makes the sorting of keys internally and hence it changes the order to [x2, x1] and hence there is the difference in result when called the model with arguments as `dict` vs `list` .
```
x1 = keras.Input((10,), name='IT')
x2 = keras.Input((10,), name='IS')
y = keras.layers.subtract([x1, x2])
model = keras.Model(inputs={"IT": x1, "IS": x2}, outputs=y)
x1 = keras.ops.ones((1, …
```
=> Fix issue with unsorted dict

keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py
This PR updates the dtype used in `einsum` in `dot_product_attention` for tensorflow and numpy.
Initially, I followed jax's implementation which casts `key` and `query` to higher precision early to mimic the behavior of `preferred_element_type="float32"`. However, performing `einsum` in float32 is much slower than float16 or bfloat16. Additionally, the original MHA implementation doesn't cast them to float32.
Therefore, it seems reasonable to use the dtype of `key` and `query` directly for `einsum`.
Related to https://github.com/keras-team/keras-hub/pull/2014
=> Allow lower precision in `einsum` in `dot_product_attention`

keras/src/metrics/iou_metrics.py, keras/src/metrics/iou_metrics_test.py
Hello,
this is an attempt to show and fix the issue I opened:
#20574
=> Fix confusion matrix type

keras/src/layers/preprocessing/image_preprocessing/mix_up.py
Fixes Torch GPU Test on `mix_up`
```
FAILED keras/src/layers/preprocessing/image_preprocessing/mix_up_test.py::MixUpTest::test_mix_up_basic_functionality - TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
FAILED keras/src/layers/preprocessing/image_preprocessing/mix_up_test.py::MixUpTest::test_mix_up_basic_functionality_channel_first - TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
FAILED keras/src/layers/preprocessing/image_preprocessing/mix_up_test.py::MixUpTest::test_tf_data_compatibility - TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
===== 3 failed, 9336 passed, 1214 …
```
=> fixes torch GPU test on mix_up

keras/src/layers/preprocessing/normalization.py, keras/src/layers/preprocessing/normalization_test.py
Fix Layer normalization issue with scalar mean & variance.
With scalar mean instead of broadcasting reshaping applied currently. Changed the same.
Fixes #20624.
=> Fix Layer normalization issue with scalar mean & variance

keras/src/layers/rnn/simple_rnn.py
I observed a  few typos in simple_rnn
=> Fix typos in simple_rnn

keras/src/backend/jax/export.py, keras/src/backend/numpy/export.py, keras/src/backend/tensorflow/export.py, keras/src/backend/torch/export.py, keras/src/export/export_lib.py, keras/src/export/export_lib_test.py, keras/src/layers/__init__.py, keras/src/layers/core/dense_test.py, keras/src/layers/core/einsum_dense_test.py, keras/src/layers/core/embedding_test.py, keras/src/models/model.py, keras/src/models/model_test.py, keras/src/trainers/data_adapters/py_dataset_adapter_test.py, keras/src/utils/jax_layer_test.py
This PR includes the following changes:
- Rename `export_lib.export_model` to `export_lib.export_saved_model`
- Decouple backend-specific logic in `keras.export.ExportArchive`, simplifying the implementation of `ExportArchive`.
- Add `is_static` option and its logic to `ExportArchive.add_endpoint` for the jax backend: This allows the SavedModel artifact produced with `is_static=True` to be loaded using `tf.lite.TFLiteConverter.from_saved_model`. Without this option, the loading would fail.
- Expose `input_signature` option to `Model.export` and add supports for using a structure of `keras.InputSpec`, `tf.TensorSpec`, `backend.KerasTensor` or backend tensor.
- Improve the docstrings
Once this PR is accepted and merged, I plan to add support for TFLite and ONNX formats.
Notes:
- …
=> Rework `Model.export` and `keras.export.ExportArchive` to support exporting in TFLite and ONNX formats in the future

pyproject.toml
#20599 added dependency to sklearn, but was not included in `pyproject.toml`. This caused the nightly wheel to not include it and fails TensorFlow nightly build.  This PR adds scikit-learn as a Keras Deps.
=> Adds scikit-learn dependency to setup

keras/src/layers/preprocessing/image_preprocessing/mix_up.py
I have updated the code with the following changes:
1. Modified the example to ensure it works seamlessly on the Keras platform.
2. Adjusted the mix_weight implementation to apply different weights to each sample in the batch, enabling more diverse augmentations.
3. Fixed a typo by correcting "mixup" to "mix_up" for consistency.
=> Update example and logic for mix_up

CONTRIBUTING.md
It looks like that the internal structure of `keras/` changed to `keras/src` at a certain point. Hence, the paths are not valid anymore and `pytest` cannot find the proper files. For example:
```sh
$ pytest keras/losses/losses_test.py
ERROR: file or directory not found: keras/losses/losses_test.py
```
After fixing all these paths, the tests run successfully locally.
=> Fix paths for pytest in contribution guide

keras/src/wrappers/fixes.py, keras/src/wrappers/sklearn_test.py, keras/src/wrappers/sklearn_wrapper.py, keras/src/wrappers/utils.py, pyproject.toml
Conditionally import sklearn. Only error on usage of keras sklearn symbol usage.
Kinda awkward that we need to declare empty classes for the classes we are missing from sklearn (if it isn't installed), but this seems like the simplest solution.
=> Make sklearn dependency optional

keras/src/layers/rnn/gru.py, keras/src/layers/rnn/gru_test.py, keras/src/layers/rnn/lstm.py, keras/src/layers/rnn/lstm_test.py
This change is to make the implementation of recurrent dropout consistent with GRU (changed as of https://github.com/keras-team/keras/pull/20656 ) and Keras 2.
Also fixed a bug where the GRU fix would break when using CUDNN with a dropout and no recurrent dropout. The solution is to create multiple masks only when needed (implementation == 1).
Added coverage for the case when dropout is set and recurrent dropout is not set.
=> Change recurrent dropout implementation for LSTM.

keras/src/export/export_lib_test.py
These are invalid options in the latest version of jax2tf, they will just immediately throw.
=> Never pass enable_xla=False or native_serialization=False in tests

keras/src/layers/preprocessing/image_preprocessing/mix_up.py
We need to make sure to use get any tensors places on cpu before using them in the tensorflow backend during preprocessing.
=> Fix up torch GPU failing test for mix up

keras/src/layers/preprocessing/image_preprocessing/random_contrast.py, keras/src/layers/preprocessing/image_preprocessing/random_contrast_test.py, keras/src/layers/preprocessing/image_preprocessing/random_hue.py, keras/src/layers/preprocessing/image_preprocessing/random_hue_test.py
I’ve updated the processing logic for the value_range argument in the following components:
1. random_contrast
- Added the value_range argument.
- Corrected the existing test cases and added new test cases to validate the value_range functionality.
2. random_hue
- Set a default value for the value_range argument.
- Introduced new test cases to cover the value_range functionality.
=> Adjust value_range for random_contrast and random_hue

keras/src/metrics/iou_metrics.py
Multiple Example Title has removed in OneHotMeanIoU funtion.
=> Multiple Example Title has removed in OneHotMeanIoU funtion

keras/src/layers/preprocessing/image_preprocessing/center_crop.py, keras/src/layers/preprocessing/image_preprocessing/equalization.py, keras/src/layers/preprocessing/image_preprocessing/random_crop.py, keras/src/layers/preprocessing/image_preprocessing/random_flip.py, keras/src/layers/preprocessing/image_preprocessing/random_grayscale.py, keras/src/layers/preprocessing/image_preprocessing/random_rotation.py, keras/src/layers/preprocessing/image_preprocessing/random_translation.py, keras/src/layers/preprocessing/image_preprocessing/random_zoom.py, keras/src/layers/preprocessing/image_preprocessing/solarization.py
I have added a training condition to prevent certain image processing steps from being applied during the inference phase.
=> Add training status condition during image processing

keras/src/layers/attention/attention.py, keras/src/layers/attention/attention_test.py
This pull request addresses an issue in the Attention layer where the return_attention_scores parameter wasn't correctly handled in the compute_output_shape method. This fix ensures that attention scores are returned when return_attention_scores=True.
Modified compute_output_shape method to return the shape of both the attention output and the attention scores when return_attention_scores=True.
=> Fix: Return Attention Scores when `return_attention_scores=True`

keras/src/layers/attention/attention.py, keras/src/layers/attention/attention_test.py
fix attention layer output with symbolic tensors and return_attention_scores = True .
Fixes #20621
=> fix attention output with symbolic tensors and attention scores

guides/functional_api.py
Add an empty line so the list is rendered as a list, not as a single line of text
Currently:
=> minor: Fix Functional API guide

keras/api/_tf_keras/keras/layers/__init__.py, keras/api/layers/__init__.py, keras/src/layers/__init__.py, keras/src/layers/preprocessing/image_preprocessing/random_posterization.py, keras/src/layers/preprocessing/image_preprocessing/random_posterization_test.py
I implemented the RandomPosterization image processing feature before working on rand_augment, as it includes related image processing functionalities. 
Here is my [gist](https://colab.research.google.com/drive/1al4qLGvJXnmZ29-5kOasZxlrsx1RCzER?usp=sharing)
=> Add random_posterization processing layer

.kokoro/github/ubuntu/gpu/build.sh, keras/src/export/export_lib_test.py, keras/src/models/model_test.py
Following #20685 
We should skip `torch_xla` related tests on Torch GPU CI.
=> Fix torch gpu CI

keras/api/_tf_keras/keras/layers/__init__.py, keras/api/layers/__init__.py, keras/src/layers/__init__.py, keras/src/layers/preprocessing/image_preprocessing/random_sharpness.py, keras/src/layers/preprocessing/image_preprocessing/random_sharpness_test.py
I implemented the RandomSharpness image processing feature before working on rand_augment, as it includes related image processing functionalities.
Here is my [gist](https://colab.research.google.com/drive/1pxRnlb0f4tkfGb21yI9E-NxBiDh1-4_s?usp=sharing)
=> Add random_sharpness processing layer

keras/api/_tf_keras/keras/layers/__init__.py, keras/api/layers/__init__.py, keras/src/layers/__init__.py, keras/src/layers/preprocessing/image_preprocessing/random_shear.py, keras/src/layers/preprocessing/image_preprocessing/random_shear_test.py
I have implemented the transform_images method in the RandomShear image processing layer. If this pull request is accepted, I can proceed with implementing the transform_bounding_boxes method as well.
here is my [gist](https://colab.research.google.com/drive/1rHyfQrsRCccJnNI_GMMlQfkRA-WFURic?usp=sharing)
=> Add random_shear processing layer

keras/src/utils/backend_utils_test.py
closes #20708
On the same machine that produced the test failure, I tried the following 2 code bits in a shell:
```python
x = np.random.uniform(size=[1, 2, 3])
torch.as_tensor(x, device=torch.device("mps"))
```
as well as
```python
y = np.random.uniform(size=[1, 2, 3]).astype("float32")
torch.as_tensor(y, device=torch.device("mps"))
```
the first produced the same error from #20708 while the second didn't, so this should fix things.
=> fix: Torch MPS backend failing test

keras/src/layers/preprocessing/image_preprocessing/random_shear.py, keras/src/layers/preprocessing/image_preprocessing/random_shear_test.py
I have implemented the transform_bounding_boxes method to support random shear functionality.
here is [gist](https://colab.research.google.com/drive/1bVmbBKBbxahThCx23ve9YU1sIONNMXn2?usp=sharing)
=> implement transform_bounding_boxes for random_shear

keras/src/callbacks/backup_and_restore.py
Updated example for BackupAndRestore class example  as it raises error as model is not build.
Fixed [#20712](https://github.com/keras-team/keras/issues/20712)
=> Update BackupAndRestore class example

keras/src/export/onnx.py, keras/src/export/saved_model.py, keras/src/export/tf2onnx_lib.py, requirements-common.txt
This PR adds hacks to `tf2onnx` to ensure Keras remains compatible with `numpy>=2.0.0`.
Additionally, the export logic has been simplified, removing the need for a temporary SavedModel.
=> Patch `tf2onnx` to ensure compatibility with `numpy>=2.0.0`

keras/src/layers/preprocessing/image_preprocessing/random_color_jitter.py
To suppress the warning mentioned below, I declared the build method.
`UserWarning: `build()` was called on layer 'random_color_jitter', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
warnings.warn(`
=> Add build method to supress warning

keras/src/ops/math.py
The `window_length` parameter in `tf.keras.ops.istft` requires `tf.int32` dtype, but this isn't documented. This can cause unexpected `ValueError` when using `tf.int64` and `tf.int16`
Here is the Example case:
```
input_dict = {
'stfts': tf.constant([[-0.87817144+1.14583987j, -0.32066484+0.25565411j]], dtype=tf.complex128),
'frame_length': tf.constant(256, dtype=tf.int16),
'frame_step': tf.constant(5120,dtype=tf.int64)
}
result = tf.signal.inverse_stft(**input_dict)
print(result)
```
The code throws the following error:
```
ValueError: window_length: Tensor conversion requested dtype int32 for Tensor with dtype int64
```
=> Specified window_length dtype requirement in tf.keras.ops.istft in math.py

keras/src/layers/preprocessing/stft_spectrogram.py, keras/src/layers/preprocessing/stft_spectrogram_test.py
by simply using `ops.shape(x)` instead of `x.shape`.
=> Allow dynamic shape in `STFTSpectrogram` layer.

README.md
**Details:** Mention about OpenVINO backend on the main page
cc: @fchollet, please take a look.
=> Add OpenVINO into README.md

keras/src/metrics/iou_metrics.py
Multiple Example Title has removed in metrics.MeanIoU method.
=> Multiple Example Title has been removed in metrics.MeanIoU method

keras/src/utils/jax_layer_test.py
The `DTypePolicy` test produces lower precision results.
=> Fix flaky `JaxLayer` test.

keras/src/backend/common/keras_tensor.py, keras/src/backend/common/keras_tensor_test.py, keras/src/backend/jax/__init__.py, keras/src/backend/jax/core.py, keras/src/backend/numpy/__init__.py, keras/src/backend/numpy/core.py, keras/src/backend/openvino/__init__.py, keras/src/backend/openvino/core.py, keras/src/backend/tensorflow/__init__.py, keras/src/backend/tensorflow/core.py, keras/src/backend/torch/__init__.py, keras/src/backend/torch/core.py, keras/src/layers/core/input_layer.py, keras/src/layers/core/input_layer_test.py, keras/src/ops/core.py, keras/src/ops/core_test.py
Added `ragged` option to `KerasTensor`, `InputLayer` and `convert_to_tensor`. The logic is the same as for sparse tensors.
Fixes https://github.com/keras-team/keras/issues/20731
=> Preliminary parts needed for ragged support, including densification.

keras/src/export/saved_model.py, keras/src/export/saved_model_test.py, requirements.txt
This new implementation is in line with what was done in Keras 2. It tracks all `TrackableResource`s, and lookup tables and hashmaps are subclasses of `TrackableResource`.
This allows users to attach preprocessing functions that are not solely based on Keras preprocessing layers.
=> Implemented more generic asset tracking mechanism in saved model export.

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/ops/__init__.py, keras/src/ops/einops.py, keras/src/ops/einops_test.py
Closes #20332.
Add an `einops` style `rearrange()` operation to the `keras.src.ops.einops`.
Making a new module for this makes sense if we plan to add other similar operations and want to re-use some of the private-marked utility methods here or generalize the logic further.
It makes use of solely `reshape()` and `transpose()`, so these natively run on all backends. Furthermore, only these two operations are applied so it should be fine with symbolic tensors (sometimes, `einops` doesn't work correctly with symbolic tensors in a computation graph).
Direct comparison with `einops`, using the examples from the official documentation:
```
import keras
import einops
tensor = np.random.randn(2, 10, 10, 3)
examples = [
(tensor, 'b h w c -> b h w c', {}),
(tensor, 'b h w c -> b …
```
=> [Keras Ops] Add einops-style `rearrange()` to `keras.ops`

keras/src/backend/common/backend_utils.py, keras/src/backend/common/dtypes_test.py, keras/src/backend/common/variables_test.py, keras/src/backend/torch/layer.py, keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/bounding_box.py, keras/src/ops/core_test.py, keras/src/ops/image_test.py, keras/src/ops/math_test.py, keras/src/ops/nn_test.py, keras/src/ops/numpy_test.py, keras/src/random/random_test.py, keras/src/saving/saving_lib_test.py, keras/src/visualization/draw_segmentation_masks.py, keras/src/wrappers/sklearn_test.py, keras/src/wrappers/sklearn_wrapper.py
Some tools don't like the mix of code with and without type hints.
=> Remove all type annotations for consistency.

keras/api/_tf_keras/keras/layers/__init__.py, keras/api/layers/__init__.py, keras/src/layers/__init__.py, keras/src/layers/preprocessing/image_preprocessing/aug_mix.py, keras/src/layers/preprocessing/image_preprocessing/aug_mix_test.py
I have implemented the AugMix image processing feature. Please let me know if any further corrections or improvements are required.
here is [gist](https://colab.research.google.com/drive/1W_ek6TOKIy_-c8_vNHNP0LIVhF4lvxfW?usp=sharing)
=> Add aug_mix processing layer

keras/src/utils/jax_layer.py
All floats will now follow the global dtype policy unless a specific dtype policy is passed to the layer.
=> `JaxLayer` now uses the global dtype policy by default.

keras/src/backend/tensorflow/image.py, keras/src/ops/image_test.py
The issue arose from improper handling of out-of-bound coordinates, causing invalid indexing when using `dtype='uint8'` with TensorFlow backend.
Changes made:
- Improved processing of coordinates to handle all `fill_mode` cases, including `'reflect'`, correctly.
- Simplified the logic for gathering and applying fill values, ensuring consistent behavior across data types.
- Added test cases for `uint8`, `float32`, and various `fill_mode` settings to validate the fix.
Tests for `uint8` and `float32` now succeed, and the logic for `nearest` `fill_mode` and manual casting is also fixed.
Fixes #20608 and #20645.
=> fix(ops): Fix issue with map_coordinates for uint8 dtype

keras/src/backend/torch/nn.py, keras/src/layers/pooling/average_pooling_test.py, keras/src/ops/nn_test.py
Was able to still reproduce the error, the PyTorch backend had inconsistent behavior between static shape inference and dynamic execution for pooling operations, particularly with 'same' padding and non-unit strides, figured that the root cause was by incorrect padding calculation logic that didn't properly handle asymmetric padding cases.
Key changes:
- Rewrote `_compute_padding_length()` to handle stride-based padding
- Fixed padding calculation to properly support asymmetric padding cases
- Standardize `channels_first`/`channels_last` conversion in pooling ops
- Cleaned up padding application in `_apply_same_padding()`
- Added proper handling of `data_format` throughout pooling pipeline
This fixes the issue where MaxPooling2D with 'same' padding would produce different shapes between …
=> fix(ops): Fix inconsistent padding calculation in PyTorch backend ops

keras/api/_tf_keras/keras/quantizers/__init__.py, keras/api/quantizers/__init__.py, keras/src/quantizers/quantizers.py, keras/src/quantizers/quantizers_test.py
This PR includes:
- Fixes JAX GPU CI issues
- Enhances dtype inference in the computation of `fake_quant_with_min_max_vars`
- Replaces `ops.multiply` with `ops.where` to optimize computation
- Adds tests for bfloat16 and float16 output dtypes
cc @doncarlos999
~~EDITED:~~
~~I'm going to test this new op to check if `tf.lite.TFLiteConverter` can correctly recognize it.~~
~~(I suspect it won’t, and we may need to make some changes when using the TF backend)~~
EDITED2:
- Fixes the export of `keras.quantizers.fake_quant_with_min_max_vars`
- Adds `FakeQuantWithMinMaxVars` operation
- Uses `tf.quantization.fake_quant_*` as a shortcut to be recognizable for TFLite converter.
A POC:
```python
import keras
class QuantConv2D(keras.layers.Conv2D):
def convolution_op(self, …
```
=> Improve `fake_quant_with_min_max_vars`

keras/src/backend/jax/trainer.py, keras/src/backend/numpy/trainer.py, keras/src/backend/tensorflow/trainer.py, keras/src/backend/torch/trainer.py, keras/src/callbacks/callback_list.py
The history is only used in `model.fit`, no need to create it for `evaluate` and `predict`. The history is attached to the model and therefore lives for as long as the model is around.
The executor used in `CallbackList` was never shut down, causing it to keep a thread around, which in turn had thread locals that were leaked.
=> Fix memory leaks in `model.evaluate`.

keras/src/backend/mlx/math.py
This is addressing #19571 
Added implementations for `fft2`, `rfft`, and `irfft`
Fixed my last implementation of `fft` to align with the other backends.
All relevant tests from `keras/src/ops/math_test.py::MathOpsCorrectnessTest` for `fft`, `fft2`, `rfft`, and `irfft` passed
=> mlx - implement `fft2`, `rfft`, and `irfft` and fix `fft`

keras/src/backend/mlx/linalg.py, keras/src/backend/mlx/numpy.py, keras/src/backend/mlx/rnn.py
This addresses #19571 
All tests in `keras/src/layers/rnn/` (excluding those with convolutions) are passing!
A few notes:
- Modified `mlx.numpy.flip` as `slice` did not work with mlx arrays
- I tried `[::-1]` for simple flipping, but it failed to propagate gradients with the bidirectional rnn layers
- I used jax's qr factorization in `mlx.linalg.qr` as mlx's implementation only works on square matrices for now (is numpy preferred in this case?)
=> mlx - `rnn`

keras/src/applications/convnext.py, keras/src/applications/efficientnet_v2.py
- Validate architecture and weights compatibility before API request
- Enhance error messages for mismatched model name and weights
- Fixes #20271
**Original Error Message (Unnecessary Model Weights Download):**
```
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/convnext/convnext_large_notop.h5
785596384/785596384 ...
ValueError: Incomplete or corrupted file detected. The auto file hash does not match the provided value of 6fc8009faa2f00c1c1dfce59feea9b0745eb260a7dd11bee65c8e20843da6eab.
```
**New Error Message (Prevents Unnecessary Download and Prompts Early):**
```
ValueError: Model name "convnext_large" does not match weights variant "convnext_small". When using imagenet weights, the model name must contain the weights variant (e.g., …
```
=> fix(applications): Improve validation and error handling for ConvNeXt weights and fix broadcasting in EfficientNetV2

keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/iou.py
Fix `ciou` implementation bug in bounding_boxes/iou.py.
As per the CIOU paper there seems a bug in implementation of `v` in `compute_ciou` as reported by the user of #20780
As per original paper and other resource referred by the user changing the implementation.
Fixes #20780.
=> fix ciou implementation bug in bounding_boxes/iou.py

keras/api/_tf_keras/keras/layers/__init__.py, keras/api/layers/__init__.py, keras/src/layers/__init__.py, keras/src/layers/preprocessing/image_preprocessing/cut_mix.py, keras/src/layers/preprocessing/image_preprocessing/cut_mix_test.py
I have implemented the transform_images method in the CutMix image processing layer. If this pull request is accepted, I can proceed with implementing the transform_bounding_boxes method as well.
here is my [gist](https://colab.research.google.com/drive/1IYjpcGD7J2XMSi2tcLpogcFoKElNXhZl?usp=sharing)
=> Add cut_mix processing layer

keras/src/metrics/reduction_metrics.py, keras/src/metrics/reduction_metrics_test.py
Previously, `BinaryAccuracy` would return incorrect results when given boolean inputs in JAX backend, and would raise errors in TensorFlow backend. This was because the metric expects numerical values (floats/integers) but wasn't properly handling boolean array inputs.
Fix by casting `y_true` and `y_pred` to `floatx()` in `MeanMetricWrapper.update_state()`. This ensures consistent behavior across backends and proper handling of boolean inputs.
Fixes #20178 raised in August 2024 but still persists in this version.
=> fix(metrics): Fix BinaryAccuracy metric to handle boolean inputs

keras/src/layers/core/masking.py, keras/src/layers/core/masking_test.py
Currently , the Masking layer accepting Tensor also for argument `mask_value` . After saving and loading the model the `mask_value` no longer a tensor. Hence the issue. The issue with be an model which have Masking layer and uses a Tensor as `mask_value`.
Either the Masking layer should not allow Tensors for `mask_value` or while reloading the model we need to take care of this explicitly.
I am proposing to handle `mask_value` explicitly during reloading the model.
Might fix #20706
=> Fix issue with Masking layer with Tensor as `mask_value`

keras/src/backend/common/backend_utils.py, keras/src/backend/mlx/nn.py
This implements 
- `nn.depthwise_conv`
- `nn.separable_conv`
- `nn.conv_transpose`
All tests related to convolutions in `keras/src/ops/nn_test.py::NNOpsCorrectnessTest` are passing
=> `mlx` - more conv

keras/src/layers/attention/multi_head_attention.py
I have a small refactoring for the class `MultiHeadAttention` :space_invader: 
I propose to replace the private attribute `_return_attention_scores` with an extra argument in `_compute_attention`.
This would make subclassing more straightforward and avoid cases where the attention scores are `None`.
This [issue shows in `CachedMultiHeadAttention`][cmha-issue] on KerasHub.
The rationale is explained in more details in #20802 
[cmha-issue]: https://github.com/keras-team/keras-hub/issues/2055
=> Refactoring: turn the attribute `_return_attention_scores` into an argument

keras/api/_tf_keras/keras/layers/__init__.py, keras/api/layers/__init__.py, keras/src/layers/__init__.py, keras/src/layers/preprocessing/image_preprocessing/random_erasing.py, keras/src/layers/preprocessing/image_preprocessing/random_erasing_test.py
I have implemented the RandomErasing image processing feature. Please let me know if any further corrections or improvements are required.
here is my [gist](https://colab.research.google.com/drive/1QX-6SYL_d2nPzdFktDOKcxG_D0EfK_6k?usp=sharing)
=> Add random_erasing layer

keras/src/backend/numpy/image.py, keras/src/backend/torch/image.py, keras/src/ops/image_test.py
The resize doesn't work as expected while setting flag `pad_to_aspectio_ratio=True`.
1. [Resize with JAX](https://colab.sandbox.google.com/gist/sineeli/2fecee7658464ab0c02867e2883864dc/resize-with-tensorflow-backend-correct.ipynb) works as expected.
2. [Resize with Torch](https://colab.sandbox.google.com/gist/sineeli/1187a1426655a28fe4b39c69da9566db/resize-with-torch-backend-bug.ipynb) needs fix.
3. [Resize with Torch Fixed Code](https://colab.sandbox.google.com/gist/sineeli/9da8ee127669a58ee6e3bc263d25816e/resize-with-torch-backend-fixed.ipynb)
=> fix torch backend resize with `pad_to_aspectio_ratio` is set to `True`

keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/ops/numpy_test.py
- Adjust input for negative zero values in argmax.
- Modify implementation to use core ops with floating-point handling.
- Attempts to fix #20350.
=> fix(ops): Handle floating-point edge cases in ops.argmax()

keras/src/backend/mlx/core.py, keras/src/backend/mlx/linalg.py, keras/src/backend/mlx/nn.py, keras/src/backend/mlx/rnn.py
This addresses #19571, to complete the rest of `mlx.nn.py` excluding the pooling functions
This implements:
- `psnr`
- `ctc_loss`
- `ctc_decode`
- `_ctc_greedy_decode`
- `_ctc_beam_search_decode`
- it's not very efficient, mostly because mlx does not have a `unique` function (I probably spent too much time on this 😅)
- we could disable it in the tests (I saw that for torch)
This patches the following:
- `one_hot`
- `categorical_crossentropy`
- `moments` 
- `batch_normalization`
- this now depends on jax's `norm` function until mlx's `norm` supports singular value norms
- (is numpy preferred here?)
=> implement remaining functions in `mlx.nn.py` excluding pooling

keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/ops/numpy_test.py
- Update JAX and NumPy backends to handle subnormal float comparisons (**TODO:** Ensure TensorFlow compatibility).
- Add test case to verify subnormal float value handling.
- Addresses issue #20355.
=> fix(ops): Fix ops.argmin() handling of subnormal float values in Keras backends

keras/src/backend/mlx/linalg.py, keras/src/backend/mlx/numpy.py, keras/src/ops/numpy_test.py
This address #19571
This implements the remaining functions in `mlx.numpy.py`
A few notes:
- the following depend on jax
- `linalg.det`
- I started to implement `linalg.det` with `mlx.linalg.svd`, but due to verbosity decided to use `jax.numpy.linalg.det`
- `slogdet`
- decided to use jax's implementation while `linalg.det` also does
- `nonzero`
- `quantile`
- `einsum` fails with ellipsis in subscripts (for now)
- recently fixed here https://github.com/ml-explore/mlx/issues/1717
Questions:
- a number of data type tests are failing, it seemed like they expected some default output data types, e.g. `int32`, `uint32`, and `float32` (according to some subtypes)
- do we need to force the mlx backend functions to output these dtypes by default?
- is it okay to add some custom handling for …
=> implement remaining functions in  `mlx.numpy.py`

keras/api/_tf_keras/keras/layers/__init__.py, keras/api/layers/__init__.py, keras/src/layers/__init__.py, keras/src/layers/preprocessing/image_preprocessing/random_gaussian_blur.py, keras/src/layers/preprocessing/image_preprocessing/random_gaussian_blur_test.py
I have implemented the RandomGaussianBlur image processing feature. Please let me know if any further corrections or improvements are required.
here is my [gist](https://colab.research.google.com/drive/1ECBkK4aLhtyDgIAw_U1OEYXZKaL4Fj86?usp=sharing)
=> Add random_gaussian_blur layer

keras/src/layers/normalization/batch_normalization.py, keras/src/layers/normalization/batch_normalization_test.py
- Update masked moments calculation to properly account for broadcast dimensions when summing mask weights.
- Added test to verify broadcast mask handling produces zero-centered outputs.
- Fixes #19848.
=> fix(layers): Fix incorrect masked mean/variance in BatchNormalization layer

keras/src/backend/mlx/nn.py
This PR implements support for max_pool and average_pool operations in the MLX backend.
To achieve this functionality the following functions were copied from mlx repository:
_non_overlapping_sliding_windows and _sliding_windows
The tests related to pooling in: 
- eras/src/ops/nn_test.py
- keras/src/layers/pooling
were passed
=> Add max_pool and average_pool for MLX

keras/src/backend/mlx/core.py
`multi_head_attention_test.py::MultiHeadAttentionTest::test_lora` test was failing on loading the model.
It was due to `mlx.core.array()` not able to load h5py Dataset objects. Now loading it with numpy first.
Does that check I added in `mlx.core.convert_to_tensor` look good?
=> mlx - fix error with loading models with h5 and update  `mlx.core.while_loop`

keras/src/backend/__init__.py, keras/src/backend/mlx/__init__.py, keras/src/backend/mlx/export.py, keras/src/backend/mlx/nn.py, keras/src/export/saved_model.py
This is a small patch for `pytest` to run with `mlx` (after the merge with master)
Addresses #19571
=> mlx - patch for pytest to run

keras/src/saving/serialization_lib.py, keras/src/saving/serialization_lib_test.py
Fixes https://github.com/keras-team/keras/issues/20806
This a workaround for an incompatibility between 3.6 and 3.7 introduced by serialization bug fix https://github.com/keras-team/keras/pull/20406
=> Fix for deserializing custom functions serialized with Keras <= 3.6.

requirements-jax-cuda.txt
The jax version currently is causing jax.nn.dot_product_attention import error
repro - https://colab.sandbox.google.com/drive/1dRNCwDLRUYcVpOul8V94GTo9HfN0dRoE#scrollTo=jKIdMM2reib0
I am not sure why the tests in Keras are not failing but KerasHub is seeing the following error
```Flash attention is not supported in your current JAX version. Please update it by following the official guide: https://jax.readthedocs.io/en/latest/installation.html```
coming from https://github.com/keras-team/keras/blob/14d9256108a65470512fa0340ecaf9d8eb5b003a/keras/src/backend/jax/nn.py#L1017-L1037
The root of the error being `AttributeError: module 'jax.nn' has no attribute 'dot_product_attention'`
=> Fix jax version

requirements.txt
Error with torch 2.6:
```
ImportError: /opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/_XLAC.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN5torch8autograd12VariableInfoC1ERKN2at6TensorE
/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/torch_xla/__init__.py:20: Impo
```
=> Fix CI breakage with torch-xla.

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py, keras/src/testing/test_case.py, requirements-jax-cuda.txt, requirements-tensorflow-cuda.txt, requirements-torch-cuda.txt, requirements.txt
Based on this issue https://github.com/jax-ml/jax/issues/24280, we should patch `argmin` and `argmax` ops only when using the CPU due to the flush-to-zero (FTZ) issue.
Since we need `signbit` to patch these ops, adding it is straightforward.
=> Add `signbit` and fix `argmin` and `argmax`

requirements-jax-cuda.txt, requirements-tensorflow-cuda.txt, requirements-torch-cuda.txt, requirements.txt
This is needed to make it compatible with the pinned version of torch we're using.
Note that torch-xla 2.6 doesn't support GPU https://pypi.org/project/torch-xla/2.6.0/ GPU support will be coming back with 2.7.
=> Pin version of torch-xla to 2.5.1.

keras/src/trainers/data_adapters/__init__.py, keras/src/trainers/data_adapters/tf_dataset_adapter_test.py
Changes:
- Added `DistributedDatasetsFromFunction` to the list of recognized dataset types in `is_tf_dataset()`
- Added test cases to verify adapter properties and model integration support
Fixes #20134.
=> fix(trainers): Add support for DistributedDatasetsFromFunction in data adapters

keras/src/backend/mlx/linalg.py
Adds support for `linalg.eigh` on MLX backend.
=> feat(linalg): support eigh on mlx

.github/workflows/actions.yml, .github/workflows/nightly.yml, .kokoro/github/ubuntu/gpu/build.sh, keras/src/trainers/data_adapters/tf_dataset_adapter_test.py, requirements-jax-cuda.txt
Currently, the JAX GPU CI failed because `jax>=0.5.0` is incompatible with `python3.9`.
This PR upgrades the testing environment from py3.9 to py3.10.
Note: I cannot access the internal machine for GPU CI but I think these changes should be fine. Could someone test it by adding the label in this PR?
=> Use Python 3.10 for testing environment

keras/src/backend/jax/trainer.py
On the Jax backend we were not using donate_argnums during `predict()`. This works when a model is mostly trainable, but when a model is mostly or all frozen, this will result in 2x the memory jump (which is why we use donate_argnums for fit and evaluate).
This change adds `donate_argnums` to the predict function to avoid the memory spike. But because this means all incoming state (including the trainable variables) will be deleted by jax, this means we need to sync the trainable variables state much like in fit and evaluate. An alternative would be to change the predict_step signature (so we could only donate non-trainable variables), but this would be a breaking change and confusing.
=> Don't duplicate frozen parameters during predict()

keras/src/backend/mlx/math.py
This PR is an MLX backend implementation of reduce_sum and reduce_max in backend/mlx/math.py
The relevant tests in math_test.py are now successful.
=> MLX segment_sum and segment_max implementation

keras/src/applications/applications_test.py, keras/src/applications/convnext.py
Convnext fails with custom inputs that are more than 1 layer, it looks like a bug. I added a test that highlights the problem and fails for all Convnext and then fixed the issue.
=> Fix convnext to work with any custom input tensors

keras/src/export/onnx.py, keras/src/export/saved_model.py, keras/src/models/model.py, keras/src/utils/torch_utils.py, requirements-jax-cuda.txt, requirements-tensorflow-cuda.txt, requirements.txt
Fix #20826
This PR uses `None` for `verbose` during export, allowing low-level functions and backends to determine the actual value of `verbose`
Additionally, use the TorchDynamo-based ONNX exporter first and fall back to the TorchScript-based one if encountering any issues, making it more future-proof.
Note: We can remove `torch-xla` in the requirements if the testing backend is not torch.
=> Prevent information leakage and improve the ONNX export for the torch backend

keras/api/_tf_keras/keras/layers/__init__.py, keras/api/layers/__init__.py, keras/src/layers/__init__.py, keras/src/layers/preprocessing/image_preprocessing/random_perspective.py, keras/src/layers/preprocessing/image_preprocessing/random_perspective_test.py
I have implemented the transform_images method in the RandomPerspective image processing layer. If this pull request is accepted, I can proceed with implementing the transform_bounding_boxes method as well.
here is my [gist](https://colab.research.google.com/drive/1l5jLASctK0kUBmDRlrUlnLeehuo9yzy4?usp=sharing)
=> Add random_perspective layer

keras/src/layers/convolutional/conv2d.py
- Make it clear that, contrary to what the Keras 3 [docs](https://keras.io/keras_3/) state, Conv2D operations may exceed the documented 1e-7 precision difference across backends.
- Document that large convolutions can show notable variations due to accumulated floating-point operations.
Fixes #20804.
=> fix(layers): Update Conv2D docstring to clarify numerical precision across backends

integration_tests/import_test.py, keras/src/backend/torch/image.py, keras/src/utils/module_utils.py, requirements-common.txt, requirements-jax-cuda.txt, requirements-tensorflow-cuda.txt, requirements-torch-cuda.txt, requirements.txt
We can simplify the logic of `resize` and `rgb_to_grayscale` and remove the dep of `torchvision`
=> Remove `torchvision` dep and simplify `resize` and `rgb_to_grayscale` in torch backend

keras/src/layers/rnn/time_distributed.py, keras/src/layers/rnn/time_distributed_test.py
If the model includes an Embedding layer with `mask_zero = True` parameter and sub sequent model has time distributed layer it is observed that training fails in graph mode if there is `partial_batch_size` . This happens due to concatenation of partial batch dataset which makes `batch_size` to None and hence shape to (None,...).
Hence the model fails with graph execution error if we try to compare batch_size with the respective value from mask.
Hence I am proposing to omit the `batch_size` comparison for TF backend with graph mode. It would have been better if this check is for when there is actually a `partial_batch_size` but not sure how to propogate this to time distributed layer .
Fixes #20754 
Code to replicate the issue:
```
import keras
model = keras.Sequential([ …
```
=> fix time_distributed layer with mask and partial_batch_size

keras/src/layers/preprocessing/hashed_crossing.py, keras/src/layers/preprocessing/hashed_crossing_test.py
Previously, the output of `HashedCrossing` would always have `None` batch size as a result of the underlying Tensorflow `tf.sparse.cross_hashed`.
The previous reshaping logic in `HashedCrossing` would fix the last dimension (expected to be 1) but not the batch dimension.
=> `HashedCrossing` layer preserves the static batch size when known.

keras/src/backend/tensorflow/numpy.py, keras/src/ops/numpy_test.py
- Fix shape handling in `keras.ops.rot90` to correctly swap height/width dimensions based on k rotations.
- Refactor test suite to use parameterized test cases and cover edge conditions more thoroughly.
=> fix(ops): Fix TensorFlow backend keras.ops.rot90 shape transformation and improve test coverage

keras/src/backend/tensorflow/math.py
Fix `ifft2` op with TF backend with dtypes other than `float32` .  The Op should work for `float64` as well.
In the implementation of `ifft2` h, w converted to `float32` irrespective of input dtype. Casting them to input dtype will resolve the issue.
Fixes #20904
=> fix ifft2 op with TF backend

keras/src/backend/jax/export.py, keras/src/backend/tensorflow/export.py, keras/src/backend/torch/export.py, keras/src/export/saved_model.py, keras/src/export/saved_model_test.py
Previously, `track` would only work with `Layer`s or `Model`s unless the backend was TensorFlow. It would raise an error on JAX for instance.
It is now possible to export saved models with a mix of Keras models and TensorFlow native preprocessing involving resources even with the JAX backend.
- Added example on how to use `ExportArchive` to export a function combining a model with some TensorFlow native preprocessing with a resource.
- Added unit test testing the combining of a model with some TensorFlow native preprocessing with a resource.
- Renamed `track` to `_track_layer` in backend specific `ExportArchive` classes because that is the use case.
- Use `super()` instead of `BackendExportArchive` for consistency.
=> Always allow `ExportArchive.track` to track TensorFlow resources.

keras/src/optimizers/loss_scale_optimizer.py, keras/src/optimizers/loss_scale_optimizer_test.py
Fixes #20878. TensorBoard isn't able to report the correct step because this optimizer doesn't forward the `iterations` property.
=> Add iterations property to LossScaleOptimizer

keras/src/backend/mlx/__init__.py, keras/src/backend/mlx/linalg.py, keras/src/backend/mlx/math.py, keras/src/backend/mlx/numpy.py, keras/src/ops/linalg_test.py, keras/src/ops/math_test.py, keras/src/ops/numpy_test.py
- implements `stft` and `istft`
- aligns dtype handling in `mlx/numpy.py` with other backends (matmul, tensordot, etc. still in progress)
- swaps jax dependency to numpy (for ease of testing)
=> `mlx` - `stft`, `istft`, and dtype handling in `numpy.py`

keras/src/backend/mlx/numpy.py
This PR is an implementation of the following functions for MLX backend as part of #19571 
- rot90
- unravel_index
The following tests were successfully passed:
- numpy_test.py::NumPyTestRot90
- numpy_test.py::NumpyOneInputOpsCorrectnessTest::test_unravel_index
- numpy_test.py::NumpyDtypeTest::test_unravel_index_uint8
- numpy_test.py::NumpyDtypeTest::test_unravel_index_uint32
- numpy_test.py::NumpyDtypeTest::test_unravel_index_uint16
- numpy_test.py::NumpyDtypeTest::test_unravel_index_int8
- numpy_test.py::NumpyDtypeTest::test_unravel_index_int64
- numpy_test.py::NumpyDtypeTest::test_unravel_index_int32
- numpy_test.py::NumpyDtypeTest::test_unravel_index_int16
=> Implementation of rot90 and unravel_index functions for MLX backend

keras/src/models/cloning.py, keras/src/models/cloning_test.py
Currently cloning of model is not considering compiled config.
As reported in #20884, the minimal code snippet is as follows.
```
from keras.layers import Dense, Input
from keras.models import Sequential, clone_model
clf = Sequential()
clf.add(Input((7,)))
clf.add(Dense(8, activation="relu"))
clf.add(Dense(1, activation="sigmoid"))
clf.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
print("Original compiled?", clf.compiled)
cloned = clone_model(clf)
print("Cloned compiled?", cloned.compiled)
```
Added a fix for Sequential model and Functional model also.
Fixes #20884 .
Similar issue #20876
=> Fix cloning with compiled sequential model

conftest.py
It is not necessary to decorate excluded openvino tests with other backends.
=> Only load OpenVINO excludes file when backend is "openvino".

keras/src/layers/core/masking_test.py
Tests should only write files in a temp folder.
=> Fix `masking_test.py` saving a file in the current folder.

keras/src/utils/file_utils.py, keras/src/utils/file_utils_test.py
Recognize `/placer` paths as remote locations,
allowing users to save Keras models directly to
Placer paths.
=> Recognize placer as a remote location

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
This is implementation of numpy.arctan2 on the OpenVINO backend.
@rkazants, could you please review?
=> [OpenVINO backend] Support arctan2. (#29010)

.github/workflows/actions.yml, integration_tests/mlx_custom_fit_test.py, keras/src/backend/common/dtypes_test.py, keras/src/backend/mlx/core.py, keras/src/backend/mlx/numpy.py, keras/src/backend/mlx/trainer.py
This implements:
- `numpy.searchsorted`
- `numpy.histogram`
- `integration_tests/mlx_custom_fit_test.py` (if this was okay to add)
- very similar to jax
Question/comment:
- mlx added float64, but only on the cpu. I'm not sure the cleanest way to handle this, any thoughts? 
- I was thinking about a custom wrapper that executed functions within a context manager to the cpu when a float64 is present
- usually, it's (a) passed as the stream, (b) with a context manager, or (c) setting the default device
```python
import mlx.core as mx
x = mx.array([1, 2, 3], dtype=mx.float64)
y = mx.array([4, 5, 6], dtype=mx.float64)
z = mx.add(x, y, stream=mx.cpu) # (a)
with mx.stream(mx.cpu): # (b)
z = mx.add(x, y)
mx.set_default_device(mx.cpu) # (c)
z = mx.add(x, y)
```
=> `mlx` - numpy.searchsorted and numpy.historgram implemented

requirements-common.txt
`google` isn't used anywhere in Keras. It was added by mistake in a previous commit.
GitHub Page: https://github.com/MarioVilas/googlesearch/
PyPi Page: https://pypi.org/project/google/
=> Remove unused dependency

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
Specifically to make it simpler to have multi-backend `polar()` for DeepSeek in KerasHub (https://github.com/keras-team/keras-hub/issues/2077), but is otherwise applicable as a Keras operation.
Equivalent to `torch.polar()`. Note that this is _not_ equivalent to SciPy's [polar()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.polar.html), which performs decomposition.
```
>>> import keras
>>> import numpy as np
>>> import torch
>>> 
>>> abs = np.array([1, 2])
>>> angle = [np.pi / 2, 5 * np.pi / 4]
>>> keras.src.ops.polar(abs, angle)
Array([-4.3711388e-08+1.j       , -1.4142137e+00-1.4142134j], dtype=complex64)
>>> torch.polar(torch.tensor(abs).float(), torch.tensor(angle).float())
tensor([-4.3711e-08+1.0000j, -1.4142e+00-1.4142j])
```
=> [Keras Ops] Add `keras.ops.polar` operation 

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
Support numpy.arange operation for openvino backend and pass the tests. 
Besides, I add dtype checks and conversions to other operations to avoid situations where the dtype is a built-in Python type, such as **dtype=int**.
=> [Openvino Backend] support numpy.arange, modify dtype check

keras/src/backend/tensorflow/numpy.py
Tril/triu ops fail (post compilation) because `tf.cond` expects `k` to be a tensor:
```
>>> inputs = keras.Input((5,))
>>> outputs = keras.ops.tril(inputs)
>>> model = keras.Model(inputs, outputs)
>>> model.predict(keras.ops.ones((2, 5)))
File "/Users/abheesht/Work/repos/keras/keras/src/utils/traceback_utils.py", line 122, in error_handler
raise e.with_traceback(filtered_tb) from None
File "/Users/abheesht/Work/repos/keras/keras/src/utils/traceback_utils.py", line 122, in error_handler
raise e.with_traceback(filtered_tb) from None
TypeError: Exception encountered when calling Tril.call().
pred must not be a Python bool
Arguments received by Tril.call():
• x=tf.Tensor(shape=(2, 5), dtype=float32)
```
Post this PR, this …
=> Fix tril/triu ops

keras/src/metrics/accuracy_metrics.py, keras/src/metrics/reduction_metrics.py
This is a follow up to https://github.com/keras-team/keras/pull/20782 and a replacement for https://github.com/keras-team/keras/pull/20782
We cannot cast `y_pred` and `y_true` to the expected output dtype in `MeanMetricWrapper`. Some metrics expect integers (indices or IDs for instance) and fail if `y_pred` and `y_true` are provided as floats.
It is the responsibility of the metric function to cast as needed. In this case, the correct approach in `BinaryAccuracy` is to use the regular type promotion rules to ensure that the comparison between `y_pred` and `threshold` is done without losing precision. `ops.greater` already does the type promotion correctly. Previously, `threshold` was incorrectly cast to the `y_pred` dtype, which in this case would lower its precision.
=> Fix `BinaryAccuracy` to handle boolean inputs.

keras/src/backend/common/dtypes_test.py, keras/src/backend/common/variables_test.py, keras/src/backend/mlx/__init__.py, keras/src/backend/mlx/core.py, keras/src/backend/mlx/numpy.py, keras/src/backend/mlx/random.py, keras/src/backend/mlx/trainer.py, keras/src/callbacks/tensorboard_test.py, keras/src/layers/core/einsum_dense_test.py, keras/src/layers/preprocessing/image_preprocessing/cut_mix.py, keras/src/layers/preprocessing/image_preprocessing/equalization.py, keras/src/layers/preprocessing/image_preprocessing/mix_up.py, keras/src/layers/preprocessing/normalization.py, keras/src/losses/loss_test.py, keras/src/trainers/data_adapters/array_data_adapter.py, keras/src/trainers/data_adapters/array_data_adapter_test.py, keras/src/trainers/data_adapters/array_slicing.py, keras/src/trainers/data_adapters/data_adapter_utils.py, keras/src/trainers/data_adapters/generator_data_adapter.py, keras/src/trainers/data_adapters/generator_data_adapter_test.py, keras/src/trainers/data_adapters/py_dataset_adapter.py, keras/src/trainers/data_adapters/py_dataset_adapter_test.py, keras/src/trainers/data_adapters/tf_dataset_adapter.py, keras/src/trainers/data_adapters/tf_dataset_adapter_test.py, keras/src/trainers/data_adapters/torch_data_loader_adapter.py, keras/src/trainers/data_adapters/torch_data_loader_adapter_test.py, keras/src/trainers/trainer_test.py, keras/src/utils/module_utils.py
This update includes:
- `MLXTrainer` update for compilation (heavily mimics jax's trainer)
- all data adapters work with mlx
- faster `bincount`
- added `mlx.core.enable_float64()` similar to jax's `enable_x64()` to put in tests and let the user manage `float64` (must be on cpu)
Note:
- compilation in `MLXTrainer` works great except when `ops.cond` is involved, but can mostly be handled by evaluating both branches and doing a `where`. The most notable occurrence of this is in `loss_scale_optimizer`. I'm going to propose a `_mlx_stateless_apply()` in the next PR that avoids `where`
=> `mlx` - trainer update for compilation and data adapters

keras/src/backend/mlx/linalg.py, keras/src/backend/mlx/numpy.py
The following functions are now supported for mlx:
- diagflat
- solve
The trunc function is fixed where it was giving wrong answer for negative values.
All tests for the 3 functions are now successful.
=> Support diagflat, solve and fix trunc function

keras/src/backend/numpy/image.py
To improve performance, I optimized the convolution logic in gaussian_blur by replacing the NumPy-based implementation with scipy.signal.convolve2d. 
Below are the performance test results on my local machine:
- Before Optimization:
```
%%time
%load_ext autoreload
%autoreload 2
from keras.src.backend.numpy.image import gaussian_blur
images = np.random.uniform(size=(2, 800, 800, 3)).astype("float32")
kernel_size = (3, 3)
sigma = np.random.uniform(size=(2,)).astype("float32")
transformed_image = gaussian_blur(images, sigma=sigma)
```
CPU times: user 7.59 s, sys: 0 ns, total: 7.59 s
Wall time: 7.59 s
- After Optimization:
```
%%time
%load_ext autoreload
%autoreload 2
from keras.src.backend.numpy.image import gaussian_blur
images = np.random.uniform(size=(2, 800, 800, 3)).astype("float32") …
```
=> Refactor gaussian_blur in numpy to utilize scipy.signal.convolve2d

keras/src/layers/rnn/rnn.py, keras/src/layers/rnn/rnn_test.py
The error occurred because the PyTorch autograd engine detected that tensors required for gradient computation were modified in-place, invalidating the computational graph.
Fix: Added explicit state cloning in RNN.step() for PyTorch backend when stateful=True to create new tensor objects with separate memory allocation.
=> Fix PyTorch stateful RNN/LSTM gradient computation error resolves #20875

keras/src/layers/rnn/gru.py, keras/src/layers/rnn/lstm.py
After [this PR](https://github.com/keras-team/keras/pull/19645) we can dropout input in cuDNN-based RNN. This PR fixes docstring to reflect the new implementation. Furthermore we don't want to apply dropout during inference like happens when `self.use_cudnn` is `False`: https://github.com/keras-team/keras/blob/c356cae26e36ecd726dc1d5d41282dccdadf5f65/keras/src/layers/rnn/lstm.py#L274-L276
=> Enable cuDNN RNNs when dropout is set and `training=True`

keras/src/layers/preprocessing/discretization.py, keras/src/layers/preprocessing/discretization_test.py
Previously, serialization / deserialization would fail if:
- the layer was saved / restored before `adapt` was called
- the layer was saved / restored after `adapt` was called, but the dataset was such that the number of bins learned was fewer than `num_bins`
The fix consists in not serializing `bin_boundaries` if init was called with `num_bins`. This is consistent with how `tf_keras` works.
Tightened the error checking:
- never allow `num_bins` and `bin_boundaries` to be specified at the same time, even if they match (same as `tf_keras`)
- don't allow `num_bins` and `bin_boundaries` to be `None` at the same time
- verify that `adapt` has been called in `call`
Also removed `init_bin_boundaries` as the value was never used and its presence can be inferred.
=> Fix `Discretization` serialization when `num_bins` is used.

keras/src/backend/jax/core.py, keras/src/backend/jax/distribution_lib.py, keras/src/backend/jax/distribution_lib_test.py, keras/src/backend/jax/trainer.py, keras/src/backend/tensorflow/distribution_lib.py, keras/src/distribution/distribution_lib.py
- Added `backend_mesh` property to `keras.distribution.DeviceMesh` to access the native mesh object.
- Added `backend_layout` property to `keras.distribution.TensorLayout` to access the native layout or sharding object.
The values are cached. Changed the code to access these directly instead of calling the convertion functions every time.
Made the following renames so that these functions can be used in backend agnostic code:
- `_to_jax_device` to `_to_backend_device`
- `_to_jax_mesh` and `_to_dtensor_mesh` to `_to_backend_mesh`
- `_to_jax_layout` and `_to_dtensor_layout` to `_to_backend_layout`
=> Add access to native mesh and layout distribution objects.

keras/src/backend/numpy/image.py
We can still use it for the resize op, but we shouldn't fail to import without jax installed. Fixes https://github.com/keras-team/keras/issues/20966
=> Don't require jax on the numpy backend

keras/src/models/functional.py, keras/src/models/functional_test.py
Consider a model where its `input` property is represented as `[[[input_layer_1, 0, 0]]]`.
When serialized and deserialized, it turns into `[[input_layer_1, 0, 0]]`.
This change removes the input_tensor un-nesting logic from `functional_from_config` method which adds special handling for the above case, now the code proceeds with the regular flow irrespective of triply nested input arrays and maintains consistent representations across serialization round-trips.
=> Fixes inconsistent serialization logic for inputs

keras/src/backend/mlx/core.py, keras/src/backend/mlx/export.py, keras/src/backend/mlx/math.py, keras/src/backend/mlx/nn.py, keras/src/layers/core/einsum_dense_test.py, keras/src/layers/normalization/spectral_normalization.py, keras/src/layers/preprocessing/normalization.py, keras/src/layers/reshaping/up_sampling2d_test.py, keras/src/losses/losses.py, keras/src/models/model_test.py, keras/src/optimizers/loss_scale_optimizer.py
This includes the following:
- `segment_sum` and `segment_max` functions are vectorized and avoid explicit array evaluation, without numpy dependency (allows for compilation and `vmap`)
- replaces calls to `cond` with mlx backend specific logic when required for compilation
- (would appreciate any feedback here)
- all tests in `optimizers`, `losses`, `metrics`, `models`, `callbacks`, `utils`, and `layers` now passing (or skipped)
=> `mlx` - updates post compilation

keras/src/backend/tensorflow/core.py, keras/src/export/tfsm_layer.py, keras/src/export/tfsm_layer_test.py
=> Wrap tf variables in keras variables for TFSMLayer

keras/api/_tf_keras/keras/ops/image/__init__.py, keras/api/ops/image/__init__.py, keras/src/backend/jax/image.py, keras/src/backend/numpy/image.py, keras/src/backend/tensorflow/image.py, keras/src/backend/torch/image.py, keras/src/ops/image.py, keras/src/ops/image_test.py
I have added the elastic_transform method for NumPy, TensorFlow, Torch, and JAX. If this concept and implementation prove to be effective, I can proceed with adding the ops layer and corresponding test cases.
torchvision's [elastic_transform](https://pytorch.org/vision/main/generated/torchvision.transforms.ElasticTransform.html)
here is my [gist](https://colab.research.google.com/drive/1upYpl7yfeqsO4BXIS1fpeEZmqEBNsH_z?usp=sharing)
=> Add elastic_transform processing for image.py

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py, keras/src/ops/numpy_test.py
**Overview**:
- This PR implements support for numpy.bincount operation
**Testing:**
- Ensured all tests are passing & other functionalities remain unaffected.
**CC:**
- @rkazants
=> [OpenVINO backend]: Support numpy.bincount

keras/src/backend/openvino/core.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
Implements the numpy.argsort operation for the Keras 3 OpenVINO backend.
Fixes [#29012](https://github.com/openvinotoolkit/openvino/issues/29012)
@rkazants, could you please review?
=> [OpenVINO backend] Support numpy.argsort

keras/src/backend/jax/nn.py
The mask is named `array` in [`NumpyMask`](https://github.com/jax-ml/jax/blob/1aca76fc133a36903cf154a499b1cc319d340a48/jax/experimental/pallas/ops/tpu/splash_attention/splash_attention_mask.py#L423).
=> Fix incorrect argument in JAX flash attention.

keras/src/backend/jax/trainer.py
This PR fixes an issue with the Jax backend, where, if `fit()` is interrupted, it cannot be restarted because variable values are not restored. 
It's a little tricky to reprex with a too-small example, since it seem a different code path is taken when provided a trivially small dataset.
Starting from the `cats_vs_dogs_small` dataset however, this is easy to reproduce. 
Script `interrupt-train.py`
```python
import os
os.environ["KERAS_BACKEND"] = "jax"
import keras
keras.config.disable_traceback_filtering()
from keras.utils import image_dataset_from_directory
from pathlib import Path
new_base_dir = Path("cats_vs_dogs_small")
inputs = keras.Input(shape=(180, 180, 3))
x = keras.layers.Rescaling(1 / 255)(inputs)
x = keras.layers.Conv2D(32, 3, activation="relu")(x)
x = …
```
=> Restore variables on `fit()` interrupt with Jax backend

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
Hi, @rkazants, could you review? This would close openvinotoolkit/openvino#29360
=> [OpenVINO backend] Support numpy.full_like

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
Hi, @rkazants, could you review this pr? This would close https://github.com/openvinotoolkit/openvino/issues/29357
=> [OpenVINO backend] Support numpy.empty

keras/src/backend/mlx/core.py, keras/src/saving/saving_api_test.py, keras/src/saving/serialization_lib_test.py, keras/src/trainers/data_adapters/array_slicing.py, keras/src/trainers/data_adapters/data_adapter_utils.py, keras/src/trainers/data_adapters/tf_dataset_adapter.py
This contains the following:
- patches data adapters with other backends to accept `mlx` arrays
- all `saving` saving tests passing
=> `mlx` - data adapters and saving

integration_tests/import_test.py
Previously, if no wheel was found, the `[-1]` subscript would fail, preventing the `if not whl_path` clause from outputting the error message.
=> Make `import_test.py` debuggable from console output.

keras/src/backend/jax/image.py, keras/src/backend/numpy/image.py, keras/src/backend/torch/image.py
Starting with 2.1, the first argument of `np.reshape` is positional only.
Removed keyword `a` and for consistency did the same with other backends.
=> Make code compatible with Numpy >= 2.1.

keras/src/backend/openvino/excluded_concrete_tests.txt
**Details:** tests for exp and expand_dims missed in https://github.com/keras-team/keras/pull/20982.
=> [OpenVINO Backend] Get back tests for exp and expand_dims to precommit

keras/src/losses/losses.py
Updated example in docstring for Binary Focal Crossentropy Loss
While reading the documentation for Binary Focal Crossentropy Loss, the example imo seems to lack clarity on how the resultant loss translates to an increased focus on _harder_ examples, compared to Binary Crossentropy Loss.
=> [Documentation] Updated Binary Focal Crossentropy Loss Docstring

keras/src/tree/optree_impl.py
The following will break as reimporting Keras will try to re-register the Tensorflow list/dict wrappers. Presumably anything that forced an actual reimport of `keras` would trigger the same crash.
```python
import keras
keras.config.set_backend("tensorflow")
```
=> Fix optree regsitration

keras/src/optimizers/lion.py
Wording fix only. No change in functionality.
=> Fix typo in Lion optimizer

keras/src/models/model.py, keras/src/saving/saving_api.py, keras/src/saving/saving_api_test.py, keras/src/saving/saving_lib.py, keras/src/saving/saving_lib_test.py
Continuing the work based on #19286
This PR introduces `max_shard_size` in `Model.save_weights`.
Behind the scenes, this PR refactors `H5IOStore` by combining it with `H5Entry`. This change allows for more fine-grained control when storing weights. Specifically, it enables the creation of a new shard file once the current shard file reaches its capacity due to incoming weights.
Compatibility has been verified, but please let me know if anything was overlooked.
The test for LoRA weights saving/loading in KerasHub has been included.
Ping @mattdangerw and @divyashreepathihalli for requesting this feature.
A simple demo script:
```python
import os
from keras import applications
model = applications.EfficientNetB0(weights=None, input_shape=(224, 224, 3))
ref_input = …
```
=> Introduce weights sharding

keras/src/backend/common/variables.py, keras/src/backend/tensorflow/core.py, keras/src/backend/tensorflow/distribute_test.py, keras/src/metrics/metric.py
This allows the `synchronization` argument to be set on Keras Variables, and passed to `tf.Variable`. The main motivation for this is to allow the synchronization to be set to "on_read" for Metrics, which fixes https://github.com/keras-team/keras/issues/21061.
=> Allow synchronization value to be set on Variables

keras/src/backend/tensorflow/numpy.py
Fixes #21047
keras == 3.9.0 + tensorflow < 2.18.0 is throwing `OverflowError: Python int too large to convert to C long` errors.
This is due to the new function `keras.src.backend.tensorflow.numpy.signbit`, where the signbit is identified by comparing the tensor to `tf.constant(0x80000000, dtype=tf.int32)`. The construction of this constant tensor fails on tensorflow < 2.18.0.
The underlying cause is that this calls `np.array(0x80000000, dtype=np.int32)` which throws the overflow error.
The intention of this constant tensor is to create a constant with binary representation `10000...` so that the signbit can be tested. Rather than relying on overflow of `tf.int32.max + 1`, this can instead be instantiated more reliably from `tf.int32.min`.
=> Use tf.int32.min rather than relying on integer overflow

keras/src/layers/preprocessing/image_preprocessing/random_saturation.py, keras/src/optimizers/muon.py
I have resolved the runtime warning that occurred when the factor was set to 1.0.
```
layer = keras.layers.RandomSaturation(factor=(1, 1), value_range=(0, 1))
...
RuntimeWarning: divide by zero encountered in divide
factor = factor / (1 - factor)
```
=> Fix warning for random_saturation

keras/src/ops/numpy_test.py
This PR contains changes to numpy_test.py in order to:
1. Forcing the following tests  to run on CPU. 
* NumpyDtypeTest::test_correlate_*
* NumpyDtypeTest::test_eye_int64
* NumpyDtypeTest::test_identity_int64
All tests are now successful
2. Skipping the following tests because mlx.core.matmul does not support non-floating multiplication. This will eventually be supported by mlx (https://github.com/keras-team/keras/issues/19571#issuecomment-2649744226) but not a top priority.
* NumpyDtypeTest::test_einsum_*
* NumpyDtypeTest::test_inner_*
* NumpyDtypeTest::test_matmul_*
* NumpyDtypeTest::test_tensordot_*
* NumpyDtypeTest::test_dot_*
3. Skipping the following tests that do not work on GPU (https://github.com/ml-explore/mlx/issues/1895):
* …
=> various numpy_test changes

keras/src/callbacks/callback.py
Keras callbacks do not properly handle Torch DistributedDataParallel models. When using DDP, the keras.Model is wrapped in a DDP instance which is obviously not a keras.Model. The keras.Model must be retrieved from the DDP's `module` property, and the callbacks should execute against that instead.
Example of the Problem:
```
import os
os.environ["KERAS_BACKEND"]="torch"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # For simplicity ...
os.environ["MASTER_ADDR"] = "127.0.0.1"
os.environ["MASTER_PORT"] = "29500"
import tempfile
import keras
import torch
from torch.nn.parallel import DistributedDataParallel
def test_callback(model):
"""
Runs a callback through its lifecycle without actually doing any training...
"""
logs = {"val_loss": 10}
checkpoint_path = tempfile.NamedTemporaryFile('w', …
```
=> Special handling of Torch DDP in callback

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
I have added support for numpy.log10 in OpenVINO backend by:
1. Implementing log10(x) as log(x)/log(10) using available operations from OpenVINO
2. Remove numpy.log10 from excluded_concrete_tests.txt file
About implementation:
- I followed same pattern like other math functions in backend
- Added handling for proper type conversion with integral types
- Tests pass successfully on CPU environment
Related to: https://github.com/openvinotoolkit/openvino/issues/29486
cc @rkazants  could you please review?
=> [OpenVINO backend] Support numpy.log10

keras/src/backend/tensorflow/saved_model_test.py, keras/src/ops/function.py, keras/src/ops/function_test.py
Raise error if inputs are not connected with output in functional model.
The below code fails with `tensor_dict` related error which is not useful to users.
```
model_1 = Sequential([
Input(shape=(6,)),
layers.Dense(3, activation="sigmoid"),
])
model_2 = Sequential([
Input(shape=(3,)),
layers.Dense(1, activation="sigmoid"),
], )
combined = Model(Input(shape=(6,)), model_2(model_1(Input(shape=(6,)))), name='nested_model')
combined.compile(loss='binary_crossentropy', optimizer='adam')
output = combined.train_on_batch(np.random.normal(0, 1, (8, 6)), np.random.normal(0, 1, (8, 1)))
```
=> Raise error if inputs are not connected with output in functional model

keras/src/export/export_utils.py, keras/src/export/saved_model_test.py
Fixes https://github.com/keras-team/keras/issues/20835
Also changed multi-input tests to exercise `model.export()` and its signature inference logic.
=> Fix `Model.export` to Saved Model for models with dict inputs.

keras/src/callbacks/model_checkpoint.py
The _save_model method combined the logic to determine if the checkpoint should be saved, and the logic to create the paths and save the checkpoint.
This PR separates the check the determine whether the checkpoint should be saved from the I/O logic, and in doing so resolves two bugs in the current implementation:
1. Host directory is created for every for save iteration, regardless of whether the model will be saved or not. For example, when `save_freq == 'epoch'` and `save_best_only == True`, a folder is created to save the model for every epoch, even though the model is only saved when the monitored condition is satisfied. The folder should only be created when the model or model weights will be saved.
2. If  `save_best_only==True`, and the monitored value is an numpy array or backend …
=> Resolve two bugs in keras.callbacks.ModelCheckpoint

keras/src/layers/layer_test.py
The functions that go through `remat()` should actually be called, if not, remat is not really applied.
=> Add verification to remat tests.

keras/src/layers/layer.py, keras/src/layers/layer_test.py, keras/src/ops/operation.py
When RematScope was applied to a model the following error was encountered
```
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-38319c893c81>](https://localhost:8080/#) in <cell line: 0>()
12     "padding_mask": np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]]),
13 }
---> 14 gemma_model_backbone(input_data)
1 frames
[/usr/local/lib/python3.11/dist-packages/keras/src/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
120             # To get the full stack trace, call:
121             # `keras.config.disable_traceback_filtering()`
--> 122             raise e.with_traceback(filtered_tb) from None
123         finally:
124             del …
```
=> Fix Remat error when called with a model

keras/src/utils/tracking_test.py
JAX will soon fail when `jnp.array` is called with None, so this test will be broken under newer JAX versions if kept as is.
=> `TrackingTest` no longer assigns None to variables

requirements.txt
This PR address a platform specific installation found on macOS when runnign `pip install -r requirements.txt` .The error caused from the use +cpu suffix in pytorch version,which is not supported in macOS.
Issue reference:
Fixes #21121
Tested on:
- MacOS(15.4)
- Python 3.12.6
=> fixed torch version issue for macOS

keras/src/activations/activations.py
I updated the docstring for the elu activation function to include a description of the alpha argument.
=> Add alpha argument description to elu docstring

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
* Adds numpy.expm1 function to OpenVino backend.
* Closes [[Good First Issue][Keras 3 OpenVINO Backend]: Support numpy.expm1 operation #29358](https://github.com/openvinotoolkit/openvino/issues/29358)
=> [OpenVINO backend] Support numpy.expm1

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
**Overview**:
- This PR implements support for numpy.identity operation
**Testing:**
- A single Test for bfloat16 is failing on my local end, rest all are passing.
**CC:**
- @rkazants
=> [OpenVINO backend]: Implement numpy.identity

keras/src/layers/convolutional/base_conv.py, keras/src/layers/convolutional/conv_test.py, keras/src/layers/core/dense.py, keras/src/layers/core/dense_test.py, keras/src/layers/core/einsum_dense.py, keras/src/layers/core/einsum_dense_test.py, keras/src/layers/core/embedding.py, keras/src/layers/core/embedding_test.py
Fixes #21111
This PR adds a new configurable parameter, lora_alpha, across several Keras layers to enhance the LoRA functionality. The changes allow users to independently control the scaling of the LoRA delta relative to lora_rank, providing finer granularity during fine-tuning.
=> Add configurable lora_alpha parameter for LoRA in multiple Keras layers

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
Added decomposition for `numpy.isclose` in the OpenVINO backend as specified in [#29484](https://github.com/openvinotoolkit/openvino/issues/29484).
@rkazants , Could you please review this pr.
=> [OpenVINO backend] Added support for numpy.isclose operation

keras/src/layers/layer_test.py
The functions that go through `remat()` should actually be called, if not, remat is not really applied.
=> Add verification to remat tests. (#21102)

keras/src/backend/jax/trainer.py
This flag no longer does anything in jax.
=> Removing references to jax.config.spmd_mode('allow_all').

keras/src/utils/torch_utils.py, keras/src/utils/torch_utils_test.py
The TorchModuleWrapper layer does not allow automatic inference of the output. Therefore, the model that owns this layer cannot be used like other keras.Model. For example, you cannot use model.summary().
And now the vast majority of models are based on Torch. By adding this feature, we can let ordinary Torch models enjoy the workflow of Keras without making too many modifications.
=> allow TorchModuleWrapper compute output shape

keras/src/trainers/data_adapters/data_adapter_utils.py, keras/src/trainers/data_adapters/generator_data_adapter_test.py
Previously, only 2D Tensorflow ragged tensors were supported. This adds support for any rank.
Also added tests for ragged tensors with `GeneratorDataAdapter`.
=> Improve `tf.RaggedTensor` support in `DataAdapter`s.

keras/src/backend/tensorflow/numpy.py, keras/src/layers/core/embedding.py, keras/src/layers/core/embedding_test.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py, keras/src/testing/test_case.py
Adds support for indices indices in the form of a `tf.RaggedTensor` to the `Embedding` layer by adding support to `ops.take`. The output is also ragged.
Also:
- adds support for negative indices in the sparse tensor use case.
- adds support for ragged tensors in `TestCase.run_layer_test`.
=> Add `tf.RaggedTensor` support to `Embedding` layer.

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
**Overview:**
- fixes https://github.com/openvinotoolkit/openvino/issues/30120
**Testing:**
- Passing all tests 
**CC:**
- @rkazants
=> [OpenVINO Backend]: support numpy.ndim

keras/src/testing/test_case.py
The loss needs to not have any non-compilable op.
=> Fix Embedding test with ragged tensors on GPU.

keras/api/_tf_keras/keras/activations/__init__.py, keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/activations/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/activations/__init__.py, keras/src/activations/activations.py, keras/src/activations/activations_test.py, keras/src/backend/jax/nn.py, keras/src/backend/numpy/nn.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/torch/nn.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py
Since Keras lacks built-in support for the sparse_sigmoid activation function, I implemented it across TensorFlow, PyTorch, and NumPy, aiming to maintain consistency with existing implementations available in Jax.
=> Add sparse_sigmoid activation

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
**Overview:**
- fixes https://github.com/openvinotoolkit/openvino/issues/30121
**Testing:**
- All Tests Passing
**CC:**
- @rkazants
=> [OpenVINO BACKEND] - feat: implement numpy.nonzero for openvino backend

keras/src/backend/jax/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
`ops.zeros_like` is in particular useful for creating a mask of the populated values in the sparse tensor.
=> Add sparse support to `ops.ones_like` and `ops.zeros_like`.

keras/src/backend/common/variables.py
The jax types like `jax.float32` have a string representation of
```
<class 'jax.numpy.float32'>
```
so with the previous code, would be "standardized" as `float32'>` (trailing quote and angle bracket), which is an invalid type.  But, the JAX dtypes _do_ have a `__name__` property, so should be properly detected if we switch the order around.
Kept the old `jax.numpy` string version in place in case that worked with older versions of JAX.
=> Fix dtype detection for JAX types.

keras/src/layers/core/embedding.py, keras/src/trainers/data_adapters/generator_data_adapter_test.py
The `ragged` attribute exists only with `KerasTensor`s.
Minor fix of a unit tests that was using the same local variable for two nested loops.
=> Fix `Embedding.compute_output_spec` with a non-`KerasTensor` input.

keras/src/layers/core/embedding.py
Without the need to also override `compute_output_spec`.
=> Allow `Embedding` subclasses to only override `compute_output_shape`.

keras/src/distribution/distribution_lib.py, keras/src/distribution/distribution_lib_test.py
If explicitly overwriting a variable._layout, we want to keep this layout in any future calls.  This allows auxiliary variables (e.g. gradients, optimizer momentums) to use the same explicit layout.
=> Return explicitly layout if already set on variable.

keras/src/optimizers/base_optimizer.py, keras/src/optimizers/loss_scale_optimizer.py, keras/src/optimizers/loss_scale_optimizer_test.py
If `variable.overwrite_with_gradient`, the gradient represents the desired final value of the variable.  If we did scale it, we're changing that final value.
=>  Don't scale gradients if overwriting variable with gradient.

shell/format.sh
For folks who are used to the old format, this will print instructions. And for people like me, saves needing to remember
`SKIP=api-gen pre-commit run --all-files`
When I just want the formatter. api_gen.py is too slow to run every time.
=> Add back shell/format.sh, but it just runs pre-commit

.github/workflows/actions.yml, .github/workflows/nightly.yml, README.md, requirements-common.txt, requirements-openvino.txt
Unlike jax/torch/tensorflow which all vie for a certain cuda, I don't think openvino has trouble co-installing.
And without this the basic requirements.txt will not give a working dev environment. You can't run our pre-commit without openvino installed due to import errors.
=> Add openvino to the basic requirements file

keras/src/backend/mlx/image.py, keras/src/backend/mlx/random.py
This continues work on #19571
This PR includes the following:
- implemented `image` ops: `compute_homography_matrix`, `perspective_transform`, `gaussian_blur`, and `elastic_transform` (very similar to jax implementations)
- adjust `random.normal` to use `loc` and `mean` directly in `mlx` method
=> `mlx` - new image ops implemented

keras/src/layers/layer.py, keras/src/layers/layer_test.py, keras/src/models/functional.py, keras/src/models/sequential.py
This PR introduces a framework for supporting custom call-context arguments in Keras layers, allowing for more flexible context-aware logic within custom layers.
Currently, Keras layers have special handling for the `training` argument in `Layer.__call__`, which allows its value to be propagated through nested layers. This PR generalizes this mechanism.
1. `Layer.call_context_args`: Custom layers can now define a class attribute `call_context_args` (a set of strings) to declare argument names they expect to be propagated across the model. The `training` argument is implicitly included and does not need to be added to this collection.
2. The call methods in `Functional` and `Sequential` models are updated to accept `**kwargs`.
3. `CallContext`: The `CallContext` object is updated to …
=> Adds Support For Custom Call-Context Arguments

keras/src/trainers/trainer.py
It is unexpected for `Trainer.get_compile_config` to return `None` when calling it from subclasses. This change breaks backward-compatibility, but should not significantly impact any real use-cases.
=> Fix Trainer.get_compile_config base case (empty dict)

keras/src/optimizers/loss_scale_optimizer.py, keras/src/optimizers/loss_scale_optimizer_test.py
The outer `LossScaleOptimizer` ignores the inner's loss-scale factor when scaling the loss.  When computing unscaled gradients, we therefore need to eliminate the inner's loss scale factor, otherwise the gradients get incorrectly scaled.
=> Clear static loss-scale for inner optimizer in LossScaleOptimizer.

keras/src/layers/layer.py, keras/src/layers/layer_test.py
Previously model authors were required to define call-context args in the entry-point layer to tell keras that these arguments should be propagated down. This was slightly awkward.
This also means that in case the entry-point layer is a pre-defined layer (eg. `Dense`), we need to subclass it to tell it to propagate these arguments in its context. This is bad UX.
```py
class Inner(layers.Layer):
call_context_args = ("foo_mode",)
def call(self, x, foo_mode=False):
add_val = ops.where(foo_mode, 1.0, 0.0)
return x + add_val
class Outer(layers.Layer):
call_context_args = ("foo_mode",)
def __init__(self):
super().__init__()
self.inner = Inner()
def call(self, x):
return self.inner(x)
sample_input = np.array([[1.0], [2.0]])
inp = Input(shape=(1,))
out = Outer()(inp)
model = models.Model(inp, …
```
=> Adds `_register_call_context_args` to declare and use call-context arguments.

keras/src/backend/torch/optimizers/torch_parallel_optimizer.py, keras/src/optimizers/adadelta.py, keras/src/optimizers/adafactor.py, keras/src/optimizers/adagrad.py, keras/src/optimizers/adam.py, keras/src/optimizers/adamax.py, keras/src/optimizers/base_optimizer.py, keras/src/optimizers/ftrl.py, keras/src/optimizers/lamb.py, keras/src/optimizers/lion.py, keras/src/optimizers/loss_scale_optimizer.py, keras/src/optimizers/muon.py, keras/src/optimizers/nadam.py, keras/src/optimizers/rmsprop.py, keras/src/optimizers/sgd.py
If `variable.overwrite_with_gradient == True`, then the only optimizer variable ever used for that variable is `base_optimizer._accumulated_gradients`. All other optimizer variables are unused.  This can be extremely wasteful if the training variables are large, for example in the case of large embedding tables that span multiple hosts/devices.
Added a convenience function in the base optimizer `add_optimizer_variables(...)` that loops through the variable list and automatically adds a variable only if appropriate.  If a variable would otherwise be unused, a `None` is inserted into the list.  This is needed to keep `optimizer._get_variable_index()` consistent. Updated all built-in optimizers to use this.
NOTE: if a custom optimizer that exists out in the wild still does create unused …
=> Don't create unused optimizer variables.

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Adds keras.ops.bartlett, which computes the Bartlett window. Supported across NumPy, TensorFlow, PyTorch, and JAX backends, but not supported on OpenVINO.
=> Implement bartlett function in keras.ops

keras/src/backend/jax/rnn.py, keras/src/backend/numpy/rnn.py, keras/src/layers/rnn/rnn_test.py, keras/src/layers/rnn/stacked_rnn_cells_test.py
There is currently a bug specific to JAX backend when using a stacked RNN with a mask (due to the fact that stacked RNN states are **nested** lists):
```python
sequence = np.ones((2, 3, 4))
mask = np.array([[True, True, True], [True, True, False]])  # shape (2, 3)
cell_kwargs = dict(
units=5,
kernel_initializer="ones",  # just to check consistency between backends
recurrent_initializer="ones"  # just to check consistency between backends
)
rnn_cells = [layers.LSTMCell(**cell_kwargs) for _ in range(4)]  # 4 cells
lstm_layer = layers.RNN(rnn_cells)  # stacked RNN
output = lstm_layer(sequence, mask=mask)  # <--- raises error on JAX when mask used!
```
This PR fixes this bug (I also double-checked that the output is consistent across JAX/TF/Torch …
=> Fix stacked RNN with mask in JAX & Numpy backends

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py, pytest.ini
Added numpy.ravel 
@rkazants can you please review it
=> Openvino numpy ravel

keras/src/backend/mlx/core.py, keras/src/dtype_policies/dtype_policy_map_test.py, keras/src/initializers/constant_initializers_test.py, keras/src/layers/attention/grouped_query_attention_test.py, keras/src/layers/attention/multi_head_attention_test.py, keras/src/layers/layer_test.py, keras/src/models/model_test.py, keras/src/ops/linalg_test.py, keras/src/ops/nn_test.py, keras/src/quantizers/quantizers_test.py
This continues #19571
This includes the following:
- `remat`
- adjusted tests
- thread safety set to `False` following https://github.com/ml-explore/mlx/issues/2067 (in all tests this only caused an issue with the progress bar)
With this PR, all that remains are the final linalg ops to pass all tests on Apple silicon. Next steps are to do one more merge with master, continue to work on passing automated GitHub tests, and test Keras Hub.
Outstanding tracked issues are:
- thread safety (noted above) https://github.com/ml-explore/mlx/issues/2067
- conv issues on cpu https://github.com/ml-explore/mlx/issues/2038
Last local test results: `6 failed, 10830 passed, 1977 skipped, 3 xfailed, 7 xpassed in 167.21s (0:02:47)`
=> `mlx` - remat and continued test updates

keras/src/backend/tensorflow/numpy.py
When there are dynamic dimensions, like typically the batch size, `tf.broadcast_dynamic_shape` is not always compilable.
Replace with an adhoc implementation for dynamic dimensions where we rely on the broadcast itself to fail when the shapes are not broadcastable.
Tested with https://github.com/keras-team/keras-rs/blob/main/examples/listwise_ranking.py on GPU as I was not able to distill a simple reproduction of this.
=> Make `take_along_axis` with TF backend compilable.

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Adds keras.ops.blackman, which computes the Blackman window. Supported across NumPy, TensorFlow, PyTorch, and JAX backends, but not supported on OpenVINO.
=> Implement blackman function in keras.ops

keras/src/backend/openvino/numpy.py
Raise NotImplementedError in the OpenVINO implementation for:
- angle
- bartlett
=> Add NotImplementedError for angle & bartlett on openvino

keras/src/optimizers/adadelta.py, keras/src/optimizers/adafactor.py, keras/src/optimizers/adam.py, keras/src/optimizers/adamax.py, keras/src/optimizers/base_optimizer.py, keras/src/optimizers/ftrl.py, keras/src/optimizers/lamb.py, keras/src/optimizers/nadam.py
Added optimizer variables were orginally interleaved during `build` prior to #21232, e.g. `{momentum0, velocity0, momentum1, velocity1, ...}`.  In #21232, the order was changed to non-interleaved for some optimizers, e.g. `{momentum0, momentum1, ..., velocity0, velocity1, ...}`.  This broke some custom checkpoint serialization compatibility that relied on the order of variables remaining consistent.
Here we modify the base function `add_optimizer_variables(...)` to support creating multiple optimizer variables per training variable, and interleaves creation to restore backward compatibility.
=> Interleave optimizer variable creation to restore backward-compatibility

keras/src/backend/tensorflow/numpy.py, keras/src/ops/numpy_test.py
Change https://github.com/keras-team/keras/pull/21239 broke one use case when the axis dimension is dynamic, the type of the indices is not int32, and the op is run in graph mode.
Note that the additional unit tests don't actually cover this.
=> Fix `take_along_axis` with TensorFlow with non-int32 indices.

integration_tests/model_visualization_test.py, keras/src/utils/model_visualization.py
There were several issues with `keras.utils.plot_model()` / `keras.utils.model_to_dot()` when rendering nested models with `expand_nested=True`:
- Sequential models were not expanded
- Edges going into nested models would always connect to the first box in the subgraph, which is incorrect because:
- Functional models can have multiple inputs and the edge needs to point to the correct input
- The destination of the edge can be further nested sub-models like Sequential sub-models
- Edges going out of nested models would always connect from the last box in the subgraph, which is incorrect because:
- Functional models can have multiple outputs and the edge needs to come from the correct layer
- The source of the edge can be further nested in sub-models since there is no "output" box
This adds …
=> Bug fixes in `plot_model` with nested models.

keras/src/backend/mlx/linalg.py
As part of mlx backend support (#19571), this PR adds support for the following functions in linalg.py:
- lu_factor (supported no in mlx)
- solve_triangular (currently supported in mlx)
- lstsq (implemented the same way as TensorFlow's one was implemented)
- eig (used numpy's implementation until it is supported on mlx)
=> Several linalg functions support

keras/src/layers/core/dense.py, keras/src/layers/core/einsum_dense.py, keras/src/layers/core/embedding.py, keras/src/layers/layer.py
I'm working on bringing QAT in Keras and want to clean up the current quantization impl.
This PR simplifies the logic of `quantize` in `Dense`, `Einsum`, and `Embedding` by utilizing `quantized_build`.
It also adds `overwrite_with_gradient` to `Layer.add_weight` to avoid manually assigning the property to variables.
=> Simplify the logic of `quantize` and float8 build.

keras/src/backend/jax/distribution_lib.py, keras/src/utils/rng_utils.py
Keep track of a `global_random_seed`, and ensure it is set when initializing `keras.distribution.initialize(...)`.
In multi-host processes in JAX, all processes require consistent random number generation.  Otherwise, initializers on different hosts would produce inconsistent values, resulting in both compilation and runtime failures.
=> Initialize random seed for distributed models.

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py, pytest.ini
=> Add openvino backend support for numpy.hstack

keras/src/backend/jax/optimizer.py, keras/src/optimizers/base_optimizer.py
Previously the iterations count was incremented in `backend_apply_gradients(...)`. However, this meant that if all variables had `overwrite_with_gradient`, or any other special handling within a custom optimizer, the iteration count would never be increased.  The iteration isn't updated via "applying gradients" anyways, so it seems to make more sense to increment it directly in `apply`.
=> Increment optimizer._iterations in apply(...).

keras/src/backend/jax/distribution_lib.py, keras/src/backend/jax/distribution_lib_test.py
In some cases we need to explicitly specify the layout in JAX (e.g. for sparse-core tables).  The previous distribution lib was hard-coded to expect `jax.sharding.Sharding`.  Generalized to support explicit Layouts.
The previous `distribute_variable`/`distribute_tensor` code also used explicit device placement calls.  JAX should be able to handle all this automatically.  See [Making process-spanning arrays from external data](https://docs.jax.dev/en/latest/multi_process.html#making-process-spanning-arrays-from-external-data).
=> Add support for jax.experimental.layout layouts.

keras/src/backend/common/variables.py, keras/src/backend/jax/core.py, keras/src/optimizers/base_optimizer.py
If a variable has a particular layout (e.g. is sharded across multiple devices/hosts), then any corresponding auxiliary variables, like optimizer gradient accumulators, need to have the same layout. This requires use to set the variable layout prior to initialization so that it is initialized correctly and efficiently across devices.
Added optional `kwargs` to the base `Variable` class so they can handle (and ignore) any backend-specific options.  Modified `JaxVariable` to allow setting the layout parameter on construction. Modified `add_variable_from_reference` to copy the layout from the reference variable.
=> Allow variable layout to be set on construction.

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Adds keras.ops.hamming, which computes the Hamming window. Supported across NumPy, TensorFlow, PyTorch, and JAX backends, but not supported on OpenVINO.
=> Implement hamming function in keras.ops

keras/src/backend/jax/nn.py, keras/src/layers/preprocessing/image_preprocessing/random_grayscale.py, keras/src/layers/preprocessing/image_preprocessing/random_grayscale_test.py
Fixes [#21276](https://github.com/keras-team/keras/issues/21276).
When we were passing a single image without including a batch dimension, it was not being handled properly and causing problem. The documentation mentions both 3D(unbatched -> W, H, C) and 4D(batched -> batch, W, H, C) images are accepted by RandomGrayscale layer.
Now it has been fixed.
=> Fixed RandomGrayscall.call for single unbatched image.

keras/api/_tf_keras/keras/config/__init__.py, keras/api/config/__init__.py, keras/src/backend/config.py, keras/src/backend/jax/trainer.py, keras/src/backend/tensorflow/trainer.py, keras/src/backend/torch/trainer.py, keras/src/trainers/epoch_iterator.py, keras/src/trainers/trainer_test.py
I've wanted this tool for a while, figured I should just propose it. Often I need to test out a script or colab I did not write, and just want to run a few train steps without for every fit call without finding every call to fit in the script. This adds a debugging tool to do just that.
```
KERAS_MAX_EPOCHS=1 KERAS_MAX_STEPS_PER_EPOCH=5 python train.py
```
=> Add an easy way to run a script for a few steps only

.kokoro/github/ubuntu/gpu/build.sh, requirements-jax-cuda.txt, requirements.txt
Update JAX GPU version and fix failing GPU tests
=> update JAX GPU version

keras/src/backend/jax/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Arguably, the result of `ones_like` and `zeros_like` should not be sparse.
=> Revert "Add sparse support to `ops.ones_like` and `ops.zeros_like`."

keras/src/layers/core/einsum_dense.py
Replaced the use of the + operator with ops.add(x, bias) when adding the bias term in EinsumDense
=> Use ops.add for bias addition in EinsumDense

keras/src/backend/openvino/core.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
Hi @rkazants 
I've supported ```ops.split```, which I need for my GSoC project.
Could you please review it? Thanks!
While working on it, I found an issue with ```convert_to_numpy```, it doesn’t handle a list of ```OpenVINOKerasTensor```. I included a simple reproducer to demonstrate the problem.
```python
from datetime import datetime
ov_tensor = ops.convert_to_tensor(np.array([1, 2, 3]))
tensor_list = [ov_tensor for _ in range(3)]
start_time = datetime.now()
print("Start:", start_time.strftime("%I:%M:%S %p"))
_ = ops.convert_to_numpy(tensor_list)
end_time = datetime.now()
print("End:", end_time.strftime("%I:%M:%S %p"))
```
The issue is with ```np.array(x)``` in ```convert_to_numpy``` where x is a list of ```OpenVINOKerasTensor```, which is being …
=> [OpenVINO Backend] support ops.split

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Adds keras.ops.kaiser, which computes the Kaiser window. Supported across NumPy, TensorFlow, PyTorch, and JAX backends, but not supported on OpenVINO.
=> Implement kaiser function in keras.ops

CONTRIBUTING.md, pyproject.toml
The latest versions of JAX (0.6.0) and TensorFlow (2.20) no longer support Python 3.9.  They do support 3.12.
=> Bump up minimum version of python to 3.10.

keras/src/backend/tensorflow/image.py, keras/src/ops/image_test.py
When calling the tensorflow version of `keras.ops.image.map_coordinates` with `coordinates` containing an index outside of the input image dimensions and constant padding, the output image is filled with `fill_value` due to a missing axis annotation in the tensorflow backend code.
Script to reproduce with current master branch:
```python
import keras
import matplotlib.pyplot as plt
def main():
img = tf.random.normal((128, 128))
grid = tf.stack(
tf.meshgrid(
tf.range(0, img.shape[0], dtype=tf.float64),
tf.range(0, img.shape[1], dtype=tf.float64),
),
axis=0,
)
grid_with_oob = tf.stack(
tf.meshgrid(
tf.range(-1, img.shape[0] - 1, dtype=tf.float64),
tf.range(-1, img.shape[1] - 1, dtype=tf.float64),
),
axis=0,
)
identity_mapped = keras.ops.image.map_coordinates(img, …
```
=> Fixed missing axis annotation in tf map_coordinates

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Adds keras.ops.hanning, which computes the Hanning window. Supported across NumPy, TensorFlow, PyTorch, and JAX backends, but not supported on OpenVINO.
=> Implement hanning function in keras.ops

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/nn/__init__.py, keras/api/ops/__init__.py, keras/api/ops/nn/__init__.py, keras/src/layers/normalization/layer_normalization.py, keras/src/ops/nn.py, keras/src/ops/nn_test.py, keras/src/utils/python_utils.py
from https://github.com/keras-team/keras/issues/21313 and https://github.com/keras-team/keras/pull/21323
To improve the performance of the torch backend, we add a new op and use the cudnn operator of the torch in this op
=> add ops.layer_normalization

keras/src/backend/jax/nn.py
Reverts keras-team/keras#21254
=> Revert "Fixed issue with dot_product_attention when using TPU. "

keras/src/trainers/data_adapters/py_dataset_adapter.py, keras/src/trainers/data_adapters/py_dataset_adapter_test.py
It can now be iterated without failure when it has a finite number of batches.
Previously, it was iterable by accident due to a legacy feature of Python that predates the introduction of `__iter__`. Specifically, Python would see `__getitem__` implemented and would iterate by passing sequential indices. However, `__getitem__` was expected to throw an `IndexError` to indicate the end of the iterator as `__len__` is ignored by Python.
Instead, we return an iterator that knows about the length of the dataset.
Fixes https://github.com/keras-team/keras/issues/21151
=> `PyDataset` now implements `__iter__`.

.gitignore, keras/src/optimizers/adamw_test.py, keras/src/optimizers/ftrl_test.py, keras/src/optimizers/lion_test.py, keras/src/optimizers/nadam_test.py, keras/src/optimizers/sgd_test.py
Added some unit tests to increase code coverage in `optimizers`
=> Increase coverage in optimizers

keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/nn.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/core.py, keras/src/backend/numpy/math.py, keras/src/backend/numpy/nn.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/core.py, keras/src/backend/openvino/image.py, keras/src/backend/openvino/math.py, keras/src/backend/openvino/nn.py, keras/src/backend/openvino/numpy.py, keras/src/backend/tensorflow/nn.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/math.py, keras/src/backend/torch/nn.py, keras/src/backend/torch/numpy.py, keras/src/ops/core.py, keras/src/ops/image.py, keras/src/ops/math.py, keras/src/ops/math_test.py, keras/src/ops/nn.py, keras/src/ops/numpy.py, keras/src/ops/ops_test.py
Added tests to verify that:
- All the parameters in the op class `call` (dynamic / tensor parameters) and `__init__` (static / non-tensor parameters) match the parameters in the op function
- the names should match
- default values should match
- the order should be consistent, usually with the static parameters all at the end
- Ops are exported in `keras.ops`
- Ops are exported in their module, e.g. `keras.ops.numpy`
- Ops are implemented in every backend
- The backend implementation has the same signature as the op wrapper (same parameters in the same order with the same default values)
Note about default values: only the default values declared in the common op function are used by users, which is why those values were not changed and were applied to the class and backend …
=> Make ops consistent and test ops consistency.

keras/src/layers/pooling/average_pooling2d.py
Let's fix comment in AveragePooling2D.
=> Fix comment

keras/src/backend/openvino/core.py
Hi @rkazants ,
Supporting comparison ops (>, <, <=, >=, ==, !=) for `OpenVINOKerasTensor`, which is needed for my GSoC project.
Could you please review it?
=> [OpenVINO Backend] support comparison ops (>, <, <=, >=, ==, !=) for OpenVINOKerasTensor

keras/src/ops/numpy.py
The `dtype` parameter is never a tensor and should therefore be a static parameter in the `OnesLike` and `ZerosLike` operations.
=> Make `dtype` a static parameter of `OnesLike` and `ZerosLike`.

keras/src/backend/openvino/core.py, keras/src/backend/openvino/excluded_concrete_tests.txt
Hi @rkazants
I've updated `ops.slice` to support `OpenVINOKerasTensor` slicing, which I need for the GSoC project.
Could you please review it?
Thanks!
=> [OpenVINO Backend] update slice method

keras/src/layers/layer.py, keras/src/ops/operation.py, keras/src/ops/operation_test.py
- The `dtype` in `Operation.__init__` was used to populate `self._dtype_policy`, but was not used by `Operation` itself, nor by any of the subclasses besides `Layer`.
- `Operation`s never apply the dtype policy.
- The serialization of `self._dtype_policy` is already implemented in `Layer`, and in a different way than in `Operation`.
- Many ops (e.g. `cast`) have a `dtype` parameter in their `__init__` which has different semantics from `_dtype_policy` and which cannot be a `DTypePolicy`. While it doesn't appear to interfere, it just makes it very confusing.
=> Move `_dtype_policy` from `Operation` to `Layer`.

keras/src/metrics/confusion_metrics.py, keras/src/metrics/confusion_metrics_test.py, keras/src/metrics/metrics_utils.py
We implement the AUC metric described in https://research-information.bris.ac.uk/files/72164009/5867_precision_recall_gain_curves_pr_analysis_done_right.pdf
This metric is intended to help classifiers when the true label fraction is far from balanced (0.5) and to be independent of the true label fraction, allowing to compare values between reweighted models, unlike the original PR curve.
=> Add implementation of precision-recall gain AUC

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Adds keras.ops.corrcoef, which computes the Pearson correlation coefficient matrix. Supported across NumPy, TensorFlow, PyTorch, and JAX backends, but not supported on OpenVINO.
=> Implement corrcoef function in keras.ops

keras/src/wrappers/sklearn_wrapper.py
The examples in the docstrings for `SKLearnClassifier` and `SKLearnRegressor` are currently not working. This PR addresses the problems mentioned in, and closes #21384:
- General Fixes:
- Import layers from `keras.layers`
- Import `Model` from `keras.models`
- Remove unnecessary `[]`
- `SKLearnClassifier` Fix:
- Use a 2 class classification problem as an example (instead of the 3 class example)
- `SKLearnRegressor` Fix:
- Use `linear` activation because it is a regression problem that does not fall between `[0, 1]`
=> Fix SKLearnClassifier and SKLearnRegressor examples

keras/src/layers/convolutional/base_conv_transpose.py, keras/src/layers/convolutional/conv1d_transpose.py, keras/src/layers/convolutional/conv2d_transpose.py, keras/src/layers/convolutional/conv3d_transpose.py
- Added `output_padding` Argument in `Conv1DTranspose`, `Conv2DTranspose`, and `Conv3DTranspose` layers, which was previously missing in the constructors of these layers.
- Improved  description of `dilation_rate` argument.
- Added `allow_zero=True` as an extra argument to `standardize_tuple()` in `BaseConvTranspose`
- The documentation for `Conv1DTranspose`, `Conv2DTranspose`, and `Conv3DTranspose` layers has been updated to include the `output_padding` argument.
Fixes https://github.com/keras-team/keras/issues/19870 and https://github.com/keras-team/keras/issues/20408
=> Update output_padding argument in convolution transpose layer

keras/src/wrappers/fixes.py, keras/src/wrappers/sklearn_wrapper.py, keras/src/wrappers/utils.py
This PR addresses a bug where the `SKLearnClassifier` and `SKLearnRegressor` wrappers raise an `AttributeError` when used without other `scikit-learn` utilities (e.g. `make_classification`).
- Explicitly imports `sklearn.utils.multiclass.type_of_target` instead of relying on indirect access via `sklearn.utils`
- Cleans up related imports in related files:
- Replaces several indirect accesses with explicit imports (`make_pipeline, OneHotEncoder, MetadataRequest, check_is_fitted`)
- Avoids the use of private API `sklearn.utils._array_api` by using `np.squeeze` directly, which is consistent with the docstring expectations
Fixes #21386
=> Fix missing and fragile scikit-learn imports in Keras sklearn wrappers

keras/src/backend/jax/distribution_lib.py, keras/src/backend/jax/distribution_lib_test.py
It is being renamed to jax.experimental.layout.Format.  The comments can be kept generic anyways to support other layout instances in the future.
=> Remove references to jax.experimental.layout.Layout.

keras/src/utils/io_utils.py
[print_msg](cci:1://file:///d:/Github/keras/keras/src/utils/io_utils.py:91:0-112:29) now defaults to UTF-8 when `sys.stdout.encoding` is unset, preventing a `TypeError` during logging in non-interactive or redirected-output environments.
=> Fix crash when `sys.stdout.encoding` is `None`

keras/src/backend/openvino/core.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/ops/core_test.py
Hi @rkazants ,
I've supported `ops.while_loop`, and it is ready for review.
=> [OpenVINO Backend] support while_loop

keras/src/backend/openvino/core.py, keras/src/backend/openvino/excluded_tests.txt, keras/src/ops/core_test.py
Hi @rkazants ,
I've updated `__getitem__` using `gather_nd` as suggested, and I've avoided using `convert_to_numpy`. Also, I've enabled `variables_test`.
`__getitem__` passed all tests aviable + I've tested it locally.
Here are my test cases:
```python
from keras.src import testing
class GetItemOpsTest(testing.TestCase):
def test_getitem(self):
self.np_tensor = np.arange(24).reshape(2, 3, 4)
self.tensor = ops.convert_to_tensor(self.np_tensor)
t = self.tensor[1]
n = self.np_tensor[1]
self.assertEqual(t.shape, n.shape)
self.assertTrue(np.array_equal(ops.convert_to_numpy(t), n))
t = self.tensor[1, 2, 3]
n = self.np_tensor[1, 2, 3]
self.assertEqual(t.shape, n.shape)
self.assertTrue(np.array_equal(ops.convert_to_numpy(t), n))
t = self.tensor[1:2]
n = …
```
=> [OpenVINO Backend] update __getitem__

keras/src/backend/jax/distribution_lib.py
The `jax.experimental.layout.Format` configuration has a `"format"` attribute rather than a `"layout"` attribute.
=> Add "format" support for latest JAX.

keras/src/ops/math_test.py, keras/src/ops/operation_utils.py
Using `keras.ops.math.logsumexp` with an int for `axis` in a functional model would throw an error.
=> Fix symbolic call of `logsumexp` with int axis.

keras/src/backend/mlx/linalg.py, keras/src/trainers/trainer_test.py
This is a PR for 2 small changes:
- Use `mlx.core.linalg.eig` instead of numpy's now that it is supported in MLX
- skip `test_fit_with_data_adapter` for multiprocessing in case of MLX. This works fine on a Mac however it does not work on Linux. I skipped the test regardless of the OS. If it's better to skip it only for MLX on Linux, I can do that.
This is part of supporting MLX backend #19571
=> MLX small changes

keras/src/ops/nn.py, keras/src/ops/nn_test.py
- Added tests.
- Fixed numeric stability issues in half-precision training by using float32 for computations (which is also the default in Flax)
- Updated the fn signature of the `Operation`.
Ref: https://github.com/google/flax/blob/main/flax/linen/normalization.py
=> Fix `rms_normalization` and `layer_normalization` to ensure consistent precision in computations.

keras/src/layers/layer.py, keras/src/layers/layer_test.py
This fix addresses a bug in the Layer class where an explicitly passed `mask` keyword argument was ignored during the computation of the output mask for subsequent layers.
Currently, when a layer is called with an explicit mask (e.g., `layer(inputs, mask=my_mask)`), the framework correctly uses this mask for the layer's internal `call()` computation. However, when preparing to propagate a mask to the next layer, the framework incorrectly ignores this explicit mask. Instead, it only checks for a `_keras_mask` attribute attached directly to the input tensor.
If the input tensor has no such attribute, the output mask is computed as `None`, effectively breaking the mask propagation chain.
The fix modifies how the `previous_mask` variable is determined within the `Layer.__call__` method. The …
=> Ensures mask kwarg is used for output mask propagation

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Adds keras.ops.cbrt, which computes the real-valued cube root of each element in the input tensor.
Supported across NumPy, TensorFlow, PyTorch, and JAX backends. Not supported on OpenVINO.
=> Implement cbrt function in keras.ops

keras/src/backend/openvino/core.py
Hi @fchollet 
I just added a check for `np.ndarray` in the function that was recently merged.
=> update a small feature in __getitem__ for openvino backend

keras/src/trainers/data_adapters/__init__.py
Updated the error message for `class_weight` with PyTorch DataLoaders to suggest two solutions: modifying the `__getitem__` method or using a custom training loop. Included a link to the user guide for the custom training loop.
Fixes [#21355 ](https://github.com/keras-team/keras/issues/21355)
=> Improve error message for class_weight with PyTorch DataLoaders

keras/src/callbacks/lambda_callback.py
The [LambdaCallback](https://keras.io/api/callbacks/lambda_callback/) docstring previously stated that callback methods receive their arguments as positional arguments, including `on_train_batch_begin` and `on_train_batch_end`.
However, `batch` is passed as a positional argument, but `logs` is passed as a keyword argument for `on_train_batch_begin` and `on_train_batch_end` methods. This PR updates the docstring to specify that `on_train_batch_begin` and `on_train_batch_end` expect a positional argument `batch` and a keyword argument `logs`.
Fixes : [#21459 ](https://github.com/keras-team/keras/issues/21459)
=> fix argument description for on_train_batch callbacks in LambdaCallback

requirements-common.txt
Reported in https://github.com/keras-team/keras/issues/21390#issuecomment-3068295932
The root cause is that the test fails with `onnxscript==0.3.2` which is the latest version.
I don't have the capacity to investigate the root cause in `onnxscript`. As a workaround, we can pin the version to 0.3.1.
cc @pctablet505
=> Pin onnxscript version to `0.3.1`.

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/math.py
this PR updates the LogSumExp operation to work correctly with the OpenVINO backend and resolves related numerical issues. 
We use `keepdims=True` for `reduce_max` to ensure the output shape of the maximum matches the input shape for broadcasting during subtraction. If `keepdims=False`, the reduced axis is removed, so the shapes don't align and broadcasting fails or produces incorrect results. By always keeping the reduced dimension (`keepdims=True`), we guarantee that `x - max` works as intended, regardless of which axis is reduced. After all computations, we squeeze the result only if the user requested `keepdims=False`, so the final output shape matches expectations. This approach ensures both correct broadcasting and correct output shape.
fixes #21470
=> Fix LogSumExp Implementation for OpenVINO backend.

keras/src/layers/core/dense.py, keras/src/layers/core/einsum_dense.py, keras/src/layers/core/einsum_dense_test.py
This PR adds `int4` quantization support to the `EinsumDense` layer, and integrates it with LoRA.
1.  `int4` Quantization for `EinsumDense`:
* `_int4_build` method to create packed `int4` kernels (stored as `int8`) and associated scale variables.
* `_int4_call` forward pass that unpacks the kernel on-the-fly and uses a custom gradient for backpropagation.
2.  LoRA Support for `int4` Layers: LoRA can be enabled on `int4`-quantized `EinsumDense` layers. The `enable_lora` method correctly infers the original, unpacked kernel shape, ensuring the LoRA matrices are created with the correct dimensions to operate in the full-precision space.
For `EinsumDense`, the `int4` packing is performed along the **first kernel reduction-axis** (`_kernel_reduced_axes[0]`). This axis is chosen because it's …
=> Adds int4 quantization support to EinsumDense

keras/src/backend/jax/core.py, keras/src/ops/core.py, keras/src/ops/core_test.py
TF's slice op supports -1 for shape (https://www.tensorflow.org/api_docs/python/tf/slice), which means that all remaining elements in dimension i are included in the slice. Since all the shapes are static in JAX, it errors when -1 is passed. We have a feature request to support -1 shape for the JAX backend as well to have a better UX.
=> Support shape -1 for `slice` op in the jax backend

keras/src/ops/core.py
I have fixed the [vectorized_map ](https://keras.io/api/ops/core/#vectorizedmap-function)function example in core.py, which had some syntax errors.
=> Docs - Fixed Syntax Error in vectorized_map function example

README.md
This PR enhances the clarity and polish of the Keras README by correcting minor but important inconsistencies in platform naming:
- Updated “python” to “Python” to reflect the proper name of the language.
- Corrected “MacOS” to “macOS” to match Apple’s official styling.
While subtle, these adjustments contribute to a more professional, accurate, and trustworthy documentation experience for new developers evaluating or onboarding with Keras 3. Maintaining consistent terminology strengthens the credibility and quality of open source documentation.
=> docs: enhance clarity and consistency in README by correcting platform capitalization

keras/src/ops/numpy.py
Adds support for the cbrt operation in compute_output_spec.
Ensures correct output shape and dtype inference for cube root computations.
=> Update compute_output_spec method to support cbrt operation

examples/demo_custom_mlx_workflow.py, keras/src/layers/preprocessing/stft_spectrogram_test.py, keras/src/ops/nn_test.py, keras/src/trainers/trainer_test.py
This PR includes the following:
- `examples/demo_custom_mlx_workflow.py` (simple demo file, other backend examples should probably be tested)
- reduced tolerance on some stft spectrogram tests
- disable multiprocessing trainer test for CI (passes on Apple silicon)
- skip nn tests for activations with float64 (https://github.com/ml-explore/mlx/issues/2252)
=> `mlx` - more changes to tests to pass CI

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py
Hi @rkazants 
I've supported `tri`, `triu` and `tril`, and they are ready for review.
=> [OpenVINO backend] support tri, triu, and tril

keras/src/backend/common/keras_tensor.py, keras/src/backend/jax/trainer.py, keras/src/trainers/data_adapters/__init__.py, keras/src/trainers/data_adapters/data_adapter.py, keras/src/trainers/data_adapters/data_adapter_utils.py, keras/src/trainers/data_adapters/grain_dataset_adapter.py, keras/src/trainers/data_adapters/grain_dataset_adapter_test.py, keras/src/trainers/data_adapters/tf_dataset_adapter.py, keras/src/trainers/data_adapters/tf_dataset_adapter_test.py, keras/src/trainers/data_adapters/torch_data_loader_adapter.py, keras/src/trainers/data_adapters/torch_data_loader_adapter_test.py, keras/src/trainers/trainer_test.py, requirements-common.txt
This PR adds a new `GrainDatasetAdapter`.
With this PR, we can now pass a `grain.MapDataset`, `grain.IterDataset`, or `grain.DataLoader` (with `worker_count >= 0`) into `Model.fit`, `Model.predict`, and `Model.evaluate`.
Thanks to @mattdangerw for the detailed doc on this proposal!
We propose gradually switching Keras default mode of preprocessing from [tf.data](https://www.tensorflow.org/guide/data) to [PyGrain](https://github.com/google/grain). We want the following:
1. A uniform preprocessing experience across backends. Write preprocessing once, switch backends seamlessly. Have the option, but not the requirement, to use backend specific solutions (e.g. torch data loaders).
2. Minimal dependencies. We should not depend on the TensorFlow binary (which is huge) or TensorflowText (which …
=> Add Grain integration.

keras/src/backend/openvino/core.py
@rkazants  
@fchollet  
I've noticed that this test (and several similar ones) pass on all backends **except OpenVINO**:  
https://github.com/keras-team/keras-hub/blob/master/keras_hub/src/layers/preprocessing/masked_lm_mask_generator_test.py#L46-L59
After investigating, I found that the following minimal example works correctly on `TensorFlow`, `JAX`, and `Torch` backends, but fails with `OpenVINO`:
```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
os.environ["KERAS_BACKEND"] = "openvino"
tensor = np.array([[1, 2, 3], [4, 5, 6]], dtype="float32")
tensor = ops.convert_to_tensor(tensor)
print(np.array(tensor, dtype="int32"))  # Works on other backends, fails here for OpenVINO
```
```
(env) …
```
=> [OpenVINO backend] fix numpy conversions

keras/src/backend/openvino/numpy.py
@rkazants 
@fchollet 
This test fails due to passing tuple to transpose:
https://github.com/keras-team/keras-hub/blob/master/keras_hub/src/layers/modeling/rotary_embedding_test.py#L88-L98
=> [OpenVINO backend] fix_transpose

keras/src/backend/openvino/core.py
@rkazants 
These tests fails due to passing lists and tuples:
https://github.com/keras-team/keras-hub/blob/master/keras_hub/src/layers/modeling/rotary_embedding_test.py#L88-L98
https://github.com/keras-team/keras-hub/blob/master/keras_hub/src/layers/modeling/rotary_embedding_test.py#L110-L157
https://github.com/keras-team/keras-hub/blob/master/keras_hub/src/utils/tensor_utils_test.py#L198-L205
here is a reproducer:
```python
data = ops.convert_to_tensor(np.random.rand(2, 3, 4), dtype="float32")
permuted_data = ops.transpose(data, (0, 2, 1))
print(ops.convert_to_numpy(permuted_data))
```
=> [OpenVINO backend] add supporting for lists and tuples in get_ov_output

keras/src/saving/serialization_lib.py, keras/src/utils/torch_utils.py, keras/src/utils/torch_utils_test.py
Fixes : https://github.com/keras-team/keras/issues/19226
The `get_config` method of `TorchModuleWrapper` was attempting to decode a byte array as a UTF-8 string, which was causing an error.
=> fix torch module wrapper serialization error

keras/src/backend/jax/nn.py
Fix #21507
This PR addresses the issue by using `None` for kwargs if not specified in `_can_use_flash_attention`.
Hopefully, this change will make the impl more robust.
=> Fix `_can_use_flash_attention`.

keras/src/layers/reshaping/up_sampling2d.py, keras/src/layers/reshaping/up_sampling2d_test.py
The current approach transforms the tensor to channels_last, before passing it in ops.image.resize, which has been defined as channels_first if keras.backend.set_image_data_format has been called on channelsfirst in the user's code. This creates a bug, a passed in tensor [16, 3, 224, 224] will return as shape [16, 448, 224, 448] instead of [16, 3, 448, 448]. Setting the data_format as the expected channels_last fixes that issue.
I changed the unit tests to integrate keras.backend.set_image_data_format, also I noticed 
layer = layers.UpSampling2D(
size=(length_row, length_col),
data_format=data_format,
)
Inside test_upsampling_2d_bilinear, wasn't using interpolation="bilinear", so I corrected that too
Closes #21401.
=> Fix: UpSampling2D bilinear set_image_data_format(channels_first) bug

keras/src/backend/openvino/core.py
@fchollet
I found out that `OpenVINO` backend handles some Tensors incorrectly:
Example:
https://github.com/keras-team/keras-hub/blob/master/keras_hub/src/utils/tensor_utils.py#L161
When `x=tf.Tensor`, it returns `ov.Tensor`, which is incompatible with keras ops
I took torch approach to handle that:
https://github.com/keras-team/keras/blob/master/keras/src/backend/torch/core.py#L219-L221
Additionally, there are some missing `f`'s in `__getitem__`, I added them.
=> [OpenVINO backend] fix __getitem__ and convert_to_tensor issues

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Adds keras.ops.isneginf, which checks whether each element in the input tensor is negative infinity.
Supported across NumPy, TensorFlow, PyTorch, and JAX backends. Not supported on OpenVINO.
=> Implement isneginf function in keras.ops

keras/src/backend/jax/distribution_lib.py, keras/src/backend/torch/core.py, keras/src/layers/preprocessing/image_preprocessing/resizing_test.py, keras/src/layers/preprocessing/rescaling_test.py, keras/src/layers/preprocessing/tf_data_layer.py, keras/src/utils/backend_utils.py
This PR enhances `TFDataLayer` to detect whether it is part of a Grain data pipeline. If so, `TFDataLayer` will force computation and data placement on the CPU.
`test_grain_compatibility` has been added in `Rescaling` and `Resizing` to verify that the output device is CPU in GPU tests.
A demo colab:
https://colab.research.google.com/drive/13RNE_KTbc13Shp5c1uIKzCbo-Ztfe5Ik?usp=sharing
Results:
|`worker_count`|Best Step Speed|
|-|-|
|0 (single worker)|49 ms/step|
|2|17 ms/step|
cc @divyashreepathihalli @mattdangerw
=> Force computation and data placement on the CPU when using a Grain data pipeline.

keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
I added support for the assume_unique and invert arguments to the isin method in keras.ops.
=> Add assume_unique and invert arguments to keras.ops.isin

keras/src/trainers/trainer.py
This commit improves the documentation for `evaluate()` when used with compiled metrics in Keras 3.  The existing documentation can be imprecise because `model.metrics_names` does not always provide a complete list of the values returned by `evaluate()`.
[colab gist ](https://colab.sandbox.google.com/gist/sonali-kumari1/9d8548135711679d9d7730d53f24b2f4/-21487.ipynb)
Fixes : [#21487](https://github.com/keras-team/keras/issues/21487)
=> docs: Keras 3 evaluate() and compiled metrics clarification

keras/src/backend/jax/nn.py
What do you think about logging of exceptions, instead of hiding them? + There is an example of such hidden exception when head_shards and q_seq_shards were just not initialized because get_dist()==None.
And despite hardware supports flash attention - this code silently falls back to the standard with O(N^2) memory.
=> It worth not hiding exceptions

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/linalg/__init__.py, keras/api/ops/__init__.py, keras/api/ops/linalg/__init__.py, keras/src/backend/jax/linalg.py, keras/src/backend/numpy/linalg.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/linalg.py, keras/src/backend/tensorflow/linalg.py, keras/src/backend/torch/linalg.py, keras/src/ops/linalg.py, keras/src/ops/linalg_test.py
The Cholesky inverse is a fast and numerically stable algorithm for calculating the inverse of a special type of matrix: one that is symmetric and positive-definite.
Instead of calculating the inverse directly, this method first breaks the matrix down into simpler components using Cholesky decomposition.  This approach is generally more efficient and less prone to floating-point errors than a general-purpose inversion method.
Its numerical stability makes it a key component in advanced machine learning algorithms like GPTQ quantisation, where it is used to efficiently compute the inverse of Hessian matrices for layer-wise weight compression.
=> Added cholesky inverse operation to all the backends

keras/src/utils/torch_utils.py, keras/src/utils/torch_utils_test.py
Raise an exception and explain the user about the risks.
=> Disable `torch.load` in `TorchModuleWrapper` when in safe mode.

keras/src/backend/jax/nn.py
from cl/794615827
"_Keras is the only user of a deprecated JAX api (jax_default_dtype_bits) for electing float32 default dtypes. This API will be removed in an upcoming JAX release.
A recent JAX change to default dtype handling if that flag is set broke a Keras test ([cl/794553125](http://cl/794553125)). Since the behavior that Keras is relying on is deprecated it is probably best to update Keras not to depend on that default dtype handling in the first place in the test that broke (ctc_loss)._"
=> [JAX] Fix breakage due to default dtype handling in ctc_loss.

keras/src/saving/serialization_lib.py
There is a confusing case when a user has decorated their class or function with `@keras.saving.register_keras_serializable()`, but gets the error message: "Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()`". This happens if the decorated function or class has not been imported/loaded and the decorator has not been run.
This augments the error message to explain this case.
=> Improve deserialization error about `@register_keras_serializable`.

keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/ops/core.py, keras/src/ops/core_test.py
All ops that take tensors as inputs are in scope for serialization. They get serialized if they appear as part of a functional model.
The `VectorizedMap` op class needs a custom `get_config()` and `from_config()` to handle the `function` parameter, which is not a simple type. The fallback `get_config` logic only handles simple types.
Note that some other ops will need a similar change, which will come in a separate PR because it requires a another change.
=> Make `vectorized_map` op serializable.

keras/src/layers/core/lambda_layer.py, keras/src/legacy/saving/legacy_h5_format.py, keras/src/legacy/saving/legacy_h5_format_test.py, keras/src/legacy/saving/saving_utils.py, keras/src/legacy/saving/serialization.py, keras/src/saving/saving_api.py, keras/src/saving/saving_lib_test.py, keras/src/saving/serialization_lib.py, keras/src/saving/serialization_lib_test.py, keras/src/utils/torch_utils.py
Also:
- removed no-op renaming code in legacy saving
- uncommented unit tests in `serialization_lib_test.py`
- made various error messages related to `safe_mode` more consistent
=> Propagate `safe_mode` flag to legacy h5 loading code.

keras/src/backend/tensorflow/trainer.py, keras/src/models/model_test.py, keras/src/trainers/data_adapters/array_data_adapter.py, keras/src/trainers/data_adapters/data_adapter_utils.py, keras/src/trainers/data_adapters/generator_data_adapter.py, keras/src/trainers/data_adapters/grain_dataset_adapter.py, keras/src/trainers/data_adapters/tf_dataset_adapter.py, keras/src/trainers/data_adapters/torch_data_loader_adapter.py, keras/src/tree/dmtree_impl.py, keras/src/tree/optree_impl.py, keras/src/tree/tree_api.py
Here is an example of a model with 2 inputs, the second one being optional:
```python
class OptionalInputLayer(layers.Layer):
def __init__(self):
super().__init__()
self.dense = layers.Dense(2)
def call(self, x, y=None):
z = x if y is None else x + y
return self.dense(z)
def compute_output_shape(self, x_shape):
return x_shape
i1 = Input((2,), name="input1")
i2 = Input((2,), name="input2", optional=True)
outputs = OptionalInputLayer()(i1, i2)
model = Model({"input1": i1, "input2": i2}, outputs)
```
With this definition, the model can be called in Jax/TF/Torch without issue, even when input2 is None:
```python
model({"input1": np.ones((2, 2)), "input2": None})  # WORKS
model.predict_on_batch({"input1": np.ones((2, 2)), "input2": None})  # WORKS AS WELL
```
It is even possible to train **on …
=> Fix support for optional inputs in model.fit

keras/src/backend/tensorflow/rnn.py, keras/src/layers/core/lambda_layer.py, keras/src/layers/rnn/gru_test.py, keras/src/legacy/saving/legacy_h5_format.py, keras/src/legacy/saving/legacy_h5_format_test.py, keras/src/legacy/saving/saving_utils.py, keras/src/legacy/saving/serialization.py, keras/src/saving/saving_api.py, keras/src/saving/saving_lib_test.py, keras/src/saving/serialization_lib.py, keras/src/saving/serialization_lib_test.py, keras/src/utils/torch_utils.py, keras/src/utils/torch_utils_test.py, keras/src/version.py
Cherrypicks of :
https://github.com/keras-team/keras/pull/21575
https://github.com/keras-team/keras/pull/21602
https://github.com/keras-team/keras/pull/21603
=> Version bump to 3.11.3

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Adds keras.ops.hypot, which computes the element-wise hypotenuse of right triangles given two tensor inputs (x1 and x2).
Equivalent to computing sqrt(x1**2 + x2**2) with broadcasting support.
Supported across NumPy, TensorFlow, PyTorch, and JAX backends.
Not supported on OpenVINO.
=> Implement hypot function in keras.ops

conftest.py, keras/src/backend/common/dtypes.py, keras/src/backend/common/dtypes_test.py, keras/src/backend/common/variables_test.py, keras/src/backend/numpy/numpy.py, keras/src/backend/torch/nn.py, keras/src/constraints/constraints.py, keras/src/initializers/constant_initializers.py, keras/src/initializers/constant_initializers_test.py, keras/src/layers/preprocessing/stft_spectrogram_test.py, keras/src/ops/core_test.py, keras/src/ops/math_test.py, keras/src/ops/nn_test.py, keras/src/ops/numpy_test.py, keras/src/optimizers/adam_test.py, keras/src/optimizers/adamax_test.py, keras/src/optimizers/adamw_test.py, keras/src/optimizers/lamb_test.py, keras/src/optimizers/nadam_test.py, keras/src/optimizers/schedules/learning_rate_schedule.py, keras/src/random/random_test.py
This PR removes the usage of `JAX_DEFAULT_DTYPE_BITS=32` which is considered deprecated in JAX.
To reflect this change, the 64-bit dtype tests have also been removed.
TODO:
We might need a flag to enable 64-bit dtypes when using `backend.result_type`.
=> Remove the usage of `JAX_DEFAULT_DTYPE_BITS` and the tests for 64-bit dtypes.

keras/src/layers/preprocessing/integer_lookup.py, keras/src/layers/preprocessing/integer_lookup_test.py
Well, now that there's a brief pause before the next KerasHub project, it's core Keras time again :)
This PR fixes a documentation mismatch in `IntegerLookup` where the `one_hot` output mode was incorrectly described as only supporting rank-2 inputs. In reality, the layer supports arbitrary input ranks with `output_shape = input_shape + (vocabulary_size,)`. Also, let's add a few additional tests to clarify this behavior and ensure good test coverage.
Closes #21564
=> fix(layers): Fix IntegerLookup docstring output shape documentation and add test coverage

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/numpy/__init__.py, keras/api/ops/__init__.py, keras/api/ops/numpy/__init__.py, keras/src/backend/jax/numpy.py, keras/src/backend/numpy/numpy.py, keras/src/backend/openvino/excluded_concrete_tests.txt, keras/src/backend/openvino/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Adds keras.ops.gcd, which computes the element-wise greatest common divisor of two tensor inputs (x1 and x2).
Equivalent to applying the integer gcd operation with broadcasting support.
Supported across NumPy, TensorFlow, PyTorch, and JAX backends.
Not supported on OpenVINO.
=> Implement gcd function in keras.ops

keras/src/ops/operation.py, keras/src/ops/operation_test.py
Dear Keras team,
I'm a co-developer of the [BayesFlow](https://github.com/bayesflow-org/BayesFlow) library. We are currently facing the challenge that we want to be able to adapt the defaults of our networks when we find better configurations, but do so without breaking model loading for models that were saved to disk with the old defaults. We currently use the auto-config functionality to keep our code simple, and ideally we would like to continue to do so. Our problem is the following:
The current auto-config implementation only stores the supplied arguments, but not the values of the optional arguments of the constructor. As a consequence, loading a model fails when the default value of an optional argument has changed, even when the rest of the code of the model remains unchanged. …
=> Store defaults of optional arguments in auto-config

keras/src/layers/merging/concatenate.py, keras/src/layers/merging/merging_test.py
We were trying to grab use a symbolic input shape as a fixed broadcast shape. Instead we need to capture the input as a input node who's shape should be used to broadcast at execution time on real input tensors.
Fixes #21581
=> Fix issue with concatenate, masking and symbolic inputs

keras/src/backend/numpy/numpy.py, keras/src/backend/tensorflow/numpy.py, keras/src/backend/torch/numpy.py, keras/src/ops/numpy.py, keras/src/ops/numpy_test.py
Fixes https://github.com/keras-team/keras/issues/21465
Replaces https://github.com/keras-team/keras/pull/21472
=> Allow `searchsorted` to take a dynamically sized tensor.

keras/src/ops/operation_utils.py, keras/src/ops/operation_utils_test.py
Pull request to fix issue #21648
=> fix: use canonicalize_axis function in reduce_shape function

keras/src/export/onnx.py, keras/src/export/onnx_test.py
Fixes #21637 
Currently, when exporting a Keras model with the Torch backend to ONNX, the provided InputSpec.name is ignored. Instead, inputs are saved as generic names such as args_0, which makes exported models harder to use and integrate with downstream pipelines.
This PR updates the Torch backend export logic to properly propagate InputSpec.name into torch.onnx.export via the input_names argument. If a name is not provided, it gracefully falls back to the existing default (input_i). 
Example
```
spec = [keras.InputSpec(name="input", shape=(1, 10, 16), dtype="float32")]
model.export("test.onnx", format="onnx", input_signature=spec)
```
Before:
ONNX model input name → args_0
After:
ONNX model input name → input
Please let me know what else is needed on this..
=> Fix Torch ONNX export not respecting InputSpec.name

keras/src/backend/common/variables.py, keras/src/backend/common/variables_test.py
Variable paths do not represent a filesystem path and should not be OS dependent, they should always use "/" as a separator.
This reverts https://github.com/keras-team/keras/pull/21343 just for variables.
=> Do not use `os.path.join` for variable paths.

keras/src/ops/operation.py
Operation and layer names do not represent a filesystem path and should not be OS dependent. Namescope paths always use "/" as a separator, which is what we should be looking for.
This reverts https://github.com/keras-team/keras/pull/21343 just for `Operation`.
Note that [the unit test](https://github.com/keras-team/keras/blob/master/keras/src/ops/operation_test.py#L331) was correct. Simply, we never run it on Windows, which is why this was not caught.
=> Do not use `os.path.sep` to detect `/` in names.

keras/src/backend/common/variables.py, keras/src/backend/jax/core.py, keras/src/backend/tests/compute_output_spec_test.py
Previously, with the JAX backend, when tracing in `backend.compute_output_spec`, we would replace the `None` dimensions with 83 then 89 and infer dynamic dimensions in the output by finding the dimensions which changed.
JAX has a mechanism for tracing with dynamic dimensions, which has been exposed publicly for about a year. While the `_DimExpr` class itself is not public, one can create instances of it by using `jax.export.symbolic_shape()`.
Also replaced `jax.make_jaxpr` with `jax.eval_shape`.
Not strictly. Some dimensions in some contexts will now be `_DimExpr` instead of ints. But:
- You can do math on `_DimExpr`, which makes it seamless, you don't even see you're not handling ints.
- The export to TF workflow already used `_DimExpr`, so it's not completely new. In fact there was …
=> Use JAX DimExpr for dynamic shapes in `compute_output_spec`.

guides/writing_your_own_callbacks.py
When running tests under `guides`, I noticed `writing_your_own_callbacks.py` failing with error:
```
AttributeError: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.` exception
```
As `numpy` has been released to 2.3.3, raising this small fix to make `writing_your_own_callbacks.py` able to run along with latest `numpy` version.
The change has been verified against `keras=3.11.3` version.
=> Fix test failure in guides writing_your_own_callbacks.py

keras/src/layers/core/dense.py, keras/src/layers/core/dense_test.py, keras/src/layers/core/einsum_dense.py, keras/src/layers/core/einsum_dense_test.py, keras/src/quantizers/gptq.py, keras/src/quantizers/gptq_core.py, keras/src/quantizers/gptq_test.py, keras/src/quantizers/quantizers.py, keras/src/quantizers/quantizers_test.py
Integrates native 4-bit kernel packing for GPTQ in `Dense` and `EinsumDense`. Kernels are stored packed (two nibbles/byte) and unpacked only at call time. This change also extends `pack_int4`/`unpack_int4` to support both `"int8"` and `"uint8"` paths.
This change reduces the memory requirements for 4-bit integer quantized kernels by half.
1. Build (`_gptq_build`): Allocate `quantized_kernel` with packed columns when `weight_bits==4`
(`units = ceil(cols/2)` for `Dense`; analogous for `EinsumDense`, storing `gptq_unpacked_column_size`).
2. Quantize (`gptq.py`): If 4-bit: `pack_int4(..., axis=0, dtype="uint8")` before assigning.
3. Call (`_gptq_call`): If 4-bit: `unpack_int4(..., axis=0, dtype="uint8")` → `dequantize_with_sz_map(...)` → matmul, Otherwise: dequantize directly.
1. Packing …
=> Adds 4-bit packing support to GPTQ Quantization

keras/src/backend/common/dtypes.py, keras/src/backend/common/dtypes_test.py
Arithmetic operations on 64-bit floating point numbers incorrectly result in 32-bit result dtypes.
The root cause of the issue is that https://github.com/keras-team/keras/pull/21604 forced 64-bit dtypes to be remapped to 32-bit dtypes to be consistent with JAX's dtype promotion rules. However, this breaks behavior for clients depending on `"float64"` types in their code.
=> Fixes float64 type promotion issue

keras/src/trainers/compile_utils.py, keras/src/trainers/compile_utils_test.py
Fixes #21675
In Keras 3.x, compiling models with dict outputs and dict metrics can fail when `CompileMetrics` receives `output_names` that don't match the dict keys of `y_pred`. The builder prefers `output_names` (often internal op names like `['dense', 'dense_1']`) over actual dict keys (e.g., `{'a', 'b'}`), causing `ValueError ("key 'a' does not correspond to any model output"`)
This change ensures that `CompileMetrics.build` resolves output names by preferring dict keys when `y_pred` is a dict, and honors `self.output_names` only if its set matches the dict key set (to preserve stable ordering). It stores the resolved names `(_resolved_output_names`) and uses them consistently for flattening (`_flatten_y`) and metric name prefixing, preserving correct mapping of dict outputs.
Added …
=> Ensures compiled metrics resolve output names correctly

keras/src/callbacks/callback_list.py
A memory leak related to the executor in `CallbackList` was fixed in https://github.com/keras-team/keras/pull/20779
However, calling `Executor.shutdown` within `__del__` is intrisincally unsafe and can create deadlocks because the garbage collector can be called in different contexts.
This new approach uses the `on_train/test/predict_begin` and `on_train/test/predict_end` callbacks to detect when we're done with the executor.
- it counts the number of "begin"s and "end"s to handle the case of `evaluate` within `fit` (we do not shutdown the executor at the end of `evaluate` but instead keep it around for the rest of the training)
- it also handles `CallbackList` being reused between calls to `fit`, `evaluate` or `predict` even though Keras doesn't reuse.
Also renamed `_clear_futures` to …
=> Fix deadlock in `CallbackList`.

keras/src/backend/jax/nn.py, keras/src/backend/jax/numpy.py, keras/src/backend/jax/optimizer.py, keras/src/layers/attention/attention.py, keras/src/layers/layer_test.py, keras/src/layers/normalization/layer_normalization_test.py, keras/src/layers/normalization/rms_normalization_test.py, keras/src/layers/rnn/gru.py, keras/src/layers/rnn/lstm.py, keras/src/layers/rnn/simple_rnn.py, keras/src/ops/core_test.py, keras/src/ops/nn.py, keras/src/optimizers/adafactor.py, keras/src/optimizers/base_optimizer.py, keras/src/optimizers/loss_scale_optimizer.py
JAX uses `__jax_array__` to handle non-JAX types. For instance when doing `a * v` where `a` is a `jax.Array` and `v` is a `keras.Variable`, the `jax.Array.__mul__` implementation calls `v.__jax_array__()` because `v` is not a JAX type.
However, `__jax_array__` did not work in all contexts, and the next version of JAX further restricts which contexts it works in.
The fix rarely involves explictly calling `v.value`. Instead, we rely on existing mechanisms that are already in place to unwrap variables in a lot of contexts:
- ops are always supposed to call `convert_to_tensor` on tensor inputs and `convert_to_tensor` extracts values from variables
- using `keras.ops` instead of native ops (+ - * / < > & etc.) unwraps variables. It is already a best practice to use `keras.ops` instead of …
=> Remove reliance on `__jax_array__` to unwrap variables.

keras/api/_tf_keras/keras/ops/__init__.py, keras/api/_tf_keras/keras/ops/linalg/__init__.py, keras/api/ops/__init__.py, keras/api/ops/linalg/__init__.py, keras/src/backend/jax/linalg.py, keras/src/backend/numpy/linalg.py, keras/src/backend/openvino/linalg.py, keras/src/backend/tensorflow/linalg.py, keras/src/backend/torch/linalg.py, keras/src/ops/linalg.py, keras/src/ops/linalg_test.py
from https://github.com/keras-team/keras/issues/21698
We implemented the jvp operator. Since numpy and OpenVINO as inference frameworks do not have automatic differentiation capabilities, no design is made.
=> Add jvp op

.github/workflows/nightly.yml, keras/src/applications/mobilenet_v3.py
fixes #21508 
Adds `build-python-latest` job in Nightly pipeline
=> Add daily Python 3.13 CPU-only tests to nightly workflow
