README.md
datasets/data_utils.py
models.py

Thanks for the awesome library! This pull request is just for minor typo fixes.

Various typo fixes

---

setup.py

Data directory permission issue. Revert until figured out

Revert "Improved setup.py"

---

keras/models.py

When `fit(shuffle=True)`, shuffle data before each epoch. `True` by default.

Add the shuffle option to Sequential.fit

---

examples/cifar10_cnn.py
keras/optimizers.py

The new formula is compatible with torch.
and might be fix  https://github.com/fchollet/keras/issues/21

Change the learning rate annealing schedule in SGD

---

keras/models.py

as mentioned in previous PR: generalization of predict_proba and predict_classes to number of dimension > 2

generalization to ndim for predict_proba and predict_classes

---

docs/sources/layers/core.md
keras/layers/core.py

TimeSharedDense layer adds a dense layer useful after recurrent layers output with 'return_sequence=True'

added TimeSharedDense layer

---

keras/models.py

Fixed standardize_y to allow using classes that emulate ndarray API and also replaces lists by slices in the case of sequential samples.

Fixed standardize_y to allow using classes that emulate ndarray API

---

keras/models.py

Hey I made what I think is a fix for this (it crashed for me when I tried verbose=2)

fix verbose=2?

---

keras/models.py
test/test_save_weights.py

This PR closes #59. The test is currently a script but will be turned into a function as soon as we start working on the test suite.

Adding save/load weights functionality to model weights

---

docs/sources/initializations.md

Two new initializations: `glorot_uniform` and `he_uniform`

Add new initializations to the docs

---

docs/sources/regularizers.md
keras/regularizers.py

As far as W_regularizer can be equal only to a single function, one should be able to mix L1 and L2 regularizations

Add L1-L2 (ElasticNet) regularization

---

keras/models.py

Moved logic to predict().  Predict_proba now calls predict and warns if output aren't valid probabilities.

Add predict() for Sequential models

---

keras/layers/recurrent.py

Add the printing of the inner activation to the recurrent models that have one

Add inner_activation to get_config

---

docs/mkdocs.yml
docs/sources/utils/visualization.md
keras/utils/dot_utils.py
test/test_dot_utils.py

Hey Francois,
I wrote a small utility to visualize the network structure using `pydot`. For example, the follow code:
```python
ent_lookup = Sequential()
ent_lookup.add(Embedding(10, 2))
ent_lookup.add(Flatten())
rel_lookup = Sequential()
rel_lookup.add(Embedding(20, 2))
rel_lookup.add(Flatten())
word_sequence = Sequential()
word_sequence.add(Embedding(10, 5))
word_sequence.add(GRU(5, 2))
model.add(Merge([word_sequence, ent_lookup, rel_lookup], mode='concat'))
model.add(Activation('relu'))
model.add(Dense(6, 2))
model.add(Activation('softmax'))
g = Grapher()
g.plot(model, 'mymodel.png')
```
generates something like:
Let me know if you want to merge this. If so, I can polish up the code, add comments and docs etc...

Model structure visualization using dot

---

keras/layers/core.py

Need to reference member variables.

fix weight saving and loading

---

docs/sources/layers/core.md

Add documentation for autoencoder models.

add autoencoder to docs

---

keras/layers/convolutional.py

This was the best I could come up with, and its working.

Added 1D Convolution and Pooling

---

examples/lstm_text_generation.py

Both the training features and labels can be represented as numpy
booleans instead of float32 / float64. This enables standard low RAM
machines to scale up to large datasets. Especially important if you
either have many characters (ASCII), long sequences, or a large dataset.

Decrease memory usage of LSTM text gen example

---

docs/sources/initializations.md
keras/initializations.py

as an example of its use, see http://arxiv.org/abs/1504.00941

add identity matrix initialization

---

keras/layers/core.py
tests/manual/check_models.py

Currently attempting to merge overlapping Models fails due to duplicate params and duplicate inputs. This simply avoids duplicate params and inputs in the merge function. This will be necessary to support Fork in the future, and it looks like the functionality is desired for #242.

Fixed Merge handling of overlapping Models.

---

examples/skipgram_word_embeddings.py

create keras directories if needed

---

keras/layers/core.py
keras/layers/embeddings.py

Embedding is supposed to return None for its mask when it's not in
masking mode.

Return None when not masking Embedding.

---

examples/mnist_irnn.py

Updated description and fixed hardcoded batch_size value.

Modified comment and fixed batch_size

---

docs/sources/layers/noise.md
keras/layers/noise.py

Now that the noise module is official I wanted to push my original noise layer addition of Gaussian Dropout, which is multiplicative (rather than additive) Gaussian Noise.

Add GaussianDropout

---

keras/layers/noise.py

Oops, didn't notice this change in API

change Layer to MaskedLayer & sqrt bugfix for GaussianDropout

---

tests/auto/keras/test_normalization.py

Author: Thomas McColgan <thomas.mccolgan@gmail.com>
test config and weight init in batch normalization
add tests for batch normalization

Squashed commit of the following:

---

examples/lstm_text_generation.py

Modify to use proper multinomial sampling, with temperature to control diversity. This seems to generate qualitatively better results and is technically more correct.

Update lstm_text_generation.py with proper multinomial sampling

---

.travis.yml
setup.py

Upgrades to .travis.yml to upgrade to their latest config recommendations.
Also constrains the testing to the tests/ directory to avoid a naming clash with a test_ file in the main package which isn't for automated testing.

Travis upgrade

---

tests/auto/keras/layers/test_core.py
tests/auto/keras/layers/test_recurrent.py

Making progress on the tests slowly but surely. Here is another intermediate PR, brings test coverage to ~60%.

More testing, esp core layers

---

keras/models.py
tests/auto/test_graph_model.py

Added `sample_weights` functionality to `Graph`.  Also added corresponding test.

Added sample_weights to Graph

---

keras/optimizers.py

Per #428
Added `get_state` and `set_state` methods to `Optimizer` for accessing internal states.

Added get_state and set_state method to Optimizer base class.

---

.gitignore

git-ignore tags file

---

examples/babi_rnn.py

Trains two recurrent neural networks based upon a story and a question.
The resulting merged vector is then queried to answer a range of bAbI tasks.
The results are comparable to those for an LSTM model provided in Weston et al.:
"Towards AI-Complete Question Answering: A Set of Prerequisite Toy Tasks"
http://arxiv.org/abs/1502.05698
With default word, sentence, and query vector sizes, the GRU model achieves:
- 52.1% test accuracy on QA1 in 20 epochs (2 seconds per epoch on CPU)
- 37.0% test accuracy on QA2 in 20 epochs (16 seconds per epoch on CPU)
In comparison, the Facebook paper achieves 50% and 20% for the LSTM baseline.
Whilst this is not a task where the RNNs is expected to win, I still feel it provides a good demonstration.
The task utilises multiple features from Keras that do …

Example: Use RNNs to answer questions from bAbi

---

docs/sources/models.md

There was some confusion around whether you could mask individual
timesteps.

Add documentation for time distributed sample weighting

---

keras/layers/convolutional.py

Should downsample on `steps`.
Issue: #490

MaxPooling1D downsample on `steps`

---

keras/models.py

fix: json dump to string

---

keras/utils/theano_utils.py

Added support for ndim_tensor to be used to create vectors. This helps batch normalization when there is a 1D input.

ndim_tensor should support one dimensional tensors.

---

keras/models.py

The same thing that I did for Sequential. I forgot to commit the addition for Graph models in the previous PR.

Added cost masking to Graph models

---

keras/layers/containers.py

Just a little typo. Thanks for maintaining this great library!

Fixed typo in containers.Graph

---

keras/wrappers/scikit_learn.py
tests/manual/check_wrappers.py

Moved fit/predict params to init. Changed test accordingly.

---

keras/callbacks.py
keras/optimizers.py

Fix #536, make what the title says, some pep8 and add LrSetter callback
ToDo:

Make lr and momentum shared_scalars

---

keras/preprocessing/image.py

Fixed missing import for list_pictures.

Fix for issue #636

---

keras/layers/core.py

In a graph model, this would allow having a branch generating a mask to another branch, which can be useful in many models.

Added element-wise multiplication as merge mode

---

tests/auto/keras/layers/test_convolutional.py

This is missing a test of the new CuDNN support in convolution2d ([here](https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L152)). Maybe someone could add that, since I don't have it set up on my machine?

Add tests for convolutional layers

---

keras/layers/containers.py
keras/layers/core.py

This resolves #633 by giving the option to define the concatenation axis as a parameter. I oriented myself on the caffe branch and tested it.
This is my first PR though. So please forgive me eventual formal mistakes...

concatenation axis as param for Merge() and Graph.add_output/node()

---

keras/optimizers.py

fix SGD get_config

---

keras/utils/layer_utils.py

add Masking layer to utils.layer_utils for saving/loading

---

docs/sources/layers/core.md

Added 'mul' mode documentation to Merge.

Updated documentation of Merge layer

---

keras/utils/visualize_util.py

visualize_util.py 
could probably use a better way to keep track of names but still allow directed edges in sequential mode without names

added visualization tools to view Sequential and Graph models

---

keras/layers/containers.py
keras/layers/core.py
tests/auto/test_graph_model.py
tests/auto/test_sequential_model.py

Adds a simple count_params method to the base layer class and the sequential and graph containers.

Parameter counting method for models.

---

keras/callbacks.py

Print "Epoch %d out of %d" instead of just "Epoch %d"

"Epoch %d out of %d"

---

keras/layers/core.py
tests/auto/keras/layers/test_core.py

- Average support for merge
- TimeDistributedMerge

Added averaging support in merge and a TimeDistributedMerge layer

---

keras/optimizers.py

Check this out from Neural Turing Machines paper. Last phrase before Conclusions, almost unnoticed.

Clip value as in Neural Turing Machines paper

---

keras/optimizers.py

the right order is min, max and not max, min as I did before.

Fix order of sings of clipvalue

---

keras/models.py

Fix bug with Graph sample_weights

---

keras/layers/convolutional.py

Fix bug in deserialization of convolutional layers

---

docs/sources/models.md

see https://github.com/fchollet/keras/issues/736

add class_weight/sample_weight parameters to doc #736

---

keras/preprocessing/sequence.py

Fix typo in docstring

---

keras/layers/core.py

Fix in two more layers. Also it would be better if the argument of Reshape was a tuple. What do you think?

Fix Reshape and Permute deserialization

---

keras/models.py

This allows you to do nice things like save JSON models so that they're human
readable & editable. For example:
```py
with open('output.json', 'w') as f:
f.write(model.to_json(indent=4, sort_keys=True))
```

Added **kwargs to to_json and to_yaml.

---

keras/utils/layer_utils.py

Otherwise will fail to load model from config if there is permute layer.

Fix: added "Permute" into imports of line 8: keras/keras/utils/layer_utils.py

---

keras/constraints.py

Fix variable sharing issue with NonNeg constraint.

---

examples/imdb_cnn_lstm.py

Sentiment analysis using recurrent convolutional network. Better and faster results when compared to using either convnet or rnn alone.

Faster and better Sentiment Analysis example. (85% test accuracy in 2 epoches)

---

setup.py

fix setup.py: add six as a requirement

---

keras/callbacks.py

Modification of previous PR https://github.com/fchollet/keras/pull/823. 
Now follows standard API of monitor directions.

Monitor directions #2

---

keras/layers/containers.py

property input_shape for Sequential

---

keras/layers/core.py
tests/auto/test_sequential_model.py

Dot and cos merge modes

---

keras/layers/containers.py

Add dot_axes argument, used by the recently added dot merge mode.

Add dot_axes argument to Graph

---

keras/models.py
keras/utils/layer_utils.py

A small change permitting the use of custom loss functions, custom
optimizers, custom activation functions, and so on.
As discussed in #868.

Change the custom_layer api to support custom_objects

---

keras/layers/core.py

Make the default value of dot_axes more useful.

Fix dot_axis API

---

keras/objectives.py

For Sequence to Sequence Processing

Added Root Mean Square Error

---

keras/utils/layer_utils.py

TimeDistributedMerge needed to be imported into layer_utils, so it could be serialized with to_json, etc

imported TimeDistributedMerge

---

keras/layers/core.py

This is a patch pull request to fix the issue with the dot output shape. 
From https://github.com/fchollet/keras/issues/936 i opted for this fix.

[Patch] Fixing issue with dot output shape 

---

examples/imdb_bidirectional_lstm.py
keras/layers/recurrent.py

I reposted the pull request fixing the issues and removing some clutter

Added backward option for Bidirectional RNN

---

examples/imdb_bidirectional_lstm.py

Show accuracy is not present in Graph model's `fit()`.

Fix imdb bidirectional

---

docs/sources/layers/core.md
keras/layers/core.py
tests/auto/test_sequential_model.py

Lambda layer can be used to implement any arbitrary function layer.

Lambda Layer

---

keras/utils/visualize_util.py

Update visualize_util.py to fix #1036

---

keras/utils/layer_utils.py

Fix load_from_json for models with Lambda layer

---

examples/neural_turing_machine_copy.py
keras/layers/ntm.py

Neural Turing Machine with RNN controller (I believe we are the first to open source such thing) can be used as any other RNN model. 
This model can be used as plug and play, but those interested in attention related stuff should checkout the code. There are probably ways to make this code more clean and efficient. Suggestions are welcome.
A usable version is already available via Seya: https://github.com/EderSantana/seya/blob/master/examples/NTM.ipynb

Neural Turing Machines

---

examples/neural_turing_machine_copy.py

Even more informative docs. Sorry for not doing all the work at once.

Fix typos and even more informative docs.

---

examples/babi_memnn.py

Output of `question_encoder` is 3D : sequence of vectors, not single vector.

Fix misleading comment in babi_memnn.py

---

docs/sources/layers/advanced_activations.md
keras/layers/advanced_activations.py

see [Fast and Accurate Deep Network Learning by Exponential Linear Units (ELUs)](http://arxiv.org/abs/1511.07289)

add exponential linear units activation layer

---

.travis.yml

fix tensorflow travis config

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
tests/keras/backend/test_backends.py

* Rename dim to axis
* Repeat works on any dimension

Update expand_dims and repeat

---

keras/models.py

* fixed validation y size for weighting

---

keras/backend/common.py

convert floatx to ascii

---

docs/sources/models.md

Could be better but it's consistent with the data attribute.

Description of validation_data in the Graph doc

---

docs/sources/backend.md

The comments for all-zeros and all-ones were reversed in backend.md

Fix mistake in backend documentation

---

keras/layers/recurrent.py

With this method, I believe no other recurrent method will need to overwrite
get_output.
Fix #1181

Add get_initial_state method to Recurrent

---

keras/layers/containers.py

Fix add_shared_node()

---

keras/utils/generic_utils.py

Regarding #1203. The functionality remains exactly the same for values greater than 1e-3 and for smaller values the progress bar prints fixed width exponentials.

Increased Progbar precision

---

docs/sources/models.md

Be coherent in the examples of Sequential() and Graph() in terms
of argument ordering.

doc: Preserve the right order for model.compile

---

docs/sources/models.md

Arguments were missing in the documentation.
Pull request is related to https://groups.google.com/forum/#!topic/keras-users/rRdL01zGKi4

Updated doc with the missing arguments in Graph

---

.travis.yml
keras/backend/tensorflow_backend.py
tests/keras/backend/test_backends.py

would love to start using the tensorflow backend with python 3

add tensorflow 0.6.0 testing with python 3.4 to travis

---

docs/sources/layers/recurrent.md

Fix minor typo in recurrent.md

---

keras/callbacks.py

Fix an issue with string formatter inside model checkpointer when breaking string to 2 lines

fix model checkpointer string formatter bug

---

keras/layers/containers.py
keras/layers/core.py
tests/keras/layers/test_call.py
tests/keras/test_models.py
tests/keras/test_normalization.py

In this PR:
* Fix `Siamese` layer
* Fix bugs in `__call__` (required by `Siamese`). This includes:
1)  mask support
2) support for nested models
3) temporarily disable layer cache during `__call__`
* Test for `__call__` with nested model
* **Tests for `Siamese` layer (all 5 APIs - 2 Sequential + 3  Graph)**

Siamese Layer - Complete fix + tests

---

tests/keras/layers/test_core.py

I noticed that some of the core layers are being tested from test_models.py, and the tests actually look more like integration tests. This PR is a start to addressing this.

Some more testing of Siamese layer

---

keras/layers/core.py
keras/layers/normalization.py
tests/keras/layers/test_core.py
tests/keras/test_normalization.py

This pull request fixes the DisconnectedInputError in issues #1275 and #1386

Fixes DisconnectedInputError in #1275 and #1386

---

CONTRIBUTING.md
README.md
keras/optimizers.py
tests/keras/test_optimizers.py

Added adamax optimizer from section 7 of Adam paper.

adamax optimizer

---

keras/models.py

models: Cast the mask to floatX to avoid theano upcasting

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py

Currently,  only 3D input is supported by the rnn function.

RNN : Support for nD data

---

keras/preprocessing/text.py

Many RNN models are char level. I find many examples about RNN write there own code to parse chars into vector. Make `Tokenizer` supports char level would help a lot.

make Tokenizer supports char level

---

keras/constraints.py
tests/keras/layers/test_embeddings.py
tests/keras/test_constraints.py

squashed commits from https://github.com/fchollet/keras/pull/1504

add axis arguments to constraints

---

keras/layers/convolutional.py

Currently, the output shape of Convolution2D is incorrectly documented.

Fix documentation of output shape for Convolution2D

---

keras/preprocessing/image.py

Here only the fix for: every batch of saved images gets overridden by the next batch.

Fixed ImageDataGenerator.flow

---

keras/preprocessing/image.py

https://github.com/fchollet/keras/issues/1551

In ImageDataGenerator.flow shuffle before every epoch

---

docs/templates/preprocessing/image.md
keras/preprocessing/image.py
tests/keras/preprocessing/test_image.py

added the random_shear transformation for images.

added random_shear() to random_transform

---

keras/preprocessing/image.py

replace https://github.com/fchollet/keras/pull/1581

ImageDataGenerator thread safe

---

keras/layers/containers.py
keras/layers/core.py
keras/layers/recurrent.py

Issue[ #1363] (https://github.com/fchollet/keras/issues/1363) is not fixed when stateful RNN is not the first layer or for Graph.

fix issue #1363

---

docs/README.md

I'm new to markdown, so the formatting might be a bit off.
-Dave

added more detail to the building documentation instructions

---

keras/callbacks.py
keras/models.py
tests/keras/test_callbacks.py

This PR closes #1631.
The fit_generator method now adds the `validation_data` attribute to the model so that callbacks could access this data.

Support + tests for fit_generator + tensorboard

---

keras/backend/tensorflow_backend.py
keras/layers/advanced_activations.py
tests/keras/layers/test_advanced_activations.py

Added the recently proposed SReLU activation. 
http://arxiv.org/abs/1512.07030
see issue #1662

SReLU activation

---

keras/models.py

#1582 added a new parameter sample_weight_mode(s) for model, which should be correctly saved and loaded.

Support saving/loading sample_weight_mode(s)

---

keras/callbacks.py

ModelCheckPoint references nonexistent attribute

---

keras/layers/core.py

Handle case `input_shape == None`.(Previous layer is a join `Merge`).

Lambda layer: Bug Fix

---

keras/layers/containers.py

Same change as in #1805, 
I force pushed that and PR was sealed.
Sorry I think I used wrong method for squashing commits.

fix add_shared_node SiameseHead naming

---

examples/babi_rnn.py

bAbI: Doubling the FB LSTM baseline :)

---

keras/layers/core.py

Change Siamese set_weights function to avoid false nb layers value

Update Siamese layer set weights function

---

keras/layers/core.py

There is also a similar line in `embeddings.py` but I don't know if that's the same situation as these or not. If so, just say so and I will change it.

corrected documentation of "weights" argument

---

keras/layers/wrappers.py
keras/utils/layer_utils.py
tests/keras/layers/test_wrappers.py

This is what I had in mind initially. The same principle can also be applied to `Residual`, `Highway`, etc.
@farizrahman4u @lukedeo @EderSantana any feedback?

Add generic TimeDistributed layer.

---

examples/lstm_text_generation.py

Fix error that arises on some systems where python tries to read text as ascii

prevent UnicodeDecodeError

---

keras/backend/__init__.py
keras/backend/common.py

https://github.com/fchollet/keras/issues/2122#issuecomment-202960223
I've only tested this with the Theano backend. Perhaps someone could check TensorFlow support as well?

Support low-precision floats

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
tests/keras/backend/test_backends.py

Noticed this was missing when I needed it.

add sign operation to backends

---

examples/babi_memnn.py
keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
keras/engine/topology.py
tests/keras/backend/test_backends.py
tests/keras/test_sequential_model.py

please see discussion here: #2152

Fix merge_dot tests

---

keras/engine/training.py
keras/models.py
tests/keras/test_sequential_model.py

Here's a PR to address https://github.com/fchollet/keras/issues/2191

add in predict_generator and tests

---

keras/engine/training.py

```test_on_batch``` and ```predict_on_batch``` had the wrong ```uses_learning_phase``` flag

Bug fix to set correct uses_learning_phase flag

---

docs/templates/getting-started/faq.md

and added a note about the functional API.

corrected parameter for learning_phase

---

examples/mnist_sklearn_wrapper.py

I created this example for myself while trying to figure out how to use the sklearn wrapper, and I hope it's useful to others as well. Thanks for any feedback.

Add scikit_learn wrapper example

---

keras/layers/wrappers.py

Just a fix so TimeDistributed doesn't rebuild whatever it was handed.  in reference to #2425

adding built check inside TimeDistributed

---

docs/templates/objectives.md
keras/objectives.py

I also added a clarifying note to the source. This was in response to #2444.

added doc for sparse_categorical_crossentropy

---

docs/autogen.py

https://github.com/fchollet/keras/issues/2454

allows python3.5 to build alongside < 3.5

---

examples/inception_v3.py

@fchollet 
According to Table 1 in [paper](http://arxiv.org/pdf/1512.00567v3.pdf) and [inception_v3](https://github.com/tensorflow/models/blob/master/inception/inception/slim/inception_model.py) implement from TensorFlow, I found that there are some mismatch numbers. Please check it, great thanks for your implement!

correct inception_v3 network

---

keras/optimizers.py

Only SGD have an empty weights list.

add weights for SGD optimizer

---

docs/templates/preprocessing/image.md

Shown default values of arguments in ImageDataGenerator docs

Improved docs of ImageDataGenerator

---

keras/engine/training.py

Adds support for returning each target's loss as a metric. Couldn't find an easy way to do this with metrics without repeating all loss functions, and this is important to us for tuning our loss functions.
Feel free to reject or refactor, I know it's a feature and not a bugfix. Or maybe I'm just dumb and there's an easy way to do this (tried "loss" as the metric in the multi_output dictionary, didn't work, would have had to respecify each function by name)

Added simple support for returning a multitarget loss

---

keras/regularizers.py

this is a pull request for issue #2569. it passes the test_regularizers.py.

fix activity regularizer so it can deal with multiple inbound nodes

---

keras/legacy/models.py

updated for list check bug in predict/predict_on_batch

---

keras/callbacks.py

Ref: https://github.com/fchollet/keras/issues/2570

one line fix for TensorBoard callback issue

---

keras/datasets/cifar.py
keras/wrappers/scikit_learn.py

Revert "remove unused import statement in keras dir"

---

keras/datasets/cifar.py
keras/wrappers/scikit_learn.py

Reapply "remove unused import statement in keras dir"

---

examples/mnist_siamese_graph.py

fixed shape typo

---

examples/mnist_irnn.py

Fixed the year from "7 Apr 201" to "7 Apr 2015".

Fixed typo

---

docs/templates/getting-started/sequential-model-guide.md

I was trying out Keras for the first time right now and I did get an error with `Dense` not being defined.
Fixing the import in this commit, can be a big confusion for beginners.

Added Required Import Line in Docs

---

keras/engine/topology.py

Fix json serialization in merge layer

---

docs/templates/objectives.md
keras/objectives.py
tests/keras/test_objectives.py

As suggested in #2473, here's an implementation for a kullback-leibler divergence objective function as it might be useful for other users.

Added objective: Kullback Leibler Divergence

---

keras/layers/normalization.py

Add mode=2 option to the docstring in BatchNormalization

---

keras/preprocessing/text.py

Fix tf-idf

---

keras/preprocessing/text.py

I'm sorry 😢
Fix 53aaa842ed4cb3b8619032eb6c5deedef32fdbc0
Fix #2974

Fix tf-idf again

---

keras/preprocessing/text.py

Fix TF-IDF in Python 2

---

keras/engine/topology.py

Fix #3008
here is a sample code: https://gist.github.com/henry0312/b14496e1ead8e87db337514e729947f6

Fix json serialization in merge layer with lamda output shape

---

keras/layers/core.py

Fix #2582 
Fix #3001
here is a sample code: https://gist.github.com/henry0312/e183da836489eb9a548a9bd095ec9bbb

Fix json serialization in Lambda layer

---

keras/callbacks.py

For easier gitter integration.

Added optional path argument to RemoteMonitor callback

---

docs/templates/getting-started/sequential-model-guide.md

I replace deprecated class , `TimeDistributedDense` , to `TimeDistributed(Dense(128))`.  Please review it, because I didn't run this program.

Remove deprecated class.

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py

fix docs bugs

---

keras/layers/normalization.py

A one-line fix for issue #1962.

Add masking support to BatchNormalization layer

---

keras/layers/convolutional.py

Not very important, but kinda handy.

Convnet aliases

---

examples/imdb_cnn.py

The imdb_cnn example is broken since keras 1.0.5.
Use the alternative code from https://github.com/fchollet/keras/pull/2320#issuecomment-210076413 to fix it.

Fix broken imdb_cnn example

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
tests/keras/backend/test_backends.py

Need these for a personal project.

Logical ops

---

keras/callbacks.py
keras/engine/topology.py
keras/engine/training.py
keras/models.py
keras/optimizers.py
keras/utils/io_utils.py
tests/test_loss_masking.py
tests/test_loss_weighting.py
tests/test_model_saving.py

Comments welcome.
This introduces the ability to save at the same time:
- the model structure
- the weights
- the training configuration (including the state of the optimizer)
Thus it allows to resume training exactly where you left off, which wasn't previously possible.
We'll need to add a couple callbacks to go with it.

Add model saving functionality

---

docs/templates/preprocessing/image.md

Just a minor fix in the document.

remove keyword for cifar10.load_data

---

keras/engine/topology.py

In Merge layer dot_axes param affects also 'cos' mode

Docs update for Merge layer

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
tests/keras/backend/test_backends.py

Converts integer indices of shape (batch_size, input_length) to its one hot representation of shape (batch_size, input_length, nb_classes).

One hot op

---

keras/callbacks.py

Fix docs for the **save_best_only** param in the ModelCheckpoint callback. 
Fix typo and expand doc for the **mode** param

Fix documentation for ModelCheckpoint callback params

---

keras/backend/theano_backend.py

Avoid all the broadcasting stuff.

Bug fix : squeeze

---

examples/imdb_fasttext.py
keras/optimizers.py

Add the reference paper for the Adagrad optimizer: [Adaptive Subgradient Methods for
Online Learning and Stochastic Optimization](http://www.jmlr.org/papers/volume12/duchi11a/duchi11a.pdf).

Add a reference paper for Adagrad

---

examples/imdb_bidirectional_lstm.py
keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
keras/engine/topology.py
keras/layers/wrappers.py
tests/keras/backend/test_backends.py
tests/keras/layers/test_wrappers.py

```python
model.add(Bidirectional(LSTM(10, return_sequences=True), input_shape=(10, 20)))
model.add(Bidirectional(GRU(5), merge_mode='sum'))
model.add(Activation('sigmoid'))
```

Bidirectional Wrapper

---

examples/mnist_net2net.py

Example based on paper ["Net2Net: Accelerating Learning via Knowledge Transfer"](http://arxiv.org/abs/1511.05641). The results on MNIST showed the advantages of 
1. Net2WiderNet over Random-Padding
2. Net2DeeperNet over Random-Initialization

add example mnist_net2net.py

---

examples/imdb_lstm.py
keras/backend/tensorflow_backend.py
keras/layers/recurrent.py
tests/keras/backend/test_backends.py
tests/keras/engine/test_topology.py

No support for `go_backwards` though. I'll have to look further into how to reverse a dynamic-length sequence in TF.

Add support for dynamic RNNs in TensorFlow.

---

keras/backend/theano_backend.py

by preventing transfer to CPU or copy on the CPU just to get the shape.

Small speed up

---

keras/callbacks.py

Resolves the acute symptoms in https://github.com/fchollet/keras/issues/3357
Doesn't address the question of having a better __repr__ since that is a much wider change.

Write TensorBoard Histograms with Tensor names

---

keras/engine/topology.py
keras/layers/core.py
keras/utils/generic_utils.py

Fix #2814 lambda function serialization and deserialization

---

keras/backend/tensorflow_backend.py
tests/keras/backend/test_backends.py

Try except clause to import ctc_loss in new path on tensorflow 0.10.

CTC import compatibility with tensorflow 0.10

---

keras/metrics.py
tests/keras/test_metrics.py

I needed this for a Kaggle competition and it seemed useful in general so I thought I'd contribute it back.
Let me know if there are changes you'd like before merging it in.

Add Matthews correlation coefficient to metrics

---

keras/engine/topology.py

Dot/cos merge : bug fix

---

examples/neural_doodle.py

Keras neural doodle example based on region-based style transfer.
See #3705 for details.

add examples/neural_doodle.py

---

docs/templates/getting-started/faq.md

Fix a small typo in help files

---

examples/neural_doodle.py

Re-implement the style loss function for better normalization of features from different CNN layers. 
The result is better doodling qualities for some images.
See #3731 for details.

update examples/neural_doodle.py based on issues #3731

---

README.md

Assigned @fchollet as channel admin on Gitter

Added Gitter channel badge

---

tests/keras/layers/test_recurrent.py

This makes tests in this file run ~2x quicker with TF due to clear_session call.

Split multitest in test_recurrent

---

keras/metrics.py
tests/keras/test_metrics.py

Fixes bug in matthews correlation coefficient metric and adds test to make sure it's actually working.

Matthews Correlation fix and test

---

keras/layers/wrappers.py

TF dynamic rnn not working with ndim > 3
#3830

TimeDistributed : unroll RNN when using TF backend

---

keras/callbacks.py
tests/keras/test_callbacks.py

I'm proposing to add two callbacks to keras. If there's interest I'll clean up according to the guidelines, otherwise no hard feelings :-). 
ReduceLROnPlateau:
Monitors a loss and reduces the learning rate with a given factor.
CSVLogger:
Writes logs to a CSV.

ReduceLROnPlateau Callback and CSVLogger Callback

---

examples/variational_autoencoder_deconv.py

@tboquet also, did you get this to work on TF using keras 1.1?

Keras is TF first. Fix TH first example

---

keras/utils/io_utils.py

I don't think there's any real reason for them to be required, though I might be missing something.

Change HDF5Matrix so start and end are optional

---

keras/backend/tensorflow_backend.py

Old access was not working on new version of Tensorflow. This should
work for all versions.

Fix control_flow_ops import

---

examples/README.md

Allowing for easier browsing in github. I, and I think others, would like to be able to know what each example does quickly from the github ui.

Descriptions of examples as a README.md file

---

keras/layers/pooling.py
tests/keras/layers/test_convolutional.py

Add GlobalMaxPooling3D and GlobalAveragePooling3D

---

keras/callbacks.py

Small fix for ReduceLROnPlateau when cooldown=0. See #3991.

ReduceLROnPlateau fix for cooldown=0 (Fixes #3991)

---

keras/backend/theano_backend.py

The Theano backend currently uses the cuDNN batch normalization for inference (`theano.sandbox.cuda.dnn.dnn_batch_normalization_test`), but does not yet use the training function `theano.sandbox.cuda.dnn.dnn_batch_normalization_train`. This training function directly computes the means and variances. Instead, keras.backend's `normalize_batch_in_training` computes the variance and mean on its own.
This patch would let `normalize_batch_in_training` use the cuDNN training function, similar to what `batch_normalization` already does.
A simple benchmark suggests that using the cuDNN BN training function can be much faster:
```
Without dnn_batch_normalization_train:
Time per iteration: 435.557 ms
With dnn_batch_normalization_train:
Time per iteration: 357.126 ms
```
To check the implementation …

Use Theano's cuDNN batch normalization for training

---

docs/templates/getting-started/sequential-model-guide.md
keras/engine/training.py
tests/keras/engine/test_training.py

Added ability to return more than one metric from a function

---

keras/backend/theano_backend.py

This changes the `conv3d` function in the Theano backend to use Theano's new `theano.tensor.nnet.conv3d` wrapper function (similar to `conv2d`). This will be optimised to use cuDNN, so it should be preferable to the current implementation.

Use Theano's new theano.nnet.conv3d interface

---

examples/image_ocr.py

Python 3 support of image_ocr.py

---

keras/backend/theano_backend.py

In the current Theano master, there is now a `pool_3d` that can replace the two calls to `pool_2d`. The new function will also optimize to a call to cuDNN's 3D pooling implementation.
This patch uses `pool_3d` if it is available, but keeps the stacked `pool_2d` implementation for compatibility with older Theano versions.

Use Theano's pool_3d function

---

keras/engine/training.py
keras/models.py

Two small fixes for Python 3. I ran into those issues by playing around with the seq2seq library.
The problems can be easily reproduced by running [the test script](https://github.com/farizrahman4u/seq2seq/blob/master/tests/test.py) of seq2seq. Those error can also arise from other usages.
I hope it's okay to directly open a pull request without reporting an issue first.

Fixes for Python 3

---

keras/callbacks.py
tests/keras/test_callbacks.py

Fixes issue: https://github.com/fchollet/keras/issues/4048

Bug fix in TensorBoard callback and corresponding test

---

keras/engine/training.py
keras/models.py

Took me some time to figure this out because I read only the doc of the sequential API!

Enhance doc about usage of sample weights in validation data tuple

---

keras/callbacks.py

Added a new parameter called `min_delta` to the `EarlyStopping` callback.
This will allow for EarlyStopping to kick in, when only minor improvements are observed to the monitored quantity. For example, when the `val_acc` only improves from `0.9501` to `0.9502`, if `min_delta=0.001, we can cause `EarlyStopping` to kick in and stop the training.
I have kept the default value to 0, to maintain existing behavior in any place it might be used.

Additional parameter to customize EarlyStopping

---

docs/autogen.py
docs/mkdocs.yml
keras/utils/data_utils.py
keras/utils/layer_utils.py
keras/utils/np_utils.py

Add more util docs

---

examples/variational_autoencoder.py
examples/variational_autoencoder_deconv.py

In discussion with Amar Shah @amarshah.
The loss/negative lower bound is now correct with this fix.

changed VAE sampling variance to 1

---

keras/backend/tensorflow_backend.py
keras/engine/training.py

Bug fix when target is a SparseTensor.
Check for sparsity when creating target placeholder.
Remove shape argument when creating sparse placeholder.

Bug fix when target is a SparseTensor.

---

keras/backend/tensorflow_backend.py

Fix for issue #3965

---

.travis.yml

Updated Travis TensorFlow to 0.11.0.
I need this for other pull requests.

Update Travis TensorFlow to 0.11.0

---

keras/layers/recurrent.py
tests/keras/layers/test_recurrent.py
tests/keras/layers/test_wrappers.py

Please see https://github.com/fchollet/keras/issues/4421

Bug fix of Bidirectional(LSTM(..., stateful=True))

---

keras/engine/training.py
tests/keras/engine/test_training.py

Previously check was expecting target to alway be two dimensional.

Check all output dimensions for compatibility in training

---

docs/autogen.py
keras/engine/topology.py
keras/layers/core.py
tests/keras/layers/test_core.py

Removing the requested lines from pull #4133

Finishing Colincsl's SpatialDropout1D

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
tests/keras/backend/test_backends.py

Hi, this is in reference to #4434 .
Tell me if it needs anything more. I believe K.rnn is really unintuitive to use for simple maps and folds if it can even be used.

Add map, foldl, foldr to the backend

---

keras/metrics.py

set the default value of beta=1

def fbeta_score(y_true, y_pred, beta=1)

---

keras/preprocessing/image.py

Used when I tried to use generator for fine tuning pre-trained model.
I believe it might help in many more use cases.
another approach will be to use this function instead of standardize but I think this is better.

Adding preprocess function to ImageDataGenerator

---

keras/backend/common.py

Documentation - Add # Argument # Return # Example in backend/common.py

---

keras/callbacks.py

This PR replaces old deprecated tensorflow API calls by the  new renamed functions calls.

Replaced old tensorboard calls by calls compatible with tensorflow 0.12

---

keras/callbacks.py
tests/keras/test_callbacks.py

Discussed in issue #4589 . Went with 'period' since I got no final sanction either way. Can change it to frequency if preferred.

Add a 'period' variable to ModelCheckpoint to save every period epochs

---

keras/layers/convolutional.py

Fix a typo in Cropping3D docs.

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
tests/keras/backend/test_backends.py

Make sure that changes to the global floatx are effectively taken into account by the backend.
Fixes #3891.

Fix backend handling of global floatx

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
keras/layers/advanced_activations.py
tests/keras/layers/test_advanced_activations.py

A general fix for all appropriate activation functions for this issue https://github.com/fchollet/keras/issues/3568
Now with tests included!

Fix issue #3568: allow sharing of activation function parameters along specified axes

---

ISSUE_TEMPLATE.md

Updated ISSUE_TEMPLATE.md to potentially help cut down on the github issues that are just implementation questions. I don't know if it will help, but feel free to merge if this is interesting!

updated the issue template markdown with a bit more information

---

keras/layers/convolutional.py

Regarding #4722. Now cropping 1d/2d/3d works for undefined input shapes.

update croppings (flexible input shape)

---

examples/neural_style_transfer.py

Having the option to pass optional parameters such as iterations, style/content/tv weights would be quite helpful especially when we execute the code automatically from other processes etc. It also helps speed things up when we test and try out various parameter combinations to check which ones give the best results.

Allow to pass optional arguments to style transfer example

---

examples/mnist_siamese_graph.py

Correct me if I am wrong: I think the code in the current example:
```
def compute_accuracy(predictions, labels):
'''Compute classification accuracy with a fixed threshold on distances.
'''
return labels[predictions.ravel() < 0.5].mean()
```
is not accuracy over all the samples, but over samples with negative prediction.

fix a bug in evaluating accuracy

---

keras/backend/tensorflow_backend.py

make tf backend's sparse crossentropy more robust to unknown dimensions.
dynamic rnn issue is not touched.

fix issue #4816

---

keras/layers/advanced_activations.py

Add reference paper for Leaky ReLU

Add References

---

examples/image_ocr.py
examples/imdb_bidirectional_lstm.py
examples/imdb_cnn.py
examples/imdb_lstm.py
examples/lstm_text_generation.py
examples/mnist_hierarchical_rnn.py
examples/mnist_mlp.py
examples/mnist_siamese_graph.py
examples/neural_doodle.py

Remove unused imports and unused local variables in several examples.

Remove unused imports and unused variables

---

keras/layers/advanced_activations.py

Add the function definition of SReLU.
Refine the style of function definitions.

Add Docstring for SReLU; Docstring Style Fix

---

.travis.yml
keras/backend/tensorflow_backend.py
keras/optimizers.py
tests/keras/test_optimizers.py

tensorflow 0.12 fixes

---

keras/callbacks.py

The TensorBoard callback does not currently support the new summary methods in TF 0.12. This PR adds support for these new methods using attribute detection to maintain backwards compatibility.
Further, as noted in #4794, when building Tensorflow from source, the version string contains a `.head` suffix which causes the version to be parsed as a `LegacyVersion` by `parse_version` in Python 3. Since this version always compares as less than `0.12.0`, the check does not pass. I also changed the existing version checks to fix this issue.

Add support for TF 0.12 to TensorBoard callback

---

keras/backend/tensorflow_backend.py

- Specify return types as many as possible.
- Make them more markdown-friendly.

documentation - TF backend (complete)

---

docs/templates/layers/writing-your-own-keras-layers.md

the version tag should be 1.2.0, afaik 1.1.3 doesn't exist
Btw. https://keras.io/layers/writing-your-own-keras-layers/ shows an older version of this page.

corrected version

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
keras/engine/topology.py

Both TensorFlow and Theano support this parameter so it seems convenient to have it in Keras too.

Added dtype parameter to zeros_like and ones_like

---

keras/preprocessing/image.py

Small fix to array_to_img function, it won't change the value of parameter x when set scale=True now.

Small fix to array_to_img function

---

examples/deep_dream.py

The expression of  pictures should be (img_height, img_width, 3) or (3, img_height, img_width), not (img_width, img_height, 3) or (3, img_width, img_height).

Bugfix: Fix issue in deep dream example

---

keras/callbacks.py
tests/keras/test_callbacks.py

CSVLogger callback did not regard separator value and prepended header to existing files although append argument was specified.
Also, added tests to confirm functionality.

Bugfix CSVLogger Callback separator and append parameters, added tests

---

keras/engine/training.py

This is a pull request to address issue #4969 it is my first pull request, apologize if it causes problems, I added an exception much like other exceptions in the code

improve error message for malformed validation arguments in fit

---

keras/layers/advanced_activations.py

Remove ambiguity of `abs` call

change abs to K.abs

---

examples/addition_rnn.py

Adds more explanation. Make the code fit 80 column and intuitive.

Improves code comment and refactoring.

---

keras/backend/tensorflow_backend.py

Hello,
thank you for keras!
When upgrading to TensorFlow 1.0 rc 1, I encountered some errors in keras related to API breaks.
From what I can see, keras usually follows the approach of "try the newest api, if it fails fall back to older", via attribute errors. As this does not work with the rename of tf.concat_v2 to tf.concat (which previously existed but with different semantics), I have introduced a tf_major_version/tf_minor_version and switched to the new API based on tf_major_version >= 1. The alternative would be to catch a type error, but this would seem pretty broad to me.
I have run the tests with both python 2.7 and 3.5 and tensorflow 0.12.1 and tensorflow 1.0.0rc1 (so four times), they seem to pass. I have run the CPU-only tests.
This should solve #5265.
Thank you
Thomas
P.S.: I …

Fix compatibility with tensorflow 1.0rc1

---

keras/constraints.py

Hi,
I have added a new constraint, for constraining the norm of the weights to an interval. In addition, the new constraint has a 'rate' parameter to control how the constraint is enforced.
All current constraints change the weights in a hard way to achieve the desired norm value. For example, consider the unit norm constraint. If we start training a network with random initial weights, the weights will already be rescaled to norm 1 after the first batch is processed. This might get the network stuck at a local minimum, because it moves the weights suddenly in a direction that might be incompatible with the gradient. The tunable 'rate' parameter allows the weights to change in a more predictable way, only doing a fragment of the rescaling required to reach norm 1 after each step. Hard …

add MinMaxNorm constraint

---

docs/templates/getting-started/faq.md

Tired of retyping these definitions.
Expandable so that we can add simple more definitions (like "shape", "symbolic", etc").

FAQ updates

---

keras/utils/io_utils.py

fix typo for load array

---

keras/preprocessing/image.py

The ImageDataGenerator.random_transform() method performs a series of costly operations on CPU which can be avoided if real-time data augmentation is turned off. To achieve this, I refactored the aforementioned method to avoid any unnecessary matrix multiplications.
I tested the patch and it yields a significant speed improvement, especially if your CPUs can't keep up with your GPUs.
Moving PR to Keras-2, original [here](https://github.com/fchollet/keras/pull/5436).

Speed up preprocessing by avoiding unnecessary random transforms.

---

keras/backend/theano_backend.py

Theano parameter update for one hot encoding. 
[gw1] PASSED tests/keras/losses_test.py::test_objective_shapes_2d 
[gw0] PASSED tests/keras/losses_test.py::test_objective_shapes_3d 
tests/keras/losses_test.py::test_cce_one_hot 
[gw0] PASSED tests/keras/losses_test.py::test_cce_one_hot

Theano test case fix: Updated num_classes to nb_class for one hot encoding

---

keras/backend/theano_backend.py
tests/keras/layers/convolutional_test.py

- Maxpooling1D and AveragePooling2D now passes tests with Theano backend
- Also added test cases with different padding modes for average pooling1d

Fixed issues with conv2d in Theano backend

---

keras/backend/theano_backend.py
keras/engine/training.py

- Added some error messages related to dimensions of `sample_weights` in training.py
- Couple of failed tests for Theano, probably not caused by this PR

Added error message + PEP8 Fix

---

examples/imdb_cnn.py
examples/imdb_cnn_lstm.py
examples/lstm_benchmark.py
examples/mnist_acgan.py
examples/mnist_hierarchical_rnn.py
examples/mnist_irnn.py
examples/mnist_siamese_graph.py
examples/mnist_transfer_cnn.py

I got several of the examples fixed up to work with the new API; let me know whether there are any problems

Update several examples to work with the new API

---

keras/layers/merge.py

- All merge layers now pass test with Theano

Fixed dot layer issues with Theano

---

keras/layers/advanced_activations.py

Added broadcasting for `alpha`

Fixed PReLU activation for Theano backend

---

examples/variational_autoencoder.py
examples/variational_autoencoder_deconv.py

Hi!
This is my first PR, so sorry for any mistakes!
I updated the variational autoencoder examples (both MLP and ConvNet version) to the new API.
PEP8 runs without errors here.
Thanks for making keras!
Cheers,
André

Updated VAE examples (MLP and ConvNet) to the new API

---

keras/utils/conv_utils.py

- Added `deconv_length` inference for `full` padding
- `conv2d_transpose` now passing tests

Fixed deconv length inference in conv_utils

---

keras/backend/theano_backend.py

Port to keras-2 of this PR: https://github.com/fchollet/keras/pull/5590

Less theano profile

---

docs/templates/getting-started/sequential-model-guide.md

Add documentation link in sequential model.

---

keras/layers/noise.py

Noise should be multiplicative for GaussianDropout

GaussianDropout Bugfix

---

keras/layers/pooling.py
keras/legacy/interfaces.py
tests/keras/legacy/interface_test.py

Add API conversion interface for MaxPooling1D layer

Add API conversion interface for MaxPooling1D layer

---

keras/layers/pooling.py
keras/legacy/interfaces.py
tests/keras/legacy/interface_test.py

Adapt MaxPooling1D layer conversion interface for both AvgPooling1D and MaxPooling1D

---

keras/layers/advanced_activations.py
keras/legacy/interfaces.py
tests/keras/legacy/interface_test.py

Removed BatchNormalization and changed PReLU legacy support to fit new abstraction function.

Add PReLU API conversion interface.

---

keras/layers/pooling.py
keras/legacy/interfaces.py
tests/keras/legacy/interface_test.py

- update 'generate_legacy_interface' to deal with change of conversions of argument value
- Add API conversion interface for both AvgPooling2D and MaxPooling2D

Add API conversion interface for both AvgPooling2D and MaxPooling2D

---

keras/layers/normalization.py

Fixed picking of the normalized form corresponding to the training phase
from
```python
return K.in_train_phase(normed,
normalize_in_training,
training=training)
```
to
```python
return K.in_train_phase(normalize_in_training,
normed,
training=training)
```

Fix BatchNormalization

---

keras/layers/embeddings.py
keras/legacy/interfaces.py
tests/keras/legacy/interface_test.py

I'm not sure on how to deal with the removed `dropout` kwarg

Add API conversion interface for Embedding layer.

---

keras/layers/convolutional.py
keras/legacy/interfaces.py
tests/keras/legacy/interface_test.py

Also modified generate_legacy_interface to allow value conversions in positional args.

Add UpSampling*D API conversion interface. 

---

keras/layers/core.py
keras/legacy/interfaces.py
tests/keras/legacy/interface_test.py

Lambda layer conversion doesn't do much except make sure all arguments are not positional since a new argument was introduced. I couldn't really come up with a solid way to check this without a try except block, so I didn't add commit any tests in for this layer.

Add SpatialDropout/Lambda API conversion interfaces.

---

docs/autogen.py
docs/mkdocs.yml

The merge import corrected and initializers spelling corrected in mkdocs.yml as per autogen.py

merge layer reference and initializers name corrected

---

docs/templates/getting-started/sequential-model-guide.md

Fix sample codes for keras-2

---

keras/layers/core.py

output was not assigned when if-clause was not entered

Dropout created UnboundLocalError

---

docs/templates/getting-started/faq.md

It wasn't explicitly said anywhere in the docs that HDF5 inputs were supported. Resolves #2674.

Add HDF5 inputs to FAQ

---

docs/templates/getting-started/faq.md
docs/templates/getting-started/sequential-model-guide.md

There were some small mistakes in the docs that could lead to misunderstandings.

fix small inconsistencies in the documentation

---

keras/layers/convolutional.py
keras/layers/local.py
keras/layers/pooling.py

Issue #5845 
Change `(.. width, height..)` to `(..height, width..)`

Docstring fix for Conv, Local, Pooling layers

---

keras/applications/resnet50.py

Fix with fchollet/deep-learning-models#46

Fix ResNet-50 comment

---

docs/templates/preprocessing/image.md
keras/engine/training.py

Previously still `samples_per_epoch` in some doc strings.

Updated fit_generator to steps_per_epoch (Keras 2.0)

---

docs/mkdocs.yml

docs: comment out theme_dir

---

keras/activations.py

Related to https://github.com/fchollet/keras/issues/1169#issuecomment-220265092

Expand softmax for usage in FCNs

---

keras/layers/convolutional.py

fix causal padding dostrings

---

keras/wrappers/scikit_learn.py

As per title, this hopes to fix #5941 .

Fix IndexError in scikit_learn wrapper (#5941)

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
keras/optimizers.py
tests/keras/backend/backend_test.py

This is a Keras 2 port of the PR #3791
Can also close #3792 if this is merged

add cumsum and cumprod ops to backend

---

keras/layers/convolutional.py

Minor typos

---

examples/addition_rnn.py
examples/antirectifier.py
examples/imdb_cnn_lstm.py
examples/imdb_lstm.py
examples/lstm_text_generation.py
examples/mnist_cnn.py
examples/mnist_hierarchical_rnn.py
examples/mnist_irnn.py
examples/mnist_mlp.py
examples/mnist_net2net.py
examples/mnist_siamese_graph.py
examples/mnist_swwae.py
examples/mnist_transfer_cnn.py
examples/pretrained_word_embeddings.py
examples/reuters_mlp.py
examples/stateful_lstm.py

Keep the style clean when calling the model.fit() functions.

Style fix for examples.

---

keras/models.py

Pass custom_objects through to layer deserialization in Sequential

---

keras/layers/merge.py
tests/keras/layers/merge_test.py

```python
a = Input((10, 5))  # batch_size, 10, 5
b = Input((5,))  # batch_size, 5
c = add([a, b])  # batch_size, 10, 5
model = Model([a, b], c)
```

Allow broadcasting in Merge layer

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
tests/keras/backend/backend_test.py

This is the exact same commit as in #5658 . For some reason (probably oversight) it was reverted in the merge at commit 1f87cff. 
For reasons why this commit should be accepted see #5658 again.

Added dtype to map_fn

---

examples/mnist_acgan.py

Looks like eec61d9 changed the stride from 1 to 2.

copy paste error

---

docs/templates/getting-started/faq.md

Added documentation with the location of the Keras directory and configuration file.
https://github.com/fchollet/keras/pull/5882#discussion_r108232111

Keras directory docs (#5882 discussion)

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
keras/layers/normalization.py

Convert python3 `range` to `list`. Similar fixes as in #6060

Python3 support modification

---

keras/utils/layer_utils.py

Num of params should be int
np.sum([]) returns  0.0.
So if one layer has zero parameters the total number of params will be a float.

BugFix: Num of params should be int

---

examples/cifar10_cnn.py

Remove unused variables in cifar10_cnn.py

Remove unused variables in cifar10_cnn.py

---

docs/templates/backend.md
docs/templates/constraints.md
docs/templates/getting-started/sequential-model-guide.md
keras/initializers.py
keras/layers/core.py
keras/layers/local.py
keras/models.py

Hi, I recently review the whole docs and here are some modifications.
And, there are also two things:
- No documents for augment "mask" in Lambda layer.
- There is "convolutional_recurrent.py" in the source code but no corresponding documents for it. Maybe you just forget to add this part in 'autogen.py'?

review the docs

---

docs/templates/preprocessing/image.md

Missing preprocessing_function

Update documentation for ImageDataGenerator

---

docs/templates/applications.md

Minor corrections on the applications documentation to use the new Model API.

DOCS: Updated applications doc to use the new Model API.

---

keras/applications/resnet50.py

I'm an entrepreneur focus on AI applications in real-life business. Decided to go deep into keras and maybe contribute, let this typo fix be the start point :)

Fix doc typo in ResNet50.

---

keras/backend/tensorflow_backend.py
tests/keras/backend/backend_test.py

Bug fix: K.batch_dot(); tf backend

---

examples/variational_autoencoder.py
examples/variational_autoencoder_deconv.py

Hi!
I've implemented the `add_loss` feature in the example for the variational autoencoder (VAE), with both MLP and CNN.
But I'm not sure If I used it correctly, as there is little to no documentation on this feature as of now.
One thing which wonders me is the usage of `zero_loss` in the code, as shown in this [issue](https://github.com/fchollet/keras/issues/5563) (which basically does nothing).
It passes the PEP8 checks, I appreciate any concern towards the idiomatic use of the keras 2.0 API.
For reference, the HN discussion is [here](https://news.ycombinator.com/item?id=13873837).
edit: Fixed a typo in the vae_loss function.
Thanks for your time.
André

Use add_loss in VAE examples

---

keras/models.py

model_fom_config expects a dict... --> model_from_config expects a dict...

typo in model_from_config error flag

---

keras/engine/training.py

The problem fixed in #2842 similarly exists for uses of `fit_generator`. Example code:
```python
train_d = np.random.rand(128, 64)
test_d  = np.random.rand(2, 128, 32)
x = Input(shape=(64, ))
a = Dense(32)(x)
b = Dense(32)(x)
shared_dense = Dense(32, name='shared_dense')
out1 = shared_dense(a)
out2 = shared_dense(b)
model = Model(inputs=x, outputs=[out1, out2])
model.compile(optimizer='rmsprop', loss='mse')
def gen():
while True:
yield (train_d, [test_d[0], test_d[1]])
hist = model.fit_generator(gen(),steps_per_epoch=1,epochs=1)
```
this should display statistics for `shared_dense_loss_1` and `shared_dense_loss_2`, as when using `model.fit`. Currently it only displays `shared_dense_loss`, using the value of what …

Fix Model.fit_generator for multiple outputs with same name.

---

keras/utils/layer_utils.py

Changed line 82 from "# node is node part of the current network" to "# node is not part of the current network"

Corrected a comment in function "print_layer_summary_with_connections" && Fixed issue #6286

---

keras/activations.py

Trying to solve https://github.com/fchollet/keras/issues/6279

add warnings when advanced activations are passed into Activation

---

keras/datasets/imdb.py
keras/datasets/reuters.py

Fix oov_char=None case in IMDB/Reuters datasets

---

.travis.yml
keras/backend/common.py
keras/backend/tensorflow_backend.py
keras/layers/__init__.py
keras/models.py
tests/test_documentation.py

Added a test to enforce doc in the core modules.
I leave legacy behind since it's deprecated and the from_config function since it's only used internally.

Add test for documentation

---

keras/callbacks.py

Handle properly values with str type in CSVLogger #6459

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
keras/engine/training.py

I'm not sure about the integration with TF. This is useful when using Theano profiler. I think it would be great to have that upstream. What do you think?

Add function names to help profiling/printing of function.

---

keras/callbacks.py
tests/keras/test_callbacks.py

Fixes #6364. Also added a test for running tb callback with a convnet, but couldn't run tests as they all fail with `node down: Not properly terminated` message.

Tensorboard: Check weight dimensions better in write_images

---

docs/templates/preprocessing/text.md
keras/preprocessing/text.py

Added `char_level` argument to `Tokenizer` docs

Tokenizer docs patch

---

keras/backend/theano_backend.py

This mimics `nn.l2_normalize` of TensorFlow and makes it numerically more stable.

Changed l2_normalization in theano_backend.py

---

keras/utils/generic_utils.py

fix tuple error message

---

keras/callbacks.py
tests/keras/test_callbacks.py

This is my simple implementation of batch histogram computation.

Added batch histogram computation

---

tests/keras/utils/io_utils_test.py

A test to cover HDF5 Matrix and ensure, fit, predict, and evaluate work correctly with them.

adding io_utils test for hdf5matrix

---

keras/preprocessing/image.py

Fixes [#6612](https://github.com/fchollet/keras/issues/6612)
This PR is an alternative to [PR #6614](https://github.com/fchollet/keras/pull/6614)

PR2: Make epsilon for ZCA parameterizable

---

keras/backend/tensorflow_backend.py

In comment: expended -> expanded

Fix a typo in expand_dims()

---

docs/templates/preprocessing/text.md

Replaced base_filter() with the exact value of default filter

Updated filters in text processing documentation

---

docs/templates/callbacks.md
docs/templates/getting-started/faq.md
docs/templates/preprocessing/image.md
keras/utils/vis_utils.py

And, should I replace `X` to `x` in [FAQ page](https://github.com/fchollet/keras/blob/master/docs/templates/getting-started/faq.md)?
e.g. 
> You can do batch training using `model.train_on_batch(X, y)` and `model.test_on_batch(X, y)`. See the models documentation.

Improve documents

---

examples/imdb_bidirectional_lstm.py

Uniform single quotation marks.

first commit

---

keras/metrics.py
tests/keras/metrics_test.py

This is a follow up PR from [Add top_k_sparse_categorical_accuracy and test code #6830
](https://github.com/fchollet/keras/pull/6830#pullrequestreview-41820587), added rename to the function name.

Add sparse_top_k_categorical_accuracy and test code

---

keras/backend/theano_backend.py

The #6613 is reopened due to the conflict.

Add error message for Conv2DTranspose on Theano

---

keras/utils/vis_utils.py

pydotplus is better supported on windows
For the ease of visualizing models on win-64, python3.x series

added support of pydotplus

---

keras/backend/cntk_backend.py

Update the error messages in cntk with more meaningful content.

update with more meaningful error message for CNTK backend

---

keras/optimizers.py
tests/integration_tests/test_temporal_data_tasks.py

@kracwarlock code from PR #4915
it works, what needs to be done to get it merged?

fixes #3859 clipnorm tensorflow

---

tests/keras/legacy/models_test.py
tests/keras/preprocessing/image_test.py
tests/keras/test_callbacks.py
tests/keras/test_sequential_model.py
tests/keras/utils/data_utils_test.py
tests/keras/utils/io_utils_test.py
tests/test_multiprocessing.py

Use the pytest tmpdir fixture

---

keras/backend/common.py
keras/backend/tensorflow_backend.py

Fixed some descriptions in backend.

Fixed some descriptions in backend

---

keras/__init__.py
keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py
keras/engine/topology.py
keras/layers/core.py
keras/layers/wrappers.py
keras/legacy/layers.py
keras/utils/__init__.py
keras/utils/generic_utils.py
keras/utils/test_utils.py
keras/wrappers/scikit_learn.py
tests/keras/utils/generic_utils_test.py

Revert "Avoid DeprecationWarning from inspect.getargspec"

---

tests/keras/backend/backend_test.py
tests/keras/preprocessing/image_test.py

This PR is to increase test coverage described in "Requests for Contributions" and currently being developed. [This build](https://travis-ci.org/fchollet/keras/builds/244096190) is set as a baseline.

Increase test coverage

---

tests/test_multiprocessing.py

https://github.com/fchollet/keras/blob/master/tests/test_multiprocessing.py#L286-L290

Fix test in multiprocessing

---

keras/engine/training.py
tests/keras/engine/test_training.py

_check_array_lengths properly handles corner cases with None

---

keras/engine/training.py

If there is only one worker there is no risk of duplicated data.

Don't warn of repeated data with one worker

---

keras/layers/merge.py

Because people seem have some problem understanding this new API, I added an example code.
https://github.com/fchollet/keras/issues/3921#issuecomment-308597601

add example in Merge layer - Add()

---

keras/backend/cntk_backend.py
keras/layers/recurrent.py
tests/keras/layers/convolutional_recurrent_test.py
tests/keras/layers/recurrent_test.py

This pull request is for the stateful RNN support in cntk backend, which is missing in the first release.
Also enable the stateful rnn test on cntk backend.

Enable stateful RNN with cntk backend

---

docs/templates/getting-started/functional-api-guide.md

*shrugs* mostly the typo "of top" -> "on top" was bugging me a bit.

Clearer wording in the Shared Layers Section

---

keras/preprocessing/sequence.py

keras.preprocessing.sequences: Re-add seed parameter to skipgrams.

---

examples/cifar10_cnn.py

Add save model, evaluate test data and who small sample of predictions for example. Also, included string labels for predict in order to print to screen.
Ran this locally to confirm runs before PR.

Add save, evaluate and predict functionality for example

---

keras/models.py

Saving using `with` statement instead of manually opening and closing file

Update save_model function

---

keras/callbacks.py
tests/keras/test_callbacks.py

Fixes https://github.com/fchollet/keras/issues/7470

Fix csvlogger on nan

---

keras/backend/tensorflow_backend.py
keras/backend/theano_backend.py

Fix for https://github.com/fchollet/keras/issues/7496

Fix is_keras_tensor documentation

---

keras/backend/cntk_backend.py
keras/layers/core.py
tests/keras/backend/backend_test.py
tests/keras/engine/test_topology.py

This PR replaces `type` with `isinstance` for consistency of type checking.

Update type checking

---

keras/backend/theano_backend.py

https://github.com/fchollet/keras/issues/7512

fix issue #7512

---

keras/backend/cntk_backend.py
tests/keras/backend/backend_test.py

This PR adds batchnorm tests for CNTK.

Add batchnorm tests for CNTK

---

docker/Dockerfile

This pull request is to fix issue #7525 
Update docker file with cntk 2.1 installed.

update docker with cntk 2.1

---

keras/engine/topology.py
tests/keras/engine/test_topology.py

Fixes https://github.com/fchollet/keras/issues/7589

Fix mask for multi output --> multi inputs

---

keras/engine/training.py

grammar fix

---

keras/engine/topology.py
keras/models.py
tests/keras/test_sequential_model.py

Model cloning is similar to calling a model on new inputs, except that it creates new layers (and thus new weights) instead of sharing the weights of the existing layers.
This is made possible of top of existing tensors as well.

Add `clone_model`.

---

keras/preprocessing/text.py
tests/keras/preprocessing/text_test.py

Fix text_to_word_sequence with unicode text

---

tests/keras/applications/imagenet_utils_test.py

Adjusted pull request to achieve 100% coverage on imagenet_utils

Test: checking imagenet utils, achieve 100% coverage

---

keras/engine/topology.py

`input` will never be `list` :)

Fix typo in Layer.add_loss.

---

tests/keras/activations_test.py

Increases the test coverage of activations.py to 100%

Increase activations test coverage to 100%

---

keras/layers/convolutional.py

Found a copy-paste error in the `Cropping3d` documentation.

Fix Cropping3D documentation

---

tests/keras/engine/test_training.py

This test is from https://github.com/fchollet/keras/pull/6928/files#diff-9d57d7c70e0731dcbeaa5c2d20fdc38eR885, and demonstrates one regression when compared to #6928. I'm aware of others but did not want to overwhelm things with too many PRs.

test demonstrating regression in #7645, input tensors

---

keras/engine/topology.py
tests/keras/engine/test_topology.py

Exit process_node if we need to add an unprocessed node

---

keras/backend/tensorflow_backend.py

`lablels` should be `labels` in tensorflow_backend.py

Minor typo fix

---

keras/preprocessing/image.py

.ppm is already supported by PIL

add .ppm support to ImageDataGenerator

---

docs/templates/preprocessing/image.md
keras/preprocessing/image.py

Update for PPM format

---

docs/templates/datasets.md
keras/datasets/__init__.py
keras/datasets/fashion_mnist.py
tests/keras/datasets/test_datasets.py

added fashion-mnist dataset from: github.com/zalandoresearch/fashion-mnist

Fashion mnist dataset

---

keras/backend/tensorflow_backend.py
tests/keras/backend/backend_test.py

use `tf.as_dtype` to convert string to Dtype , see #7819 
+ [x] add unit test.
+ [ ] pass all tests.

tf backend supports bool variable

---

keras/backend/tensorflow_backend.py

To prevent discouraging another newbie due to unverbose documentation.

More verbose docstring for print_tensor

---

keras/engine/topology.py

Currently `conv_utils.convert_kernel()` will be called during weight loading if the runtime backend is different from what's saved in the .h5 weight file. This behavior is correct only before CNTK is introduced. CNTK also (by default) uses correlation in `C.convolution()`, so there's no need to convert the kernel matrices when loading a TF weight file.
This PR fixes the prediction issue of `InceptionV3` and `InceptionResNetV2` with CNTK backend mentioned in #7753 (still not fully functional, see below).
TF:
```
[[('n02504458', 'African_elephant', 0.90738195),
('n01871265', 'tusker', 0.056970455),
('n02504013', 'Indian_elephant', 0.0023501299),
('n03124170', 'cowboy_hat', 0.0002272828),
('n03134739', 'croquet_ball', 0.00017391924)]]
```
TH:
```
[[('n02504458', 'African_elephant', …
```

No need to convert kernel between TF and CNTK in weight loading

---

examples/mnist_siamese_graph.py

Currently it is calculating precision rather than accuracy.

Fix compute_accuracy() in mnist_siamese_graph.py

---

examples/mnist_siamese_graph.py

Correct test accuracy in examples/mnist_siamese_graph.py, and update GPU performance.

Correct test accuracy in mnist_siamese_graph.py

---

keras/utils/data_utils.py

We got some complaints about `on_epoch_end` being required by default. So I made the doc clearer and made it optional.
@joeyearsley

Make on_epoch_end optional

---

.travis.yml

This request is to fix the ci break for cntk.

fix travis failure

---

examples/mnist_siamese_graph.py

Change compute_accuracy() argument order and names for consistency with https://github.com/fchollet/keras/pull/7199 and the rest of this file and other files in example/

Change compute_accuracy() argument order and names

---

keras/utils/generic_utils.py

Before:
16256/17820 [==========================>...] - ETA: 0s
After:
17820/17820 [==============================] - ETA: 0s
Also improve code readability if => elif. No semantics change.

Fix bug where progress indicator doesn't always complete

---

keras/utils/generic_utils.py

```
Before:
- 0s
- 1s
- 2s
After:
- 2s
```

Don't print newline if target is unknown in Progbar.update()

---

keras/utils/generic_utils.py

... as requested in https://github.com/fchollet/keras/pull/6670#issuecomment-302830241. While at it, do some code refactoring and making code identical. There should be no semantics change whatsoever, except one extra flush() where before we relied on '\n', which doesn't work if stdout is not a tty.

Remove self.target=-1 hack

---

examples/mnist_siamese.py

Switch to Model functional API

---

tests/keras/legacy/models_test.py
tests/keras/test_callbacks.py
tests/keras/test_sequential_model.py
tests/keras/wrappers/scikit_learn_test.py

Same as https://github.com/fchollet/keras/pull/8120

Rename num_class => num_classes

---

tests/integration_tests/test_vector_data_tasks.py
tests/keras/legacy/models_test.py
tests/keras/optimizers_test.py
tests/keras/test_callbacks.py
tests/keras/test_sequential_model.py

...and other less-comprehensible stuff. Also remove "," from "Dense(4,)".

Use named constant num_classes instead of literals

---

keras/layers/convolutional.py
tests/keras/layers/convolutional_test.py

Fixes https://github.com/fchollet/keras/issues/8146

Add dilation to SeparableConv2D

---

keras/backend/tensorflow_backend.py

Fixes https://github.com/fchollet/keras/issues/8183

Fix data_format on K.conv1d

---

keras/engine/training.py
keras/models.py

This is a backward-compatible API change (API additions only).

Sync Sequential.compile() with Model.compile()

---

keras/preprocessing/image.py

Normalize pixels uniformly by the image mean and std
Fixes #8205

Fix samplewise normalization in ImageDataGenerator

---

keras/layers/cudnn_recurrent.py
keras/layers/recurrent.py

Fix recently introduced breakage.

Fix cuDNN RNNs

---

keras/layers/merge.py
keras/legacy/layers.py

Reduces graph ops. Made possible by PR https://github.com/fchollet/keras/pull/8250

 Simplify - remove K.cast()

---

examples/mnist_dataset_api.py

Just another MNIST classification example, this time with TF's Dataset API.
This is my first attempt at contributing to an open-source project, so be nice :)

Added TensorFlow Dataset API example.

---

keras/engine/training.py

...plus some collateral Model.fit() docstring fixes

Sync docstring of Model.evaluate() with Model.fit()

---

examples/mnist_acgan.py

See https://github.com/fchollet/keras/pull/8482#issuecomment-344401396 for an example how it looks like now.

acgan: Draw real as well as generated images side-by-side

---

keras/engine/training.py
keras/models.py

...since it doesn't matter if the the samples in "your dataset" are unique or not.

Replace 'unique samples' with 'samples'

---

.travis.yml

based on my similar fix at https://github.com/farizrahman4u/keras-contrib/pull/182

.travis.yml fix mkl errors

---

examples/cifar10_resnet.py

1. Use 3-digit epoch.
2. Add model type to the file name.

Change file name/format of saved models

---

examples/addition_rnn.py

Cosmetic changes to addition_rnn example console output. From & To are below.

addition_rnn example formatting changes

---

keras/engine/topology.py

Input should allow `shape=()` in the event that the final shape of the tensor should be `(batch_size)`

Input should allow shape=()

---

keras/engine/topology.py

Add CNTK to the list of backends and `code` indicators.

Input() docstring fixes

---

keras/backend/tensorflow_backend.py

the previous example code cant get the expected result，it get a ValueError
so i  fix this problem

fix incorrect example code in the def variable

---

keras/utils/data_utils.py

Using a closing context will guarantee that the pool will get cleaned up. It's also a much nicer way of doing it.
Fixes https://github.com/fchollet/keras/issues/8665

Force the pool to close in OrderedEnqueuer

---

docs/templates/why-use-keras.md

Fix typo in why use keras docs

---

.travis.yml
keras/backend/cntk_backend.py
keras/layers/recurrent.py
tests/keras/layers/recurrent_test.py

1. Update with cntk 2.3.1
2. Fix the dropout in recurrent layer.

Integrate with cntk 2.3.1

---

keras/preprocessing/image.py

also replace literals `1e-7` with `K.epsilon()`

Fix potential division by zero and numerical instability

---

keras/preprocessing/image.py

resolves https://github.com/fchollet/keras/issues/7792

Ensure correct usage of zca_whitening in ImageDataGenerator

---

tests/keras/utils/data_utils_test.py

Minor typo correction

---

keras/callbacks.py

Fill keys in CSVLogger before stop_training is checked

---

docs/autogen.py

I fixed the last survivor of the updated links .

updated links to the new github repo

---

examples/lstm_stateful.py

I think this part should be float type annotation.

Fix type annotation

---

keras/preprocessing/image.py

Change shear intensity from radians to degrees

---

docs/templates/applications.md

Add quotation marks to applications.md

Add quotation marks

---

docker/Dockerfile

Based on ContinuumIO/docker-images#49

Add dependency

---

docs/templates/applications.md
keras/applications/__init__.py
keras/applications/densenet.py
keras/applications/imagenet_utils.py
tests/keras/applications/applications_test.py

This PR adds DenseNet121, DenseNet169, DenseNet201, and those test codes.

Add DenseNet models

---

tests/keras/engine/test_training.py

also put `predict()` before `compile()` and change `validation_split` from 0.2 to 0.5 (there are only 2 samples).

Combine test_sparse functions together

---

examples/lstm_text_generation.py

This seems like a good place to use the on_epoch_end callback to print the generated text, instead of explicitly performing iterations with epoch=1.

 Use callback to print generated text in lstm_text_generation example

---

keras/layers/recurrent.py

It appears to be a copy-paste error.

Minor fix to an error message from RNN

---

keras/preprocessing/image.py

Adapted from https://github.com/keras-team/keras/pull/8398

Added examples for fill_mode to ImageDataGenerator docstring

---

keras/engine/training.py

Reopend due to the conflict of #8892. This PR refactors _standardize_input_data to make it faster described in "Requests for Contributions".

Refactor `_standardize_input_data` to make it faster

---

examples/cifar10_resnet.py

1. v1: remove BN from projection (i.e non-identity) residual shortcut connections (line 213)
2. v2: add BN-ReLU after first Conv2D, before splitting into 2 paths and remove first BN-ReLU from the first residual unit (line 257). v2 paper says:
>When using the pre-activation Residual Units (Fig. 4(d)(e) and Fig. 5), we
pay special attention to the first and the last Residual Units of the entire network.
For the first Residual Unit (that follows a stand-alone convolutional layer,
conv1), we adopt the first activation right after conv1 and before splitting into
two paths; 
This change improved ResNet56v2 test accuracy from 92.60% to 93.01%. 
ResNet110v2 test accuracy "changed" from 93.03% to 93.15% (I changed it in the table to mark the fact that I tested it).

cifar10-resnet: fix network topology

---

examples/mnist_denoising_autoencoder.py

Adding the classic denoising autoencoder using MNIST dataset.
Sample output:

Denoising Autoencoder on MNIST

---

tests/keras/applications/applications_test.py

Recent travis errors are very much the same as what I've encountered in [this PR](https://github.com/keras-team/keras/pull/7914#issuecomment-330184920). For example, in [this build](https://travis-ci.org/keras-team/keras/builds/276674041), there were also random memory errors in py3 backend tests and a timeout error in py2.
In the above-mentioned PR, the root cause is a memory leak in CNTK backend. The memory occupied by the application models is not released back to the system after the application tests. This PR implements the same workaround as what've done in the tests for Inception-ResNet v2. The network is created in a subprocess, so the memory will be released once the subprocess is terminated.

Workaround against CNTK memory leak in DenseNet tests

---

keras/engine/topology.py

This PR follows up [one](https://github.com/keras-team/keras/commit/2bf4a17899820f23ff2f6e014cd78b6c8f09f4a7) of the current commits.

Remove print function in signature

---

keras/layers/recurrent.py

This PR addresses errors #8976 and follows up #9006.

Make RNNs generate dropout masks whenever they are called

---

keras/models.py

Add what will raise ValueError.

Update document for ValueError

---

tests/keras/regularizers_test.py

As suggested in #8990 I removed fit calls. 
Here in the regularization tests (the assert is all that is really needed).
The speed gain is going to be very small, but if we can reduce the number of lines in the codebase, It's not a bad thing.

Removed fit call from regularizers tests.

---

examples/cifar10_cnn_tfaugment2d.py

Supply an Augment2D-on-GPU example.
Signed-off-by: CUI Wei <ghostplant@qq.com>

Add a GPU-efficient Augment2D example (TF-only)

---

keras/utils/data_utils.py

Fix PR https://github.com/fchollet/keras/pull/8275 for Python2.

Fix __len__ in CIFAR10Sequence example in Python2

---

keras/layers/wrappers.py
tests/keras/layers/wrappers_test.py

Fix `trainable` setting on wrapper layers.

---

keras/optimizers.py
tests/keras/optimizers_test.py

This should prevent people posting issues with cryptic error messages.

Better error message when there is no gradient defined

---

examples/cifar10_cnn_tfaugment2d.py
keras/backend/cntk_backend.py
keras/backend/tensorflow_backend.py
tests/keras/preprocessing/text_test.py

There are some minor typos on comments and docstring so I decided to fix them.

Fix typos on comments and docstrings

---

docs/templates/why-use-keras.md

It is not OpenGL- but OpenCL- enabled GPUs, right?

Fix a typo

---

keras/wrappers/scikit_learn.py
tests/keras/wrappers/scikit_learn_test.py

Add sample_weight parameter to KerasClassifer

---

examples/mnist_sklearn_wrapper.py

Issue #9286 .Add Activation('relu') for every Dense layer other than the last one.

Fix mnist sklearn wrapper example

---

keras/engine/training.py

Metrics weren't in predict before, I propose that we keep it that way.
Fixes https://github.com/keras-team/keras/issues/9394

remove metrics for predict

---

keras/models.py

Fix an explanation of epoch in fit_generator.

Fix an explanation of epoch

---

keras/preprocessing/image.py
tests/keras/preprocessing/image_test.py

**This is a cleanup of @zhudaoruyi's PR at #8652.**
**All credit goes to him!**

Add random brightness to Image Preprocessing (Code Cleanup)

---

keras/backend/cntk_backend.py
tests/keras/backend/backend_test.py
tests/keras/layers/convolutional_test.py

This PR adds separable conv2d for CNTK. The tests may be conflicted with #9359.

Add separable conv2d for CNTK

---

tests/keras/backend/backend_test.py

This PR cleans up conv backend tests and makes their styles consistent.

Clean up conv backend tests

---

keras/applications/mobilenet.py

I don't think the message is coherent with the if just before and what is written in the documentation.

Corrected misleading error message.

---

keras/engine/training.py
keras/utils/data_utils.py
tests/test_multiprocessing.py

So Travis is not working right (hence the multiple PR) Sorry for that.

Fix sequence bug

---

tests/keras/backend/backend_test.py

This PR replaces `parametrize` with `skipif` in order to reduce test time. Most of the backend tests conduct functionality checking based on whether all the backends give the same outputs, while some backend tests like `test_ctc` do with desired outputs. If that is the case, it is unnecessary to test all backends with `pytest.mark.parametrize`.
For example, the `test_ctc` for `TensorFlow` and `Theano` have been running in the `KERAS_BACKEND=cntk` environment. Currently, such tests have been performed inefficiently.

Replace `parametrize` with `skipif`

---

keras/engine/topology.py

Clairfy the behavior of Container.get_layer

---

examples/cifar10_cnn_capsule.py

Fix https://github.com/keras-team/keras/issues/9519
In accordance to issue 9519 I implemented the missing sum around the margin_loss implementation.

Bug-fix cifar10 capsule missing K.sum() margin_loss

---

examples/addition_rnn.py

Changed "invert the input" to "reverse the input"
"Invert" is misleading, since it's not clear what "inverting" an input means.  "Reverse" is clearly defined for a sequence.  The terminology from the [second paper cited in the comments of the code](http://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf) (cited by the first), is "reverse".

Small terminology change in an LSTM example

---

tests/keras/backend/backend_test.py

This PR makes conv backend tests efficient in order to reduce test time.
I think the `test_rnn` needs to be improved with the same way because it is often seen in the slowest 10 test durations.

Make conv backend tests efficient

---

tests/keras/backend/backend_test.py

This PR makes depthwise conv backend tests efficient in order to reduce test time.

Make depthwise conv backend tests efficient

---

tests/keras/backend/backend_test.py

This PR makes separable conv backend tests efficient in order to reduce test time.

Make separable conv backend tests efficient

---

keras/engine/topology.py
tests/keras/layers/core_test.py

bug fix - run_internal_graph()

---

keras/backend/theano_backend.py

Reference: "Numerical Stability" part @ http://cs231n.github.io/linear-classify/#softmax

Small fix to Theano softmax for numerical stability

---

keras/layers/convolutional.py

Fix the number of arguments on ZeroPadding3D.

Fix the number of arguments

---

keras/callbacks.py
tests/keras/test_callbacks.py

Regarding #9541, and to get your attention :)

Fixed inconsistencies regarding ReduceLROnPlateau

---

keras/preprocessing/sequence.py

Fix a typo in the docstring - :)

Fix Typo in TimeSeriesGenerator DocString

---

keras/backend/tensorflow_backend.py

Typo reported in #9821 .
I'm not 100% sure it's really a typo because english isn't my first language, but I'm pretty sure it is.

Small mistake in the docs.

---

examples/README.md
examples/mnist_dataset_api.py

Updated Dataset API example for TF 1.7 and added it to the examples README file.

Updated example, added to README

---

keras/layers/wrappers.py
tests/keras/layers/wrappers_test.py

This PR fixes the issue raised in #7514.

Fix Bidirectional Regularization

---

pytest.ini

Increase pytest duration from 10 mins to 20 mins

---

.travis.yml

CF https://github.com/keras-team/keras/issues/10100

Revert TF version to 1.7 on Travis CI.
