keras-team/keras

keras/objectives.py
`T.nnet.categorical_crossentropy(np.zeros(N), np.ones(N))` returns `inf`.
I got this issue in `examples/cifar10_cnn.py`.
=> Fix categorical_crossentropy/binary_crossentropy with NaN value

setup.py
- using setuptools if available
- specified required and optional dependencies, as listed in read me. `scipy` could probably be made optional because all of its usages in `np_utils.py` can be replaced with `numpy`, and the remaining usages are all image-related.
=> Improved setup.py

keras/activations.py
Allows softmax activation over tensor3 values. Given output A from this activation, `sum(A[i][j][:])==1.0`
Impetus: Output from RNNs is generally considered of size `(nb_samples, time_steps, values)`. This activation allows for softmax over this tensor3, where the softmax is applied over a vector of size `(values, )` which corresponds to the softmax of one sample at one time step.
Example:
```python
model.add(SimpleRNN(2, 3, return_sequences=True))
model.add(Activation('time_distributed_softmax'))
sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mse', optimizer='sgd')
A = model._predict(np.asarray([[[1,1],[2,2]], [[3,3], [4,4]]]))
print A
print np.sum(A[0][0][:])
```
Yields
```python
[[[ 0.32846826  0.33231813  0.33921361]
[ 0.32311559 …
```
=> Added Time Distributed Softmax to allow softmax activation over 3D inputs

keras/models.py
Fixed a bug wherein the number of batches that was calculated would be too large when `Num_Examples % batch_size == 0`
=> Fixed logic to determine the number of batches per epoch

keras/models.py
Apologies, the `nb_batch` size fix from last time resulted in an unsuitable datatype for the `range` function - I missed that in the tests as I was working in another branch and just happen to notice the `nb_batch` bug.
=> Fixed incorrect datatype in range function from the last commit

docs/sources/initializations.md, keras/initializations.py
This PR adds two new initialization methods:
*    The method from "Understanding the difficulty of training deep feedforward neural networks", Glorot & Bengio, AISTATS 2010. This works very well for sigmoid/tanh activation functions. This is known as the "xavier" initialization in Caffe, where it is the default initialization method for dense layers.
*    The improvements on the above method made by He et. al, which they showed works much better when using ReLU activation functions.
This time, care was taken that everything runs under Py2, and also works with convolutional layers.
=> New initializations

keras/utils/io_utils.py
This class enables one to use slices of datasets in an HDF5 file as matrices for training/testing algorithms in keras.
Usage example:
```
X_train = HDF5Matrix(datapath, 'features', train_start, train_start+n_training_examples, normalizer=normalize_data)
y_train = HDF5Matrix(datapath, 'targets', train_start, train_start+n_training_examples)
```
The arguments are:
`datapath`: path to HDF5 file
`dataset`: name of the dataset in the HDF5 from which to take the data
`start` and `end`: indices to slice the given dataset
`normalizer`: function to be applied to the data coming from the dataset on-the-fly. Can be used for centering/standardizing/scaling data, but cannot change the dimensions of the data in any way.
=> Added helper class to use data in HDF5 datasets

keras/datasets/cifar10.py, keras/datasets/data_utils.py, keras/layers/core.py
This PR fixes two py3 compatibility issues
1. It fixes a float<>integer division problem in the `Flatten` layer (This layer is broken in py3 without this fix)
2. It makes sure that CIFAR10 can be loaded without re-pickling on Python 3: a fix was introduced today to make downloading possible, but the pickle file is still a bit tricky to load in py3. This PR fixes that.
=> Python3 compatibility

keras/models.py
Adding layer configuration info as attributes to the corresponding layer group in the HDF5 file exported by `model.save_weights`. For now this information is ignored when loading weights from a file, but it may be useful for reconstructing a model in case a user loses the corresponding source code.
=> Added layer config info to exported HDF5 file

keras/utils/generic_utils.py
Currently, the Progressbar doesn't play nice within IPython-notebooks ( http://imgur.com/UOyIloR ). Using "\r" instead of  several "\b" works well (both on the shell and within notebooks). I tested it under Linux only, but PyMC's progressbar also uses "\r", so I assume this works on every plattform.
=> Make Progressbar work in IPython notebooks

keras/models.py
Hi,
h5py cannot handle None, so when I call save_weights  on model with default parameters (for example image_shape in Conv) I got error. So I just ignored None values.
=> Fix save_weights in models.py when None

keras/datasets/cifar10.py, keras/datasets/data_utils.py, keras/datasets/reuters.py
Using `os.path.join` to generate paths according to the user's OS (i.e., using `\` as the file path separator on Windows and `/` on POSIX). This was tested on OS X and Windows 8, both with Python 2.7 and Python 3.4.
=> Fixed path concatenation for datasets

keras/layers/advanced_activations.py
This was causing `model.save_weights` to break on models with a PReLU layer, as it does not store `input_shape` as an attribute. We do not need to save it, though, since this is just an activation layer.
=> PReLU layer does not need to dump input_shape as a config parameter

docs/sources/activations.md, docs/sources/constraints.md, docs/sources/optimizers.md, docs/sources/regularizers.md, examples/mnist_nn.py, keras/constraints.py, keras/datasets/mnist.py, keras/layers/advanced_activations.py, keras/layers/convolutional.py, keras/layers/core.py, keras/layers/embeddings.py, keras/layers/normalization.py, keras/layers/recurrent.py, keras/models.py, keras/optimizers.py, keras/regularizers.py, test/test_constraints.py
I've moved the functions to relevant modules which can be used as below. And I've separated the weight and bias regularizers for better clarity, with the defaults being no regularization or constraints.
I don't think it makes sense to have the regularizers and constraints specified by strings, i.e. W_constraint='maxnorm' , since the user will usually want to specify the parameter and it's not clear how to do that with the string convention. It works fine when the defaults are probably fine, as with the initializations. But even in that case, how would one specify the scale for the initialization ```init='normal' ``` if you wanted to change it? The way I have it below seems clearer and easier to work with and is similar to the way the dropout rate is specified. Let me know what you think …
=> Layerwise constraints and regularization

keras/preprocessing/image.py
Fixed conversion between NumPy Array and PIL Image object when input image is grayscale.
Originally,
* (Line 90: `array_to_img`) When NumPy Array `x` with one channel is passed to `array_to_img`, `Image.fromarray(x.astype("uint8"), "L")` raised `ValueError: Too many dimensions: 3 > 2.`.
* (Line 95: `img_to_array`) When grayscale image is passed to `img_to_array`, `x` becomes 2D array and `x = x.transpose(2, 0, 1)` raised `ValueError: axes don't match array` 
* (Line 100: `load_img`) When grayscale image is loaded, but grayscale is set False, this function still returns the grayscale image. This behavior cause a problem when loading multiple images including both color and grayscale images.
=> NumPy Array <-> PIL Image conversion when image is grayscale

examples/kaggle_otto_nn.py
The original file somehow works because `labels` is a global variable :)
=> Fix a typo in the kaggle otto exmaple.

README.md
As the title indicates the README had a missing parenthesis in a python code example.
=> fixed missing parenthesis in README

docs/sources/models.md, keras/models.py
This allows to specify a theano.compile.mode.Mode instance to use, for example to use a MonitorMode
with a post_func to debug nans.
=> Add theano_mode argument to models.compile. 

keras/utils/generic_utils.py
Pad the progress bars so formatting stays when going from 99 to 100, etc.
Behavior before:
900/7228 [==>...........................] - ETA: 226s - loss: 0.4990
1050/7228 [===>..........................] - ETA: 194s - loss: 0.4868
Behavior after:
900/7228 [==>...........................] - ETA: 226s - loss: 0.4990
1050/7228 [===>..........................] - ETA: 194s - loss: 0.4868
=> Pad the progress bar strings

keras/utils/generic_utils.py
When running model.fit with verbose=1 inside screen, the progress bar currently prints out lines that scroll upward on the terminal. For instance, on the following test script:
```
from keras.utils.generic_utils import Progbar
pb = Progbar(target=10, verbose=1)
for i in range(1, 11):
pb.update(i, [('test', i)])
```
The output is:
```
10/10 [==============================] - 0s - test: 5.0000     
me@test:~/tmp/kerastest$ ========>...] - ETA: 0s - test: 5.0000
8/10 [=======================>......] - ETA: 0s - test: 4.0000
7/10 [====================>.........] - ETA: 0s - test: 4.0000
6/10 [=================>............] - ETA: 0s - test: 3.0000
5/10 [==============>...............] - ETA: 0s - test: 3.0000
4/10 [===========>..................] - ETA: 0s - test: 2.0000
3/10 …
```
=> Fix progress bar issue in screen where output clobbered previous output

keras/preprocessing/sequence.py
```sampling_table``` should be looked up with the index from the vocabulary, and not with the positional index from the sequence.
=> Fix sampling table lookup in skipgrams

keras/wrappers/scikit_learn.py, test/test_wrappers.py
Resolves issue #149
Some quick notes/observations:
- After a few design iterations, I opted to use a constructor that accepts a pre-defined (but not yet compiled) Keras model.  I'm reasonably sure this is the most sensible approach, but not 100% sure.  The advantage is that one can still build model definitions using the existing APIs, which are very fluid and expressive.  The disadvantage is that it's not possible to build a model using all default parameters, as one can do with the other scikit-learn estimators (I'm not sure this even makes sense for a neural net though).
- In order to allow meta-estimators such as ensembles to make copies of the base estimator, I'm making a copy of the model definition in the fit method before compilation.  I don't think this will cause any problems, …
=> scikit-learn classifier wrapper

docs/sources/models.md, keras/models.py
A patch for the FIXME (https://github.com/fchollet/keras/blob/df4e3a2d8d2195505ff2c744a37d1ecf467c2e9a/keras/models.py#L368) in the save_weights method.
If overwrite is not changed to True the method will throw an IOError when the file already exists.
=> Overwrite parameter for keras.models.save_weights

keras/layers/core.py, test/test_autoencoder.py
This implementation creates a base autoencoder class that should be inherited for all other implementations of autoencoders. Since we have added a get_hidden() method this can be used later on when we start stacking autoencoders. I.e. we can do something along the lines of:
```python
if isinstance(my_new_stacked_autoencoder_layer, AutoEncoder):
return previous_layer.get_hidden() # instead of .get_output()
```
A denoising autoencoder has also been added to demo how to inherit from AutoEncoder.
I have tried to be consistent with your coding style. Let me know if there are any issues.
=> add autoencoder and denoising autoencoder

keras/layers/core.py
Hey François,
I added a check for the shape of the current layer and the weights to be loaded in `keras.layers.Layer.set_weights`. Without that check it can happen that the weights alter the structure of the model. It raises an exception which is probably what should happen. Printing out a warning instead would work too, I guess.
Negative test case:
```
from __future__ import absolute_import
from __future__ import print_function
from keras.layers.core import Dense, Activation, Merge
def createModelA():
model.add(Dense(784, 50))
model.add(Activation('relu'))
model.add(Dense(50, 10))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
return model
def createModelB():
model = …
```
=> Loading weights with incompatible shape

docs/sources/callbacks.md, keras/callbacks.py, test/test_callback_modelcheckpoint.py
I found myself often training similar models over and over again only to find out from what epoch on the validation loss stopped decreasing.
In a similar manner to `pylearn2.train_extensions.best_params.MonitorBasedSaveBest`, this callback stores the model weights either after each epoch or only if the validation loss improved in the current epoch compared to the last best epoch. This behaviour can be controlled with the `save_best_only` parameter.
=> Modelcheckpoint callback to save model weights

keras/models.py
Hey François,
the `save_weights` method makes more trouble. :)
For Python 2.x using `input()` does not work. Instead to reliably get the input in python 2/3 one needs to use different functions.
=> Fixed python 2.x bug with input() in save_weights()

keras/layers/recurrent.py
It appears this was a bug in the implementation of SimpleRNN. The `init` initializer was being used for both sets of weights.
=> Use the inner_init for internal weights in SimpleRNN

keras/layers/convolutional.py
fix for #170, including constraints. Nothing fancy, just copied the code from the dense layer, but I suppose it should work the same.
=> regularization and constraints for Convolution1D and Convolution2D

keras/layers/core.py, tests/manual/check_autoencoder.py
Trying to build a deep denoising autoencoder (see the ``build_deep_denoising_autoencoder`` function in this merge request) 
```
encoder = containers.Sequential([Dense(input_dim, hidden_dim, activation=activation), 
Dense(hidden_dim, hidden_dim/2, activation=activation)])
decoder = containers.Sequential([Dense(hidden_dim/2, hidden_dim, activation=activation), 
Dense(hidden_dim, input_dim, activation=activation)])
autoencoder.add(Dense(input_dim, input_dim))
autoencoder.add(DenoisingAutoEncoder(encoder=encoder, decoder=decoder, 
output_reconstruction=False, tie_weights=True))
```
fails with 
```
DisconnectedInputError: grad method was asked to compute the gradient with respect to a variable that 
is not part of the computational graph of the cost, or is used only by a non-differentiable …
```
=> Make Autoencoder.connect call encoder.connect()

docs/sources/activations.md, keras/activations.py
There is no reason to have two different functions for this! The softmax
function can just be configured to always perform the softmax across the
trailing dimension (i.e. nb_dimensions)
=> Remove time_distributed_softmax in favour of softmax

keras/utils/generic_utils.py
in get_from_module(), a unicode identifier should be treated as a str
type.
=> utils/generic_utils: fix unicode strings problem

docs/sources/layers/recurrent.md, keras/layers/recurrent.py
Reference: An Empirical Exploration of Recurrent Network Architectures, Jozefowicz et al. 2015. http://www.jmlr.org/proceedings/papers/v37/jozefowicz15.pdf
They describe top RNN architectures evolved through the evaluation of thousands of models,  serving as alternatives to LSTMs and GRUs. These classes, `MutatedRNN_1`, `MutatedRNN_2`, `MutatedRNN_3` correspond to the `MUT1`, `MUT2`, and `MUT3` architectures described in the paper. Note that `input_dim` and `output_dim` must be equal in the `MUT1` and `MUT2` architectures.
I originally tried to implement these in a single class, but had to split them out.
In my tests on the IMDB dataset, everything being equal, these do improve on LSTM and GRU, particularly `MutatedRNN_1`.
=> Implementations of additional RNN architectures

keras/layers/core.py
The scan in get_output TimeDistributedDense leaked memory like crazy. Changing it to match get_output in Dense seems to have fixed the problem and behaves identically.
=> Fix memory leak

keras/preprocessing/sequence.py
I discuss this in issue #287. I think in most cases with a recurrent network you prefer to truncate the beginning of the sequence rather than the end, since the beginning is "furthest" from the label.
=> Support truncation off beginning of sequence

keras/constraints.py
=> Fix unitnorm to be a class, like other constraints

examples/mnist_irnn_rmsprop.py
This is a variant of IRNN experiment with sequential MNIST in "A Simple Way to Initialize Recurrent Networks of Rectified Linear Units " by Quoc V. Le, Navdeep Jaitly, Geoffrey E. Hinton
arXiv:1504.00941v2 [cs.NE] 7 Apr 201
http://arxiv.org/pdf/1504.00941v2.pdf
Optimizer is replaced with RMSprop which gives more stable and steady improvement.
Reaches to 80% train/test accuracy and 0.55 train/test loss after 70 epochs
15 minuts per epoch on a GRID K520 GPU.
=> Example: IRNN on sequential MNIST

tests/auto/keras/test_constraints.py
Weird file deletions have gone. Rebase done. Sorry for before :)
=> New pull request -- much cleaner

docs/sources/layers/core.md, keras/layers/core.py
Reference : `Vincent, Pascal, et al. "Stacked denoising autoencoders: Learning useful representations in a deep network with a local denoising criterion." The Journal of Machine Learning Research 11 (2010): 3371-3408.`
=> Create Gaussian Noise layer

keras/initializations.py
Standard deviation values were being passed as scale values for uniform distributions. 
But the relationship is: scale = standard deviation * sqrt(3).
So, the s values in glorot_uniform, lecun_uniform, and he_uniform should have been multiplied by sqrt(3) before being passed into uniform() function. Now it is fixed.
=> Fix mistakes in uniform initializations equations

examples/imdb_conv.py
Added a toy example of a model using a 1D conv layer on top of embeddings. The performance of this model seems comparable to that of the LSTM in imdb_lstm.py, reaching an acceptable 83.16% on the test data at epoch 10. All feedback welcome. I also want to add a character level 1D example but ran into the issue described in #388.
=> added conv1D example

keras/callbacks.py, keras/optimizers.py
Removing `regularizer` from `get_updates` signature in base class to match derived classes.
=> Match get_updates signature

keras/layers/convolutional.py
Convolution2D only has border_mode='Full' or 'valid' and the image size changes upon convolution. I added a layer that allows to shrink the image after using Convolution2D with border_mode='Full' back to the original size (before the Convolution2D)
Example, assume images are 28x28 as in the mnist example
model.add(Convolution2D(32, 1, 3, 3, border_mode='full'))   # images are now 30x30 
model.add(Activation('relu'))
model.add(CropImage(1))                                     # images are now 28x28
Thanks for a great package
=> CropImages to maintain sizes in CNN

keras/constraints.py, keras/layers/containers.py, keras/layers/convolutional.py, keras/layers/core.py, keras/layers/embeddings.py, keras/layers/noise.py, keras/models.py, keras/optimizers.py, keras/regularizers.py, keras/utils/generic_utils.py, keras/utils/layer_utils.py, tests/manual/check_yaml.py
- Sequential now has to_yaml() method to dump models as yaml strings.
- models module has sequential_from_yaml() method to load from such strings
- Models can be stored with and without parameters.
- It's possible to (de-)serialize non-standard optimizers, constraints and regularizers.
- Includes a test that checks for equality of configs before and after serialization.
=> Yaml support for Keras Sequential models

keras/layers/core.py
I added the Permute layer as a Core layer, as suggested by loyeamen on https://github.com/fchollet/keras/issues/401. It permutes the dimensions of the data according to the given tuple.
=> Added Permute layer as suggested by loyeamen on #401

docs/sources/models.md, keras/models.py
I'm currently using the `io_utils.HDF5Matrix` class, but HDF5 does not support array-indexing unless the indicies are in ascending order. This breaks shuffling. 
The solution I've been using is to add a 'batch' option to the shuffle argument; this shuffles in chunks dictated by the batch size. Essentially items within a batch aren't shuffled, but the order of batches _is_.
There's one slightly funny detail: if the number of items does not divide by the batch size the last batch is left in place.
=> implement batch shuffle

docs/sources/layers/advanced_activations.md, keras/layers/advanced_activations.py, keras/utils/theano_utils.py
This is meant to complement this PR: https://github.com/fchollet/keras/pull/421
This non-linearity is useful for modeling neural activity, especially when combined with Poisson loss.
With these additions it is possible to implement all of the models from this paper in keras:
http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003143
=> Add parametric softplus non-linearity

keras/preprocessing/text.py
Currently, `one_hot` advertises the same parameters as `text_to_word_sequence`, however it does not do anything with them.  I just pass them through properly.
=> Fixed parameter passing for preprocessing.text.one_hot

docs/sources/layers/core.md, keras/layers/core.py, tests/auto/keras/layers/test_core.py
Support masking of sequences without the Embedding layer, by masking out timesteps whose values equal a specific mask_value (default 0).
=> layers.core: add Masking layer

keras/layers/core.py, tests/auto/keras/layers/test_core.py
The following - rather artificial - example shows a potential flaw in the current masking approach:
```python
X = np.asarray([[[1e+30]]])
y = np.ones((1, 1, 1))
model.add(Masking(mask_value=1e+30))
model.add(SimpleRNN(1, 1, init='one', activation='relu', return_sequences=True))
model.compile(loss='mse', optimizer='sgd')
logs = model.fit(X, y, nb_epoch=3)
```
Produces the following output:
```
Epoch 0
1/1 [==============================] - 0s - loss: inf
Epoch 1
1/1 [==============================] - 0s - loss: nan
Epoch 2
1/1 [==============================] - 0s - loss: nan
```
**Explanation:** In all recurrent layers, the input value is multiplied with some matrix (usually `W`) before the time dimension is evaluated (Theano `scan`). The mask is currently only …
=> Proper handling of output values in Masking layer

docs/sources/optimizers.md, keras/optimizers.py
Updated adam solver to v8 of paper. The kappa (lambda) parameter has no practical use and has been removed.
Fixed the calculations for `beta_1_t` and `beta_2_t` which were also wrongly implemented from v4 of the paper.
=> Updated adam solver to v8 of paper

keras/objectives.py
I added Poisson loss as an objective. The Poisson loss is the negative log likelihood of data y_true given predictions y_pred, according to a Poisson model (assumes that y_pred > 0). Thus, the loss function is given by y_pred - y_true * log(y_pred).
This loss is typically used in computational neuroscience, when predicting the probability that a neuron will fire. Should be used after a softplus activation, to ensure that y_pred > 0. Often more useful in computational models of cells than the usual cross entropy loss as Poisson loss more heavily penalizes the model for predicting a spike during long periods of cell inactivity, than cross entropy would.
This complements PR https://github.com/fchollet/keras/pull/422.
=> Added Poisson Loss as an objective

examples/babi_rnn.py
This PR contains two bugfixes (missing vocabulary item in QA19 + issues with running on Python 3) and additional documentation (results and comparison to the Facebook LSTM baseline when run over all 20 tasks).
=> Fixes and full results for bAbi RNN example

keras/datasets/data_utils.py
urlretrieve will blindly swallow any 4xx and 5xx responses
and then save the html error response in the local file. This
is probably exactly what we don't want, because not only will
the program crash if there is a network hiccup when the error
file cannot be opened, but it will continue to do so when rerun
until the corrupt cached file is found and manually removed.
Luckily, urlretrieve is just a thin wrapper around
FancyURLopener, so we can make our own thin wrapper
that throws an exception instead of caching the
wrong file.
Tested to be working as before when running cached and
uncached datasets, and also verified to fail loudly
when asked to fetch http://httpstat.us/500
=> data_utils: add error handling on url fetches

keras/utils/layer_utils.py
Recently, I tried to save my model using model.to_yaml() and then load it via keras.models.model_from_yaml(). However, I got an "Invalid layer: Convolution2D" Exception.
I found this is due to the global namespace of keras.utils.layer_utils misses all the layer classes in keras.layers.convolutional. Thus, saving and loading any model with layers from keras.layers.convolutional will trigger the "Invalid layer" exception.
The line in this PR fixed this problem.
=> Fix conv layers loading for model_from_config

keras/models.py, tests/auto/test_loss_masking.py
Fixes #395
This is a natural continuation of PR #446 
This allows masking of the cost function for sequence to sequence learning with different lengths. It does so with an optional flag `mask_cost` at `model.compile`.
=> Optionally mask cost function for sequence to sequence learning

keras/preprocessing/text.py
Calling sequences_to_matrix results in an IndexError when nb_words = None. This is caused by a 1-indexed word_index, since sequences_to_matrix expects 0-indexing. Converts word_index to 0-based indexing.
=> Fixes IndexError when converting sequences to matrix with nb_words = None

keras/layers/convolutional.py
I've added two new layers to perform up sampling to convolutional.py, in response to: https://groups.google.com/forum/#!topic/theano-users/wy9Fuy5pWU0
The documentation for both layers is below:
UpSample1D:
Description: This layer up samples input across one dimension (e.g. inverse MaxPooling1D)
Input shape: (nb_samples, steps, dim)
Output shape: (nb_samples, upsampled_steps, dim)
Potential use case: For stacking after a MaxPooling1D Layer
UpSample2D:
Description: This layer upsamples input across two dimensions (e.g. inverse MaxPooling2D)
Input shape: (nb_samples, stack_size, nb_row, nb_col)
Output shape: (nb_samples, stack_size, new_nb_row, new_nb_col)
Potential use case: For stacking after a MaxPooling2D Layer
=> Added Up Sampling (inverse Max Pooling) Layers

keras/utils/io_utils.py
`refs` is a class attribute, not an instance attribute. If we make `refs` an instance attribute, this will cause `HDF5Matrix` to open the same HDF5 file more than once (which should never happen).
=> Recent update broke HDF5Matrix

examples/addition_rnn.py
An implementation of sequence to sequence learning for performing addition.
Input: "535+61"
Output: "596"
Padding is handled by using a repeated sentinel character (space).
By default, the JZS1 recurrent neural network is used. JZS1 was an "evolved" recurrent neural network that explicitly performed well on arithmetic benchmark in [An Empirical Exploration of Recurrent Network Architectures](http://jmlr.org/proceedings/papers/v37/jozefowicz15.pdf)
Input may optionally be inverted, shown to increase performance in many tasks in [Learning to Execute](http://arxiv.org/abs/1410.4615) and [Sequence to Sequence Learning with Neural Networks](http://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf) theoretically as it introduces shorter term dependencies between …
=> Example: Sequence to sequence learning for addition using RNNs

keras/layers/containers.py
The default value for this is {} so I'm guessing it wants dict input, rather than a list of tuples or something that would otherwise work as-is.
=> Fix Graph.set_previous with dict connection_map

docs/sources/layers/convolutional.md
Added link to `scipy.signal.convolve2d` documentation.
=> Add SciPy Link to Conv Layer Docs

keras/models.py, tests/auto/test_loss_masking.py
We used nonzero() on the weights in order to ensure that if there
happened to be a NaN or an Inf in the output that was going to be masked
about by the weights anyway, it wouldn't propagate (because 0*inf = NaN)
however this was causing interaction issues if you also used a mask,
because that wasn't using nonzero() properly.
This fixes that, and also fixes what I believe was an issue where I was
calling mean() instead of dividing by the sum of the sample weights.
Please think about this carefully: getting the normalization across both forms of weights right is a bit subtle, and I screwed up a number of times before creating this PR. I *think* it's right now though.
=> Fix weight mask interaction in objectives

keras/models.py
As far as I can tell there is no reason not to support class_weight with
time distributed data, rewriting the standardize_weights function with
that in mind.
=> Allow class_weight's use with time distributed data

keras/layers/convolutional.py
When are are multiple gpu the theano.config.device would be for example "gpu0", "gpu1".
=> Multiple GPU works

examples/cifar10_cnn.py, examples/mnist_cnn.py
This code is my proposal for closing #469. Magic numbers are removed from both MNIST and CIFAR10. CIFAR10 also features a reasonably intuitive approach to handling multiple layers with various pooling / filter sizes. I've tried following the general convention for variables and comments as set forth by other examples.
Note: It'd be a good idea to add a subsample / stride example in the near future as there are no tests / examples of that within Keras and it's non-trivial but that's likely a separate issue. I've still not gotten subsampling to work in my code for the [Right Whale Recognition](https://www.kaggle.com/c/noaa-right-whale-recognition) Kaggle competition, where the high image resolution almost demands it.
=> Removing magic numbers from MNIST and CIFAR10

setup.py
Keras documentation says `h5py` is optional, but a recent commit 1ebec1e515bac4c4c4564a410c2de3ee33bb8a1e made it a requirement. Because there are problems installing `h5py` inside a virtualenv, I would suggest that it remains optional.
This fix uses the extras option to specify optional dependencies. Usage:
```bash
pip install 'package[h5py]'
```
=> Remove h5py requirement and made it optional.

keras/utils/generic_utils.py
By allowing sum_values[k] to be other things than lists, it makes it easier for children classes to print "any value" (in my case, a timedelta object).
=> Add a bit of flexibility in Progbar.update

keras/layers/core.py
Some advanced models are made easier with this simple addition. It does not break anything, just add an extra option to Merge layers. This option allows it to work with layers that get several inputs separately.
For example, I'm writing a DRAW model using Keras and I believe this is the only non-standard thing that the model would require to run with Keras out of the box.
=> Add merge_mode join

docs/sources/callbacks.md, keras/callbacks.py, tests/manual/check_callbacks.py
enable string formatted filenames (e.g. weights.{epoch:02d}.hdf5), so
every epoch will be saved to a different file without overwriting.
=> support for multiple files in ModelCheckpoint

keras/layers/convolutional.py
Similar to Convolution2D, checks if cuDNN available, and if so, uses it in Convolution1D as well.
On the imdb_cnn example, I'm getting about a ~1 s speedup with cuDNN on a Tesla K80.
```
mini-     seconds/epoch 
batch  w/o cuDNN  w/ cuDNN
-----  ---------  --------
32            13        12
64             8         7
128            5         4
```
=> Use cuDNN in Convolution1D layer if available

keras/layers/containers.py, keras/layers/convolutional.py, keras/layers/core.py, keras/layers/embeddings.py, keras/layers/normalization.py, keras/layers/recurrent.py, tests/auto/keras/layers/test_convolutional.py, tests/auto/keras/layers/test_core.py, tests/auto/test_shape_inference.py
Note: this PR does NOT modify the model construction API at all, since that is apparently still under debate. Instead, this PR just introduces the logic needed to add automatic shape inference to Keras.
All layers now have an attribute `output_shape` that returns a shape tuple (or a dictionary mapping output names to shapes in the case of the `Graph` container).
The input shape of connected layers is inferred from the output shape of the previous layer. For a layer that is not connected (like the first layer in a network), you can set input shape manually by setting the layer attribute `_input_shape` to a tuple. This allows to skip `Input` layers entirely.
```python
input_layer = Dense(...)
input_layer._input_shape = (None, 10)
```
`None` dimensions in shape tuples are variable dimensions …
=> Add .output_shape attribute in all layers (+tests)

keras/layers/convolutional.py
In my previous PR I removed the default of `None` for the stride in MaxPooling, which was ambiguous and defaulted to a stride equal to the pool size. This broke the Keras CNN examples which were using this default.
I reverted the change to restore backwards compatibility.
=> Fix compatibility with old MaxPooling interface

keras/models.py, keras/utils/generic_utils.py, keras/utils/layer_utils.py
Keras currently uses globals() to access layers. (This doesn't work
across modules.) Hacky solution was to pass a dict mapping name -> class.
I called this dict `custom_layers`. I have a few questions before we merge this in:
1. What would be a better name for this kwarg? `user_layers`? `layers`?
2. Is there a better way of doing this that I'm not seeing?
3. Are there any other places I missed that where should add the `custom_layers` argument?
Currently serialziation with custom layers works fine. The problem that this fixes is trying to call `model_from_*` with a configuration file that has a custom layer name that isn't inside of Keras' `globals()`. This solution allows us to serialize / deserialize models with custom layers. For example:
```py
from keras.models import model_from_yaml …
```
=> First crack at threading `custom_layers` through.

keras/layers/convolutional.py
In commit cb77f7d, `image_shape` and `filter_shape` were added - correctly on `T.nnet.conv.conv2d` in `Convolution1D`, but mistakenly on `dnn.dnn_conv` in `Convolution2D`. This causes the following error when using dnn: `TypeError: dnn_conv() got an unexpected keyword argument 'image_shape'`. 
refs:
http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html#functions
http://deeplearning.net/software/theano/library/tensor/signal/conv.html
=> correct image_shape and filter_shape parameters in Convolution2D

README.md, docs/sources/examples.md, docs/sources/layers/embeddings.md, examples/imdb_lstm.py, keras/layers/embeddings.py, tests/manual/check_callbacks.py, tests/manual/check_model_utils.py
Most notably the Embedding layer could not be serialized to JSON or YAML due to needing `input_shape.` All examples with an Embedding layer have been modified to reflect this as well.
Regarding the manual tests, I tried to update all the models to reflect the new API, but I can't get all of them to pass (not sure they were passing before, though).
=> fixes for new API: Embedding layer, additional examples

examples/cifar10_cnn.py
“TypeError: Cannot cast ufunc subtract output from dtype('float64') to
dtype('uint8') with casting rule 'same_kind'” in
keras/preprocessing/image.py, line 239, when using data augmentation.
=> Bug fixes:

keras/utils/layer_utils.py
This should fix the problem`Exception: Invalid layer: LRN2D` while loading a model that includes LRN2D layer.
```py
model.add(Convolution2D(30, 3, 3, input_shape=(1, 28, 28)))
model.add(LRN2D())
model_def = model.to_yaml()
model_from_yaml(model_def)
```
The code above could reproduce the problem.
=> FIx `Exception: Invalid layer: LRN2D`

keras/layers/core.py
`join` is a valid merge mode, but if we use it gets catch on a exception
=> add join to valid merge modes

examples/mnist_transfer_cnn.py, keras/layers/containers.py, keras/layers/core.py
Following the discussion in #622, here is a simple strategy to "freeze" specific layers during training. IT works for ```Sequential``` and ```Graph``` models.
It adds a ```trainable``` attribute to the core ```Layer``` class and check its value when creating the model. If a layer's ```trainable``` flag is modified after addition to a model, the model needs to be rebuilt and recompiled. For this, a ```rebuild``` function has been added to ```Sequential``` and ```Graph``` classes.
=> added possibility to freeze layers during training

keras/__init__.py
Learning from other data processing library. It is important that user-code is able to check for version, e.g. http://stackoverflow.com/questions/28501072/how-to-check-which-version-of-nltk-scikit-learn-installed.
- https://github.com/nltk/nltk/blob/develop/nltk/__init__.py#L26
- https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/__init__.py#L24
This mini improvement would allow:
```
>>> import keras
>>> keras.__version__
0.2.0
```
And from the command line
```
$ python -c "import keras; print keras.__version__"
0.2.0
```
Note that the current version number is consistent with [PEP0440](https://www.python.org/dev/peps/pep-0440/) =)
Also note, `numpy` and `scipy` has a more complicated `__version__` string but i think it's an overkill for now =):
- …
=> Added version information and docstring to __init__

keras/models.py
Tested usage:
```python
f = h5py.File('/path/to/data', 'r')
X = f['X'].value
y = f['y'].value
m = keras.models.Sequential()
m.add(keras.layers.recurrent.LSTM(32, input_dim=13, input_length=20, return_sequences=False))
m.add(keras.layers.core.Dense(10, activation='softmax'))
m.compile(keras.optimizers.RMSprop(), keras.objectives.categorical_crossentropy)
m.fit(f['X'], f['y'], shuffle='batch', nb_epoch=5)
m.evaluate(f['X'], f['y'])
m.predict(f['X'])
m.fit(X, y, shuffle=True, nb_epoch=5)
m.evaluate(X, y)
m.predict(X)
```
=> fixed error in reading hdf5 dataset

keras/layers/core.py
Make sure that only layers with same output_shape are merged using sum, ave and mul modes.
=> Assert input shapes of Merge layer are equal

keras/utils/layer_utils.py
When loading regularizers/constraints from config, and the object isn't
found, don't consume the 'name' key.
This enables expansions to keras to be saved/loaded with dictionaries as
some of their parameters.
=> utils.layer_utils: don't consume 'name' when loading

keras/layers/core.py
Following the discussion https://groups.google.com/forum/#!topic/keras-users/PYbBnZXCvO4, here is a simple change to the '''Dropout''' layer that follows the Caffe implementation. 
Data rescaling is done during training instead of testing. This has the advantage of making the layer equal to identity at test time. Therefore, it can be safely removed in a production environment.
However, this will break compatibility with previously saved models.
=> Dropout: rescale data at training time (breaks bw compat.)

keras/preprocessing/sequence.py
In case of an empty sequence (as a result of clearing stop words for example), don't raise an error but continue to the next sequence.
=> Handle an empty document

keras/layers/core.py
The assertion checked the opposite of what was desired. That is, it checked that inputs aligned along the concat axis, rather than on every axis _except_ the concat axis.
=> Fix merge concat mode

keras/layers/core.py, tests/auto/test_sequential_model.py
- More helpful error messages when invalid inputs are passed to `Merge`.
- Tougher enforcement of input formatting expectations for `dot_axes`, because the format is complicated and not obvious. Errors will be common and need to be catched.
- Fixed incorrect output shape computation for dot mode in `Merge`.
=> Fixes and input checks for dot mode in merge.

keras/layers/core.py
When mode='ave', and the dtype of the input is float32, dividing the sum
by shape[1], which is of dtype int64, results in an output of dtype
float64, which is wrong.
fixed to use theano.tensor.mean instead.
=> Fix TimeDistributedMerge

keras/layers/containers.py
As the graph container was not using each individual layer's get/set
weights, but rather the super class layer.get_weights, which works on
self.params(), it was missing some weights in the process, i.e., the
BatchNormalizationLayer has custom get_weights which allows to save the
running mean/std. However, these running computations are not added to
BatchNormalizationLayer.params(), resulting in losing these weights
after serializing a graph model utilizing a BatchNormalizationLayer.
Fixed to use each node's get/set weights.
=> Fix containers.graph sav/get_weights

keras/layers/recurrent.py
I double checked my bidirectional RNN code and looked closely to the theano scan implementation and i found an error where the return sequences flag is active. (it actually return the reversed sequences that may cause failure in particular where stacking Bidirectional Layers.
Here is the fix.
=> Fixed error go_backward and return sequences.

docs/sources/layers/core.md, keras/layers/core.py
Fixed a typo in `Lambda` layer. Also allowed it to pass kwargs through to the `Layer` constructor. This lets you pass an `input_shape` kwarg so that you can use `Lambda` as the first layer. I also updated the docs to reflect the change.
For example, this is what I wanted to do, which wasn't possible before:
```{python}
def img_norm(X):
return X / 255
model.add(Lambda(img_norm, input_shape=(3, img_size, img_size)))
model.add(Convolution2D(32, 10, 10))
```
=> Lambda layer enhancements

docs/mkdocs.yml, docs/sources/visualization.md, keras/utils/visualize_util.py
This adds a new to_graph function in visualize_util that allow to get the pydot.Graph object directly, without necessarily rendering to a file. This allow to render the graph inline in a ipython notebook.
This also adds a 'visualization' doc section with examples of visualize_util usage.
=> Add visualize_util.to_graph and docs

examples/addition_rnn.py, examples/imdb_bidirectional_lstm.py, examples/mnist_irnn.py, keras/activations.py, keras/backend/tensorflow_backend.py, keras/layers/containers.py, keras/layers/embeddings.py, tests/keras/backend/test_backends.py
I have a clockwork RNN implementation in layers/recurrent.py:
```python
class CWRNN(Recurrent):
'''
Clockwork Recurrent Unit - Koutnik et al. 2014
Clockwork RNN splits simple RNN neurons into groups of equal sizes.
Each group is activated every specified period. As a result, fast
groups capture short-term input features while slow groups capture
long-term input features.
References:
A Clockwork RNN
http://arxiv.org/abs/1402.3511
'''
def __init__(self, output_dim, periods=[1],
init='glorot_uniform', inner_init='orthogonal',
activation='sigmoid',
weights=None, truncate_gradient=-1, return_sequences=False,
input_dim=None, input_length=None, **kwargs):
self.output_dim = output_dim
assert output_dim % len(periods) == 0
self.periods = np.asarray(sorted(periods, reverse=True))
self.init = …
```
=> Add Clockwork RNN

.travis.yml, keras/backend/__init__.py, pytest.ini, tests/test_graph_model.py, tests/test_sequential_model.py
Hello,
Thank you for this framework! It seems to be the best one on the market:) These changes speeds up travis testing time 2 times using some pytest and travis configuration options.
Summary of changes:
- py.test is configured to display test profiling information that shows 10 slowest tests. This would allow additional speed ups if anyone has ideas on some particular test. The slowest test is usually cifar dataset test and tensorflow convolutions. It seems that there are some other IT tests that could be sped up.
- py.test is configured to run with pytest-xdist with 2 processes in parallel because travis does provide multicore support (1.5 cores) and because the slowest cifar test spends time on download which can run in parallel with other tests.
- travis is configured to split …
=> Speed up keras test infrastructure

docs/sources/layers/core.md, keras/layers/containers.py, keras/layers/core.py, tests/keras/layers/test_call.py
Add a `__call__` method to Layer and Sequential. We can do the following:
```python
X = K.placeholder(ndim=2)
Y = model(X)
```
One interesting application is where a model is used as an upper layer of another model. In that case, we don't have access to its `get_input`:
```python
encoder = Sequential()
decoder = Sequential()
model.add(encoder)
model.add(decoder)
X = K.placeholder(ndim=2)
Y = decoder(X)
```
This code temporally change the value of a specific element of the graph by `X` and call `get_output`. Regardless of the fact that the specific element is a `previous` or `input`. For example, the following code would crash:
```python
X = decoder.get_input()  # this is not a placeholder Tensor, it is a graph
Y = decoder.get_output()
F = function([X], Y)
```
I also updated some docs. Let …
=> Add __call__

tests/keras/layers/test_call.py
We were having precision problems with float32 comparing compiled function and np.dot
I changed the input to ones to reduce randomness. The test fail with rtol 0.13, I increased it to 0.2
=> Fix tolerance comparing __call__ to np.dot

examples/cifar10_cnn.py
The progbar in the cifar10 example didn't work, because due to the back end changes train_on_batch now returns the loss as a 1x1 matrix.
=> Fixed the progbar in the cifar10 example

docs/sources/layers/convolutional.md, keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/layers/convolutional.py, tests/keras/backend/test_backends.py, tests/keras/layers/test_convolutional.py, tests/test_shape_inference.py
We address  #522,  #230, #768, #786 and propose a solution that should cover most of those tickets. PR includes
- Added Pooling1D and Pooling2D classes in convolutional
- MaxPooling1D/2D and MeanPooling1D/2D as derived classes implemented (instead of "pool_mode" flags)
- In particular, all existing examples change untouched (same API as before)
- Extended tests and docs
Note: I didn't include SumPooling, bc there seems to be no implementation in TF (that I know of), but I included a suggestion for Theano in comments. If wanted, we can pretty quickly implement other pooling modes later on.
=> General 1D & 2D Pooling layers

keras/utils/visualize_util.py
This improves visualize_util.plot with :
- Support for container layers (using recursive=True to show container details)
- Shape information in the plot (using show_shape=True)
[Here is a notebook](https://github.com/julienr/ipynb_playground/blob/master/keras/visutils_model2dot.ipynb) with some test networks showing what this does.
I haven't tested it extensively, so I would consider it work in progress for now. I would also like feedback for further improvements & options.
=> [WIP] utils.visualize_util improvements

.gitignore, keras/backend/theano_backend.py, keras/layers/containers.py, keras/layers/recurrent.py, keras/models.py, tests/keras/layers/test_recurrent.py
Ideally, I could set my RNN's to stateful and use them to predict sequences in a stateful way.  Right now, the `_predict` function generated in the model does not run the updates necessary to set the RNN state.
~~The one problem I see is that we have collision with other layers that also set updates, namely the `BatchNormalization` layer.  A solution to this is to have the RNN state updates go to another variable, `state_updates` and leave `updates` for things that should only happen on training.  This seems like the right way of doing things, but the `get_param` function is thrown around a lot with tuple expansion and it seems like a mess to dig into that (maybe a good place for a `NamedTuple`).~~
EDIT: 56fa445 adds new property, `state_updates` to the `model` object that returns only …
=> Run non-optimization updates on predict for stateful RNN's

tests/keras/layers/test_core.py
This is a work in progress. I will be working on this all weekend (I hope). My timezone is CET. If anyone wants to join me, let me know ( @olegsinyavskiy @EderSantana @farizrahman4u ?) and I will give you push access.
Things that are not tests as such but that would be nice to have
Tests that need to be written, in approximate order of coverage increase they will bring
I recon if all these are met, we should be pretty close to 90%, which seems like a more presentable number.
=> Sprint to bring up test coverage

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/layers/convolutional.py, tests/keras/backend/test_backends.py
Currently, UpSampling1D/2D does tiling on its input ([0, 1] => [0, 1, 0, 1]).
This modifies those layers to repeat individual entries instead (so [0, 0, 1, 1] => [0, 0, 1, 1]), as discused in #1226 and #1287 and should fix those issues.
This works by adding a new backend operation ``repeat_elements`` which has the same behavior as ``np.repeat``.
The tensorflow implementation uses a `split` and a `concat`. This might not be the most efficient way to do it, but at least it works. I am just starting to learn tensorflow, so if some indexing tricks wizard knows a better way, please let me know :-)
=> Modifies UpSampling1D/2D to repeat entries instead of tiling arrays.

keras/layers/core.py, keras/layers/normalization.py, keras/layers/recurrent.py
It seems that refactoring for multiple backends introduced some typos and some input or output shapes (especially one-dimensional) were not tuples anymore. In some circumstances, like using a LSTM layer with `forget_bias_init='he_normal'`, Keras crashed:
```
model.add_node(LSTM(embedding_dim, return_sequences=True, forget_bias_init='he_normal'), name='lstm', input='shared_1')
File "/home/xxx/venv/src/keras/keras/layers/containers.py", line 262, in add_node
layer.set_previous(self.nodes[input])
File "/home/xxx/venv/src/keras/keras/layers/core.py", line 53, in set_previous
self.build()
File "/home/xxx/venv/src/keras/keras/layers/recurrent.py", line 328, in build
self.b_f = self.forget_bias_init((self.output_dim))
File "/home/xxx/venv/src/keras/keras/initializations.py", line 46, in …
```
=> Fix shapes should be tuples.

keras/utils/visualize_util.py
Added support for importing `pydot-ng` with `pydot` as fallback when visualizing, similar to like it is done in `Theano` (eg. https://github.com/Theano/Theano/blob/master/theano/printing.py or in a PR https://github.com/Theano/Theano/pull/3772).
=> Import pydot-ng with pydot as fallback when visualizing.

examples/babi_memnn.py
Fix the wrong link for "Towards AI-Complete Question Answering: A Set of Prerequisite Toy Tasks"
=> Fix the wrong link

keras/models.py
Hi,
for this pull request, I adapted the return value of the predict_on_batch() function such that it is consistent with the predict() method. That means, both function return a dictionary of their predicted outputs instead of an ordered list. Exemplary usage:
```python
predictions = model.predict_on_batch({"input1": X1,"input2": X2,"input3": X3}})
Y1 = predictions["output1"]
Y2 = predictions["output2"]
```
This way, it is more intuitive to retrieve the specific output one is interested in.
I believe this is a small change that many people might profit from.
Any comments?
=> Output Format of predict_on_batch in Graph() Model as Dictionary

examples/lstm_text_generation.py
The variable `iteration` is shadowed between the second loop and the third loop. So if I want to print `iteration` there, I always get `399`.
This is not a bug for now but since this is an example and many people may write more code from here. It's better to fix it.
=> fix iteration shadowed in loop

keras/backend/__init__.py, keras/datasets/data_utils.py
I ran keras on a distributed environment. On worker nodes, it might possibly we don't have writing permission for the `_keras_dir`. In this case, the running will be failed. I think we can check its permission and assign it to temporary directory in this case.
=> Check keras_dir writing permission and assign temporary directory

keras/models.py
We don't need to call `objectives.get` twice here.
=> Minor: remove duplicate code

keras/layers/core.py, tests/test_shape_inference.py
This block of code correctly returns a y with shape `(5, 2)` however model.output_shape incorrectly returns the value of dims `(-1, 2)`
```python
x = np.random.random((6, 10))
model.add(Reshape(dims=(-1, 2), input_shape=x.shape[1:]))
model.compile(loss='mean_squared_error', optimizer='sgd')
y = model.predict(x, batch_size=16)
print y.shape
print model.output_shape
```
=> Fixed handling of negative dimensions in Reshape layers

keras/utils/layer_utils.py
The arguments `concat_axis` and `dot_axes` are currently not loaded from the .json file, which causes the loading procedure to fail when the architecture includes a merge layer.
=> Fix: Loading merge layer from serialized data

keras/backend/theano_backend.py
This patch closes #1276.
As I understand the bug, the padding is applied on both sides horizontally and vertically when using custom padding in cuDNN.
To be consistent with the behavior of [T.nnet.conv.conv2d](https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py#L577-L581)                     the same trick is applied here.
The convolution is padded according to the `full` mode and then sliced to have the same size as the input.
=> Fixed dnn_conv output size

keras/layers/containers.py
batch_input_shape fix when dtype is not a float.
=> batch_input_shape fix

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/layers/convolutional.py, tests/keras/layers/test_convolutional.py
This allows to take advantage of tensorflow’s resize_images operator in UpSampling2D. This was discussed in #1293 .
This also modifies `test_upsampling_2d` to test with different dim_ordering.
=> Add K.resize_images backend op.

keras/backend/theano_backend.py
A simple copy paste of the [fix](https://github.com/fchollet/keras/commit/13379da81bff3d72d7ade8b662640545f4c1b559) following this [discussion](https://groups.google.com/forum/?hl=fr#!topic/keras-users/zLMpqJTSZJ8) for the conv2d using base Theano.
This way we should have the same behavior when using one or the other.
*The last [fix](https://github.com/fchollet/keras/commit/13379da81bff3d72d7ade8b662640545f4c1b559) has been tested on both cuDNN v3 and cuDNN v4.
=> Evaluate the kernel of base Theano conv2d with the same border mode

keras/models.py
Following #1025, #1119, #911 and #868 custom objectives functions still can't be loaded when loading a saved model with `model_from_json` or `model_from_yaml`. I made a simple change to check if the names of the outputs were not in the `custom_objects` passed so we can feed it to the `.compile` method.
`globals()` seems to be local at the module level and the custom function is not visible inside the `objectives.py` module.
As always, I'm not sure if it's the best way to do it but I tried to minimise the changes in other modules and submodules.
For the tests, should I add a custom objective, compile it and try to serialize it using json and yaml?
=> Added compatibility for custom loss functions

keras/callbacks.py
Adding `dict_items` [does not work](https://stackoverflow.com/questions/13361510/typeerror-unsupported-operand-types-for-dict-items-and-dict-items) in Python 3. Workaround is to create a copy of the dict and `update` it with the other dict.
=> FIxed Tensorboard callback for Python 3

examples/neural_style_transfer.py
How about removing cv2 dependency and use scipy.misc function instead?
I haven't used opencv so far so I have no idea if there would be any performance difference. If they are not that different from each other, it would make it easier to run for some people.
=> Remove cv2 dependency and use scipy.misc

keras/models.py
In model.to_json, some unhandled types are manually converted to JSON type:
- if the object is any numpy type, convert using obj.item()
- for python objects of the type 'type', return the name as a string
This avoids an error being thrown when these types appear in the model config. Fixes https://github.com/fchollet/keras/issues/1355
=> models: when dumping config to json, parse unhandled types correctly

examples/lstm_stateful_seq.py
Adding an example using statefull LSTM to predict a sequence.
The sequence is generated on runtime and is a cosine curve, the curve amplitude is getting multiplied by an exponentially decreasing factor. 
The example will also generate a plot using matplotlib if the lib is present.
I've run autopep8 on the code before submitting
Example of the plot generated.
=> Add example of stateful LSTM sequence prediction

keras/models.py
When loading a model from config, the returned object doesn't have a name.
```python
from keras.models import model_from_json
loaded_model = model_from_json(model_str)
print(loaded_model.name)
AttributeError                            Traceback (most recent call last)
<ipython-input-73-3f3d9efa33de> in <module>()
----> 1 loaded_model.name
/opt/conda/lib/python2.7/site-packages/Keras-0.3.1-py2.7.egg/keras/layers/core.py in name(self)
60     @property
61     def name(self):
---> 62         return self._name
63 
64     @name.setter
AttributeError: 'Graph' object has no attribute '_name'
```
This PR add the name of the model along with the `__class__`.
=> Added the name of the model when loading it from config

keras/layers/noise.py
Just a small fix to add back a missing square root to match the original paper (and the documentation).
=> Add sqrt for proper noise sigma calculation

keras/backend/theano_backend.py
As with the theano backend, when using multiple GPUs, one may set gpu by theano.sandbox.cuda.use instead of via config. In this case, the theano's dnn module cann't be imported properly, make CNN training very slow
=> Check gpu status correctly when using theano's cuda.use to choose gpu

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py
The change to the dimshuffle/transpose call to support >3d inputs was
correct for the inputs array but did not apply to the mask array. This
fixes that.
=> Support >3d mask matrices.

keras/preprocessing/image.py
Currently, polynomial interpolation of 3rd order is done when shifting. However, that is not needed because the images are shifted by integer values (crop_left_pixels, crop_top_pixels), and there is nothing to interpolate.
Setting ```order=0``` will speed up random shifts significantly.
=> Speed up random shifts in data augmentation

tests/keras/backend/test_backends.py
It looks like this was a copy+paste bug where neither `random_uniform` nor the theano backend were being tested. Thanks for keras!
=> Fixed backend tests for `random_uniform` and `random_normal`

examples/imdb_cnn_lstm.py, examples/mnist_transfer_cnn.py
The example GPU commands did not contain the correct filename
=> Minor typos in example commands

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/layers/core.py, keras/layers/embeddings.py, keras/objectives.py, tests/keras/layers/test_core.py, tests/keras/layers/test_recurrent.py, tests/keras/test_objectives.py, tests/test_loss_masking.py
Fixes #1567
- The RNN backend call can now take a mask with or without the same number of dimensions as the input data
- As part of the investigation, I found that categorical_crossentropy was taking an extra mean, the function already removes the final dimension of your input, so you don't need to take a mean as you would with, say, L2 loss. This seems like a pretty severe potential issue so anyone doing sequence to sequence learning should take note.
- Since I was already down that rabbit-hole, I also fixed Masking to work with tensorflow.
=> Fix categorical crossentropy and Masking

keras/models.py
Pressing *Ctrl+C* or terminating the main program with any other exception does not close it in case you are using `fit_generator()`, because threads are not initialized in daemon mode.
=> Fix program termination when threads are used in fit_generator().

keras/models.py, tests/integration_tests/test_temporal_data_tasks.py
If `sample_weight` is to be used as a mask as well as for re-weighting then it's important that, at least when used as a mask, the output be rescaled. Otherwise the order of magnitude of your objective changes purely based on the number of masked entries in your training data.
The exact implementation is perhaps confusing, and is due to overloading of `sample_weight` to be both a weight and a mask. I personally only use it as a mask, so perhaps anyone using it for weighting should make sure that this is appropriate for their use as well. It is because of the weighting use-case that, rather than simply divide by the mean, I first convert it to a binary mask and then divide by the mean.
@EderSantana you mentioned in #1520 that, with sample_weights, on new Keras you were getting smaller …
=> Objective outputs should rescale based on sample_weights

examples/mnist_siamese_graph.py
This is a simple example of a Siamese network on MNIST datset:
* uses a graph model
* takes pairs of digits as input
I wrote more or less the same example [with a sequential model](https://gist.github.com/mmmikael/0a3d4fae965bdbec1f9d) but I think the network definition with a graph is easier to understand:
```python
g = Graph()
g.add_input(name='input_a', input_shape=(in_dim,))
g.add_input(name='input_b', input_shape=(in_dim,))
g.add_shared_node(base_network, name='shared', inputs=['input_a', 'input_b'],
merge_mode='join')
g.add_node(Lambda(euclidean_distance), name='d', input='shared')
g.add_output(name='output', input='d')
```
compared to:
```python
input1 = Sequential()
input2 = Sequential()
input1.add(Layer(input_shape=(in_dim,)))
input2.add(Layer(input_shape=(in_dim,))) …
```
=> add siamese example

docs/templates/preprocessing/sequence.md
Updated the incomplete documentation of `pad-sequences()` function. It lacked the description of a few important parameters
=> docs: update "pad_sequences()" parameters in the docs

keras/layers/core.py
Without this, attempt to use cos merge mode dies with
````
File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 533, in get_output
UnboundLocalError: local variable 'T' referenced before assignment
````
=> Merge(cos): Fix bad import

keras/layers/containers.py, keras/layers/core.py
This dramatically speeds up constructing large networks. Implementation follows that of layer caching introduced in e8e8f7.
=> Add caching for layer input/output sizes

keras/preprocessing/sequence.py, tests/keras/preprocessing/test_sequence.py
Currently pad_sequences only support 1-dimensional samples e.g. word/char sequences. Support images (2D), volumetric (3D) or any nD time sequences to be padded as well. See  #1718.
=> generalize pad_sequences

keras/datasets/data_utils.py
Previous solution to retrieve remote files is based on FancyURLopener which ignores $http_proxy and $https_proxy. The proposed solution reproduces previous behaviour (error handling and progress bar) and has been tested under Python 2.7 and 3.5
=> retrieve datasets behind http/https proxy

keras/models.py
Recent refactoring of callbacks (commits c9642571c23004a10e8bca1a5b1446af399f80db and 1a6cb71732fe2a1297a6a3d92644f45df3211d7e) missed the `fit_generator()` function and consequently no progress bar was shown (even with `verbose=1`).
=> Fix missing callback refactoring.

keras/models.py, tests/keras/test_models.py
This is an addition to allow for the use of generators as the `validation_data` parameter in `fit_generator`. In addition, a general `evaulate_generator` is implemented as well, which can be used just like `evaluate` on generators yielding validation examples.
I'm closing a previous pull request with this feature which I made without knowing how to rebase properly.
=> add support for validation generators in fit_generator and evaluate_generator

keras/layers/containers.py, tests/keras/test_models.py
`Sequential.set_weights` would fail for nested `Sequential` containers. This PR borrows the implementation of `Graph.set_weights` to get it working. It also adds tests for triply-nested `Sequential` models.
Resolves #1730.
=> Fix `Sequential.set_weights` for nested containers

keras/layers/recurrent.py
Have you noticed how default GRUs works usually worse than LSTMs? It seems that "tanh" is a more sensible activation choice. Also for GRUs, tanh seems to be the default:
see http://arxiv.org/pdf/1412.3555v1.pdf Section 3.2
=> Sensible activation for RNNs

keras/layers/containers.py, keras/layers/core.py, tests/keras/layers/test_call.py
Previously, `Graph` inherited `__call__` from `Layer`, which doesn't work as expected. I added a bunch of tests that previously failed, but the basic problem is that this example throws an `UnusedInputError`
```{python}
graph = Graph()
graph.add_input("input", input_shape=(10, ))
graph.add_node(Dense(10), input="input", name="output", create_output=True)
inputA = K.placeholder(ndim=2)
outputA = graph(inputA)
fA = K.function([inputA], outputA)
```
It also breaks Siamese graphs, since the Siamese implementation relies on `__call__`. This example also throws an `UnusedInputError`
```{python}
graph = Graph()
graph.add_input("input", input_shape=(10, ))
graph.add_node(Dense(10), input="input", name="output", create_output=True)
model = Graph()
model.add_input("inputA", input_shape=(10, )) …
```
=> Make __call__ work properly for Graph

keras/backend/theano_backend.py, keras/layers/convolutional.py, tests/keras/layers/test_convolutional.py
This PR includes the following convolution layers:
- Convolution3D
- MaxPooling3D
- AveragePooling3D
- UpSampling3D
- ZeroPadding3D
And also the corresponding test functions for these layers.
You can use it like this:
Convolution3D(nb_filters, nb_time, nb_row, nb_col)
See the convolution 3D example in examples/shapes_3d_cnn.py by @MinhazPalasara.
The shape of the underlaying 5D tensor:
`(samples, channels, time, rows, cols)` if dim_ordering='th'
`(samples, time, rows, cols, channels)` if dim_ordering='tf'.
Here I used "time" for the case of movies, of course it can be depth of a 3D volume. I didn't use the notion "depth" because some people use "depth" to stand for filter or channel, the word "depth" sometimes appears in the docstring of Keras when it means channel.
The following …
=> Convolutional layers for 3D

keras/backend/theano_backend.py, tests/keras/layers/test_convolutional.py
The caveat is that things are handled a little strangely when the pool size is even. Effectively, we only pad one side. To implement this, we actually pad both sides, then discard some entries, since Theano doesn't support asymmetrical padding. I believe this is similar to what [TensorFlow does](https://www.tensorflow.org/versions/r0.7/api_docs/python/nn.html#convolution).
Alternatively, we could raise an error when the pool size is even and the border mode is "same".
Closes #1763
=> Implement border_mode="same" for pool2d in Theano

keras/layers/containers.py, keras/layers/core.py
Reset instead of disabling layer and shape cache  in `__call__`
Previously, `__call__` did not get the speed benefits from caching because it disabled it in order to feed the layer new input. This meant that `__call__` could be very slow on complicated structures. This was especially apparent when creating complex Siamese networks.
Now, instead of disabling the caches, we temporarily empty them, then restore the originals when we're done.
To make this work, move caches to properties so that containers can override the implementation to ensure that the cache gets propagated correctly to child layers when it is changed. This way we can guarantee that all layers are pointing at the same cache objects.
=> Enable cache optimization for __call__

examples/imdb_lstm.py, keras/layers/recurrent.py
- make it possible to use RNN dropout with TensorFlow without specifying a batch size
- move initial RNN matrix multiplications outside of recurrent loop / scan -> runs faster
@yaringal @sunil-at-gh any feedback?
=> Possibly faster RNNs

keras/activations.py, keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/layers/core.py, keras/layers/recurrent.py
Found some serious bottlenecks in core parts of Keras:
* Currently `TimeDistributedDense` is implemented using `K.rnn()`, i.e, each vector in the sequence is dot with `W` sequentially, one after the other. Since each time step of the rnn is independent of the previous time step (no state involved), instead of looping through the sequence, it is possible to obtain the output in one single huge matrix operation.
* Similarly, softmax activiation for 3D data is also implemented using `rnn()`, which translates to 1 softmax op per vector.
* Now if you were to combine these two, i.e, `TimeDistributedDense(10, activation='softmax')`, Keras will loop through each of your sequence **twice**, one for the dot operation and the other for the activation. Sad ):
* Instead of making use of shaping ops …
=> Speed up TimeDistributedDense, 3D Softmax and RNNs

keras/wrappers/scikit_learn.py, tests/keras/wrappers/test_scikit_learn.py
Sorry, I don't know how to solve the problem. So I fork again. Please adopt this pull request.
#1825 messages:
Currently, the scikit_learn wrapper can not be used with scikit learn's grid_search api.
Also it's awkward to pass all the parameters used for 'fit', 'predict'... to the init of the wrapper.
I attempt to solve this two problem by refactoring the wrapper. Details are documented in BaseWrapper. Use cases can be seen from the modified check_wrappers.py.
=> Refactoring of sklearn (#same as 1825)

keras/layers/normalization.py
Currently the scaling parameter gamma is uniformly sampled between
-0.05 and 0.05. This also brings the std -0.05 and 0.05 and not to
1 as claimed by the docstring of the BatchNormalization class.
This commit fixes it by initializing gamma to 1.  The same
initialization is used by
(lasagne)[http://lasagne.readthedocs.org/en/latest/modules/layers/normalization.html#lasagne.layers.BatchNormLayer]
=> fix initialization of BatchNormalization

keras/models.py
I'm not sure if this is the entirety of the problem in #1857, but an obvious mistake was not actually using the `nb_worker` and `nb_val_worker` arguments, which this patch fixes.
=> Fixing issue 1857

keras/layers/core.py
Sorry about that. Here's the corrected documentation.
Alternatively, if you want to overwrite the other commit, I amended the https://github.com/kylemcdonald/keras/tree/patch-2 branch in my repo, so if you force merge it you can rewrite history and squash the two commits into one. I don't know if there's a precedent for keeping the history clean with Keras or not, so I wanted to provide the option.
Thanks!
=> changed doc `(input_dim,)` to `(output_dim,)`

keras/backend/tensorflow_backend.py
Results on backwards RNNs were dramatically lower on Tensorflow, compared to Theano. It turns out that in Tensorflow the reversed input is used in conjunction with the mask in non-reversed order. This change reverses the mask when going backwards.
=> Tensorflow: reverse mask on go_backwards.

keras/wrappers/scikit_learn.py
I found that the original design will show no warning when user initialize the wrapper with a parameter that is not listed in the argument list of the build_fn, which make the user unknown that the default value is used. So I add this code to avoid such situation.
=> Add code to avoid user's typo in sk_params

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/models.py
This PR allows the user to pass `kwargs` down to `K.function` when calling `model.compile`.  For the Theano backend, there are useful compile time arguments that are not available via environmental variables or other means.  I don't know if there are equivalent flags for Tensorflow and have ignored them in this case.
Specifically, my use case needs to set `on_unused_input` to something other then `'raise'` (see http://deeplearning.net/software/theano/library/compile/function.html#function.function).  I'm using the `Graph` API and have loss functions that don't depend on `y_true`.  I'd also like to expose the results of intermediate layers in the final output without involving them in the final loss function.  In both cases, Theano throws a compile time error if `on_unused_input='raise'` …
=> Allow passing kwargs down to K.function

keras/layers/advanced_activations.py
A model with ```SReLU``` can't be saved as JSON. Halts with ```TypeError: Not JSON Serializable```. This fixes this issue.
=> Fixed get_config for SReLU.

keras/preprocessing/image.py
Fix the reproducibility when using ImageDataGenerator, there were instances using python random instead of numpy random, while the initializer for the class only sets the seed to numpy.random.
Corrected by changing all instances of python random to numpy random in keras/preprocessing/image
=> Fix Reproducibility with ImageDataGenerator

keras/models.py
Added fix for training h5py dataset on Graph model. It was throwing this error before:
File "train_test.py", line 100, in <module>
M.train_video(folder_name+"/"+"dataset_"+folder_name+".h5",epochs)
File "train_test.py", line 73, in train_video
self.model.fit(d,batch_size=30,show_accuracy=True,nb_epoch=e,shuffle=False)
File "/home/bt0/12CS10038/anaconda2/lib/python2.7/site-packages/keras/models.py", line 1398, in fit
sample_weight_mode=self.sample_weight_modes.get(self.output_order[i])) for i in range(len(self.output_order))]
File "/home/bt0/12CS10038/anaconda2/lib/python2.7/site-packages/keras/models.py", line 130, in standardize_weights
assert sample_weight.ndim <= y.ndim
AttributeError: 'Dataset' object has no attribute 'ndim'
=> Added fix for training h5py dataset on Graph model

keras/models.py
Added a warning in `model.fit_generator()` if the batch generator produces more samples than expected by `samples_per_epoch`. However, the training could continue as before because learned weights would probably not be too affected in most cases.
=> Warn when epoch sees more samples than expected

docs/templates/examples.md
Hi, 
The image captioning example in the documentation appears to be misusing the merge layer and having an extra parameter in one of the GRU layers. I've changed it slightly so it now compiles correctly.
It should fix issue #1522
=> Fixed the image captioning example

keras/backend/theano_backend.py
T.nnet.conv.conv2d has been deprecated in favor of [T.nnet.conv2d](http://deeplearning.net/software/theano/library/tensor/nnet/conv.html#theano.tensor.nnet.conv2d).
I also removed the direct usage of cuDNN ops (they're used by default anyway)
=> Use T.nnet.conv2d interface

examples/deep_dream.py
Finally had a chance to look at the Deep Dream example, and wanted to share a small but helpful modification and share some other unsolicited advice :) In my experience, using pixel jitter doesn't do much, but roll/offset jitter helps a lot. Here's a comparison:
"Bad Trip" pixel jitter
"Bad Trip" offset jitter
"Dreamy" pixel jitter
"Dreamy" offset jitter
Some other things I noticed, but are harder to modify:
* The dream_l2 loss component would probably work better if it was based on the difference between the input image and the current dreamed image. This way it can be turned up to help avoid over-saturation, without making everything darker. (I haven't seen this before, but it could be good to swap L2 or add an additional loss with absolute difference in chroma where chroma is the max …
=> roll jitter instead of pixel jitter for deep dream

keras/engine/topology.py
When saving the weights a TypeError is raised by h5py.
```
[gw1] linux -- Python 3.5.1 /usr/bin/python
def test_merge_overlap():
(X_train, y_train), (X_test, y_test) = _get_test_data()
left = Sequential()
left.add(Dense(nb_hidden, input_shape=(input_dim,)))
left.add(Activation('relu'))
model.add(Merge([left, left], mode='sum'))
model.add(Dense(nb_class))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=nb_epoch, verbose=1, validation_data=(X_test, y_test))
model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=nb_epoch, verbose=2, validation_split=0.1)
model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=nb_epoch, verbose=0)
model.fit(X_train, …
```
=> fix h5py string encoding

keras/models.py
For example the Dense Layer does not have an update attribute, which
results in an error.
=> Sequential: Add defaults for _gather_[list/dict]_attr

keras/engine/topology.py
The `Merge` Layer `concat` mode has problems with `None` in its `input_shapes`.
In my opinion if any `input_shape` is None on the `concat_axis`, then this means that
the actual shape is unknown on this axis, which implies that the `output_shape[concat_axis]` should be `None` as well.
=> Merge: handle none in input_shapes

keras/backend/tensorflow_backend.py
This should make the Tensorflow backend fully mimic the broadcasting semantics of the theano.dot function. Hopefully passing all tests now.
=> Make tensorflow backend fully mimic theano.dot

keras/layers/advanced_activations.py, keras/utils/test_utils.py, tests/keras/layers/test_embeddings.py
LeakyReLU returns a tensor with float64 dtype.
It is stupid, but this line actually produces a float64 array:
```
0.5*np.array(0.2, dtype=np.float32)
```
The theano nnet.relu function does something similar like this with the
LeakyReLU alpha parameter, which lead to a float64 tensor.
The solution is to not cast the alpha to float32.
Furthermore I tighten the `test_utils.layer_test`. It is now
required that the layer's output dtype is equal to the input dtype.
=> Fix LeakyReLU return dtype

keras/backend/theano_backend.py
Previously, strides were required to be smaller than the convolution kernel. Usually, this is what a user wants, but there are edge cases where one might want to do this (for instance, projection shortcuts in Residual Networks).
I don't see any technical reason why the assert was there, but please correct me if I missed something.
=> Remove restriction on strides in theano backend conv2d

keras/utils/np_utils.py
This closes #1461 by avoiding the creation of the numpy matrix completely, which can fail depending on the type of y, or when y is not rectangular.
It's a simple change, but I'd like to try this PR to see how the CI handles it.
Edit: while looking at this function, I noticed it might also make sense to explicitly allocate the array as `dtype=np.float32`, to help avoid a common error.
=> remove creation of np.asarray in to_categorical

keras/layers/embeddings.py
This should fix the issue reported in https://github.com/fchollet/keras/issues/2276
=> Fix for issue #2276

keras/layers/recurrent.py
Typo on "input_spec"
by the way, haven't seen this note in the documentation
> note that the .build() method of subclasses MUST define
> -        # self.input_spec with a complete input shape.
=> Small typo

keras/preprocessing/image.py, tests/keras/preprocessing/test_image.py
This PR addresses issue #2286 to allow the use of ImageDataGenerator with data in the 'tf' format (which is row, column, channel). 
I removed the hard coded indices in the rotation and shifting functions, and adding axis numbers as arguments to these functions. The axis number is set in ImageDataGenerator based on whether it is called with 'tf' or 'th', and then the appropriate index is passed to the utility functions.
There are a couple of unrelated issues with ImageDataGenerator that I didn't address in this PR, hoping to keep this atomic, and come back to those once I have something acceptable on this issue.
Thanks for any feedback.
=> Allow 'tf' ordering in ImageDataGenerator

keras/engine/training.py, keras/models.py, tests/keras/test_sequential_model.py
There are some scenarios where it makes since to limit the size of the generator queue and the functionality is [built out](https://github.com/fchollet/keras/blob/1206120d1084cbe45dc2876f002cb572a97e3844/keras/engine/training.py#L369-L370) but not exposed. This small PR makes these options available to users and closes #2287.
=> Expose max_q_size and other generator_queue args

keras/callbacks.py, tests/keras/test_callbacks.py
This PR closes #2297.
The `_LEARNING_PHASE` tensor was not added to the `feed_dict` passed to the TensorFlow session.
The `model.validation_data` also had too much information (the target validation data).
I chose to append a 0 to the list instead of cutting it to be concise.
I'm not sure about how we could retrieve the info in a cleaner way so let me know if it's ok!
If we add some more metrics it should be taken in account but for now it does the job and it's explicit.
This could be changed to use the information already contained in the list.
=> Added learning phase to callbacks (#2297)

examples/imdb_cnn.py
Following this issue https://github.com/fchollet/keras/issues/2296 i propose this PR.
The mayor optimisation a part of the Max over time are:
- Dropout in the Embedding layer.
- Longer input sequences (400 instead of 100), made possible from the speedup of the Max Over Time.
- Adam optimizer.
Overall it takes 90 to 100 sec per epoch on my laptop CPU and in two epochs it reaches 0.885 accuracy that is a 5 points improvement over the previous implementation. Moreover it requires less memory (300k parameters vs 3M+) since the number of parameters do not depend  by the length of the input sequence anymore.
=> Max Over Time in imdb_cnn.py

keras/engine/training.py
Because standardize_input_data gets called on both model inputs and outputs when using the graph API, we can get this error message when data is missing for model outputs.
This happened to me, and I found it confusing that layers that I thought were outputs were referred to in the error message as "inputs."
=> Change error message in standardize_input_data

docs/templates/getting-started/functional-api-guide.md
I believe `loss_weight` in this part of the docs was a typo. 
At least, changing an argument from loss_weight to loss_weights resolved an error I was seeing in my code :)
=> Fix typo in docs. loss_weight should be loss_weights

keras/metrics.py, tests/keras/engine/test_training.py
The `Model.compile` function [supports custom metrics functions](https://github.com/fchollet/keras/blob/b32248d615abfd7835886a0f50962856f7d7c986/keras/engine/training.py#L612-L618), but this doesn't work because the `keras.metrics` module does not implement a `get` function. I've copied the function from the `keras.objectives` module.
=> Fix support for custom metrics functions

keras/callbacks.py
Using the TensorBoard callback, I get an exception
> TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.
Not sure if this is a 0.8.0 thing, but it seems to be an easy fix.
=> fixed TensorBoard callback

keras/engine/training.py
The attached commit fixes an obvious typo in the check_array_lengths function which has the effect that the consistency of the target arrays doesn't get checked.
On a side note, I'd appreciate having a way to disable the length checks completely as some of my networks legitimately have multiple input arrays of unequal length. However, this pull request contains no such thing, it just fixes the original and intended behaviour.
=> Typo in check_array_lengths

keras/engine/topology.py
The set of valid layer depths may be a strict subset of the set of valid node depths when the computation graph involves non-trivial layer reuse. The current master branch code assumes these two sets are the same, which can cause graph construction to fail.
=> fix layer/node topo sort problem

keras/engine/training.py, keras/metrics.py
It seems that currently the metric 'accuracy' won't work with `sparse_categorical_crossentropy` loss. 
Since #2450 suggests adding an additional dimension with length-1 to target, a reasonable fix would be a new `sparse_categorical_accuracy` function which removes the additional dimension instead of taking `argmax` along that dimension.
=> fix accuracy with sparse_categorical_crossentropy

keras/engine/topology.py, tests/keras/engine/test_topology.py, tests/keras/layers/test_core.py
First PR here, so review carefully!  
I noticed that `Merge()([input1, input2])` didn't work as I expected.  This was because the output tensor wasn't returned in `Merge.__call__`.  This fixes it using the same trick in `Layer.__call__` to get the output tensor (suggests that the `super().__call__` perhaps should be called instead??).
This isn't particularly required (due to the `merge` function existing as used in the docs), but it is nice to have a consistent API.  I added a test using this API instead of the merge API.
Please let me know if I can do anything else for this.
=> fixed Merge Layer functional API

keras/utils/visualize_util.py
Visualizing a model with `show_shapes=True` that has multiple outputs results in the following crash. According to how this is handled for `model.summary()` ([keras/utils/layer_utils.py](https://github.com/fchollet/keras/blob/master/keras/utils/layer_utils.py#L60)), this patch displays the string `multiple` in case of multiple inputs or outputs.
```python
from keras.utils.visualize_util import plot
plot(model, to_file="model.png", show_shapes=True)
```
```
File "./train.py", line 228, in <module>
plot(model, to_file=model_png, show_shapes=True)
File "./venv/src/keras/keras/utils/visualize_util.py", line 60, in plot
dot = model_to_dot(model, show_shapes)
File "./venv/src/keras/keras/utils/visualize_util.py", line 32, in model_to_dot
outputlabels = …
```
=> Fix plot with show_shapes and multiple inputs/outputs.

keras/layers/core.py
This was the simplest/fastest way to take the bias out of the Dense calculation.   
Example use case #2505 : wanting to embed a binary vector rather than an integer list. 
A personal use case: implementing an older algorithm that maintained a theta vector and an average theta vector for RL function approximation.  
In general, there should probably be a way to turn the bias off.  If this boolean method of just taking the bias out of the trainable_weights  isn't agreeable with the Keras style, do you have any suggestions?   this just seemed a bit easier than threading the rest of the code.
=> adding a disable_b boolean to Dense

examples/inception_v3.py, tests/keras/preprocessing/test_image.py
During CI, `test_image.py` sometimes results in path non-exist problem due to parallel issue. Such  as:
```
IOError: [Errno 2] No such file or directory: 'test_images/_0.jpeg'
```
Since the `test_images` folder has been removed. Anyone also faces this problem during your PR? 
Therefore, I modify `test_image.py` into class style and save test images in class attribute rather than save in `test_image` folder. Also use `tempfile` module to create temporary folder for `save_to_dir` to solve parallel problem.
=> Fix test_image path non-exist error in ci-travis

keras/engine/training.py, keras/utils/data_utils.py
This might be specific to Python 2.7, but the some exceptions that pass through `Model.fit_generator`, for example, are not very useful because they are first caught and then re-raised by `raise e`. This removes the original stack trace, which makes it difficult to find the source of the original exception. This patch re-raises the exception while keeping the original stack trace.
=> Re-raise exceptions to preserve stack trace

docs/templates/activations.md, keras/activations.py, keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, tests/keras/test_activations.py
I have tried implementing the softsign activation function proposed by (Bergstra et al., 2009).
My net of LSTMs compiles and runs, but during training it outputs ```loss: nan``` and the net doesn't seem to output very much of anything. I'm not sure what is going wrong.
The formula is ```x/(1 + |x|)```
As Glorot says:
> The softsign is similar to the hyperbolic tangent (its range is -1 to 1) but its tails are quadratic polynomials rather than exponentials, i.e., it approaches its asymptotes much slower.
Some say that softsign is better than tanh because it is faster and less prone to saturation.
=> Softsign activation function

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/engine/topology.py
This function parallels the existing batch_set_value function. I've also changed a few places in topology to use the new function.
For tensorflow, this can provide big speed-ups when, for example, running `get_weights` on a big model. I have a complicated multi-gpu model where `get_weights` (via `save_weights`) currently takes a few minutes to run the first time. With this PR, it runs in about 10 seconds.
=> Add `batch_get_value` to backends

keras/backend/theano_backend.py
softsign was moved from theano.sandbox.softsign to theano.tensor.nnet.nnet
=> fix soft sign deprecation warning

keras/models.py
Was trying to use the `get_config` method on `Sequential`, and was confused that I couldn't load the resulting config via `models.model_from_config`.
The behaviour of `Sequential.get_config` seems like a strange inconsistency but it also seems very intentional, so I assume it's about backwards compatibility.
edit:
the more I think about it the stranger it is that `Sequential` has this special behaviour. I'd like to be able to get the config as a dict, and the best way to do that right now is a round-trip through JSON.
One possible option would be to add a `legacy=True` argument to `Sequential.get_config`? If passed `False` we could return a dict.
I presume there's some reason that the `normalize_legacy_config` function is defined in `from_config` and not `get_config`, although it isn't …
=> clarify use of old-style get_config method

keras/preprocessing/image.py
index_array should be initialized when self.batch_index is zero.
=> Fix initialization of index_array

docs/templates/getting-started/faq.md
This closes #2664 where @GelliFrancesco asks for more info about what was meant by "just use the functional API".
I would show an example of getting a decoder too, but I don't see a simple way to do that without doing something like:
```python
encoded_input = Input(shape=(32,)
third = Dense(512)(merge(second, encoded_input))
```
Otherwise I get `UserWarning: Model inputs must come from a Keras Input layer, they cannot be the output of a previous non-Input layer.`
=> functional API intermediate output doc in faq

keras/layers/embeddings.py
From the documentation it is not entirely clear that if mask_zero is set
to True, the input_dim argument should be equal to the size of the
vocabulary + 2, as index 0 cannot be used anymore. Include this as a
comment in the docstring.
(This behaviour seems a bit strange, as it has as a consequence that the
first column of the weights of the embeddings will never be used or
updated. The resulting network thus has a redundant set of parameters).
=> Clarify docstring Embedding

keras/layers/normalization.py
We should refer the paper accepted in ICML 2015, instead of arXiv.
When I translated normalization.md into Japanese, I noticed that the reference was old :)
=> Update the reference of Batch Normalization

keras/engine/topology.py
In issue #2672, zero division problem was reported and it can be reproduced by:
```python
a = np.reshape(np.array([0, 0]), (1, 2, 1)) # zero vector has zero length
b = np.reshape(np.array([0.6, 0.8]), (1, 2, 1))
input_a = Input((2, 1))
input_b = Input((2, 1))
cos = merge([input_a, input_b], mode='cos', dot_axes=1)
model = Model(input=[input_a, input_b], output=[cos])
result = model.predict([a, b])
```
`K.maximum` can easily solve the problem.
=> Fix zero division in merge mode='cos'

keras/engine/topology.py, keras/engine/training.py
I frequently load and retrain models serialized weeks and months earlier, and it's useful to know the `optimizer` and `loss` + other args that a model was compiled with. Other people have mentioned this as well.
Thought this was simple enough that I'd take a stab. This doesn't effect any existing functionality, but it lets me manually get the required information out of a json/yaml file.
I also took the liberty of saving the keras version number, which was mentioned in a `TODO` comment.
if @fchollet or anyone else has a better idea for how to do this (or why not to do this) I'm happy to revisit.
(fixes #2498)
edit: failing a pep8 test, I'll take a look in a bit and push again
=> save keras version & compile args when serializing models

examples/variational_autoencoder.py
This is the simplest VAE example i've come across. nice work!
The only trivial nit I had was the naming of `z_log_sigma` which I had to read twice (since the corresponding mean variable wasn't called `z_mu`
=> rename z_log_sigma to z_log_std to match z_mean (which is not z_mu)

examples/babi_memnn.py, examples/babi_rnn.py
As mentioned in #2369, there are download issues from Python for `babi_rnn.py` and `babi_memnn.py`. This PR shows instructions on how to manually download it in case of problems.
```
$ python babi_rnn.py 
RNN / Embed / Sent / Query = <class 'keras.layers.recurrent.LSTM'>, 50, 100, 100
Downloading data from http://www.thespermwhale.com/jaseweston/babi/tasks_1-20_v1-2.tar.gz
Error downloading dataset, please download it manually:
$ wget http://www.thespermwhale.com/jaseweston/babi/tasks_1-20_v1-2.tar.gz
$ mv tasks_1-20_v1-2.tar.gz ~/.keras/datasets/babi-tasks-v1-2.tar.gz
File "babi_rnn.py", line 150, in <module>
path = get_file('babi-tasks-v1-2.tar.gz', origin='http://www.thespermwhale.com/jaseweston/babi/tasks_1-20_v1-2.tar.gz')
File …
```
=> Add download error suggestion for babi_rnn.py and babi_memnn.py.

keras/engine/topology.py, keras/utils/layer_utils.py
Saw @joelthchao 's reply in https://github.com/fchollet/keras/issues/2757 , so tried `model.print_summary()` , which doesn't print my network model well, cause when layer name is long, and dimension is also relatively long, it can't print whole info. So here's a small fix, makes the `print_summary` function more flexible.
=> changeable print_summary

keras/initializations.py, tests/keras/test_initializations.py
This PR addresses an issue in the calculation of `fan_out` in the `get_fans` function used in the initialization module. For convolution layers the number of output connections should be referring the number of "inputs" with respect to the backward pass; however, currently this refers to the outputs with respect to the forward pass. For a reference see equation (14) in this paper from He et al (http://arxiv.org/abs/1502.01852). This is also how `fan_in` and `fan_out` are calculated in Lasagne. 
Of course, weight initialization can be more of an art than a science so if there was a reason to just use the output shape I'd be interested to hear and feel free to close this PR. Regardless, thanks for the wonderful library!
Just for an idea of the impact of this change here is the output of …
=> Correction to fan_out initializaiton

keras/engine/topology.py
This fixes a bug I introduced during review of #2690, which caused the loss function to be incorrectly serialized. 😞
=> correctly serialize loss function (one liner)

docs/templates/preprocessing/image.md
Inside ImageDataGenerator, False is the default value for featurewise_std_normalization and featurewise_center. Document corrected to show the correct default values.
=> Default values corrected for featurewise_std_normalization and featurewise_center

keras/regularizers.py
Fix #2871
the below sample works fine:
```python
from keras.layers import LSTM
from keras.models import Sequential, model_from_yaml, model_from_json
from keras.regularizers import l2
model = Sequential([LSTM(20, input_shape=(2,3), W_regularizer=l2())])
json_str = model.to_json()
model_from_json(json_str)
yml_str = model.to_yaml()
model_from_yaml(yml_str)
```
=> Fix YAML serialization when using Regularizers

keras/backend/theano_backend.py
Uses can run into this problem while using functions at Theano backend that include RandomStreams. 
Currently, in theano_backend.py, we use this code to generate a random seed for RandomStreams
```
if seed is None:
seed = np.random.randint(10e6)
rng = RandomStreams(seed=seed)
```
However, RandomStreams does not take 0 as an input for seed and using numpy.random.randint(10e6) can potentially generate 0 as an output (even though it is very unlikely) and it will result in the following error:
```
ValueError: ('seed should not be 0', 0)
```
So I modified the code to be
```
if seed is None:
seed = np.random.randint(1,10e6+1)
rng = RandomStreams(seed=seed)
```
and seed will have a new range [1,10e6] compared to the previous range [0,10e6-1] and we can avoid running into ValueError.
=> fix bug: change seed range for RandomStreams in Theano

keras/callbacks.py, keras/utils/generic_utils.py
Limit progress bar update rate in verbose=1 mode. This patch allows to
reduce terminal I/O throughput while keeping reasonable high visual
update rate (defaults to 100 refreshes per second). It helps greatly
when working with large but simple data sets with small batches, which
leads to millions of relatively useless screen updates per second. Also
it helps to keep network traffic at reasonable rates, which
exceptionally useful within laggy networking conditions when using
keras over telnet/ssh, and improve web browser responsibility when
using keras within Jupyter Notebook.
=> limit progress bar update rate

keras/layers/core.py, keras/layers/recurrent.py
Empty lines lead to formatting errors in [http://keras.io/layers/recurrent/](http://keras.io/layers/recurrent/).
Missing newlines lead to formatting errors in [http://keras.io/layers/core/](http://keras.io/layers/core/).
=> fixed formatting error in the docstring

keras/layers/core.py
Since MaxoutDense does not have activation it might be misleading to include "activation" as one of the arguments in the function docs.
=> MaxoutDense no activation; incorrect docs

keras/wrappers/scikit_learn.py
KerasClassifier was returning a single probability when n_outputs was 1.
However, scikit requires the predict_proba method to return 2 columns in the case of binary classification.
This is needed for using threshold based evaluation metrics such as roc_auc.
Fixes #2864
=> Fix predict_proba method of KerasClassifier

keras/engine/training.py
this is a quick fix for #2852. 
I don't really know what the expected behaviour is in situations where there are multiple output shapes; I defer to @fchollet for a sense of whether this is okay in that case.
=> fix issue with shape validation when using sparse_categorical_crossentropy

keras/engine/topology.py
Hi, the parameter `output_shape` for `merge` function in `topology.py` requires exactly output shape including *batchsize* when `mode` is callable, but that is not mentioned in doc. I added that.
=> Fix description about parameter `output_shape` for function `merge`

keras/preprocessing/image.py
Since the file extension of images can be either upper case or lower case, especially for those downloaded from the web, I suggest to use fname.lower().endswith('.' + extension) in DirectoryIterator to make it case insensitive.
=> Make DirectoryIterator case insensitive

keras/engine/training.py
While users use a shared layer to get two different outputs but have one same name, the batch_logs/epoch_logs will only left one loss, because it's a `dict`.
```
train_d = np.random.rand(128, 64)
test_d  = np.random.rand(2, 128, 32)
x = Input(shape=(64, ))
a = Dense(32)(x)
b = Dense(32)(x)
shared_dense = Dense(32, name='shared_dense')
out1 = shared_dense(a)
out2 = shared_dense(b)
model = Model(input=x, output=[out1, out2])
model.compile(optimizer='rmsprop', loss='mse')
his = model.fit(train_d, [test_d[0], test_d[1]])
```
The code above will get output like below, but it should have two shared_dense_loss.
To solve this problem, I rename the duplicates name by appending it a number. Then it works well:
=> fix bug: rename duplicated loss name

keras/backend/theano_backend.py, tests/keras/backend/test_backends.py
This issue is due to an unexpected loss of dimensionality when
composing the backend tensor operations "reshape" and "squeeze"
when there are dimensions of length 1.
For example, using a Theano backend the following fails with a
complaint about dimension mismatch:
UpSampling1D(2)(MaxPooling1D(2)(Reshape((2,1))(Input(shape=(2,)))))
The issue arises due to the conflict of two behaviors specific
to the Theano backend:
-   Reshape uses Theano's reshape function. Theano's reshape
automatically makes dimensions with length 1 "broadcastable"
-   MaxPooling1D's implementation class _Pooling1D has a call method
which uses a dummy dimension which it has to remove. The manner
in which this dummy method is removed it to call "squeeze(x, axis)"
from the backend. The squeeze implementation tells Theano …
=> Fix 1D convolution layers under Theano backend

keras/optimizers.py, tests/keras/test_optimizers.py
Hello @fchollet, this is my first ever PR sorry for any mistakes. 
in my experiments I tried the combination of Adam and NAG from [here](http://cs229.stanford.edu/proj2015/054_report.pdf), and it was better than pure Adam optimizer, today I added it to Keras optimizer module and created this PR. I hope it will be helpful for someone =)
Here is some small experiments which I did, but authors from the report did bigger experiments.
The test passed ok for Theano backend, I don't have TF installed, but if it is necessary I can install it and check.
This is my results comparison for default CIFAR cnn demo from examples folder. (Mini batch = 128, the rest is default).
SGD + NAG:
Using gpu device 0: GeForce GTX 970 (CNMeM is disabled, cuDNN 5004)
X_train shape: (50000, 3, …
=> Nadam optimizer and test for it added

examples/deep_dream.py
In the example for Deep Dream, the name of an attribute `grad_values` in Evaluator object was wrong.  I fixed it.
=> Fix initial variable in Evaluator.

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/layers/normalization.py
Introduce `K.var` so that the standard deviation computation can
be made numerically stable. Instead of
K.std(x)
the user is able to write
K.sqrt(K.var(x) + self.epsilon)
avoiding a division by zero in the gradient computation of `sqrt`.
=> Resolve #2960

keras/datasets/reuters.py
I can't load `word_index` of Reuters in python3 (This function is vaild in python 2.7.11.).
In my environment:
- OSX 10.10.5 (yosemite)
- python 3.5.1 (python or anaconda3-4.0.0 via pyenv)
My error message is below:
```
>>> from keras.datasets import reuters
>>> word_index = reuters.get_word_index(path="reuters_word_index.pkl")
File "/Users/nzw/.pyenv/versions/3.5.1/lib/python3.5/site-packages/keras/datasets/reuters.py", line 67, in get_word_index
return cPickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 0: ordinal not in range(128)
```
So I fix it.
thanks.
=> Fix get_word_index

keras/callbacks.py, tests/keras/test_callbacks.py
An EarlyStopping callback object has internal state variables to tell it
when it has reached its stopping point.  These were initialized in `__init__()`,
so attempting to re-use the same object resulted in immediate stopping. This
prevents (for example) performing early stopping during cross-validation with
the scikit-learn wrapper.
This patch initializes the variables in `on_train_begin()`, so they are re-set
for each training fold.  Tests included.
=> Allow re-use of EarlyStopping callback objects

keras/layers/recurrent.py
Hi,
i think i found a typo in the first example of the recurrent layer documentation:
```python
model.add(LSTM(32, input_shape=(10, 64)))
```
Because of `return_sequences=False` (default value), i think only the last output is returned.
```python
print model.output_shape
``` 
yields on my system (Using Theano backend)
`(None, 32)`
Or did i miss smth.?
Best,
André
=> doc: fix example for recurrent layer

keras/callbacks.py
On method on_epoch_end, to add new keys to the history dict, first it is
verified if a key is not on the history dict and if that is the case, a new key
is created on the history dict with an empty list as value.
However, this operation search for a key twice in the dict. This same behavior
can be achieved in a single step using dict setdefault method.
=> Avoid double key lookup on callback.py

keras/backend/tensorflow_backend.py
It may be minor details.
Since this function is defined in only TensorFlow backend, this comment seems to be clear for docs.
=> Add comment for a note of caution

keras/engine/training.py
I accidentally ran an example with empty batches. Of course that is not useful, but in any case, looking at the code, epoch_logs = {} should clearly be moved in front of the loop.
It is only used in the last batch to collect logging information, which is only one useful initialization in the loop. The others are useless (nothing happens to epoch_logs), therefore, it should be safe and correct to move out of the loop.
Note:
The first error I got was UnboundLocalError: local variable epoch_logs referenced before assignment.
After this fix, I got the much more useful error message about incorrect input data dimensions:
Error when checking model input: expected input_1 to have 4 dimensions but got array with shape (0, 1).
=> Moved epoch_logs = {} before batch loop to avoid UnboundLocalError.

keras/preprocessing/image.py
The documentation says that [1]: 
> If [classes are] not provided, the list of classes will be automatically inferred (and the order of the classes, which will map to the label indices, will be alphanumeric).
However, the code was adding classes in the order `os.listdir` returned them. This commit alphanumerically sorts the sub-directories before mapping them to label indices.
[1] http://keras.io/preprocessing/image/
=> fix: Sort subdirs before mapping them to classes.

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/engine/topology.py, keras/layers/core.py, tests/keras/backend/test_backends.py, tests/keras/layers/test_core.py
I've seen a couple other people who seem like they need masking in merged layers. As far as I can tell, masking is only required for the `'sum'` and `'ave'` modes (and lambda functions as well probably, but those are a case of their own). I've only tested this fork with Theano + Python 2.7, but it seems to be working.
I did notice some weird behavior with the `Masking` layer. If given this data,
input a data:
[[ 1.  1.  1.]
[ 1.  1.  1.]]
input b data:
[[ 1.  1.  0.]
[ 0.  0.  0.]]
for some model that adds the inputs but masks 0's in the second input,
input_a = Input(shape=(3,), dtype='int32')
input_b = Input(shape=(3,), dtype='int32')
masked_b = Masking(mask_value=0)(input_b)
merged = merge([input_a, masked_b], mode='sum')
it gives
[[ 3.  3.  2.]
[ 0.  0.  0.]]
Is this the correct …
=> Support for masking in merged layers

keras/engine/training.py
Currently, the model will default to categorical accuracy when the loss function is binary cross-entropy. It makes more sense to use binary accuracy instead.
=> Use binary accuracy for binary cross-entropy loss

keras/engine/topology.py
Back when I wrote the cos mode it worked only with 2D tensors so it did not need the `dot_axes` argument. Now that cos mode uses this argument, we have to do sanity check in cos mode too.
Edit: 
Fix output shape in cos mode too.
=> Validate dot_axes argument in cos mode and fix output shape

keras/layers/core.py
Lambda has a weird thing right now that either needs to be pointed out or changed.
In this PR, I point it out but I'd be glad to change it as well.  
Essentially: if you pass in a tuple into `output_shape`, Keras assumes `(nb_samples,)+output_shape`.  If you pass a function into output shape, Keras assumes `tuple(output_shape())`.
=> Lambda output shape

keras/backend/common.py
The method get_uid on common.py first check if a prefix is in _UID_PREFIXED dict
and if it is not, a variable is added to the dict.
However, using a defaultdict, this check is no longer necessary.
=> Use defaultdict for _UID_PREFIXES

keras/engine/topology.py
Merge's `get_output_shape_for` returns an invalid shape when using a callable mode and a fixed output shape. `input_shape` is a list of shape tuples, so the returned output shape will have have a tuple as its first dimension.
=> fix get_output_shape_for in Merge, when mode is callable

keras/layers/recurrent.py
`Recurrent.get_initial_states` contains some awkward machinations to get an `initial_state` vector of the appropriate size filled with zeros, which can only be done at graph execution time because the batch size is needed.
The current implementation uses a call to `K.zeros`, which when using the TensorFlow backend creates a Variable.This is not desirable, because
* By default all Variable objects will be collected and trained by TF optimizers, wasting time computing the (zero) gradients, and
* By default all Variable objects will be serialzed and saved when using the `tf.train.Saver`, wasting space.
The fix is simple: use only `K.zeros_like`, which creates only operations in the graph, not extra Variables.
=> Create initial_state tensor filled with zeros without use of K.zeros

keras/engine/training.py
Small change to use the Keras data type on pre-allocations that use numpy. This is more correct and memory efficient.
=> add dtype to zeros and ones allocations in training.py

keras/engine/training.py
Was incorrectly reporting the `loss` argument instead of the `loss_weights` argument when an exception related to loss_weights was thrown.
=> Fix to error message in exception

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/layers/convolutional.py, keras/utils/np_utils.py, tests/keras/layers/test_convolutional.py
Atrous convolution(a.k.a dilated convolution or convolution with holes), both backend(theano and tensorflow) are supported. Just add `atrous_rate` to your regular Convolution2D layer.
```python
model.add(AtrousConv2D(64, 3, 3, atrous_rate=(2,2), border_mode='valid', input_shape=(3, 256, 256)))
```
Differences with theano and tensorflow backend:
* With theano backend, you can do filter dilation(>1) and filter stride(>1) at the same time. But if you are using tensorflow backend, the stride is currently missing in [tf.nn.atrous_conv2d](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/nn.md#tfnnatrous_conv2dvalue-filters-rate-padding-namenone-atrous_conv2d). So you can only do dilated convolution with stride=1 with tensorflow.
* With …
=> Support atrous convolution(a.k.a dilated convolution)

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/utils/np_utils.py, tests/keras/backend/test_backends.py
stop gradient operations are used for complicated graphs such as RNNs that feed previous outputs as new inputs:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/seq2seq.py#L103
=> stop gradients

keras/models.py, tests/keras/test_sequential_model.py
Update inbound nodes after popping last layer. Otherwise `output_shape` of the model will not be updated.
```python
model.add(Dense(10, input_dim=10))
model.add(Dense(20))
print model.output_shape  # >> (None, 20)
model.pop()
print model.output_shape  # >> (None, 20) 
```
Also since `pop()` is sort of a hack, I thought it would be good to have a test.
=> Bug fix + test - Sequential.pop()

keras/layers/normalization.py
The BN layer use ```set_weights``` to load weights provided by user, and in ```set_weights```:
```python
params = self.trainable_weights + self.non_trainable_weights
```
In BN, the trainable_weights are Gamma and Beta, non_trainable_weights are Mean and Std, So it important to point out that the weights list must be organized as [Gamma, Beta, Mean, Std] so that it could work properly. Cause by defualt, people may want to organize their weight list as [Mean, Std, Gamma, Beta], this is just the computation order of BN.
The wrong-order list won't get any warnings or errors cause the shape of these 4 parameters are exactly same.
I think this doc will be helpful.
=> add doc for layers/normalization/BatchNormalization

docs/templates/backend.md
The `print(backend._BACKEND)` syntax still works under Python 2 as well in this case.
=> Small python3 compat fix in backend doc

keras/backend/tensorflow_backend.py, keras/layers/convolutional.py, tests/keras/layers/test_convolutional.py
This PR add TensorFlow support for `UpSampling3D` and `Zeropadding3D` layers by adding `resize_volumes` and `spatial_3d_padding` to the Tensorflow backend.
Note that unlike `UpSampling2D` with TensorFlow backend, `UpSampling3D` does not perform any interpolation (There is no `tf.resize_volumes` yet)
=> Add Tensorflow support for UpSampling3D and ZeroPadding3D layers

examples/pretrained_word_embeddings.py
Current implementation set the # of rows in `embedding_matrix` to be `1 + len(word_index)`, i.e. # of unique tokens in the text. This could be a memory waste if the `MAX_NB_WORDS` is set to be much smaller, e.g., 20000 in this case. 
Changes to make the size of `embedding_matrix` to be the min of the two numbers.
=> make examples/pretrained_word_embeddings.py more memory efficient

examples/variational_autoencoder.py
A number of changes:
1. Switch from Lambda to merge, otherwise code will not run in keras==1.0.5.
2. Rename z_log_std to z_log_var in order for the objective function to make sense
3. Adjust reparameterization trick to reflect use of z_log_var, not z_log_std
4. Remove epsilon_std, since (standard) VAE uses isotropic gaussian prior.
5. Re-balance the weighting of KL and reconstruction terms
6. Use adam instead of rmsprop
7. Increase hidden unit size to improve model
8. Increase batch size to speed up training
=> Fix VAE example

examples/stateful_lstm.py
**This concerns issues #1820 and #2328 among others:**
The argument `period` was being used in a misleading way. Setting `period=25` would NOT make the period of the resulting cosine data 25, it would make it around 1000 instead. After this fix, the argument `period` does what it is supposed to do. I also changed its default value to 1000 so that the generated data with the new version are close to what was generated by the old version.
=> in stateful_lstm.py example, use of period fixed, default period set to 1000 (minor changes)

keras/backend/tensorflow_backend.py
Usage of the tf.assign() function in the set_value() and batch_set_values() functions creates new nodes on the Tensorflow graph which can eventually lead to memory overflow.
Therefore, the function has been rewritten using placeholders and feed_dict to avoid this issue.
=> remove usage of tf.assign() in part of tensorflow backend (#3316)

keras/layers/embeddings.py
In functional API, the user has to specify that input to an Embedding layer is int, which is redundant because Keras already has information about the input dtype in input_spec :  
```python
a = Input((100,), dtype='int32')
b = Embedding(....)(a)
```
=> Embedding layer - cast float to int implicitly

keras/callbacks.py
The latest TensorFlow release broke the version check in `callbacks.TensorBoard` once again, `'0.10.0rc0'` compares lexicographically less than `'0.8.0'`:
``` python
>>> tf.__version__
'0.10.0rc0'
>>> tf.__version__ >= '0.8.0'
False
```
Thus once again TensorFlow issues this warning: "Passing a `GraphDef` to the SummaryWriter is deprecated. Pass a `Graph` object instead, such as `sess.graph`." (See previous discussions and fixes here: https://github.com/fchollet/keras/issues/2570 https://github.com/fchollet/keras/pull/2574 https://github.com/fchollet/keras/commit/ebbc4d9fb83e36b1f19ffce1b8e5c0386eeb214a).
To (hopefully) fix this issue for good I propose using `pkg_resources.parse_version`.  Quoting from the [docs](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#parsing-utili …
=> Compare versions through pkg_resources.parse_version

keras/layers/recurrent.py
Added correct information for how to enable rnn statefulness on functional models (or rather models built with the functional API) with 1 or more Input layers.
=> Added to rnn statefulness doc concerning func api

examples/variational_autoencoder.py
As discussed in #3373, the Variational Autoencoder example is not working properly due to the extremely small reconstruction loss which looks introduces in the commit [f6bcaffe4a6](https://github.com/fchollet/keras/commit/f6bcaffe4a67012b4b067038bdbc5d43b807540b). This code simply brings back the multiplication of `original_dim` in the xent_loss term to match the size with the KL loss.
Thanks,
Shuhei
=> Correcting the reconstruction loss in Variational Autoencoder example.

keras/layers/advanced_activations.py
Fix https://github.com/fchollet/keras/issues/2871#issuecomment-237365465
The problem occurs because PyYAML can't recognize numpy's data types.
=> Fix YAML serialization for Advanced Activations

keras/preprocessing/image.py
When ImageDataGenerator attempts to write arrays to image files (if one is using the save_to_dir arg), it divides by the max value in the array as part of its conversion to pixels. If the entire array was 0's, the process fails because it cannot divide by 0. In this case, the process can be skipped because it does not effect the augmented data.
For my own testing with the occasional completely blank (0s) image mask, I wrote this fix for the division by zero problem on blank images. If it looks appropriate, please merge it with the repo. Thanks!
=> Skipped a division by zero in ImageDataGenerator that occurs with 0'ed arrays

keras/layers/convolutional.py
Currently, the UpSamplingND layers do not work when specifying an input shape of None.
This code:
m = Sequential()
m.add(Convolution2D(1, 3, 3, border_mode='same', input_shape=(1, None, None)))
m.add(UpSampling2D(size=(2,2)))
Gives the following output:
File "keras_test_input.py", line 11, in <module>
m.add(UpSampling2D(size=(2,2)))
File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.7-py2.7.egg/keras/models.py", line 307, in add
output_tensor = layer(self.outputs[0])
File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.7-py2.7.egg/keras/engine/topology.py", line 511, in __call__
self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.7-py2.7.egg/keras/engine/topology.py", line 569, …
=> Upsampling layer fix to work when input shape is None

examples/imdb_fasttext.py
This commit implements a fasttext example. Fasttext is a very efficient text classification model proposed by A. Joulin, E. Grave, P. Bojanowski and T. Mikolov in the paper "[Bag of Tricks for Efficient Text Classification](https://arxiv.org/abs/1607.01759)". The idea is quite similar with SkipGram, however, instead of predict the current word based on the context words, fasttext predict the category of the document based on the average of all word embeddings in the document.
I have evaluate fasttext model using the IMDB datasets. The fasttext can achieve accuracy of 88.15% after 5 epochs in 70s on a machine with Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, while the CNN achieve accuracy of 88.10% after 1 epochs in 272s.
=> Implement a fasttext example

examples/mnist_hierarchical_rnn.py
Hierarchical RNNs can perform multiple levels of modeling. As in [ A Hierarchical Neural Autoencoder for Paragraphs and Documents ](https://web.stanford.edu/~jurafsky/pubs/P15-1107.pdf), a sentence is first encoded into the a sentence vector by the first layer of a rnn, then the second LSTM takes consecutive sentences vectors as input and encodes the sentence vector sequence into a paragraph vector
Hierarchical RNNs can be done elegantly in keras using TimeDistributed Wrappers and reshaping the Data into 4D. The hierarchical mnist model first encodes columns of pixels into a column vector, then encodes the column vector sequence into a image vector. Trained on MNIST, the training and validation accuracy reached 98% in 5 epochs.
=> Implement a hierarchical rnn mnist example

keras/engine/training.py
multiprocessing.Queue.qsize() raises NotImplementedError on OS X, and the maximum queue size is already being set when the queue is constructed in the multiprocessing case, so skip the qsize() test if pickle_safe is True.
=> Allow multiprocessing on OS X

docs/templates/datasets.md, keras/datasets/reuters.py, keras/engine/training.py
Changed the imbd dataset documentation to reflect all current options - most importantly the removal of the test_split option. I also included other options (oov_char, etc), though they are rather niche, so perhaps their lack of inclusion was intentional. I also added a docstring to reuters load_data for clarity.
=> Minor imbd dataset documentation update, added docstring to reuters

keras/engine/training.py
As discussed in #3493, fit_generator could use locks for thread safety.
=> Fixing #3493: Stop ignoring ValueErrors in fit_generator

examples/imdb_fasttext.py, keras/engine/topology.py
@farizrahman4u Just wonder if there is a bug in line 1225. When there is only one dot_axes specified in the Merge layer in the dot mode, should not we change the dot_axes = [dot_axes, dot_axes] just as done in line 1147-1148? After the this fix, the following code can be ran correctly(only specify one dot_axes) otherwise will fail:
```
model_word = Sequential()
model_word.add(Embedding(1e4, 300, input_length=1))
model_word.add(Reshape((1,300)))
models.append(model_word)
model_context = Sequential()
model_context.add(Embedding(1e4, 300, input_length=5))
model_context.add(Reshape((5,300)))
models.append(model_context)
model.add(Merge(models, mode='dot', dot_axes = 2))
print model.layers[-1].output_shape
model.add(Reshape((5,)))
print model.layers[-1].output_shape …
```
=> Fix a issue when only specify one dot_axes for in the Merge layer in the dot mode

keras/backend/theano_backend.py, keras/layers/normalization.py
Following on from https://github.com/fchollet/keras/pull/3260, use Theano's new CuDNN implementation of batch normalization, falling back if it is unavailable or we are not running on a GPU.
=> Use Theano's CuDNN implementation of batch normalization

keras/backend/theano_backend.py
fix batch norm causing NaN for many datasets, fixes issue #3475
=> Fixing NaN caused by batch-norm for theano Update theano_backend.py

keras/wrappers/scikit_learn.py, tests/keras/wrappers/test_scikit_learn.py
This PR proposes two small changes to `keras/wrappers/scikit_learn.py`
According to the documentation, the sklearn classification wrapper `KerasClassifier` should accept labels for the `fit` and `score` methods in the following two formats:
1. (n_samples,)
2. (n_samples, n_outputs)
In `fit`, the 1. format is transformed to the 2. with the following code:
```python
loss_name = self.model.loss
if hasattr(loss_name, '__name__'):
loss_name = loss_name.__name__
if loss_name == 'categorical_crossentropy' and len(y.shape) != 2:
y = to_categorical(y)
```
The same code should be in `score` but is currently missing. I have added the code.
According to the documentation (and sklearn standards), the `predict` method of a regressor returns an array of shape `(n_samples,)`. …
=> Support sparse labels and squeeze prediction outputs in sklearn wrapper (bugfix)

keras/layers/convolutional.py, tests/keras/layers/test_convolutional.py
This is a new feature that is being discussed in https://github.com/fchollet/keras/issues/3162. In this repo, https://github.com/keunwoochoi/keras_cropping_layer, I uploaded example code. I tested Cropping2D on theano/tensorflow, I haven't tested it on `Cropping1D/3D` yet. I would like to know if it makes sense to add this feature first before testing 1D/3D cases. 
Some questions are: 
* Is the API okay? I think there should be some non-symmetric cropping cases. (At least I need it but I am not working on image, so..)
* In `Cropping1D`, `self.input_spec = [InputSpec(ndim=3)]` exists in `__init__()`, but it seems like this layer needs overriding `build()`as below:
```python
def build(self, input_shape):
self.input_spec = [InputSpec(shape=input_shape)]
```
Does it mean that the line in …
=> add cropping1d/2d/3d layers

keras/layers/recurrent.py
Avoid concatenating too many tensors (~100) when the actual logic is to tile, as this might cause `Blocks nested too deeply` error in large models (theano backend, Windows). This is actually an issue with Microsoft's Visual C compiler.
=> Bug fix : RNNs

keras/layers/convolutional.py
Implemented Deconvolution2D layer was missing documentation, which is important especially because it's required to infer output shape for this layer explicitly and pass as a parameter.
One of the raised issues - #3540 
Added standard docs, references and guidelines to the output shape calculation.
Also fixed typo in the exception message.
=> Docs update for Deconvolution2D layer

keras/layers/convolutional.py
Follow-up https://github.com/fchollet/keras/pull/3509
`Cropping3D` should accept 5D tensor instead of 4D.
Also removed some unnecessary whitespace.
=> Fix Cropping3D InputSpec

setup.py
`visualize_util.plot` requires pydot-ng. Added it to extras_require.
=> Add pydot-ng dependency to extras_require for visualize_util

keras/engine/training.py
The evaluate function was called with the default batch_size (32).
So it doesn't work when your GPU does not handle a batch_size of 32.
=> Bug fix, batch_size set instead of default one

keras/backend/tensorflow_backend.py
Docstring says "at least 3D", but current code is hard coded for 3D input.
=> TF dynamic RNN : Allow sequences of ndim > 3

keras/backend/tensorflow_backend.py
By default TensorFlow allocates all gradient matricies on gpu:0, which makes it pretty much impossible to do parallelize a large model.
colocate_gradients_with_ops puts these matricies next to the operations, allowing you to split your model across multiple GPUs. I ran into this issue myself and this fixed it for me.
I think it's also meant to set gradient computations to be done on the device where the operations are stored, but my belief about that comes from https://github.com/tensorflow/tensorflow/issues/2441
I'm not sure why this isn't the default in TF, so I'm not sure if this should be behind a flag or something, but having to make my own patches to keras to do multi-GPU training seems like the wrong answer.
=> Enable colocate_gradients_with_ops=True

keras/layers/core.py
Lambda layer's function can have more arguments than just the input tensor.
=> Fix lambda layer docstring

keras/engine/topology.py, keras/layers/convolutional.py, keras/layers/core.py, keras/preprocessing/sequence.py, keras/utils/data_utils.py, pytest.ini, tests/keras/preprocessing/test_sequence.py, tests/keras/test_activations.py
> Test improvements: stricter PEP8 checks in our PEP8 test. That's an easy one. In particular, we need to check for missing spaces after commas, trailing spaces, this kind of thing.
I removed trailing whitespace, missing whitespace after, and multiple spaces after from the ignored list of pep8 rules. 
There are a few more rules in regards to whitespace around operators but wasn't sure whether to remove those from the ignore list as well.
=> update pytest config for pep8 tests (#3617)

docs/templates/getting-started/sequential-model-guide.md
The mode function of `Merge` layer takes a single argument : the list of tensors being merged.
=> Bug fix : Sequential model guide

keras/backend/tensorflow_backend.py
With TF dynamic RNN support in Keras 1.0.8 a bug was introduced when using `go_backwards=True` and masking. Mask has one less dimension than input.
Example code (should we add a unit test?):
```python
from keras.layers import Input, Embedding, Dense, GRU
data_in = np.random.randint(2, size=(5, 10))
data_out = data_in[:, 0].astype(np.float32)
x_in = Input(shape=(10,), dtype='int32', name='x_in')
x = Embedding(2, 10, mask_zero=True)(x_in)
x = GRU(10, return_sequences=False, go_backwards=True)(x)
y_out = Dense(1, activation='softmax', name="y_out")(x)
model = Model(input=[x_in], output=[y_out])
model.compile(optimizer='adam', loss='mse')
model.fit([data_in], [data_out], nb_epoch=10)
```
```
File …
```
=> Fix TensorFlow RNN backwards support

keras/backend/theano_backend.py
the theano backend now uses dnn_batch_normalization which only supports
up to 4-dimensional input. This breaks any 5-d layers such as 3D
convolutions.
=> Fix Batch Norm compatibility with 3D inputs

keras/layers/normalization.py, tests/keras/layers/test_normalization.py
Added gamma_regularizer and beta_regularizer parameters to the BatchNormalization layer. Adding a keras.regularizers import was also needed for this.
While not fully mentioned in the original BatchNormalization layer, many recent papers (ResNets and DenseNets being some examples) used regularization on BN layers to achieve their results.
Usage example:
model.add(BatchNormalization(gamma_regularizer=l2(0.001), beta_regularizer=l2(0.001))
=> Added regularization option to BatchNormalization layer

examples/neural_style_transfer.py, keras/preprocessing/image.py
two commits in one
1. change of variable names in examples/neural_tansfer_style, img_width->img_nrows, img_height->img_ncols. It doesn't change the result in this example better for better consistency.
2. add docstring to keras.preprocessing.image.load_img, because its target_size parameter is (img_height, img_width), which is different from many image resize methods in other libraries, and thus needs explicit documentation to make it clear.
=> make image parameters more consistent

examples/babi_memnn.py
The implementation of bAbi [End to End Memory Network](https://arxiv.org/pdf/1503.08895v5.pdf) in the example seems to be missing the Softmax Layer.
Quoting the paper.
> The query q is also embedded (again, in the simplest case via another embedding matrix
B with the same dimensions as A) to obtain an internal state u. In the embedding space, we compute the match between u and each memory m<sub>i</sub> by taking the inner product followed by a softmax.
Also, the question encoder [here](https://github.com/fchollet/keras/blob/0df0177437ce672d654db6d7edfdc653aaf67533/examples/babi_memnn.py#L186) seems to sum over the probabilities and the question vector as suggestted in the original paper.
> Output memory representation: Each x<sub>i</sub> has a corresponding output vector c<sub>i</sub> …
=> Add missing Softmax activation to memnn example.

docs/templates/getting-started/faq.md, docs/templates/models/about-keras-models.md, keras/engine/topology.py, tests/test_model_saving.py
This PR adds the **option to load model weights by layer name** rather than by flattened layer-order. This is intended to help when fine-tuning or transfer-learning a pretrained model. The alternative as far as I can tell is to load the weights into the *original* architecture, then surgically alter the layers. For Functional API models (not Sequential models) this gets more tricky, and I didn't find examples for altering such models in the Keras documentation or elsewhere.
The proposal is to add a boolean argument, `by_name` (default `False`), to the `load_weights()` method of a model. If set to `True`, then any layers of the new model with names matching those of the old model will be loaded. Layers without names, or layers with differing names are ignored.
This lets you alter and …
=> Optionally load weights by name

examples/neural_style_transfer.py
When image_dim_ordering = 'tf', the output_shape of layers in vgg model will be `(batch_size, nrows, ncols, nchannels)` rather than `(batch_size, nchannels, nrows, ncols)`.
Thus the `batch_flatten` line in `gram_matrix` will only work with 'th' ordering. As a result,  the color of the generated images will be screwed up for 'tf' ordering. This ordering difference only affects `style_loss` and `total_variation_loss`, but not `content_loss` .
The PR fixes this bug - tested for [sample images](https://github.com/DmitryUlyanov/fast-neural-doodle/tree/master/data) for both 'th' and 'tf' ordering.
Now it seems to be a pain point to repeat these image_dim_ordering() tests. Would there be a better way?
=> fix bug in neural_style_transfer example for image_dim_ordering=tf

keras/callbacks.py
This PR modifies the TensorBoard callback to:
* Log histograms for all trainable & non-trainable weights; not just .W and .b
* Tries to provide good names for the weights even when they're not named well
* Generates image summaries for weights (behind a parameter since the value is questionable)
=> TensorBoard callback improvements

keras/backend/tensorflow_backend.py
there seems no reason to assume the output size of rnn should be the same as the state size.
=> allow output size different from state size

examples/imdb_fasttext.py
In the fastText paper 
> Bags of Tricks for Efficient Text Classification
https://arxiv.org/abs/1607.01759
uni-gram and bi-grams embedding are used.
I added the bi-grams embedding  (generated for the existing `imdb` class)
uni-gram: 88.12% test set accuracy
bi-gram: 90.19% test set accuracy
=> fastText: adding n-gram embeddings for higher test_set accuracy

keras/callbacks.py
1. Add the specification of 'auto' mode to the document of callbacks.py, these specification is from `ModelCheckpoint` class since their code logic is exactly the same.
2. Change from 'min'/'max' to `min`/`max` for better format.
=> Document refinement: add the specification of 'auto' mode for callbacks.py

docs/autogen.py, keras/layers/convolutional.py, tests/keras/layers/test_convolutional.py
See issue #3762 for discussion. Adds dilated 1D convolutions as a new built-in layer.
=> Add `AtrousConvolution1D` to convolutional layers

keras/layers/normalization.py
I am using the latest version of theano and keras, and ValueError same as #3667 occurs when using batch normalization. The error is caused by theano's batch normalization methods, which require the exactly same ndim as input. So, in all cases gamma and beta must be reshaped when using theano.
=> Fix ValueError(ndim of gamma and beta) of batch normalization when using Theano

keras/regularizers.py
My reading of regularizers is that they cannot be reused, but it doesn't actually fail in any way and seems like it results in only regularizing the last layer. Having an exception prevent this would probably improve the ergonomics.
=> Add exception when trying to reuse regularizers

docs/templates/preprocessing/image.md, keras/preprocessing/image.py, tests/keras/preprocessing/test_image.py
This makes ImageDataGenerator fully seedable with minimal changes.
- the seed argument in fit is now used
- the seed argument in flow and flow_from_directory now affects
transforms
- added example to docs of transforming images and masks together
- added test of using two seeded streams to get the same result
Related issue: [3059](https://github.com/fchollet/keras/issues/3059)
Use cases: 
- Needing repeatable behaviour from ImageDataGenerator
- Wanting to transform images and masks at the same time, e.g. kaggle ultrasound nerve segmentation challenge
=> make ImageDataGenerator behaviour fully seedable/repeatable

docs/templates/getting-started/functional-api-guide.md
Some of the variable names in this guide were misleadingly named. The outputs were named as `*_loss` implying that they held loss values, whereas they in fact held the outputs. It rather confused me; I believe my proposed naming is clearer.
=> Functional API guide: fix variable names "loss"->"output"

keras/preprocessing/image.py
`os.listdir` to `sorted(os.listdir)` for alphabetical order instead of arbitrary order. Following PR #3751 this allows masks and images with the same name to be read together.
=> List files in alphabetical order

examples/variational_autoencoder.py, examples/variational_autoencoder_deconv.py, keras/layers/convolutional.py
Following the discussions in #3540 and #3824 this pull request removes the shape inference part of the `Deconv2d` layer and use the output shape provided by the user.
Because the user must specify an output shape and the shape inference introduced does not work in all cases, the code is more concise and works in cases where the user wants to introduce operations where a precise output shape is needed.
@yaringal is this reasonnable?
=> Bypass shape inference in deconv2d and use the output shape provided by the user

docs/autogen.py, docs/mkdocs.yml, keras/utils/io_utils.py
Documentation for the HDF5Matrix class. See #2674.
Wasn't quite sure about where to actually put the documentation though. None of the other utils are actually documented either.
=> Add HDF5Matrix documentation

keras/layers/normalization.py
Fixed dead link for the references in the Batch Normalization documentation
=> Fixed dead link in batch norm documentation

keras/layers/pooling.py
It seems to be a mistake and might be unnecessary.
=> Remove a print message when using global pooling

keras/utils/generic_utils.py
From what I can see this fix for #3897 works for both Python 2 and 3.
=> Python3 fix for deserialization of closures

keras/backend/tensorflow_backend.py
To make example/image_ocr.py work with Tensorflow 0.11.
=> Fix shape inference error for newly version Tensorflow in ctc_label_dense_to_sparse

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/metrics.py, tests/keras/test_metrics.py
Implement a metric to track top-k accuracy rate in classification problems.
Related to #3986 . 
Added an overall metric called `top_k_categorical_accuracy()` to calculate accuracy rates while allowing for any of the top k values from `y_pred` to match against `y_true`. I have tried to keep the output format for the new function as close to the existing `categorical_accuracy()` function as possible.
For TensorFlow, this feature already exists as  [`tf.nn.in_top_k()`](https://www.tensorflow.org/versions/r0.11/api_docs/python/nn.html#in_top_k). With some re-shaping to suit tf's expectation, the existing function is used as-is.
For Theano, I have made use of `theano.tensor.argsort` to achieve the same result.
A simple test function has also been added to demonstrate expected operation.
=> Add top-k classification accuracy metrics

docs/templates/getting-started/sequential-model-guide.md
As the code [here](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L662) suggests whenever a model is compiled with `metrics = [name_of_the_metric_function]` works, however, the documenation suggests that `accuracy` is the only supported string representation.
=> Correct metrics usage in getting started guide.

keras/metrics.py
Looks like pull request https://github.com/fchollet/keras/pull/2872 added the KL divergence function to [objectives.py](https://github.com/fchollet/keras/blob/85c2d28e992f8f2a752393d7e9f65c8f3cbb7a7c/keras/objectives.py#L51-L54). 
I just thought it should be copied into [metrics.py](https://github.com/fchollet/keras/blob/85c2d28e992f8f2a752393d7e9f65c8f3cbb7a7c/keras/metrics.py) as well.
=> Add Kullback–Leibler divergence to metrics

keras/optimizers.py
Fixed a typo in Adamax which prevented it from using explicit decay.
=> Fixed typo in Adamax

examples/deep_dream.py, examples/neural_doodle.py, examples/neural_style_transfer.py, keras/applications/imagenet_utils.py
According to the authors of VGG, the mean pixel values are for BGR: 
> Namely, the following BGR values should be subtracted: [103.939, 116.779, 123.68].
[see here](https://gist.github.com/ksimonyan/211839e770f7b538e2d8#file-readme-md)
Mean was applied on RGB, now it applies on BGR.
=> Apply imagenet mean pixel on BGR instead of RGB.

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/layers/convolutional.py, tests/keras/layers/test_convolutional.py
I propose to implement an asymmetric padding as an option in the ZeroPadding2D.
Reasons:
- From my experience it could be definitely useful when using convolutional layers for the time series data. At some degree it's covered in #531.
- Probably it could also be useful for the image processing, but I cannot offer an example.
Open questions:
- May be it's better to add a separate layer for asymmetric zero padding instead of changing the existing ZeroPadding2D?
- There's a possible confusion in the existing ZeroPadding2D (see https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L1345-L1346) - dimensions are called width and height, respectively, but in all convolutional layers respective dimensions are rows, cols (vice versa). Should I leave the as is or change?
- May …
=> Make ZeroPadding2D optionally asymmetric

keras/optimizers.py
This commit adds the decay strength to the config dicts of all optimizers where it was not present.
=> Return decay from get_config of all optimizers

keras/backend/tensorflow_backend.py
Prior to newer TFs, cond was unavailable and thus was being
imported via private module namespaces.
Newer TFs expose tf.cond as the public interface.  There
are plans to remove private module namespace access so
this fixes keras to first try accessing through the public
namespace, and then going through the private one for older
versions of TF.
I tested this on newer TFs and it worked, but I couldn't
find out which older version of TF the old import path
was used (I tried 0.7.1 and ctc doesn't exist, and 0.8.0
and tf.cond was already available).  Let me know what
else I can do to test.
=> Switch use of TF cond function to use public function.

keras/engine/training.py
Recently I custum a video sequence DataGenerator method (based on ImageDataGenerator) for experiment. When I use model.fit_generator as following:
>history = model.fit_generator(train_data_generator, samples_per_epoch=train_data_generator.nb_sample,
nb_epoch=nb_epoch, verbose=1, callbacks=[early_stopping, model_checkpoint],
validation_data=test_data_generator, nb_val_samples=test_data_generator.nb_sample,
max_q_size=10, nb_worker=8, pickle_safe=True)
I found that the validation process consumes much longer time than training despite it contains less data.
I read the code and changed the `self.evaluate_generator()` (line 1482) in `fit_generator` to use a multiprocessing approach as training process did. However, the memory usage quickly increases and it only last for a few epochs. 
Through …
=> manually terminate threads process returned by `generator_queue()`

keras/wrappers/scikit_learn.py
7 tests failed, 1 errored, but those are the same as for the current head (d745d9ee96e5d39393ac740e5b84229beca00f1d) so I'm pretty sure this trivial PR is not causing them.
=> Make build_fn argument of sckit-learn wrappers accept class methods

keras/legacy/models.py, tests/keras/engine/test_training.py, tests/keras/layers/test_normalization.py, tests/keras/test_sequential_model.py, tests/test_loss_weighting.py
Extend the improvements brought by #3049 to legacy models.
The arguments where missing in graph's methods to be able to use the feature.
A few unused imports have also been removed.
=> Multiprocessing in legacy Graph models

keras/backend/tensorflow_backend.py
Keep the dummy input state as output state.
Tensorflow breaks if the shape of the state changes
https://github.com/fchollet/keras/issues/4008
=> Tensorflow rnn fix. Keep shape of the initial (dummy) state

examples/imdb_cnn.py
The imdb_cnn.py example is uses `MaxPooling1D(pool_length=model.output_shape[1])` for pooling. Changed it to use GlobalMaxPooling1D instead.
=> Update imdb_cnn.py to use GlobalMaxPooling1D

keras/backend/tensorflow_backend.py
LiL sparse matrices would not work correctly due to dtype being
different. Using the sparse_coo data fixes it.
LiL matrices work best when using the fit method because they support the list slicing form the slice_X function. They would not work before this fix, however.
=> Fix LiL sparse matrix on Tensorflow

keras/utils/visualize_util.py
Assuming all layers in `keras.layers.wrappers` always have __exactly one layer__ they're wrapping (@fchollet, is this invariably true?) this pull request appends the wrapped layer's name and class name to the graph for visualization.
=> Display wrapped layers in graph visualization

keras/preprocessing/image.py
When calculating covariance matrix 'sigma', denominator is # of instances (axis=0), not dimensionality (axis=1)
Proof:
http://ufldl.stanford.edu/wiki/index.php/Implementing_PCA/Whitening
http://ufldl.stanford.edu/wiki/index.php/Exercise:PCA_and_Whitening
Ng uses 2nd dim in denominator because his matrix is [features x instances]
=> Bug fix in zca_whitening

keras/models.py
This pull request will issue a clearer error message when an object that is not a `Layer` is added to a `Sequential` model (see Issue #4130 and #4074 ).
This is done by checking that the object is an instance of `keras.engine.topology.Layer` rather than through investigating that the object implements methods/properties in a layer protocol.
=> Only allow the addition to `Sequential` objects of layers that are instances of `Layer`

keras/backend/theano_backend.py, keras/layers/normalization.py
Adresses issues like : https://groups.google.com/forum/#!topic/keras-users/innS4NcLPt8
Seems like keras uses cudnn batch-norm "spatial" configuration, which normalizes over axis (0, 2, 3). When you don't use axis=1 in keras, theano tries to broadcast the axis dimension, and can't because this dimension is not 1.
One way to fix it is to shuffle dimensions to put the normalization axis over first dimension, theano batch-norm, and then shuffle it back.
I'm not sure this is the best way to do it, but I think it fixes the issue.
Results with different backends on https://github.com/keunwoochoi/music-auto_tagging-keras are now the same (they were not).
We should check the fix without cudnn too (but it should be no problem imo).
Also, it raises the question of default value of axis : for …
=> Fix Theano Cudnn BatchNorm when axis!=1

keras/utils/test_utils.py, tests/keras/layers/test_recurrent.py
This will allow parameterized tests to work correctly in both 2.7 and
3.4
There're also some low hanging fruits for test speed up (TF only though) - test_convolutional along can probably be sped up ~2x.
=> Use six for wrapping in keras_test

keras/backend/theano_backend.py, keras/layers/convolutional.py, keras/utils/np_utils.py, tests/keras/layers/test_convolutional.py
Theano supports convolution with `border_mode = 'full'`. This patch adds this to the list of supported border modes in Keras.
TensorFlow does not support full convolution (according to the documentation). In that case this will raise an exception saying `Border mode not supported: full`, similar to the current behaviour.
=> Enable full convolution with the Theano backend

keras/layers/convolutional.py
Error with the  get_config method from Deconvolution2D.
Throws the following error when saving a model with such layer.
Exception: The layer has never been called and thus has no defined output shape.
=> BUG: Deconvolution2D output shape not correctly referenced

keras/metrics.py, tests/keras/test_metrics.py
- Better names (`true_positives`, instead of `c1`, etc.)
- Refactored F-score into separate precision and recall functions for better progress reporting. It's very useful to see whether a model is learning to assign labels to samples without being regularized enough to maintain a high recall. It's also standard to report all three metrics in papers, and having the metrics available directly with model.evaluate would be very useful for this.
- Added `K.epsilon` to denominators like in `matthews_correlation`, to avoid getting `inf` in early epochs.
- Added F1 score with common aliases from different research fields (f-measure, etc.).
=> Refactor F-score into precision and recall metrics

keras/callbacks.py
Currently the `LearningRateScheduler` asserts that the returned type is a python float. This is problematic for any schedule that uses functions from `numpy`, which will most likely return a learning rate of one of numpy's dtypes (`np.float32`, `np.float64`). 
This PR requires the learning rate to be an instance of `float`, `np.float32`, `np.float64` instead of the hard requirement of a python `float`. In addition, the `LearningRateScheduler` now raises a `TypeError` instead of an `AssertionError` in the case of failure. Finally, the test suite was update to run learning rates of the new types and a test was added to test for the failure in the case of an `int`.
=> Allow for learning rate schedule of type np.float32 and np.float64

docs/templates/layers/writing-your-own-keras-layers.md
We ran into some really odd errors in an advanced usage of keras due to not setting `self.built = True` in one of our custom layers.  This PR is an attempt to help others avoid the pain that we experienced due to this bug.
In case you're curious, the place where this happened was in trying to use `tf.while_loop` to do an adaptive computation step, similar to [this paper](https://www.semanticscholar.org/paper/Adaptive-Computation-Time-for-Recurrent-Neural-Graves/4b2c003b7eb683476f96b2e653676c6cfcb8da28) by Alex Graves.  We had a layer that was trying to be built twice, which caused some funny errors when combined with `tf.while_loop`.
=> Add documentation to set self.built = True in MyLayer.build()

keras/backend/theano_backend.py
The arguments to Theano's `pool_2d` and `pool_3d` have been renamed (see Theano/Theano@ee75b95bc137125f587816e9e43cdee9981881f0). This causes a deprecation warning when using Keras with recent Theano versions. The first numbered Theano version that uses the new argument names is 0.9.0dev4.
This patch tries to use the new argument names to remove this warning. The old argument names are still there for compatibility with older Theano versions.
=> Theano: try not to use the deprecated pool_* interface

keras/layers/recurrent.py
Theano expects Python int for the argument of tile().
https://github.com/Theano/Theano/blob/rel-0.8.2/theano/tensor/basic.py#L4918
However, input_dim is numpy.int32.
It have to cast to Python int.
=> Fix recurrent.py dropout_W bug of Theano K.tile()

keras/callbacks.py
The message print EarlyStopping.on_epoch_end would be overwritten by ProgbarLogger.
I've found https://github.com/fchollet/keras/issues/2354 and the comment on https://github.com/fchollet/keras/pull/3195 and I understood print() in callback is bad idea if you use ProgbarLogger. But EarlyStopping is built-in class. I think EarlyStopping should work fine with ProgbarLogger.
I think printing in on_train_end callback is safe with ProgbarLogger.
In fact with this patch, EarlyStopping(verbose=1) can show its message like below.
```
Epoch 1/100
54000/54000 [==============================] - 2s - loss: 1.1670 - acc: 0.5984 - val_loss: 0.4293 - val_acc: 0.8937
Epoch 2/100
54000/54000 [==============================] - 2s - loss: 0.8022 - acc: 0.7288 - val_loss: 0.3453 - val_acc: 0.9102
Epoch 3/100 …
```
=> Print EarlyStopping verbose message on_train_end.

keras/datasets/cifar.py
The following code for reading in CIFAR batches is currently used in Python 3:
```python
d = cPickle.load(f, encoding="bytes")
print("keys are: {}".format(d.keys())  # debug output
for k, v in d.items():
print("key is: {}".format(k))      # debug output
del(d[k])
d[k.decode("utf8")] = v
```
This errors out with the following (running under Python 3.6b2):
```
keys are: dict_keys([b'batch_label', b'labels', b'data', b'filenames'])
key is: b'batch_label'
key is: b'labels'
key is: batch_label
File "run.py", line 78, in <module>
main()
File "run.py", line 67, in main
(X_train, y_train), (X_test, y_test) = cifar10.load_data()
File "/usr/local/lib/python3.6/site-packages/keras/datasets/cifar10.py", line 21, in load_data
data, labels = load_batch(fpath)
File …
```
=> Bugfix to CIFAR pickle reading code in Python 3

keras/engine/training.py
Weights must be sorted by names for save_model() and load_model() work properly.
This pull request fixes https://github.com/fchollet/keras/issues/3964 , https://github.com/fchollet/keras/issues/4044 and https://github.com/fchollet/keras/issues/4143 .
The discussion is https://github.com/fchollet/keras/issues/4044 .
=> Fix the load_model() bug by sorting weights by names

keras/engine/training.py, tests/keras/engine/test_training.py
This PR adds an `initial_epoch` argument to both the `fit` and `fit_generator` functions of the `Model` class. This is useful for resuming training, as can simply load in weights from a previous run and set this argument to restart where the training last finished (I also have a custom version of the `ModelCheckpoint` callback which handles this, which I can contribute if there is interest)
See also the discussion in #1872. This provides an alternative implementation addressing some of the same issues as the previous PR #2557 by @wrongu.
Unlike #2557, the break condition of the training and other parameters are respected, as instead of adding an additional 'offset' parameter the epoch counter itself, as used internally, is modified directly.
=> Add initial epoch argument to fit functions

keras/backend/tensorflow_backend.py
@fchollet 
tf.all_variables and tf.initialize_variables are replaced by tf.global_variables and tf.variables_initializer for the future version of tensorflow
```
def _initialize_variables():
if hasattr(tf, 'global_variables'):
variables = tf.global_variables()
else:
variables = tf.all_variables()
uninitialized_variables = []
for v in variables:
if not hasattr(v, '_keras_initialized') or not v._keras_initialized:
uninitialized_variables.append(v)
v._keras_initialized = True
if uninitialized_variables:
sess = get_session()
if hasattr(tf, 'variables_initializer'):
sess.run(tf.variables_initializer(uninitialized_variables))
else:
sess.run(tf.initialize_variables(uninitialized_variables))
```
=> tf.global_variables and tf.variables_initializer

keras/utils/layer_utils.py
This patch makes sure that there is always at least one space between the columns produced by `model.summary()`. This helps to separate the output shape from the parameter number. For example, this layer looks like it has a surprisingly large number of parameters:
```
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
...
____________________________________________________________________________________________________
convolution3d_1 (Convolution3D)  (None, 100, 13, 13, 132800        input_patch[0][0] …
```
=> Separate columns in model.summary() to improve readability

examples/mnist_acgan.py
Provides a simple implementation of Auxiliary Classifier Generative Adversarial Networks from [this paper](https://arxiv.org/abs/1610.09585).
=> Adding AC-GAN example on MNIST

keras/engine/training.py, tests/keras/engine/test_training.py
This was introduced by me in 6b04add93209. Thanks for @carlthome for reporting.
=> Correctly check the output dimension for None instead of target

examples/variational_autoencoder.py, examples/variational_autoencoder_deconv.py
In the paper [Auto-Encoding Variational Bayes](https://arxiv.org/abs/1312.6114), the points for visualization are generated by 
> Since the prior of the latent space is Gaussian, linearly spaced coordinates on the unit square were transformed through the inverse CDF of the Gaussian to produce values of the latent variables z.
Before:
After:
=> imporved variational autoencoder visualization for Gaussian latent space

keras/layers/pooling.py
This was fixed in Issue: https://github.com/fchollet/keras/pull/1792.
I was looking around on what to do until I found out that this feature had already been implemented. To spare others from looking around for no reason I fixed the documentation.
=> Fix border_mode = same for pooling layers documentation.

keras/callbacks.py
Currently when using the `CSVLogger` callback with `append=True`, at the beginning of a new training run which appends to an existing file the header file will be rewritten to the output
e.g. if training is resumed after epoch 2, the output would be:
```
epoch,categorical_accuracy,loss,val_categorical_accuracy,val_loss
0,0.130208333333,2.32610692581,0.154399999142,2.26858918381
1,0.173394097222,2.17767716779,0.196799999881,2.10534226418
2,0.186197916667,2.07855245802,0.177600000429,2.06805825005
epoch,categorical_accuracy,loss,val_categorical_accuracy,val_loss
3,0.201605902778,2.03062710166,0.199999999762,2.03451372261
4,0.204427083333,1.96939406792,0.229799997854,1.94915147133
```
This PR prevents the writing of the additional header line in the middle of the CSV file, so the output is …
=> Bugfix: Don't add another header line to CSV logfile when appending to an existing file

keras/utils/io_utils.py
The `tables` module changed its API from [2.x to 3.x](http://www.pytables.org/MIGRATING_TO_3.x.html)
Without the change `save_array` does not work with the latest tables version installed.
=> change 'save_array' to new tables api

keras/backend/tensorflow_backend.py
Fixes some shape invariance errors arising sometimes when building RNNs.
=> Enforce shape invariance for states in RNN loop

keras/utils/np_utils.py
Currently calling `to_categorical` gives a `numpy` deprecation warning (at least on `numpy==1.11.2`):
```
/Users/brettnaul/Dropbox/Documents/keras/keras/utils/np_utils.py:22: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
Y = np.zeros((len(y), nb_classes))
/Users/brettnaul/Dropbox/Documents/keras/keras/utils/np_utils.py:24: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
Y[i, y[i]] = 1.
```
Casting `y` to an `int` array seems safe to me since the docstring/logic assume that `y` is 0-indexed integers already.
=> Fix deprecation warning in `to_categorical`

keras/layers/core.py
I have a feeling that having `DeprecationWarning` and `Exception` later would be better, but that's up to you.
=> Warn when output shape not specified for Lambda on Theano

keras/backend/theano_backend.py
Using `IfElse` should allow Theano to [perform lazy evaluation](http://deeplearning.net/software/theano/tutorial/conditions.html) of the training and testing branches, so in theory it might be faster. `Switch` always computes both outputs.
=> Use Theano's IfElse instead of Switch for in_train_phase

keras/layers/convolutional_recurrent.py
There is a mismatch between argument of `__init__` function of `ConvLSTM2D` (`subsample`) and the document of `ConvLSTM2D` (`sub_sample`).
This fix change the argument of `__init__` function of `ConvLSTM2D` (from `subsample` to `sub_sample`) .
=> Fix document in convolutional_recurrent.py

keras/callbacks.py
I've added support for headers in the `RemoteMonitor` callback. I've defaulted them to be the generic JSON headers, as that is currently the only type dumped from this callback.
I plan on utilizing this callback extensively in the coming days for a Keras-specific, backend-independent logging/monitoring/interfacing web app.
=> Added JSON content headers

.travis.yml
Shortest tests first. 
If they fail, travis will show the error. 
Should give pull requesters faster feedback.
=> Changed order of tests for travis

keras/backend/theano_backend.py
The `deconv2d` method in the Theano backend applies a dimshuffle to the `kernel` variable, but I think it should also reorder the values in `filter_shape` to match the new `kernel.shape`.
I tried to make a test for this, but that turns out to be difficult. It seems that Theano doesn't use the `filter_shape` most of the time. (I ran into this problem while computing the gradient of the deconvolution on the old GPU backend.)
=> Theano: deconv2d should also shuffle filter_shape

docs/templates/constraints.md, docs/templates/regularizers.md
Added Convolution3D as a layer supporting the regularizers  and constraints API (as per [here](https://github.com/fchollet/keras/blob/149946c706042e0db96664aa8c7bb0d61c224d9d/keras/layers/convolutional.py#L1076)).
=> Docs fix - added Convolution3D as a layer supporting the regularizers  & constr API

docs/templates/preprocessing/image.md, keras/preprocessing/image.py, tests/keras/preprocessing/test_image.py
This is a squashed version of PR [#4552](https://github.com/fchollet/keras/pull/4552)
Added functionality to recurse subdirectories when using flow_from_directory, optionally also follow symlinks.
Sub-directories don't map to sub-classes in my code. The only change in the code is to traverse the subdirectories inside the class directories, rather than only pick the files directly in the class directories. In case where there are no sub-directories, I believe the code works as it used to.
Imagine a scenario where the cat/dog training dataset from kaggle is supplemented with a large number of cat and dog photos from other sources:
```
/cats
/cats/cats-from-kaggle
/cats/photos-of-wild-cats
/cats/external-disk -> /mnt/external-disk/cat-photos
/cats/network-volume -> …
```
=> recurse directories in DicrectoryIterator

keras/backend/theano_backend.py
(It also adds a docstring, like in the tf backend)
=> Fixes #4690, check for bool dtype in K.mean (th0.9)

keras/backend/theano_backend.py, tests/keras/layers/test_convolutional.py
MaxPooling1D with border_mode='same' caused `h_pad` to take illegal value -1 in theano_backend:pool2d.
Added test case.
=> Fix for issue #4640: Bug in theano_backend for _Pooling1D

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/layers/normalization.py
This is a continuation of #4162. The patches change the batch normalization functions to use Theano's new abstract batch normalization functions, once they are included (see Theano/Theano#5190).
The current version works for me with the appropriate Theano branch. I'll need to have another look at simplifying the code further, though. I think the parameter dimshuffle can be removed, since it should be handled by the Theano functions.
=> Use Theano's abstract interface for batch normalization

keras/backend/theano_backend.py
This should fix #4697. The previous version of the code would replace `x`, `mean` etc. with dimshuffled versions before calling the `sandbox.cuda` method. If the cuDNN function failed, however, the fallback option would receive the dimshuffled parameters but wouldn't unshuffle the result.
This patch does not overwrite the existing values, which means that they'll still be untouched if the cuda call fails.
=> Fix dimshuffle problem in old Theano batch_normalization

examples/mnist_acgan.py, examples/mnist_net2net.py
mnist_net2net.py and mnist_acgan.py can't directly run in python3.
=> Add python3 compatibility for some examples

keras/preprocessing/image.py
Hi.
Working with keras, i got a strange behaviour. 
In keras/preprocessing/image.py, the condition line 585 `if self.y is None:` was always False. I investigated and i found np.ndarray(y) was not returning a None type if y was none, but a ndarray. The representation of this array was none but the type of the object was not None.
I tested in local, and this change work for me. I also run all the test in keras preprocess and light was all green so i decided to do a pull requests.
Since the portion of code changed is very small, i decided not to create a git issue.
Have a nice day.
=> Now properly set self.y to None in NumpyArrayIterator

keras/backend/theano_backend.py
ones_like and zeros_like don't have the name parameter in their signature for theano backend so it can trigger an error if it is used.
=> Theano backend consistancy

keras/layers/core.py, keras/utils/layer_utils.py, tests/test_model_saving.py
This patch would solve a small problem when reconstructing Lambda layers. It passes the `custom_objects` list a bit further, so that calls to (global) functions work.
Here's a small example. Running this with the current version ends with `NameError: global name 'theano' is not defined`. The patch would fix this by passing the `custom_objects` to the `lambda` function.
```python
import numpy
import theano
import keras.models as km
import keras.layers as kl
inputs = kl.Input(shape=(3,))
output = kl.Lambda(lambda x: theano.tensor.sum(x) + x,
output_shape=(3,))(inputs)
model = km.Model(input=inputs, output=output)
json = model.to_json()
model = km.model_from_json(json, custom_objects={'theano': theano})
print(model.predict(numpy.zeros((5, 3))))
```
=> Use custom_objects to deserialize Lambda functions

examples/neural_style_transfer.py
It was mentioned that the width and height must match in the neural style transfer example, but this is not necessary. Since in the gram matrix computation we do a dot product of a matrix with its transpose, it would work. Since we are transferring the style of the style image onto the content image, having the aspect ratio of the content image in the final output would be ideal.
=> Maintain aspect ratio of content image in style transfer example

keras/models.py
The _initial_epoch feature_, that is added before to _Model class_ (#4429) need to be available in _Sequental class_ too.
It's just a tiny fix, that adds initial_epoch argument to [Sequential class functions](https://github.com/fchollet/keras/blob/master/keras/models.py#L598) (that are wrappers for engine [Model class functions](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L1004)).
=> Add 'initial_epoch' argument to Sequential fit() and fit_generator().

keras/utils/np_utils.py
Refactored ``keras.utils.np_utils.convert_kernel`` such that it is roughly 1/5 the amount of code as the original implementation and runs roughly twice as quickly (for typically-sized kernel banks). 
The new and old implementations were checked against each other, and produce identical results (including the errors that they raise).
=> refactored convert_kernel

keras/metrics.py
The kullback_leibler_divergence metric in metrics.py returned an output
with dimensionality N-1 (where N is the dimensionality of the target).
Add mean after sum to fix this, such that always a scalar is returned.
=> Fix kullback_leibler_divergence #4788

keras/layers/advanced_activations.py
I didn't catch when my original documentation was changed by @fchollet (overall for the better) but introducing this bug: https://github.com/fchollet/keras/issues/4851
My original docs only included the dimensions of the parameters (no batch dim) and were correct, but I think its better to change the functions to reflect the current docs.
My original docs were:
```
shared_axes: the axes along with to share parameters for
the activation function. For example if the
incoming feature maps from a 2D convolution
has dimensions 16x32x32 and you wish to share
parameters across space so that each feature
maps only has one set of parameters, set
shared_axes = [1, 2]
```
=> Fix for Issue #4851

docs/templates/initializations.md
Initialization with one was missing from the docs.
=> Add 'one' initialization to docs

docs/templates/applications.md, keras/applications/inception_v3.py, keras/applications/resnet50.py, keras/applications/vgg16.py, keras/applications/vgg19.py, keras/applications/xception.py
Fix docs to match the correct name used through Keras applications, which is input_shape.
=> docs: fix typo inputs_shape -> input_shape

keras/backend/tensorflow_backend.py
Fixed an error when PR https://github.com/fchollet/keras/pull/4632 was rewritten. @fchollet 
`s` (symbolic shape) is never `None`. Use integer shape if available, and use symbolic shape otherwise.
=> K.dot: use integer shape if available

keras/callbacks.py
Fix Checkpoint and EarlyStopping to correctly infer the monitor_op when metric is fmeasure.
=> callbacks: Maximize fmeasure as well when mode==auto

keras/backend/tensorflow_backend.py, tests/keras/layers/test_convolutional.py
Previously, running the example in [the documentation](https://keras.io/layers/convolutional/#deconvolution2d) resulted in an error for the TF backend. This fix adds the ability to handle `None` in the first dim of the `output_shape` for the TF backend. Added a test that passes for TH, but fails for TF, which under the changes from the PR now passes for both.
=> Deconvolution2D fix.

keras/backend/tensorflow_backend.py
Update the batch normalization equation in the TF backend to follow the [original paper][1] and the [TensorFlow source code][2].
[1]: https://arxiv.org/abs/1502.03167
[2]: https://github.com/tensorflow/tensorflow/blob/333dc32ff79af21484695157f3d141dc776f7c02/tensorflow/python/ops/nn_impl.py#L742
=> Fix batch normalization equation in TF backend

examples/mnist_hierarchical_rnn.py, keras/layers/advanced_activations.py, keras/layers/convolutional.py, keras/layers/convolutional_recurrent.py, keras/layers/core.py, keras/layers/normalization.py, keras/layers/recurrent.py
Use the arXiv abstract links as the source links of reference papers instead of 1) link to other websites, 2) arXiv pdf link.
=> Reference Style Fix

keras/utils/np_utils.py
Hi everybody,
Faster implementation of `utils.np_utils.to_categorical`. It uses fancy indexing instead of a `for` loop. Between 2x-10x faster depending on the shape (see `timeit` results below).
```python
n = y.shape[0]
Y = np.zeros((n, nb_classes))
Y[np.arange(n), y] = 1
```
The below snippet will run `timeit` comparing old and new.
```python
from keras.utils.np_utils import to_categorical
from timeit import Timer
from numpy.random import randint
def faster_to_categorical(y, nb_classes=None):
y = np.array(y, dtype='int').ravel()
if not nb_classes:
nb_classes = np.max(y)+1
n = y.shape[0]
Y = np.zeros((n, nb_classes))
Y[np.arange(n), y] = 1
return Y
def test(nb_classes, n):
old_timer = Timer(lambda: to_categorical(randint(0,nb_classes,(n,)), nb_classes))
new_timer = …
```
=> Faster implementation of to_categorical

keras/layers/convolutional.py, tests/keras/layers/test_convolutional.py
- A cropping of `(n, 0)` is now valid on any axis
- Previously, these would cause a slice of `[n : -0]` which is valid, but returns 0 items
- Added tests for the case of `(0, 0)` crops
I did it in this ugly way to allow for non-defined shapes (even though this is an odd case for images) and to minimize memory usage.
=> Allow (n, 0) croppings on Cropping2d and 3d

keras/initializations.py
Some layers use a `fucctool.partial` object for the weight initialization like so: `initializer=functools.partial(self.init,  dim_ordering=self.dim_ordering)`. These layers currently break when initialized with certain inits that do not accept the `dim_ordering` keyword arguments.
This PR just modifies all inits to accept `dim_ordering` as a keyword argument, even when not necessary.
Note: very possibly not the best solution. Let me know if a better one comes to mind.
Example code that currently breaks:
```python
from keras.layers import Deconvolution2D
model.add(Deconvolution2D(3, 3, 3, output_shape=(None, 14, 14, 3), init='uniform', input_shape=(12, 12, 3)))
```
=> Allow dim_ordering as a parameter to all Initialization

keras/backend/tensorflow_backend.py
I think model serialization with a deconv layer + tf backend causes a bug. I think adding this tuple cast fixes it.
This script reproduces the bug for me with the latest keras/tensorflow
```python
from keras.models import Sequential, load_model
from keras.layers import Deconvolution2D
model.add(Deconvolution2D(3, 3, 3, output_shape=(None, 14, 14, 3), input_shape=(12, 12, 3)))
model.save('tmp.model')
del model
model = load_model('tmp.model')
```
=> Potential deconv model saving fix?

docs/templates/layers/writing-your-own-keras-layers.md
Some things are missing in the custom layer skeleton:
The following lines raises :`ValueError: Invalid initialization: random`
because "random_uniform" is just "uniform"
and  `TypeError: build() missing 1 required positional argument: 'input_shape'` because input shape is missing
```
self.W = self.add_weight(shape=(input_shape[1], self.output_dim),
initializer='random_uniform',
trainable=True)
super(Embed_Attention, self).build()  # Be sure to call this somewhere!
```
=> [Documentation] "random_uniform" initializer doesn't exists.

keras/engine/topology.py
`any(input_mask)` is not valid with TensorFlow because it checks if each element is "truthy" in turn, and using a TensorFlow tensor as a bool in Python is not allowed and raises an exception.
=> Fixed checking input masks in Layer.compute_mask

keras/backend/theano_backend.py
This patch adds a better check for the `filter_dilation` parameter of `T.nnet.conv2d`. Earlier versions of Theano (such as 0.8.2) do not support filter dilation, but because `T.nnet.conv2d` accepts any `**kwargs` it also doesn't warn you if you specify this parameter. Instead, it just ignores it.
Theano 0.8.2 does show a warning that the `filter_dilation` parameter is "deprecated", but I think having a more explicit check would be helpful for cases such as #5024.
=> Check for filter_dilation support in Theano conv2d

examples/addition_rnn.py
In Python3, 50000 / 10 = 5000.0. This will result in a warning from numpy:
VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
=> Fix a warning on Python3

keras/backend/theano_backend.py
See #5001 for the issue.
This simply ensures that the `output_shape` parameter to the DeConv2d layer matches the dim_ordering defined.
=> DeConvolution2D: Make output_shape parameter respect dim_ordering

keras/engine/training.py
Beforehand, slow generators could have caused race conditions and crashes with `ValueError: generator already executing`, e.g. if a validation generator filling up the queue took longer than a single epoch that elapsed meanwhile.
This sounds exotic but this happened to me in a generator that rendered PDF files and in the initial testing, epoch size was just a small multiply of batch size (and similar to validation set size).  Of course this is not optimal usage, but nevertheless it was frustrating to debug this issue in initial model experiments.
=> Model generators: Make sure all threads finish when stop is requested

keras/engine/training.py, tests/keras/test_multiprocessing.py
Creates a new `GeneratorEnqueuer` class to replace the `generator_queue()` function. Rather than copying thread tear-down code wherever needed (see #5049), this places all the relevant code in one location. Then, since we wrap all usage of the `GeneratorEnqueuer` class in a try/finally block, we can guarantee that `enqueuer.stop()` is called and the thread pool shuts down properly. I've tested this pretty extensively by inserting random errors everywhere and ensuring that the script still terminates properly.
This refactoring lets us simplify some things. Here's how each library is used:
* Multiprocessing
* Set `thread.daemon = True`
* Shutdown with `thread.terminate()`
* Threading
* Set `thread.daemon = False`
* Shutdown with `stop_event.set()` and `thread.join()`
Because we aren't using …
=> Cleanup syntax and teardown for multithreading

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py
Theano uses round away from zero, while tensorflow uses round to nearest even number.
Example to demonstrate the issue:
class Rounder(Layer):
def __init__(self, **kwargs):
super(Rounder, self).__init__(**kwargs)
def get_output_shape_for(self, input_shape):
return (input_shape[0], input_shape[1])
def call(self, x, mask=None):
x1 = K.round(x)
return x1
model.add(Rounder(input_shape=(4,)))
model.compile(loss='mse', optimizer='sgd')
A = model.predict(np.array([-0.5,0.5,1.5,2.5]).reshape(1,-1))
print(A)
Output with tensorflow:
[[ 0.  0.  2.  2.]]
Output with theano:
[[-1.  1.  2.  3.]]
Output with theano after fix:
[[-0.  0.  2.  2.]]
This night seem minor, but it introduces issues when trying to match behaviour from botch backends when rounding numbers that end in .5 …
=> change rounding mode in theano backend to match tensorflow backend

keras/backend/tensorflow_backend.py
there is a common bug that occurs in the Deconvolution2D class when you use None for the batch size w/ the output_shape argument, which originates from tf.nn.deconv2d but can easily be alleviated in keras. It errors out saying: "TypeError: Expected binary or unicode string, got None"
The fix is to add the tf.stack() line in keras/backend/tensorflow_backend.py on line 2472:
```
def _preprocess_deconv_output_shape(x, shape, dim_ordering):
if dim_ordering == 'th':
shape = (shape[0], shape[2], shape[3], shape[1])
if shape[0] is None:
shape = (tf.shape(x)[0], ) + tuple(shape[1:])
shape = tf.stack(list(shape))
return shape
```
Example issue from TF that carries over to keras: https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/vf8eH9YMwVA
=> fix deconv2d None error

docs/autogen.py, docs/mkdocs.yml, keras/layers/core.py, keras/optimizers.py, keras/utils/generic_utils.py, keras/utils/layer_utils.py, tests/keras/utils/test_generic_utils.py
Hi everybody!
Please let me know your thoughts regarding this quick fix and slight quality-of-life for custom_objects.
* Instead of copying custom objects into globals(), they are copied into a separate dictionary.
* get_from_module checks that dictionary before checking the requested module.
* users can clear the custom objects or otherwise manipulate the dictionary if they want to
This also means that custom_objects work for custom regularizers. 
A side effect of the code is that you now can do something like:
```python
get_custom_objects()["CustomRegularizer"]=CustomRegularizer
d = Dense(dim, activity_regularizer='CustomRegularizer')
```
Below code is broken currently but works with this PR.
https://github.com/fchollet/keras/issues/4990
```python
level_1_dim = 256
level_2_dim = 64 …
```
=> Fix custom_objects for regularizers and other issues

keras/optimizers.py
I thought as the docs cite other methods, it would be good to provide a citation for this optimiser. Hinton mentions to 'keep citing the slides' for this method. 
I chose the title of the lecture in question, if there's a better title I'm sure that can be used instead, but I think the citation should be there.
=> Add reference to slides for RMSprop

keras/wrappers/scikit_learn.py
Add **params to BaseWrapper.get_params(self,_) to fix TypeError to fix issues #5103
=> Fix Sckit-learn API get_parameters bug

keras/backend/theano_backend.py
Refs #5124 and #3641.
Theano sets dimensions of shape 1 to be broadcastable for tensors in the `outputs_info` of scan. This leads to issues with Recurrent layers with 1 node/output.
```python
input = np.array([[[1]]], dtype = 'float32')
model = Sequential([LSTM(2, input_dim = 1, )])
model.predict(input).shape
#>> (1, 2)
model = Sequential([LSTM(1, input_dim = 1)])
model.predict(input).shape
```
```
>> Inconsistency in the inner graph of scan 'scan_fn' : an input and an output are associated with the same recurrent state and should have the same type but have type 'CudaNdarrayType(float32, col)' and 'CudaNdarrayType(float32, matrix)' respectively.
```
Affects all recurrent layers; ~~this may not fix the issue when …
=> Unbroadcast initial states in Theano backend (RNNs)

keras/backend/tensorflow_backend.py, tests/keras/backend/test_backends.py, tests/keras/test_sequential_model.py
This PR raises an exception if ndim is < 3 in batch_dot, to avoid unexpected outputs, as described in #5131.
=> Checking that ndim is >= 3 for batch_dot in TensorFlow backend

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py
Current docs say tensorflow always unrolls, which isn't true.
Old docstring
> unroll: with TensorFlow the RNN is always unrolled, but with Theano you can use this boolean flag to unroll the RNN.
New docstring
> unroll: whether to unroll the RNN or to use a symbolic loop (`while_loop` or `scan` depending on backend).
Cheers
=> Fix documentation of K.rnn unroll parameter

docs/templates/preprocessing/image.md
Valid formats in `preprocessing/image.py ` are as below:
`white_list_formats = {'png', 'jpg', 'jpeg', 'bmp'}`
Fixed BNP -> BMP in the documentation.
=> [Documentation] Fixed typo: 'BNP' -> 'BMP'

keras/backend/tensorflow_backend.py
Corrected cast function spec formatting which is causing (i believe) the misformatting in backend documentation: Dot hasn't got a title and is embedded in previous cast exemple, see "cast" definition here:  https://keras.io/backend
=> [Documentation] problem in dot documentation

keras/callbacks.py, tests/keras/test_callbacks.py
Reuse of `CSVLogger` object raises `ValueError: I/O operation on closed file.` because in `on_train_end` method `self.csv_file` is closed but `self.writer` is not reset to `None`.
=> fix: CSVLogger raises ValueError when it is reused.

README.md
Current link has invalid anchor at the end. Make link go directly to the README to account for future changes.
Could also link to this page directly but there's a chance they could change the URL:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md
=> Fix link to TF install docs in README

examples/pretrained_word_embeddings.py
Tokenizer returns sequence values in the range of [0, nb_words). In this
example, MAX_NB_WORDS is 20000 and the data's max value is 19999. There
is no need to use 'nb_words + 1'.
=> Fix off by one.

keras/engine/training.py
The following occurs twice in different places, so far harmlessly but
still redundantly:
self.optimizer = optimizers.get(optimizer)
[[First occurence]](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L517),
[[Second occurence]](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L727)
=> Fixed duplicate line in keras/engine/training.py.

keras/backend/tensorflow_backend.py, tests/keras/backend/test_backends.py, tests/keras/test_sequential_model.py
This PR handles the case where ndim == 2, for K.batch_dot in TensorFlow, as described in #5131. This ensure that both Theano and TensorFlow return the expected shape:
```python
from keras.layers import Embedding, Reshape, Merge
left = Sequential()
left.add(Embedding(1, 2, input_length=1))
left.add(Reshape((2,)))
right = Sequential()
right.add(Embedding(2, 2, input_length=1))
right.add(Reshape((2,)))
model.add(Merge([left, right], mode='dot', dot_axes=1))
print model.output_shape
print model.predict([np.array([0,0]), np.array([0,1])])
```
With TensorFlow:
```
Using TensorFlow backend.
(None, 1)
[[-0.00155337]
[ 0.00074518]]
```
With Theano:
```
(None, 1)
[[ 0.0001435 ]
[-0.00048947]]
```
=> Handling ndim == 2 in TF batch_dot

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py
This is a fix for #5268 which makes sure the callables are evaluated on the learning_phrase branches.
=> Always evaluate callables if learning phase is set, solves #5268

keras/layers/convolutional.py
This makes it possible to use a single `Convolution3D` layer with different input sizes (see #5108). The behaviour is then similar to that of `Convolution2D`, which also doesn't fix the input shape.
Potential downside: not providing the input shape makes it slightly harder for Theano to optimise the convolution. If the input shape is known, Theano will sometimes choose to use `GpuCorrMM_gradWeights` instead of the `GpuCorrMM` if this is faster, for example. In practice, however, Theano will mostly use the cuDNN version anyway and this should cause problems.
=> Convolution3D: do not fix input_shape. (Fixes #5108.)

examples/mnist_sklearn_wrapper.py
as title, mnist_sklearn_wrapper.py assumes image_dim_ordering to be "th"
Test Plan:                                                                                                                                                                                                        KERAS_BACKEND=theano condapython examples/mnist_sklearn_wrapper.py                                                                                                                                                KERAS_BACKEND=tensorflow condapython examples/mnist_sklearn_wrapper.py
=> fix mnist_sklearn_wrapper.py error when default image_dim_ordering=tf

keras/engine/training.py
Correction to an error phrase: all elements in the 'names' array (inputs to the model) are required not all elements that are already given.
=> Correction of an error phrase for a better feedback.

keras/backend/tensorflow_backend.py
Hello,
yesterday's additions introduced use of tf.mul, which has been replaced by tf.multiply for tf1.0
Best regards
Thomas
=> restore tensorflow 1.0rc1 compatibility

keras/backend/theano_backend.py
This should fix the `conv2d_transpose` in the Theano backend. (Mentioned as one of the points in #5358.)
=> Fix shuffling of output_shape in Theano conv2d_transpose

keras/preprocessing/image.py
Minor modifications on the load_img() method to avoid unnecessary conversions and resizes. Even though the underlying implementation of PIL will detect and avoid unnecessary transformations, it will still clone the image putting strain on the garbage collector. Adding a couple of checks will allow us to avoid this all together.
=> Speed up load_image method.

examples/mnist_sklearn_wrapper.py
`'log_loss'` is deprecated; replaced by `'neg_log_loss'`
=> Fix deprecated sklearn scoring function

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/layers/convolutional.py, keras/utils/conv_utils.py, keras/utils/test_utils.py, tests/keras/layers/convolutional_test.py
Adds a boolean causal flag to Conv1D which results in Causal (Dilated) Convolutions as suggested in the Wavenet paper. See #5297. 
Additionally, this PR fixes a bug in temporal_padding for theano, an issues with using input_data for layer_test, and an issue with test_convolution_1d where dilated convolutions where tested for only one padding type. All these are in commit d1e4ef8 which can be cherry-picked.
=> Causal Dilated Convolutions 

keras/models.py
Theano default variable name is "/variable".  Fixed save_model method for theano.
I am on to other theano related errors as well.
tests/test_model_saving.py::test_sequential_model_saving 
tests/test_model_saving.py::test_sequential_model_saving_2 
[gw0] PASSED tests/test_model_saving.py::test_sequential_model_saving_2 
tests/test_model_saving.py::test_saving_without_compilation 
[gw0] PASSED tests/test_model_saving.py::test_saving_without_compilation 
tests/test_model_saving.py::test_saving_right_after_compilation 
[gw1] PASSED tests/test_model_saving.py::test_sequential_model_saving 
tests/test_model_saving.py::test_fuctional_model_saving 
[gw0] PASSED tests/test_model_saving.py::test_saving_right_after_compilation 
tests/test_model_saving.py::test_loading_weights_by_name 
[gw1] PASSED …
=> Theano test case fix: Fix for saving models

keras/layers/merge.py, tests/keras/layers/merge_test.py
I am not 100 % sure of this either. But I think the right relationship is add : sum = multiply : product. Add is a verb, and sum is the result of addition; same goes for multiply / product. Since the "+" layer is called `Sum`  , `Product` would be more consistent than `Multiply` even though it was called `mul` mode in Keras 1.
=> Multiply -> Product

keras/utils/vis_utils.py
Currently, `import keras` will fail if pydot is not installed (for example, in a fresh virtualenv without the `keras[visualize]` option).  This commit delays the check for pydot until it is actually used, in line with the treatment of a PIL.Image dependency in keras/preprocessing/image.py
=> make pydot optional

keras/utils/io_utils.py
If an invalid key type is given, the `idx` variable will not be defined and you will get an UnboundLocalError
```
File "/mnt/dokumneter/kode/deeplearning/keras/venv/lib/python3.5/site-packages/keras/utils/io_utils.py", line 77, in __getitem__
return self.normalizer(self.data[idx])
UnboundLocalError: local variable 'idx' referenced before assignment
```
=> io utils: raise indexError for invalid key

examples/pretrained_word_embeddings.py
(Re-submitted to keras-2 branch.)
Newsgroups message contains header like 'Newsgroups: alt.atheism', which inflates the accuracy to 0.95 (2 epochs).
After removing the header, the val accuracy is 0.47 (2 epochs) and 0.71 (10 epochs).
=> skip newsgroup header

keras/backend/theano_backend.py, tests/keras/backend/backend_test.py
Shape inferences added
| Op |Test coverage|
|-----------------|:-----------------:|
| `flatten` | :heavy_check_mark: |
| `repeat_elements` | :heavy_check_mark: |
| `batch_flatten` | :heavy_check_mark: |
| `squeeze` | :heavy_check_mark: |
| `permute_dimensions` | :heavy_check_mark: |
| `repeat` | :heavy_check_mark: |
| `expand_dims` | :heavy_check_mark: |
| `spatial_2d_pooling` |
|`transpose`|:heavy_check_mark: |
|`batch_dot`|:heavy_check_mark: |
The original PR was at https://github.com/fchollet/keras/pull/5610. The suggested changes have been fixed. Had to remove shape inference for `tile` due to certain issues (still working on it)
=> Shape inference for Theano backend

keras/legacy/interfaces.py
The first entry in `args` is `self`. So, change args to args[1:]
=> Fixed argument for 'convert_legacy_kwrags'

keras/legacy/interfaces.py
@fchollet can you please merge this? Actually, #5674 breaks the build because it lacks `__class__`. sorry
=> Fix *Pooling1D conversion interface

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, tests/keras/backend/test_backends.py
Tensorflow requires to declare the return dtype of the mapping function if it is different than the mapped over sequence. This means that before we couldn't map over indexes. The following code shows what we could not do.
```python
from keras import backend as K
x = K.variable(np.random.rand(10, 3).astype(np.float32))
s = K.eval(K.map_fn(
lambda i: K.sum(x[i]),
K.arange(10),
dtype=K.floatx()  # omitting that would result in a pretty big traceback
))
```
The above functionality could be very useful because it enables code like the following
```python
from keras import backend as K
x = K.variable(np.random.rand(10, 3).astype(np.float32))
y = K.variable(np.random.rand(3, 1).astype(np.float32))
z = K.dot(x, y)
s = K.eval(K.map_fn(
lambda i: …
```
=> Added dtype to map_fn

tests/keras/legacy/interface_test.py
I changed `'pool_size=2'` to `'pool_size=(2,2)'` because it is impossible to use integer alone in old_layer(keras-1)
=> Fixes value of 'pool_size' argument of unit test about 'legacy_pooling2d_support'

keras/backend/tensorflow_backend.py, tests/keras/layers/wrappers_test.py
The tensorflow rnn() code currently assumes the 'outputs.dtype' of the step function is equal to the 'inputs.dtype' (the part used with a fixed batch size). It fails with step_functions as Embedding.
Added unit test of TimeDistributed Embedding with and without batch_input_shape
=> Do not assume outputs.dtype is equal to inputs.dtype in rnn() (tensorflow_backend.py)

docs/templates/datasets.md
Fixed two typos in this line (that appears three times in the file):
`path: if you do have the data locally (at '~/.keras/datasets/' + path), if will be downloaded to this location (in cPickle format).`
Changed "if will" to "it will" and "do have" to "do not have".
I read in another PR that there was a code freeze on the branch master so I created this PR for the branch keras-2. I hope that's correct.
=> Fix typos in docs/templates/datasets.md

keras/layers/recurrent.py, tests/keras/layers/recurrent_test.py
This adds `specify_states` flag to the `Recurrent` Layer and modifies the `BasicRNN`, `GRU`, and `LSTM` layers to use the flag. This flag allows you to call the recurrent layer on a list of tensors. The first element of the list is the input tensor. The remaining elements are the initial state tensors.
See #5358.
=> Specify States of RNN Layers Symbolically

keras/engine/topology.py
The function pops item from the original `dict` passed to the function. This causes an error when building multiple models from the same config:
```python
config = model.get_config()
model1 = Model.from_config(config) # OK
model2 = Model.from_config(config) # error
```
=> Bug fix : Model.from_config

keras/engine/topology.py
When 'max' was added to the possible merge modes, some places were apparently missed.
TBH, the merge modes could use a bit less hard coding, since all the checks seem to group into element-wise operations (sum, mul, ave, max), reductions (dot, cos) and concatenation. (Except for [one line](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1330), which might be a bug.)
=> Add merge mode 'max' where it was missing (fixes #3486)

keras/engine/training.py, keras/legacy/interfaces.py, tests/keras/legacy/interface_test.py
Original PR was at #5713. Closed it due to merge issues.
The following changes were requested
=> Legacy interfaces for fit_generator, evaluate_generator, predict_generator

docs/templates/layers/writing-your-own-keras-layers.md
because `self.kernel` wasn't available on Keras 1.0
[skip ci]
=> Update Keras version in writing-your-own-keras-layers.md

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py
Allows to write `K.stack(tensors, axis=1)` instead of `K.reshape(K.concatenate(tensors, axis=1), shape=(-1, timesteps, dim))` when need to pass list of tensors to RNN (generated by other RNNs, for example)
=> Added stack 'axis' argument

keras/engine/training.py
This PR fixes the integer check for `learning_phase` in the following functions:
- evaluate
- predict
- train_on_batch
- test_on_batch
- predict_on_batch
Without this fix, setting `learning_phase` to a fixed value won't work for theano backend.
In that case, the theano function is called with too much arguments. This results in an implicit input
for the first shared variable of the graph.
Code to reproduce:
```python
import keras.backend as K
from keras.layers import Dense, Dropout
K.set_learning_phase(0)
m = Sequential()
m.add(Dropout(0.5, input_shape=(10,)))
m.add(Dense(2, activation='softmax'))
m.predict(np.random.random((10,10)))
```
Error:
```
...
TypeError: Tried to provide value for implicit …
```
=> Fix learning_phase int check

keras/engine/topology.py
Forgetting to decode bytes strings in `keras.engine.topology.load_weights_from_hdf5_group` and `load_weights_from_hdf5_group_by_name`.
`h5py` returns string as `bytes` object in Python3.   `load_weights_from_hdf5_group()` call `preprocess_weights_for_loading()` with `original_backend` as bytes string.
https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L2879-L2882
Unnecessary weight preprocessing will be called, because string comparison between bytes and string is always false in python3.
```py
>>> b'youjo' == 'youjo'
False
```
https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L2817
```py
import keras
x = keras.layers.Input(shape=(32, 32, 3))
h = keras.layers.Conv2D(10, (10, 10))(x)
model = keras.models.Model(x, h)
model.save('conv2d.h5')
del model …
```
=> keras_v2+python3, `load_weights_from_hdf5_group` character type bug 

keras/callbacks.py
The doc string leaves out the write_images arg, which might be a little confusing for Tensorboard beginners. Added it.
=> Made minor change to missing arg in Tensorboard docstring

keras/legacy/layers.py
Set `stacklevel=2` in `warning.warn`. The stacktrace will link to the invocation of `merge` instead of the warning message within `merge`.
Will make it easier to update code to the new API. Probably other places a similar change should be made.
Cheers!
=> Set stacklevel so warning points to invocation instead of warning

examples/mnist_swwae.py
The original thread: [https://github.com/fchollet/keras/pull/5722](url)
Long story short, cleaned up resid block by making the resid pathway kernel size 1x1 and added ELU activation instead of the slower BN+RELU. The option to do either one is available; obviously each has its own advantages.
In the end (@nouiz), on Windows 10 with Theano 0.9.0rc4 and cudnn 5 I had the following results for each activation type:
ELU:
Using gpu device 0: GeForce GTX 780 (CNMeM is disabled, cuDNN 5005)
x_train shape: (60000L, 1L, 28L, 28L)
60000 train samples
10000 test samples
Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 69s - loss: 0.0247 - val_loss: 0.0062
Epoch 2/5
60000/60000 [==============================] - 71s - loss: 0.0049 - val_loss: …
=> SWWAE Example: Conv kernel size in resid pathway to 1x1 and activation from BN+RELU to ELU

keras/legacy/layers.py
The changes in commits 7e071cd7df38a9ace26cf44a8be64fc6b3aec394 and b43caf7b49746fcfa9738c5f9ea6fd46de9b5cd1 were lost when the Merge layer was removed from keras/engine/topology.py in the subsequent merge 1f87cff49383043f802100c73a1d26fcac80fc56.
This PR contains a replay of the changes on top of keras/legacy/layers.py
=> Reapply patches to legacy Merge layer

keras/utils/conv_utils.py
Fix `deconv_length` inference for `padding='same'` in conv_utils, and use `if-elif` instead of multiple `if`s
=> Fix `deconv_length` inference for `padding='same'` in conv_utils

keras/utils/generic_utils.py
When a Lambda layer is serialized as JSON, `defaults` may be serialized as a list, e.g. [None]. However `FunctionType` expects `argdefs` to be a tuple or None, not a list.
This PR addresses the primary error in #5298
=> Convert function defaults to tuple if serialized as list.

CONTRIBUTING.md
Updated https://github.com/fchollet/keras/pull/5445 for keras-2 release.
Explains the new pull request procedures for Keras 1, Keras 2, and keras-contrib, should resolve #5270.
Based on discussion in #4944 and farizrahman4u/keras-contrib#9.
=> Keras 2 and keras-contrib pull request process

keras/layers/merge.py, tests/keras/layers/merge_test.py
Simple merge layers that just extend `_Merge` and implement `_merge_function` report that they have multiple outputs (as many as inputs) with the same shape. A simple code example that showcases the problem follows.
```python
from keras.layers import Add, Input
a = Input(shape=(10, 3))
b = Input(shape=(10, 3))
add_layer = Add()
c = add_layer([a, b])
assert add_layer.output_shape == (None, 10, 3)
```
That doesn't cause any obvious problems because Keras uses the tensor shape inference which is correct but it still is wrong and could cause problems in the future (besides messing up `model.summary()` and visualizations which is already a case).
Although #5812 could probably be fixing this problem, it seemed way too complicated for what it introduces (broadcasting) and thought that a simple …
=> Fix the output shape reported by simple merge layers

keras/engine/topology.py, keras/engine/training.py, keras/legacy/interfaces.py
Added `stacklevel=2` in a few places, `stacklevel=3` for preprocessor functions.
Added a warning to `Layer.compute_output_shape`: if a class defines `get_output_shape_for` but is still using the default implementation of `compute_output_shape` from `Layer`, it prints a warning.
This script tests that the warnings all point to the correct lines in the test file (if the stacklevel is set correctly).
This probably isn't everything. The `get_output_shape_for` warning should save some heartache. Does anyone know other hot-spots that need extra warnings?
```python
from keras.layers import Dense, Input, merge, Embedding, Layer, Merge
from keras.regularizers import L1L2
n=100
_x = np.random.random((n, 10))
_y = np.sum(_x, axis=-1, keepdims=True)
x …
```
=> Update stacklevel and add warning for get_output_shape_for

examples/antirectifier.py, keras/engine/topology.py, keras/legacy/layers.py
Remove remaining references to `get_output_shape_for`. https://github.com/fchollet/keras/pull/5847 adds a warning if you define `get_output_shape_for` but not `compute_output_shape`.
=> Replace references to get_output_shape_for with compute_output_shape

keras/engine/training.py, keras/models.py, tests/keras/test_sequential_model.py
This adds a verbose option to predict_generator and a progress bar when verbose=1. Verbose is 0 by default, matching current behavior and the predict method.
(link to related issue: #3793)
=> Add verbose argument to predict_generator (Resolve #3793)

keras/layers/wrappers.py
Without this change, custom objects cannot be loaded from a wrapped layer, because `Wrapper.from_config` did not pass along the custom objects correctly.
=> Fix serialization/loading for wrapped custom objects

keras/wrappers/scikit_learn.py, tests/keras/wrappers/scikit_learn_test.py
This is a resubmission of #5321 
Scikit-learn classifiers are able to process strings in their target classes. This PR allows KerasClassifier to do the same while also exposing a `.classes_` attribute containing the classes used during fitting.
I modified the corresponding unit tests to test the behavior of KerasClassifier when fitted with string labels.
=> Add ability for KerasClassifier to process string classes.

keras/engine/training.py, keras/metrics.py
Several accuracy metrics end in a call to `K.equal()`, which gives a tensor with dtype `bool`.  The multiplication with a float mask then crashes.  This fixes that crash.
=> Make accuracy metrics work with masked outputs

keras/layers/recurrent.py
This is an obvious typo in the step function of GRU.
=> a typo in the step func. of GRU (implementation=1)

docs/templates/getting-started/faq.md, docs/templates/metrics.md, docs/templates/preprocessing/image.md
Convert some API in docs/templates to ver2.
Based on [Keras 2.0 release notes](https://github.com/fchollet/keras/wiki/Keras-2.0-release-notes), the items in Training, Losses & metrics were converted.
=> Convert API in docs/templates to ver2 (Only Training, Losses & metrics)

keras/preprocessing/image.py
The data generator function '_flow_index' has some issue, that when n can be mod by batch_size, the shuffle never happened.
The code has already  been tested.
=> Fix the issue that when n can be mod by batch_size, the shuffle never happened

keras/backend/tensorflow_backend.py, keras/layers/core.py, keras/layers/merge.py, keras/legacy/layers.py
Addresses #5867.  It looks like everywhere else in the code, masks are of type `bool`.  The cast to `uint8` causes a problem when one of the concated inputs has a mask and one doesn't, because you can't concat a `bool` tensor and a `uint8` tensor.
=> Switched mask from uint8 to bool in concat layers

keras/backend/theano_backend.py
When doing `K.reshape()`, you need to use `-1` instead of `None` for dimensions with unknown length.  The rest of the Keras code expects the shape to be `None` if the dimension has unknown length, and so setting `_keras_shape` without converting `-1` back to `None` leads to some bugs.  This fixes that.
=> Change batch size back to None in reshape

keras/layers/local.py
#5925 Fix docstring. Both `LocallyConnected1D` and `LocallyConnected2D` support only `valid` for padding.
=> fix local layer padding docstring

keras/models.py
Using `load_model` without `h5py` raises the error with wrong message.
Fixed it.
=> Fix wrong error message in `load_model`

keras/engine/training.py
When predicting in a loop, this PR uses the dtype of the first batch to create the container instead of always converting to floatX.
@fchollet any thoughts on the best way to implement this behavior? I have models that output integers and I would like to avoid casting back and forth.
* If there are some programs that rely on floats being cast, I could do this logic: Cast to floatx if it is float32 or float64, otherwise do not change dtype.
* If you want to keep current behavior, maybe we could add a flag to switch between casting to float32 or using the returned dtype.
Cheers
=> Use dtype of first batch for dtype of predicted outputs

keras/layers/wrappers.py
I don't feel like I understand what exactly name scopes do very well, so I might have done this incorrectly, but in my tests, this fixes #5820 (you can't save models with bidirectional layers, because there are overlapping names; I only ran into this with theano, incidentally; tensorflow worked fine).
=> Changed name scope within bidirectional, fixing #5820

keras/layers/convolutional.py
#5974. `Conv2DTranspose` layer should use `None` as default `data_format`
=> Conv2DTranspose default data_format change to None

docs/templates/visualization.md
Visualization documentation missed one renaming of `keras.utils.visualize_util` and the old one still does not work:
```
>>> import keras.utils.visualize_util
ImportError: No module named visualize_util
```
=> Minor fix for visualization documentation.

keras/backend/tensorflow_backend.py
In Tensorflow backend some code is unnecessarily executed multiple times, because of wrong indentation.
=> Minor fix of indentation in TensorFlow backend

tests/keras/layers/local_test.py
1. Remove unnecessary loop
2. Reduce weight size to speedup unit test
=> Refactor and speedup local layer unit test

keras/layers/wrappers.py, tests/keras/layers/wrappers_test.py
For issue #5940 and #5975 
`Bidirectional` wrapper produces error with any `Recurrent` layer with `dropout` or `recurrent_dropout` argument.
=> Fix dropout error in Bidirectional layer

keras/backend/tensorflow_backend.py
Hi, I do a lot of `clear_session()` in my code (distributed processing) and noticed a memory leak.  Tracked it down to `_GRAPH_LEARNING_PHASES` not being cleared in clear_session, which meant a lot of graph data was not being properly garbage collected.
=> Fix memory leak in tensorflow backend

keras/engine/topology.py
Simple script to reproduce:
```python
from keras.layers import*
a = Input((None, None))
x = [a, a]
b = concatenate(x, 1)
x += [b]  # This changes b._keras_history[0].input
b = concatenate(x, 1)
model = Model(a, b)
```
Works with legacy merge layer. See #5972
=> Bug fix : Error when applying layer recursively on a list in Keras 2

tests/test_multiprocessing.py
In `test_multiprocessing_training_fromfile`, `data.npz` is created but not deleted.
=> Fix: `data.npz` is not deleted

keras/layers/recurrent.py
The docstring is misleading or even incorrect: passing None is not equivalent to "not specifying an activation function"; the latter results in the default parameter value of 'tanh' being used. I've fixed it.
=> Fix misleading docstrings

keras/layers/merge.py
Cannot index a set, so batch_sizes must be cast back as a list or a tuple.
=> bug fix, cast batch_sizes as a list to support indexing

keras/layers/recurrent.py
Dropout in RNN was not working for implementation 1 and 2. (This can be checked by setting model.trainable to False to see during training if the loss changes across epochs - it should when there is dropout applied.)
=> Fix dropout in RNN

keras/layers/recurrent.py
The docstring did not specify the need to use return_sequences=True when creating a stacked recurrent network. I have replaced the original example with a more descriptive one.
=> Fix docstring relating to stacked recurrent layers

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/layers/recurrent.py
If I understand the backend code correctly, Keras reverses the input order when producing an output sequence with `go_backwards=True`. This means that the first element in the input sequence (`input[0]`) is positioned as the last element of the output sequence (`output[last]`) after being processed by a backward RNN. This is correctly used in `Bidirectional` layer. Unfortunately general documentation is a bit misleading about this, so this is the PR to fix this.
Anyway, to see what effect does a wrong implementation have, I have modified the example `imdb_bidirectional_lstm.py` to use the following model:
```py
model.add(Embedding(max_features, 128, input_length=maxlen))
model.add(Bidirectional(LSTM(20, return_sequences=True), merge_mode='sum')) …
```
=> Improve descriptions of go_backwards parameters.

docker/Dockerfile, docker/theanorc
- TensorFlow 1.0.1
- Theano 0.9 : also install pygpu dependency & use "device=cuda" in theanorc to use new
"gpuarray" backend
- Miniconda 4.2.12 (latest conda installer with python 3.5)
=> Update docker files to TensorFlow 1, Theano 0.9

keras/models.py
I were reading the Keras2 API doc, and found that the fit_generator docs for validation_steps should be validation samples divided by batch_size but not the number of samples, so I made this change.
=> Fix fit_generator docs for validation_steps

keras/layers/convolutional_recurrent.py
In Keras master (`3382c0bb894b2ecaac2562238f34c2a46bf413c9`), when using `ConvLSTM2D` with `image_data_format == channels_first` mode, the wrong axis is selected as the channel axis.
```python
>>> import keras as K, keras.layers as KL, keras.engine as KE, keras.backend as KB, numpy as np
NVIDIA: no NVIDIA devices found
>>> input = KL.Input(shape=(100,1,32,1))                                   
>>> convlayer = KL.ConvLSTM2D(32, (3,1), activation="relu", padding="same")
>>> fseq = convlayer(input)
>>> model = KE.Model(inputs=input, outputs=fseq)        
>>> model.predict(np.random.normal(size=(5,100,1,32,1)))
[snip]
Apply node that caused the error: CorrMM{half, (1, 1), (1, 1)}(Alloc.0, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort …
```
=> Bugfix to ConvLSTM2D in channels_first image_data_format mode.

keras/utils/data_utils.py, tests/keras/utils/data_utils_test.py
The changes were designed to preserve backwards compatibility while adding support
for .tar.gz, .tgz, .tar.bz, and .zip files.
sha256 hash is now supported in addition to md5.
This should resolve #5861
=> get_file() with tar, tgz, tar.bz, zip and sha256, resolves #5861.

keras/models.py, tests/test_model_saving.py
load_model fails when a model has multiple output layers that have more
than one metric. Solve this problem by adding a clause that checks if
metrics are a list.
For more elaborate description see issue #3958
=> Fix load_model for multiple output metrics in dictionary

keras/engine/topology.py, keras/models.py
`save_model` saves the model with optimizer's state.
If output model is used only for predicting, optimizer's state is useless.
This PR make it possible to save model without optimizer's state.
(It also helps avoiding #6046.)
=> Add `include_optimizer` argument to `save_model`

keras/backend/tensorflow_backend.py
Keras fails If first model weights reading is done from another thread.
This is because:
1. TensorFlow keeps dataflow graph as thread local.
2. Keras assumes the only one dataflow graph in the backend.
See https://gist.github.com/StanislavVolodarskiy/60c770d8f9864487692c88fe6faae892 to reproduce the issue.
=> Proper Keras model initialization in multithreaded environment.

examples/cifar10_cnn.py
Rmsprop with default learning rate (0.001) cannot converge in this example. 
Initialize learning rate to (0.0001) and add weight decay fix the problem.
https://github.com/fchollet/keras/issues/5239
As seen in this issue also, the loss will decrease at the begining but start increasing after few epochs due to too large learning rate.
Solution to this is decreasing the learning rate with rmsprop as I supposed or changing the optimizer like Adam or SGD.
=> fix rmsprop learning rate for convergence

keras/layers/embeddings.py
The current description of the input arguments `input_dim` and `mask_zero` are a bit confusing:
> **input_dim**: int > 0. Size of the vocabulary, ie. 1 + maximum integer index occurring in the input data.
> ...
> **mask_zero**: ... If mask_zero is set to True, as a consequence, index 0 cannot be used in the vocabulary (input_dim should equal |vocabulary| + 2).
The first line seems correct, where I would understand
> Size of the vocabulary
as
input_dim = len(vocabulary_indices)
and
> 1 + maximum integer index occurring in the input data.
as
input_dim = max(vocabulary_indices) + 1
However the second line is confusing as you say
> input_dim should equal `|vocabulary| + 2`
I would interpret `|x|` as the cardinality of `x`, i.e. `len(x)`. So you are effectively saying
input_dim = …
=> DOCS: Slight rewording of description for input_dim in embeddings

keras/applications/inception_v3.py
There is a missing IF statement on the Inception v3 model of Keras 2.0 which causes an exception to be thrown if an Input layer is provided. 
Here is how to reproduce the error:
```python
import keras.applications
from keras.preprocessing import image
from keras.layers import Input
g=image.ImageDataGenerator().flow_from_directory('/path/to/data', target_size=(299, 299), batch_size=32, class_mode='categorical', shuffle=True)
x = g.next()[0]
base_model = keras.applications.InceptionV3(weights='imagenet', include_top=False, input_shape=(299, 299, 3))
model = Model(inputs=base_model.input, outputs=base_model.layers[310].output)
features = model.predict(x) # Works!
base_model = keras.applications.InceptionV3(weights='imagenet', include_top=False, …
```
=> Fixing the input for Inception v3

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, tests/keras/backend/backend_test.py
Fixes #6113 
The `in_top_k()` function in `theano_backend.py` gives incorrect result when there are identical values in the input tensor `predictions`.
Also with this PR, the return type becomes `bool`, so the same docstring as the TF version can be used now.
=> Fix in_top_k() for Theano when identical values appear in predictions

keras/layers/wrappers.py
A comment seemed a little out of order in the `TimeDistributed` docs, and led to some confusion (see https://github.com/fchollet/keras/issues/6190). This change just tries to make things a little more explicit.
=> Update TimeDistributed docs

.travis.yml, setup.py
Added test coverage check as part of pytest execution. `py.test tests/` return code will be 1 if test coverage is less than 80% or 0 if it is over 80%.
=> Added test coverage check to pytest script

examples/mnist_siamese_graph.py
Take max of squared distance and `K.epsilon()` because some data points will throw `nan`s for euclidean distance due to numerical stability issues.
=> Update mnist_siamese_graph example

docs/templates/datasets.md
- The explanations of `num_words` and `skip_top` may be wrong: that words is replaced `oov_char`'s value in [this line](https://github.com/fchollet/keras/blob/master/keras/datasets/imdb.py#L97), not 0. 
- Remove indent of `__test_split__` to show correctly
=> Update datasets docs

keras/engine/topology.py, keras/legacy/interfaces.py
On Keras 2, loading ResNet50 models saved with Keras 1.2.2 throws a "got an unexpected keyword argument 'input_dtype'" exception. Possibly the same problem appears with other models. This is because we are missing a legacy support interface for the input layer. This PR fixes the problem by adding a new legacy support interface that converts the input_dtype parameter to dtype.
Here is how to reproduce the bug:
```
$ pip install keras==1.2.2 tensorflow==0.12.1
$ python
>>> import keras.applications
>>> model = keras.applications.resnet50.ResNet50()
>>> model.save("model.h5")
>>> exit()
$ pip install -U keras tensorflow
$ python
>>> from keras.models import load_model
>>> model = load_model("model.h5")
File …
```
=> Adding backwards compatibility for old models by converting input_dtype to dtype

keras/backend/theano_backend.py
Imported `ifelse` explicitly... without this it raised the exception `"theano.ifelse.ifelse" keras no attribute 'ifelse'` in this [line](https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py#L1373)
The exception was raising for example for `Dropout` or `BatchNormalization` layers.
=> Fixed no attribute 'ifelse'

keras/utils/io_utils.py
Slight addition to the implementation of the `HDF5Matrix` class to support support inferred slices (e.g. `data[:10]`).
This is a small issue, but it can get annoying when inferring the end index (e.g. data[_start_:]), as one has to get the shape of the data set each time.
=> HDF5Matrix support for inferred slice indexing #6297

docs/templates/preprocessing/image.md, keras/engine/training.py
According to the official document and my experience of training process,
I found out that the value of "steps_per_epoch" should equal to the value of
`Total # of samples of training dataset / batch_size`.
(it's same with the api documentation [here](https://keras.io/models/model/#fit_generator))
So I think the following parts of files should be modified.
=> Update the value of steps_per_epoch of fit_generator to be divided by batch_size

keras/utils/layer_utils.py
Model is not sequential if there is a "merge" layer somewhere in the graph. So if a layer has multiple input layers ("inbound_layers"), the entire model is in my opinion no longer sequential...
Updated the check for sequential models in the print_summary() function in layer_utils.py and commented the check for sequentiality.
=> Update check for sequential models

docs/templates/initializers.md
=> Fix doc: an obsolete code example

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, tests/keras/backend/backend_test.py
Adds the method logsumexp(x, axis, keepdims) to the backend.
Tensorflow (resp. Theano) offers an optimization for computing `log(sum(exp(x)))` as `x_max + log(sum(exp(x - x_max)))` that improves numerical stability for large values. It is exposed by `tf.reduce_logsumexp` (resp. internal graph optimization).
Having this functionality simplifies building a Conditional Random Field with Keras (see PR #4621).
=> Added logsumexp to backend.

keras/engine/topology.py, keras/layers/convolutional_recurrent.py, keras/layers/recurrent.py, tests/keras/layers/recurrent_test.py
I have begun to review the changes made in da21c15. There appears to a number of issues
- If `initial_states` is a list of tensors, it will not have the attribute `_keras_history`, and will be treated as a numerical value.
- If `initial_states` is passed as a keyword argument to `call`, it will be ignored / overwritten.
- `state_spec` may not be defined by the time it is used (`state_spec` is defined in `build`).
- In `reset_states`, there is a check if `input_spec` is not `None`. However, `input_spec` is never `None`, because it is defined in `__init__` to be `InputSpec(ndim=3)`.
- There is an inconsistency between using the singular and plural of `initial_state` and `initial_states`.
- the signature for `reset_states(state_values)` is inconsistent with the signature for …
=> Fix Specifying Initial States of RNN Layers

keras/layers/recurrent.py, tests/keras/layers/recurrent_test.py
The variable `values` is not defined in the file, 
@Joshua-Chin: Could you check that this is correct?
=> Bug fix in recurrent layer

keras/engine/topology.py
This change splits determining the computation graph depth into two phases:
1. Traversal happens in the same order as previously, but nodes are only appended to a list that is sorted in order of decreasing depth. This means that the work of updating the depth for each node is does not have to be repeated for shared subgraphs, and the algorithm can completely ignore nodes it has already seen once. This means that the runtime will be linear in the number of nodes.
2. The actual node depths are then determined by a single pass across all nodes.
Because the layer ordering only depends on the layer depth and the time the layer is first seen during traversal, the observable outputs are completely identical to the current implementation.
With this change, `make_left_tower` and `make_right_tower` …
=> Use linear time algorithm for topological sorting. (Fixes #6285)

keras/utils/vis_utils.py
I was having difficulties with the `keras.utils.plot_model` function, specifically that pydot no longer supports the `find_graphviz` function, and installing `pydot-ng` instead does not seem to fix it. This pull request should solve [issue #3210](https://github.com/fchollet/keras/issues/3210).
=> Added support for new pydot versions to fix find_graphviz error

keras/engine/training.py
Remove excess preceding 4 spaces in Model.fit(..) docstring line
corresponding to verbose parameter.
=> Fix indent size of docstring's line

docs/autogen.py, docs/mkdocs.yml
I think it makes a lot of sense to mirror the [contributing page on GitHub](https://github.com/fchollet/keras/blob/master/CONTRIBUTING.md) on the doc site, as many other projects do. While we could simply copy `keras/CONTRIBUTING.md` to `keras/docs/templates/contributing.md` and be done with it, but we can also `shutil.copyfile()` at `autogen.py` runtime, so that any future changes to `keras/CONTRIBUTING.md` will be reflected on the doc site.
=> Update docs and add contributing page

keras/callbacks.py
Esoteric issue with CSVs. With Windows and Python 2 you need to open in binary mode. Text mode works for all other OS and for Windows with Python 3. Only one configuration but probably a large user base.
With this patch, I get "0d 0a" line endings on Windows. Without it, I get "0d 0d 0a". If you open in something like Excel, every other line will be blank.
I implemented as an attribute. If someone has an odd setup where they need something else they could overwrite it easily enough.
Any fellow Keras on Windows people out there? No real way to test this on our Travis setup. Can anyone confirm or test on Windows? This is a known issue in native windows Python 2. I haven't tested this in cygwin or the new bash on Windows.
Cheers
=> Fix CSV formatting for Windows with Python 2

keras/models.py
Under many scenarios, users **DO NOT** want to compile the `fit()` function during loading. For example, users might want to make predictions rather than continue training, or to make surgery on the loaded network to build a new one.
In theano, even the compiled model is cached in temporary files, the compilation of a `fit()` function of a complex network (e.g. ResNet-50) takes unbearable times (around 300 seconds). 
Therefore, I add a `skip_compile` option to the `load_model()` function, which can greatly reduce the deployment time of a network after pretrained, especially for those who are using Theano as a backend.
=> Add skip_compile option to keras.models.load_model()

keras/utils/conv_utils.py
This PR modifies a miscondition that can not make 3D kernels in `Conv1D` pass the `convert_kernel` function.
=> Fix valid condition for TF <-> TH conversion of Conv1D

tests/test_model_saving.py
Small fix to test_saving_without_compilation. Currently the test calls compile before saving which does not appear to be the intended behavior of the test.
=> Fix error in test_saving_without_compilation

keras/callbacks.py, keras/engine/training.py, keras/models.py, tests/keras/test_callbacks.py
Adds gradient distribution visualizations to TensorBoard callback. Here is how it looks like in MNIST MLP training:
Fixes #6215.
I'm not sure about two things: 
1. ~I couldn't figure out why self.validation_data includes only the inputs if self.model.uses_learning_phase is False. So I didn't change this part, you can help me out on that.~ I'm not sure whether the only difference between `self.model.uses_learning_phase==True` and `self.model.uses_learning_phase==False` is `K.learning_phase()` element in feed_dict.
2. `model.{targets,sample_weights,total_loss}` is required for this PR. It's fine for the models using the functional API since these are available as class members but for the `Sequential` class objects, this is not the case, so I added them as members for `Sequential` as well. …
=> Visualize grad distributions in TensorBoard

keras/backend/tensorflow_backend.py
Argument `reduction_indices` is depreciated in tensorflow. It also causes shape inference issue for placeholder, example
```python
x = K.placeholder((None, 9, 9))
y1 = tf.reduce_logsumexp(x, reduction_indices=2)
K.int_shape(y1)  # gives None
y2 = tf.reduce_logsumexp(x, axis=2)
K.int_shape(y2)  # gives (None, 9)
```
=> Fixed issue in K.logsumexp in tensorflow backend

keras/preprocessing/image.py, tests/keras/preprocessing/image_test.py
This patch adds a new class_mode to keras.preprocessing.image.ImageDataGenerator.flow_from_directory method. 
This new class_mode is 'identical' and it allows to generate minibatches where the target values are identical to input values. It makes working with autoencoders trivial. This issue has been described in #4260. The patch also contains tests that ensure that the input images are not the same numpy array as target images.
=> Add a directory iterator option to allow to work easily with autoencoders (issue #4260)

keras/backend/__init__.py
Add exception handling when attempting to write keras config file to disk to match tf.contrib.keras implementation.
Basically trying to match:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/keras/python/keras/backend.py#L3648
My understanding is that writing the config file is only an "attempt" and should be treated as such?
=> Add exception handling when attempting to write keras config file

keras/utils/generic_utils.py
This PR fixes the case when using small batch sizes in `evaluate` and `predict`, the final update may be randomly throttled and the total elapsed time is not displayed. 
Note that `fit` does not suffer from this problem because it uses the `ProgbarLogger` and forces the update `on_epoch_end`.
=> Don't rate limit final Progbar update

docs/autogen.py
Two hyperlinks (namely `[here]` and `[details]`) are misrendered in TensorBoard callback documentation, see https://keras.io/callbacks/#tensorboard. PR excludes `(` in argument names, because otherwise `[link](http://` is rendered as a function/class argument.
=> Fix hyperlink misrendering in documentation

keras/callbacks.py, keras/engine/training.py, tests/keras/test_callbacks.py
In cases where jobs are submitted to a queue, it would be helpful to have training terminated automatically when NaN loss is encountered, as stated in issue #4848. This PR uses a callback to stop training at the end of a batch if the loss is NaN.
=> Add callback to terminate training if NaN loss encountered. (Update to #4849)

keras/callbacks.py
Fix bug in EarlyStopping to reset stopped_epoch in on_train_begin to allow it to be re-used. This code change allows me to know check EarlyStopping.stopped_epoch after each train to figure out if this callback triggered and at which epoch.
My exact use case is I have created a custom callback which may also trigger self.model.stop_training, just like EarlyStopping . If my custom callback triggers self.model.stop_training then the EarlyStopping callback will have stopped_epoch set to some value from a previous train.
=> Fix bug in EarlyStopping to reset stopped_epoch

examples/neural_doodle.py
1) Fixed type cast in region_style_loss() which prevented example to run: K.shape returns int32, but variable was immediately used in division operation which requires float32.
```
File "neural_doodle.py", line 241, in region_style_loss
s = gram_matrix(masked_style) / K.mean(style_mask) / num_channels
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: 'Tensor("strided_slice_8:0", shape=(), dtype=int32)'
```
2) Also updated argument in AveragePooling2D usage to match Keras2 API. Put 'padding' instead of older 'border_mode'
```
neural_doodle.py:200: UserWarning: Update your `AveragePooling2D` call to the Keras 2 API: `AveragePooling2D((3, 3), padding="same", strides=(1, 1), name="mask_block1_conv1")`
1, 1), name=name, border_mode='same')(x)
```
=> Small fixes for Neural_Doodle example

keras/callbacks.py, tests/keras/test_callbacks.py
As @smyskoff diagnosed in https://github.com/fchollet/keras/pull/5247, tensorboard callback records weights of __all layers__ by default and does not respect the `embeddings_layer_names` parameter since `tf.train.Saver()` is instantiated without arguments. This PR fixes that.
I also replaced the self.embeddings_logs list with a string, so that variables are serialized to only one file, which is sufficient. Test case is also added.
=> TensorBoard: Embed only given layers

keras/backend/__init__.py, keras/backend/common.py, keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/engine/topology.py, tests/keras/backend/backend_test.py
* raise ValueError if `inputs` is not a Keras tensor
=> Better error message for invalid functional api inputs (#6589)

keras/engine/topology.py, tests/keras/engine/test_topology.py
This PR fixes a bug where model serialization and loading is broken when a shared layer is used at several different depths in a model (issue found here: https://github.com/allenai/deep_qa/pull/357).  I first added a test that failed on master, then fixed the test.  Hopefully the test and the comments around the test and the fix are enough to explain what's going on.
=> Fix depth calculation for shared layers

keras/preprocessing/text.py
text_to_word_sequence returns a list of words not integer indices as stated. I've corrected this.
=> updated text_to_word_sequence description

keras/utils/data_utils.py, keras/utils/generic_utils.py
Includes fix get_file download progress bar #6535 with improvement to scoping clarity.
Additionally fixes bug in python 2.7 where `get_file()` crashes when downloading files where the response does not supply `'Content-Length'`:
```python
from keras.utils import get_file
listing_url = 'https://sites.google.com/site/brainrobotdata/home/grasping-dataset/grasp_listing.txt'
grasp_listing_path = get_file('grasp_listing.txt', listing_url)
```
=> get_file() progbar fix

keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/engine/training.py, keras/models.py
Enables generating profiling data when using the Tensorflow backend, as requested by #6606
Passes all of the tests using the Tensorflow backend on my machine (I haven't changed anything in the Theano backend, so haven't run those tests).
It's a bit hacky how kwargs to `model.compile` are passed into `tf.Session.run` so understand if you don't want to merge this. If you're fine with this, I can update this with an example of how to generate trace files if you'd like?
=> Add Chrome timeline support in Tensorflow

.github/stale.yml
@fchollet Merge this pull request plus follow https://github.com/integration/probot-stale to automatically mark the many 3 month old issues as stale, then close them after an additional 30 days.
I chose 30 additional days for closing because sometimes people go on vacation for a few weeks, this way they'll have time after being notified.
=> Automatically close stale issues

keras/models.py, keras/utils/generic_utils.py, tests/test_model_saving.py
Custom activation functon can't load with `keras.models.load_models(custom_objects=*)`, because given`custom_objects` doesn't bypass to `deserialize_keras_object()` through `keras.activations.get()`.
In initialization of layer (`Layer.__init__()`), the custom activation function is given as an `activation` argument as a string identifier, and deserialize it by calling `keras.activations.get()`. However, layers and `keras.activations.get()` don't take `custom_objects` as an argument. The deserialization of custom activation function is failed with `Unknown activation function` error.
To fix this bug,  use `CustomObjectScope` in `keras.models.load_models()`. By doing so, bypassing `custom_objects` over many function is not required.
Test code:
```python
import keras
import keras.backend as …
```
=> Fix failture of loading custom activation function with `keras.models.load_models(custom_objects=*)`

keras/applications/inception_v3.py, keras/applications/resnet50.py, keras/engine/topology.py
This PR fixes ImageNet weight loading for ResNet50 with channels_first described in "Requests for Contributions". I explored some possible solutions, and think this might be a concise solution.
First of all, `load_weights()` should be able to load weights even if `K.image_data_format()` and `image_data_format` of weight files are different. For loading weights saved with `channels_last` under `channels_first` runtime setting (and vice versa), `load_weights()` must be able to detects the difference of `image_data_format` between saved files and runtime setting. Because `image_data_format` is not saved as an hdf5-attribute of weight files, this PR used `K.int_shape(layer.weights[0]) != weights[0].shape` as a condition for dim-ordering conversion. Note that the `layer.weights[0]` is a …
=> Fix ImageNet weight loading for ResNet50 with channels_first

.github/stale.yml
Got notified about some stale threads, but realized I forgot to put the number of days in the post's string.
=> stale bot specifies 30 days when it posts

keras/engine/topology.py, tests/keras/engine/test_topology.py
This PR proposes an warning message for redundant outputs when using functional API.
=> Add warning message for redundant outputs

keras/models.py
One problem that I had with the current load_model function defined in keras.models, is that, when an error is raised somewhere in the body of that function, the hdf5 opened at the beginning of the function is never closed. So say I want, after having caught the exception, to modify the content of the hdf5 to solve the error, I cannot reopen it in write mode since it is already opened in read mode, and the reference to that file is lost.
Full disclosure, I got this error when trying to load hdf5 models created with keras 1, with keras 2. A problem stems from incompatible format for optimizer wieghts. Since I only care about inference in my code, a simple solution is to delete the optimizer weights from the hdf5. I only do that when I detect that load_model raised a ValueError (which …
=> close the opened hdf5 file in load model in case of error

keras/backend/tensorflow_backend.py
This PR makes docstrings consistent over `image_data_format`, `padding`, and `pool_mode`.
=> Make docstrings consistent

keras/layers/embeddings.py, tests/keras/layers/embeddings_test.py
1. Support high dimension input, e.g., in NLP, input could have shape like `(n_batch, n_sentences, n_words)`. 
2. No need to use `input_length` at all, but left for back compatibility.
=> Modify embedding to accept arbitrary input dim

LICENSE
Correction at https://github.com/fchollet/keras/pull/6800/files/8a93935d99fae4b8dc2ce0ea1a169906da0a165d#r120219133 also applies to all other contributers. It probably applies François Chollet and Google too, but I'm only a member of "All other contributors" so I figured the other changes should be made by those respective rightsholders. :-)
=> Update LICENSE dates for all other contributors

keras/layers/core.py, keras/models.py, tests/test_model_saving.py
When we use numpy arrays in arguments of Lambda layers, they cannot be serialized with model.save.
For example, running 
```
from keras.layers import Input, Lambda
mean = np.zeros((2,2,1))
xi = Input(shape=(2,2,1), name="input")
p = Lambda(lambda image, mu: image - mu, arguments={'mu':mean})(xi)
model = Model(inputs=[xi], outputs=[p])
print("Arguments to save : {}".format(model.layers[1].arguments))
model.save("titi.h5")
```
fails with "ValueError: can only convert an array of size 1 to a Python scalar"
The issue comes from models.py:get_json_type which invokes obj.item in case of a numpy object but this fails if the object is indeed a numpy array. 
This pull requests propose to handle specifically the case the serialized object is a …
=> Serializing/Desrializing numpy arrays in Lambda layer arguments

keras/engine/topology.py
Raise a descriptive error if `Model` constructor `inputs` are not inputs.
I had a typo where I swapped the inputs and outputs and the resulting error was a little weird.
> AttributeError: 'Dense' object has no attribute 'is_placeholder'
PR adds a check for `is_placeholder` just before that line so I get a message like this.
> ValueError: Input 0 (0-indexed) `<keras.layers.core.Dense object at 0x000000003C445128>` has no attribute `is_placeholder`. Is it an Input layer?
Cheers
=> Raise a descriptive error if `inputs` are not inputs

examples/neural_style_transfer.py
Incorporates the improvements suggested in https://github.com/fchollet/keras/pull/6872
Specifically - 
1) Uses VGG 19 rather than VGG16.
2) Uses block5_conv2 (conv5_2) layer for better results, in contrast to conv4_2 as suggested by the original paper.
3) Image initialization is now done using the content image itself, rather than noise.
=> Improvements to Neural Style Transfer

keras/backend/cntk_backend.py
batch_set_value() is defined twice.
@souptc
=> Remove duplicated batch_set_value in cntk_backend

keras/engine/topology.py
If an input layer is supplied an input_tensor among its arguments, it will try to determine the batch_input_shape based on this tensor. 
I am using a separate pre-trained network inside a keras custom loss function, and sending the y_pred and y_true through a network. This resulted in the shape (None, None, None, None), which eventually leads to the program failing. I know the shape beforehand, however, setting the batch_input_shape didn't help. In this PR, I made it so that the input layer will always use batch_input_shape if it is set.
=> Use batch_input_shape in input layer even if input_tensor is set

keras/engine/training.py, tests/keras/engine/test_training.py
model.fit assumes it can figure out the size of the input.
A broader question: maybe I should replace all those `len(x[0])` in the file with `x[0].shape[0]`?
=> Fix a bug when training with sparse matrices

keras/backend/tensorflow_backend.py
It seems to me that there are probably wrongly copy-pasted comments in `binary_crossentropy` and `sparse_crossentropy` so this PR fixes that.
=> Fix comments for binary_crossentropy and sparse_crossentropy.

docs/templates/applications.md
The documentation wrongly states that the 2 last inception blocks consist of layers `model.layers[172:]`. Fixes #6910.
This PR corrects the number of layers for two last inception blocks in the documentation.
=> [Documentation] Fine-tuning InceptionV3

keras/preprocessing/image.py
Sped up DirectoryIterator's __init__ execution by parallelizing via multiprocessing the samples counting and extraction of samples labels and paths.
This can speed up execution significantly when dealing with big datasets.
=> Parallel directory iterator initialization

keras/callbacks.py
I tried to use "accuracy" for early stopping and got error `Early stopping requires accuracy available!` which was not immediately clear to me (the problem is that correct name should be "acc")
Now the message is going to be something like `Early stopping conditioned on metric 'accuracy' which is not available. Available metrics are: val_loss,acc,val_acc,loss` - more helpful IMO
=> More descriptive message when user specifies non-existing metric for early stopping

docs/templates/getting-started/faq.md
Corrected minor typo in faq.md.  In particular, the word "file" was incorrectly written as "filed" in 3 locations in the faq section.  The official documentation currently reads:
Where is the Keras configuration file**d** stored?
_(note "d" at end of word "filed")_
The correction removes the "d" at end of word "filed" .
Thanks.
=> Minor typo correction in faq.md

keras/layers/wrappers.py, tests/keras/layers/wrappers_test.py
It seems that the `TimeDistributed` layer has a similar issue as the `Bidirectional` layer when passed a layer that requires the learning phase as described in:
* https://github.com/fchollet/keras/issues/5940
* https://github.com/fchollet/keras/issues/5975
* https://github.com/fchollet/keras/pull/5985
This simple example reproduces the problem and is included in the unit tests in the PR. This was tested on a clean copy of the master branch on the commit prior to the PR.
```python
from keras.layers import core, wrappers
model.add(wrappers.TimeDistributed(core.Dropout(.5), input_shape=(3, 2)))
model.compile(optimizer='rmsprop', loss='mse')
model.predict(np.random.random((10, 3, 2)))
```
The error output is longish …
=> Fix issue where TimeDistributed doesn't pass uses_learning_phase

keras/callbacks.py
Screen readers use text to speech. They read the text associated with links aloud to people hard of sight. If links are named "here" it becomes very difficult to navigate, so I fixed one case here. :-)
=> "here" links are difficult for individuals that need a screen reader for accessibility.

keras/layers/advanced_activations.py
For models containing a `LeakyReLU` layer, saving and loading the model will result in a `TypeError`.
```
TypeError: float() argument must be a string or a number, not 'dict'
```
The reason is that the scalar argument `alpha` is converted to and saved as a `numpy.array`, instead of a `float`, in the following lines:
```python
self.alpha = K.cast_to_floatx(alpha)
```
```python
config = {'alpha': self.alpha}
```
The issue can be reproduced by the following code:
```python
from keras.models import Sequential, load_model
from keras.layers import Dense, LeakyReLU
model.add(Dense(1, input_shape=(10,)))
model.add(LeakyReLU())
model.save('1.h5')
model = load_model('1.h5')
```
The solution to this problem is already implemented in the `ELU` layer:
```python
config = {'alpha': …
```
=> Fix model saving/loading for LeakyReLU layer

keras/legacy/interfaces.py, tests/keras/legacy/interface_test.py
I was going from Keras1 to Keras2 and had call like 
`model.fit_generator(gen, gen.n, verbose=1, validation_data=gen, nb_val_samples=10) `
I got an warning: 
```
UserWarning: Update your 'fit_generator' call to the Keras 2 API: 'fit_generator(<ssd_gener..., 10, 1, verbose=1, validation_data=None, validation_steps=1, workers=1)
```
but no information about other changes. So I changed nb_val_samples quickly and I got the exact same output/information as before. Quite much later I noticed that it was 30 times slower. Keras2 changed *_generator arguments (and seems like a smarter way to do things) but I didn't notice it. I should have used named arguments at everything would been fine :P Quick googling resulted that maybe others have done the same mistake but its hard to know if its about …
=> Keras 2 _*generator displaying warning always about semantic changes from Keras 1

keras/engine/training.py
training.py `'mean_squared_error'` was misspelled as `'mean_square_error'`.
=> mean_square_error => mean_squared_error

keras/__init__.py, keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/engine/topology.py, keras/layers/core.py, keras/layers/wrappers.py, keras/legacy/layers.py, keras/utils/__init__.py, keras/utils/generic_utils.py, keras/utils/test_utils.py, keras/wrappers/scikit_learn.py, tests/keras/utils/generic_utils_test.py
Running keras gives pages and pages of
```
[...]/lib/python3.6/site-packages/keras/utils/generic_utils.py:135: DeprecationWarning:
inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
```
This patch adds a `has_kwarg` function which performs the checks that were previously being done with getargspec, but avoids the DeprecationWarning and supports Python 3 features such as keyword-only and positional-only arguments.
=> Avoid DeprecationWarning from inspect.getargspec

keras/callbacks.py
Implements the silent fix that `@fchollet` proposed in https://github.com/fchollet/keras/pull/6515#issuecomment-299547853.
=> Rename tensorboard histogram names to silence warnings

keras/callbacks.py
As it says in the #4116 description, current example throws an error because of the dimensions mismatch between np.arange(...) and logs['loss']. One way to fix this is to keep track of all the losses.
=> Replace non-working plot_loss_callback example (#4116)

keras/layers/recurrent.py
The url to the original LSTM paper in `keras/layers/recurrent.py` is no longer available (404 is returned), so this PR fixes it.
=> fix url to LSTM paper

keras/engine/training.py, tests/keras/engine/test_training.py
Currently, when `evaluate_generator` receives an empty batch, it will return nans because of the `np.average` at the end.
When I encountered a bug in my code that triggered this, I thought that my network was overflowing somewhere, resulting in hours of debugging the network.
I therefore propose throwing an exception when this happens.
=> throw an error when receiving empty batch, instead of returning nans

tests/test_multiprocessing.py
There was a recent pull request that appeared to fix the problem, but actually it just ran into a different failure case. This actually fixes it. :-)
=> test_multiprocessing.py fix incorrect use of numpy.random.randint

keras/callbacks.py
When using the `RemoteMonitor` callback the headers sent with the request to the remote server defaulted to `{'Accept': 'application/json', 'Content-Type': 'application/json'}`. However, the request sent is not of type `application/json` but rather `application/x-www-form-urlencoded`. This led to some confusion when implementing a custom remote server.
Also, the [hualos](https://github.com/fchollet/hualos/) project breaks because of this bug.
This PR changes the default `Content-Type` header to `application/x-www-form-urlencoded`.
=> Fixed default header in RemoteMonitor callback.

docs/templates/preprocessing/text.md, keras/preprocessing/text.py, tests/keras/preprocessing/text_test.py
As pointed out in #2294 the one_hot function does not really implement a one hot encoding, but a hashing-based encoding, with possible collisions between words.
This method is a well-known indexing method, a.k.a. the hashing trick.
For this reason I propose to rename the function from one_hot to hashing_trick.
I also changed the implementation, as the original one_hot function used the hash() function that is not implemented as a stable hashing function (due to security concerns), and replaced it with md5() from hashlib, which is stable.
The use of md5 is not as straightforward and fast as using a dedicated hashing function, such as murmurhash, but using it as default avoids adding new dependencies to keras.
A custom hashing function can be eventually passed as a parameter to the …
=> Renamed one_hot function to hashing_trick, made hashing stable

docs/autogen.py, keras/__init__.py, keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/engine/topology.py, keras/layers/core.py, keras/layers/wrappers.py, keras/legacy/interfaces.py, keras/legacy/layers.py, keras/utils/__init__.py, keras/utils/generic_utils.py, keras/utils/test_utils.py, keras/wrappers/scikit_learn.py, tests/keras/utils/generic_utils_test.py
Pull request #6817 broke the build because of incompatible changes which had been added to master in the intervening time. The code here has been rebased on the latest master.
=> Avoid DeprecationWarning from inspect.getargspec (rebased)

keras/utils/io_utils.py, tests/keras/utils/io_utils_test.py
When replacing a numpy array with HDF5Matrix, certain attributes are required. I added `dtype`, `ndim` and `size` and updated these including `shape` with the corresponding doc strings from h5py.Dataset.
=> Add more numpy-style attributes to HDF5Matrix

keras/utils/data_utils.py
This refers to https://github.com/fchollet/keras/pull/6891#issuecomment-309889683
=> Call self.executor.join() in OrderedEnqueuer to prevent zombie worker processes

tests/keras/layers/wrappers_test.py
This makes the unit tests pass.
full issue: https://github.com/fchollet/keras/pull/7033
=> wrappers_test.py quick fix for flaky TimeDistributed test

keras/engine/training.py, tests/keras/engine/test_training.py
=> training.py _weighted_masked_objective fix crash when weights is None

keras/engine/training.py, tests/keras/engine/test_training.py
atomic component of #6928 and #7046
=> training.py _slice_arrays() fix crash when arrays are None

keras/backend/cntk_backend.py
This pull request is for issue #7055 
In current version, cntk can't support variable length input, add more meaningful error message.
We are working on this feature and hopefully could support it in next release.
=> Add more meaningful message when cnkt can't handle variable length input

keras/backend/tensorflow_backend.py
A minor change due to tensorflow API deprecated attribute. This PR also 'closes' [this](https://github.com/fchollet/keras/issues/4907). 
All tests [passes](https://travis-ci.org/vfdev-5/keras).
=> * Replace tensorflow deprecated attribute : reduction_indices -> axis

keras/callbacks.py
Same as #6954 but for callback `ReduceLROnPlateau`
=> better error message when ReduceLROnPlateau conditioned on non-existing metric

tests/keras/engine/test_training.py
This test could fail if the worker iterates over the generator before Keras could throw the ValueError.
The StopIteration was caught because exceptions were weirdly handled before and would always throw StopIteration over the real exception : ValueError.
=> Fix test in training

keras/backend/cntk_backend.py, keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/layers/convolutional.py, tests/keras/layers/convolutional_test.py
Implemented Conv3DTranspose (w/ Deconv3D and Deconvolution3D aliases) in tensorflow, theano, and cntk backends, along with the appropriate abstract layer. This is implemented in the Keras 2.0 API and you'll notice how similar these operations are to the relevant 2D ones.
=> conv3d_transpose in tf, th, and cntk

keras/initializers.py
For the 'channels_last' case the receptive_field_size needs to be computed as the product of all dimensions except the last two (input_depth, depth). The old version computes it incorrectly for Conv1D and Conv3D.
=> Fix computation of receptive field size for 'channels_last'

keras/engine/training.py, tests/test_loss_weighting.py
The error is now a ValueError, as per docs, and contains a suitable message.
The rational is that when a class is missing in `class_weight`, it is not clear for the user what is happening, and whether it is just that class, or also others.
=> Improved error message for missing class_weights.

docs/templates/activations.md, keras/applications/mobilenet.py, keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/engine/training.py, keras/models.py, tests/keras/applications/applications_test.py, tests/keras/backend/backend_test.py
This PR updates backend strings mainly involving CNTK. Additionally, `Tensorflow` are replaced by `TensorFlow` for consistency over docstrings.
=> Update TensorFlow and CNTK backend strings

tests/keras/backend/backend_test.py
This PR improves readability for backend tests. Since CNTK added, it becomes hard to add something into backend tests due to many hardcoded and cntk-specific patchwork. I think it is better to clean up the current tests first in order to write new tests for increasing test coverages. Especially, this PR focuses on integration of `cntk_check_*_tensor_operation` into `check_*_tensor_operation`.
=> Improve readability for backend tests

keras/preprocessing/image.py
This PR adds a seed parameters to keras.preprocessing.image.random_transform.
The case I had required both image and corresponding segmentation to be augmented. I'm not using the flow methods or `NumpyIterator`/`DirectoryIterator`. Instead I wrote my own generator which uses `random_transform` to transform images.
Using this PR I can use a seed like the current timestamp to feed to `random_transform` to get identical transforms for my image/segmentation pair. This is analogous to the example at the bottom of [this page](https://keras.io/preprocessing/image/). However, in that case one seed suffices. In my case I have to use a different seed every time I plan to use `random_transform` on an image/segmentation pair (otherwise if I used a constant seed I'd get the same transformation applied …
=> Add seed parameter for image augmentation method.

keras/utils/data_utils.py
This PR aims at making the Sequence faster when using "LARGE" object. 
I do not fully understand the "C Magic" behind the slowdown, but there seems to be a lot of time wasted copying the Sequence to each worker.
Sharing the Sequence is really fast.
```
('Took Holder Manager list', 0.12332582473754883)
('Took list', 30.01058602333069)
```
You can reproduce with : https://gist.github.com/Dref360/95c0d6df9372b29c103066daeb3ce3b2
This fix is supported by both Python 2 and 3.
I don't think adding a test to validate the speedup is useful since this may create a flaky test.
=> [Performance] Add a manager to share the sequence

keras/utils/data_utils.py
Reverts fchollet/keras#7256
This is actually super dumb. I should've never done that in the first place.
So if the Sequence is shared, the computation happens on the server not on the clients so no multiprocessing. 
The correct way to do that is that the internals of the Sequence should be shared, not the Sequence itself. 
In conclusion, it is not Keras' duty to handle this case but the programmer.
Sorry for the trouble.
=> Revert "[Performance] Add a manager to share the sequence"

keras/engine/training.py, tests/keras/test_callbacks.py
Without this change, setting model.stop_training = True in on_batch_end of a callback has no effect when using the fit_generator. This behaviour is different when using fit. This change makes fit and fit_generator respond alike to a training stop at the end of a batch in a callback.
=> Check if stop_training is true after on_batch_end in fit_generator

keras/preprocessing/image.py, tests/keras/preprocessing/image_test.py
This PR fixes standardize in ImageDataGenerator so that it doesn't crash when given a batch and zca whitening is selected. The following code showcases the crash that this PR fixes.
```python
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
(x_tr, y_tr), (x_te, y_te) = cifar10.load_data()
g = ImageDataGenerator(zca_whitening=True)
g.fit(x_tr)
g.standardize(x_tr[:10])  # This shouldn't crash, but it does!
```
=> Fix ImageDataGenerator.standardize to support batches

keras/engine/training.py, keras/utils/data_utils.py, tests/keras/engine/test_training.py, tests/keras/utils/data_utils_test.py
Previously, the scheduling parameter was not passed to the OrderedEnqueuer, which was needed in training.
Since the scheduling parameter is currently a binary decision, I've also altered the value to a boolean and changed the kwarg to be more descriptive.
It also, seems we may need a shuffle function inside the Sequence call. Currently, only the input is shuffled, whilst this ensures some randomness this could be improved on via a function call.
Also, @fchollet do you remember why in the generators you passed different seeds? - This is also missing from the current code, however, it is trivial to implement.
=> Passed the scheduling argument through the `*_generator` function.

keras/layers/recurrent.py, tests/keras/layers/recurrent_test.py
I noticed that when working with LSTM layers and setting `unroll=True`, Keras allows the LSTM to be initialized with one timestep, which leads to mismatched dimensions:
```
In [1]: from keras.models import Sequential
...: from keras.layers import LSTM, Dense
...: from keras import backend as K
...: 
In [2]: model = Sequential()
...: model.add(LSTM(50, batch_input_shape=(1, 1, 10), unroll=True))
...: 
In [3]: model.layers[-1].output_shape
Out[3]: (1, 50)
In [4]: K.ndim(model.outputs[0])
Out[4]: 1
```
This leads to pretty cryptic errors down the road:
```
In [5]: model.add(Dense(1))
ValueError                                Traceback (most recent call last)
<ipython-input-5-b296f1d485b9> in …
```
=> Throw exception in LSTM layer if timesteps=1 and unroll=True

keras/preprocessing/image.py
In the case of greyscale images, channel axis should be of length 1, however a warning was still displayed due to incorrect checks. Added 1 as a valid length.
=> Fixed warning showing up when channel axis is 1

keras/backend/cntk_backend.py, keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, tests/keras/backend/backend_test.py
The `stop_gradient` documentation states that the argument should be a list of
variables. The Theano implementation crashes if the argument is a list of
variables and the CNTK implementation crashes regardless but expects a list anyway (since it passes it to combine). The TensorFlow implementation expects one variable but in case a list is passed it doesn't crash as long as the shapes are all the same.
This commit handles both cases as can be expected. The following code illustrates the current Keras behaviour.
```python
val = np.random.rand(10, 3)
backends = [KTH, KTF, KC]
as = [k.variable(val) for k in backends]
bs = [k.square(a) for k, a in zip(backends, as)]
a, b = as[1], bs[1]
KTF.stop_gradient(a)  # works
KTF.stop_gradient([a, b])  # works but returns a tensor?
a, b = as[0], bs[0] …
```
=> Fix stop_gradient inconsistent API

keras/optimizers.py
The constants here are stored as float32 by default and break graph compilation for float16. The fix is to simply "cast_to_floatx()" on the constants.  Tensorflow automatically does this so I'm not sure why keras has this issue.
=> Fix graph compilation when using half floats.

docs/templates/getting-started/faq.md
There isn't any documentation on how to load custom layers when using `load_model` apart from [this issue](https://github.com/fchollet/keras/issues/4871). Putting an example in official documentation will help people who are trying to load their model with custom layers/functions.
=> add example for passing in custom objects in load_model

keras/layers/convolutional_recurrent.py, tests/keras/layers/convolutional_recurrent_test.py
Added support for the return_state=True parameter in the ConvRecurrent2D abstract class.
=> Support return_state parameter in ConvRecurrent2D

keras/layers/convolutional.py
=> Docs fix: `pointwise` instead of `depthwise` for SeparableConv2D

setup.py
Development of `pydot` has now converged [here](https://github.com/erocarrera/pydot), with version 1.2.0 providing the missing Python 3 support. The old `pydot` and `pydot-ng` are no longer maintained.
=> Switch to pydot 1.2.x

keras/backend/cntk_backend.py, keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/losses.py, tests/keras/backend/backend_test.py
This PR inverts the order of the `output` and `target` arguments in backend crossentropy methods, to make them consistent with the functions in `losses` and the functions in TF.
This is a breaking change. We believe it is an acceptable breakage because:
- API consistency is important
- the "official" API is definitely the one in `losses`, not the backend functions. The backend functions are meant as a cross-backend layer that is not used if an equivalent function exists in the higher-level Keras API.
- we don't expect that more than a handful of users were using these backend methods directly.
Also: some backend style cleanups.
=> Crossentropy backend API consistency cleanup

keras/backend/tensorflow_backend.py, tests/keras/backend/backend_test.py
Fixes #7410 
Correctly handle dynamic shape to be passed to `repeat_elements` in tensorflow backend. Before this commit, it raised error if the axis to be repeated was None.
=> Allow dynamic shape for repeat_elements

keras/models.py
This fix a minor bug in docstring. The file pointer closed in the iteration.
=> Fix doc example of models.py's method fit_generator()

docs/templates/getting-started/functional-api-guide.md, keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, keras/callbacks.py
This PR increases consistency for docstring examples. Additionally, `layer.output` raises `AttributeError` in case of multiple inbound nodes.
=> Improve examples

.travis.yml, keras/backend/cntk_backend.py, tests/keras/backend/backend_test.py, tests/keras/layers/recurrent_test.py, tests/keras/layers/wrappers_test.py, tests/keras/legacy/layers_test.py
This pull request is to update with CNTK 2.1 release features:
1. support mask in recurrent layer.
2. support reverse op and bidirection wrapper
3. cntk native op to support stateful recurrent layer.
4. update the ci test to use cntk 2.1 release binary.
=> Update cntk backend with CNTK 2.1 release

MANIFEST.in
The current release on PyPI contains the package files and setup script only. Although nominal for running a `pip install`, its content falls a bit short for packaging on Linux distributions such as Debian. This commit provides a manifest template to produce a more comprehensive tarball for PyPI:
- The README file is the single entry-point for maintainers to get information about the package. It is worth shipping regardless (`sdist` does it by default with `README.rst`, but not with `README.md`).
- The LICENSE file is the single entry-point for copyright related information. Should be shipped by default too, but is not present in the tarball for some reason. Adding it explicitly does not hurt.
- The `docs` and `examples` are worth having to enable builds of a corresponding documentation …
=> Improve content of PyPI tarball

keras/layers/wrappers.py, tests/keras/layers/wrappers_test.py
This PR fixes issue #7466. The root cause of the problem is that TimeDistributed reshapes the inputs before passing them to BatchNormalization, and batch normalization has update ops that are conditioned on the inputs. Since the inputs to TimeDistributed are different from those passed to BatchNormalization, the conditional updates don't get executed and the mean and variance don't get updated.
Wrappers could modify the inputs in many different ways, so I implemented a generic solution on the Wrapper class to map wrapper inputs to inner layer inputs. This solution should fix the issue with BatchNormaliztion and also with any other wrapped layer that might have update ops conditioned on its inputs.
=> Fix TimeDistributed BatchNormalization

keras/backend/cntk_backend.py, tests/keras/losses_test.py
If Keras needs to add value checking test for other loss functions, I will update this PR for them.
What should I do?
=> Fix sparse_categorical_crossentropy argument and add value test for it  (#7513)

keras/layers/merge.py, tests/keras/layers/merge_test.py
With the merge method being deprecated by end of 8/2017, there needs to be a way to define a subtraction of two layers. This Subtract layer takes exactly two tensors and returns the difference.
=> Subtract merge layer

keras/backend/cntk_backend.py
This pull request is to fix a bug in CNTK backend, current implementation for rnn with go_backwards = True is incorrect.
=> cntk backend: fix the reversed rnn bug

keras/applications/mobilenet.py, tests/keras/applications/applications_test.py
@fchollet There is a MobileNet image size selection problem in the current implementation. 
Due to the use of `_obtain_input_shape(...)`, the default_size provided is a static 224. While this generally works well for models with only 1 input size, for the MobileNet family of models, it is not suitable.
The issue is that when one passes `input_shape` as anything other than the default of 224 (128, 160 and 192 are supported as well), an error stating that the default size required with `include_top=True` is (224, 224, 3) is raised. This is a problem, since there exist weights for smaller input size models. They just can't be accessed with the standard working of `_obtain_input_shape`.
There are two possible ways to fix this : 
1) Make `_obtain_input_shape` support a list of default sizes. …
=> Change default size to allow different MobileNet sizes

keras/callbacks.py, tests/keras/test_callbacks.py
1. The issue described in https://github.com/fchollet/keras/issues/7397
I.e. the embedding layer has gradients represented by an IndexedSlice as opposed to a tensor. The dense gradient tensor expected by tensorflow should be extracted with the .values function.
2. Fail loudly if validation_data is None and histogram_freq is non-zero.
=> Minor tensorboard callback fixes

keras/engine/training.py, keras/models.py, tests/test_loss_weighting.py
Alternative to https://github.com/fchollet/keras/pull/7482.
This implementation is growing on me. I think the flexibility here is nice.
```python
from keras.layers import Dense
X = np.random.normal(size=(100, 10))
y = np.random.randint(2, size=100)
sample_weight = np.random.normal(size=100)
loss = 'binary_crossentropy'
model.add(Dense(10, input_shape=(10, )))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss=loss, optimizer='rmsprop', metrics=[loss], weighted_metrics=[loss])
model.fit(X, y, epochs=5, verbose=2, sample_weight=sample_weight)
```
```
Epoch 1/5
0s - loss: -1.1340e-01 - binary_crossentropy: 0.7633 - weighted_binary_crossentropy: -1.1340e-01
Epoch 2/5
0s - loss: -1.2764e-01 - …
```
=> Add weighted_metrics arg to compile

keras/preprocessing/image.py
Right now NumpyIterator wont let us use multichannel data but it's common in satellite datasets such as [Kaggle's Dstl Satellite Imagery Feature Detection](https://www.kaggle.com/c/dstl-satellite-imagery-feature-detection) or [spacenet](https://spacenetchallenge.github.io/). This changes the exception to a warning.
=> Changed exception to warning for NumpyIterator

keras/engine/topology.py, tests/keras/engine/test_topology.py, tests/keras/legacy/interface_test.py
This PR adds topology tests for the [current](https://travis-ci.org/fchollet/keras/builds/263264803) following missing lines:
```
keras/engine/topology.py                   1281    159    88%   25-26, 167-173, 279, 294, 339, 351, 411-412, 426, 438, 444-446, 454, 462, 471-472, 476, 486-487, 492, 550-553, 567, 608-611, 711-713, 731-736, 781, 784, 792, 915, 935, 1012, 1020-1022, 1046, 1054-1056, 1087, 1119, 1168, 1182, 1253, 1293, 1299-1303, 1310-1314, 1319-1322, 1334-1335, 1428, 1536-1537, 1664, 1790, 1840, 1846-1853, 2004-2010, 2037, 2041, 2057-2058, 2063, 2071, 2153, 2204, 2253, 2407, 2411, 2413-2414, 2547-2557, 2583, 2586, 2590, 2627-2634, 2695, 2700, 2786, 2803-2804, 2826, 2834, 2875-2882, 2891-2898, 2901-2904, 2954-2955, 2960-2982, 2991-2993, 2997, 3015, 3019, 3036, 3055, 3087, 3091, …
```
=> Increase test coverage

.travis.yml
It is important to reduce sizes of log files for using CI tools. This PR suppresses warnings in order to prevent the sizes from growing larger than necessary. After CNTK is added, log files include too many warnings about type conversion of float64<->32 (less meaningful). In case of [the latest log](https://travis-ci.org/fchollet/keras/jobs/264198585), there are 997 warnings which results in a heavy log file (2.6MB). Before CNTK is added, the sizes were usually 700-800KB.
=> Suppress warnings of CNTK

keras/applications/imagenet_utils.py
My previous PR (https://github.com/fchollet/keras/pull/7568) contains a small error. The if statements for the warning should have been `AND` and not or. It's currently printing the warning every time regardless of channel. 
@fchollet I apologize for the trouble but just wanted to fix this warning issue.
=> Fix warning in _obtain_input_shape

keras/engine/topology.py, tests/test_model_saving.py
This fixes #7164 by ignoring (in `get_config`) input and output layers that are not used by the model. This is consistent with the behavior we use for intermediary layers.
I also tried improving the readability of this part of the code (second commit) that makes no semantic change.
=> Fixed #7164 -- Irrelevant layers are not saved.

keras/utils/io_utils.py
Right now HDF5Matrix's raise an index error when a np.int64 number is used to index them (such as from np.arange). In contrast normal numpy array can handle this situation. This PR fixes that by also checking for numpy integer types.
=> HDF5Matrix can handle np.int64 indexing

setup.py
Hello everyone,
As you may find on PyPI: <https://pypi.python.org/pypi/keras/json>, keras is reported with an empty list of classifiers which can cause a lot of problems to anyone using the PyPI API to retrieve information about Keras (e.g. most CI tools).
This PR was made to declare the missing classifiers.
```python
######################## Old Version ########################
"classifiers": [
]
######################## New Version ########################
classifiers=[
"Development Status :: 4 - Beta",
'Intended Audience :: Developers',
'Intended Audience :: Education',
'Intended Audience :: Science/Research',
'License :: OSI Approved :: Apache Software License',
'Programming Language :: Python :: 2',
'Programming Language :: Python :: 2.7',
'Programming Language :: Python :: 3', …
```
=> Setup.py missing classifiers fixed. Now announce Py2 and Py3 compatibility

examples/variational_autoencoder.py, examples/variational_autoencoder_deconv.py
Copying almost verbatim from PR https://github.com/fchollet/keras/pull/7036 which addressed the issue without solving it.
Currently the Variational Autoencoder examples at `examples/variational_autoencoder.py` and `examples/variational_autoencoder_deconv.py` fail when the training set size is not a multiple of the batch size (related to #5255, and in a way to #3332).
This PR allows to use any batch size by computing the batch size in the `sampling` function at runtime.
Bug reproducibility steps:
- change the batch size (`examples/variational_autoencoder.py` at line 15 and `examples/variational_autoencoder_deconv.py` at line 24) to something that doesn't divide mnist train set size, for instance 51
- run `examples/variational_autoencoder.py` or `examples/variational_autoencoder_deconv.py`
=> Remove requirement that batch_size divides len(x_train) in Variational Autoencoder examples.

examples/image_ocr.py
=> fix image_ocr example steps_per_epoch and validation_steps params

examples/README.md
Added descriptions for `mnist_tfrecord.py` and `reuters_mlp_relu_vs_selu.py` to the README.
=> Updated examples/README.md

keras/layers/recurrent.py, tests/keras/layers/recurrent_test.py, tests/test_model_saving.py
Hi. I'm submitting a PR for a bug reported in #7612. 
I think the Recurrent layer should treat a part of the inputs as `initial_states`. I think this is also what you want to do according to the API doc. If you have a different design, please suggest.
=> Recurrent layer to treat 2nd and the rest of inputs as initial_states

examples/variational_autoencoder.py, examples/variational_autoencoder_deconv.py
We are getting error "ValueError: The model expects 0 input arrays, but only received one array." by passing x and y data as validation_data. As we haven't used y in computing loss. So, changing value of y to None in validation_data.
=> Change in variational autoencoder example to resolve issue #6373 

keras/engine/training.py
Previously:
```python
loss = model.evaluate(None, None, steps=steps)
```
After this CL:
```python
loss = model.evaluate(steps=steps)
```
Fixes #7757 (verified by @athundt ).
=> Framework-native tensor API improvement for evaluate, fixes #7757.

keras/wrappers/scikit_learn.py
KerasRegressor score function returns the loss (that one would like aim to minimise) and not a score (that one would like to maximise).
For instance, if you use it with gridsearchCV it would select the worst model instead of the best.
=> fix KerasRegressor score function

keras/models.py
This shall fix an documentation unclarity for the fit/fit_generator functions.
Currently it can be misunderstood that the parameter epochs is not the final epochs, but rather the difference between initial_epoch and the final_epoch.
I stumbled upon this problem for several times and now wish to fix it.
See https://github.com/fchollet/keras/issues/7804 for details.
=> docstring fix for fit / fit_generator

keras/layers/merge.py, tests/keras/layers/merge_test.py
Similar to the existing Maximum merge layer, this new layer takes a list of tensors and returns the element-wise minimum of the inputs.
=> Add minimum merge layer

keras/backend/cntk_backend.py
CNTK scalar constants need `shape=(1)` => https://docs.microsoft.com/en-us/cognitive-toolkit/Parameters-And-Constants
Was getting an error when calling
```
K.set_learning_phase(0)
```
=> Fixes set_learning_phase in CNTK

docs/templates/applications.md
- Model size was calculated by checking the file size in my `~/.keras/models/` directory
- top-1 and top-5 accuracy was found on Google from a variety of sources
- Parameters was determined using the Keras `summary()` function
- Depth was determined using the Keras `layers_by_depth` function
=> Added model comparision table

docs/templates/applications.md, docs/templates/getting-started/faq.md, keras/applications/__init__.py, keras/applications/inception_resnet_v2.py, tests/keras/applications/applications_test.py
Adds the Inception-ResNet v2 architecture to the application module, with weights extracted and converted from the [TF-slim implementation](https://github.com/tensorflow/models/tree/master/slim#pre-trained-models).
Brief summary:
- Add `keras.applications.inception_resnet_v2.InceptionResNetV2()`
- Update test for applications
- Update docs for applications
Possible issues:
1. Model weights: right now the .h5 weight files are in my own public repo.
Once the model is included into Keras, I think it's better to move the weight files here.
Is there any suggested way to do it?
2. Layer naming:
Layer naming follows TF-slim because it's easier to debug when converting the weights.
But it's not that critical once the code and weight files are included into Keras.
Right now the solution is not so …
=> Add Inception-ResNet v2 to application

examples/cifar10_cnn.py, keras/preprocessing/image.py, keras/utils/data_utils.py, tests/keras/preprocessing/image_test.py
=> Refactor image preprocessing iterators to subclass Sequence.

keras/preprocessing/image.py, tests/keras/preprocessing/image_test.py
The filenames yielded by the `DirectoryIterator` are in arbitrary order because it uses `os.walk` (which uses `os.listdir` under the hood. The docs for `os.listdir` mention that the filenames are ordered arbitrarily: https://docs.python.org/3/library/os.html#os.listdir .  On Mac OSX, the filenames seem to be sorted lexicographically, but on Ubuntu 17.04 with ext4 filesystem, they seem to be given in an arbitary, non-lexicographic order.
The Keras docs give an example of combining images with masks using `flow_from_directory`, which requires that the files be sorted: https://keras.io/preprocessing/image/ . This fix is important for that to work on all systems.
Fixes #6418
=> Sort files in DirectoryIterator because os.walk orders them arbitrarily

keras/utils/io_utils.py, tests/keras/utils/io_utils_test.py
There was a bug in the `__getitem__` method of `HDF5Matrix` class in keras/utils/io_utils.py (currently line 70) in which `stop` was set to `self.data.shape[0]`. This means that `stop` was be set to the total number of elements in the file rather than the artificial stopping point specified by `end`. This results in an IndexError when fitting a model with a validation_split. 
See https://github.com/fchollet/keras/issues/7862
The problem was solved by setting `stop` to `self.shape[0]` rather than `self.data.shape[0]`.
I could add a unit test for this, but it wasn't clear whether they should go in `test_model_methds` found in keras/tests/keras/engine/test_training.py or `test_io_utils` found in tests/keras/utils/io_utils_test.py.
Maybe it's worth merging the tests found in `test_io_utils` …
=> Fix HDF5Matrix.__getitem__ for validation_split

examples/pretrained_word_embeddings.py
When a corpus has less than MAX_NB_WORDS, num_words will be set to len(word_index) . However, since the index is zero based it causes an IndexError. eg. When there are 57 total words in the corpus you get the error 'IndexError: index 57 is out of bounds for axis 0 with size 57' since the index should stop at 56 (zero based).
=> IndexError fix

docker/Dockerfile, docker/Makefile
**Background**
[Current version of Tensorflow](https://github.com/tensorflow/tensorflow/blob/r1.3/RELEASE.md) prebuilt binaries have been built with cuDNN 6. So it does not work with a docker container image based on nvidia/cuda:8.0-cudnn5-devel and it causes the following error.
```
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory
```
[Current version of CNTK](https://docs.microsoft.com/en-us/cognitive-toolkit/ReleaseNotes/CNTK_2_1_Release_Notes) supports cuDNN 6. However [Current version of Theano](http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html#libdoc-cuda-dnn) does not support cuDNN 6 officially.
Different backends require a different version of cuDNN.
**Changes**
For flexibility, make CUDA, cuDNN and Python version of a …
=> Update dockerfile to be able to change versions of dependencies.

docker/Dockerfile, docker/Makefile
I had to make a few tweaks to the Keras Docker image to get it up and running. 
* Upgraded cuDNN5 to cuDNN6 following [Tensorflow's example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.gpu#L1). 
* Changed the workspace directory to be able to `import keras`. This fixes #6750.
* Added `SRC` as a configurable parameter in the Makefile to be able to use something like `make notebook GPU=0 BACKEND=tensorflow DATA=~/project/foo/data SRC=~/project/foo`
Before these tweaks I got `libcudnn.so.6: cannot open shared object file: No such file or directory`
After the edits, I was able to run `make test` with the following results:
```
E ValueError: Unexpectedly found an instance of type `<class 'theano.gpuarray.type.GpuArraySharedVariable'>`. Expected a …
```
=> Update Docker to cudnn6 and fix src mapping

keras/utils/layer_utils.py
When sharing iPython notebooks on GitHub (the primary way folks share their work) either as a [gist](https://gist.github.com/rjpower/eacf87bafbf8a21b09a42bdab5ca2e23) or as part of a regular [repository](https://github.com/adammenges/ml-muse/blob/master/yolo/yolov2.ipynb), `model.summary()` looks slightly off. It's consistently two characters too long (see screenshot above), with the default page size, giving ourselves as much room as possible and going full screen. We tested it on a 12" Macbook, 15" linux machine, and a 27" iMac.
Down to improve this anyway folks see fit, looking forward to the feedback.
=> Improve line length to better accommodate sharing notebooks

examples/image_ocr.py
The model used the input-shape (c,w,h) or (w,h,c) (w=width, h=height, c=channel). However, keras defines the shape as (c,h,w) or (h,w,c).
So basically rows and cols were flipped. 
This is not a problem, if the model is used by itself. But if you want to use it elsewhere, like convert it into the CoreML model format, then the input parameters are flipped. This commit fixes the „orientation“ of the input.
=> Fix input shape of OCR model

docs/templates/applications.md, keras/applications/inception_resnet_v2.py, tests/keras/applications/applications_test.py
With #7910 and #7907 applied, `InceptionResNetV2` now gives correct results for CNTK backend (the errors in #7753 and #7910 do not occur anymore after #7907 is applied). This PR unlocks the model and the related tests for CNTK backend.
=> Unlock InceptionResNetV2 for CNTK

keras/losses.py
This PR resolves #7954.
Currently cosine proximity is scaled down by `y_pred.shape[-1]` because it uses `K.mean(..., axis=-1)`. That is, if the final layer is `Dense(100)`, the cosine proximity will be divided by 100, and the range is restricted to `[-0.01, 0.01]` instead of `[-1, 1]`. Changing from `K.mean()` to `K.sum()` solves the problem.
=> Use sum instead of mean in cosine_proximity

keras/backend/theano_backend.py, tests/keras/layers/recurrent_test.py
Unbroadcasting batch size dimension is important when batch size is 1. In this case initial state of recurrent layer (LSTM, GRU) is broadcasting to row vector which leads to error: 
> Inconsistency in the inner graph of scan 'scan_fn' : an input and an output are associated with the same recurrent state and should have the same type but have type 'GpuArrayType<None>(float32, row)' and 'GpuArrayType<None>(float32, matrix)' respectively.
keras v2.0.8
theano v0.10.0b3+9.g4552f38 (dev)
=> Unbroadcast batch size dimension in Theano backend

keras/engine/topology.py
`model.layers.Input`'s constructor has a default parameter `dtype=K.floatx()`. This just calls `K.floatx()` when Keras is first imported, instead of calling `K.floatx()` at construction time. This is problematic because users call `K.set_floatx(...)` after importing Keras.
Resolves #7951
=> Fix Input dtype default value to be assigned during function call

keras/layers/core.py, tests/keras/layers/core_test.py
The current implementation of `keras.layers.Reshape` does not allow the reshaping of tensors of unknown shape (ie. `(None, None, 3)` for any arbitrary image). Strangely enough, the underlying code of `tensorflow.reshape` does allow this kind of reshape (and already handles `-1` in the target shape), I'm not sure about other backends.
**Motivation**
The following code shows what this PR fixes:
```
import keras
inputs = keras.layers.Input((None, None, 3))
outputs = keras.layers.Reshape((-1, 1))(inputs)
model = keras.models.Model(inputs=inputs, outputs=outputs)
print("Success!")
```
Without this PR the result is:
```
Using TensorFlow backend.
File "test.py", line 4, in <module>
outputs = keras.layers.Reshape((-1, 1))(inputs)
File …
```
=> Allow to reshape unknown tensors.

keras/layers/core.py
Issue 7224 in tensorflow
Dropout didn't have support for dynamic noise_shape inference and batch size had to be a fixed number which was breaking the model after save/loading. 
Now it's possible to write noise_shape=(None, 1, None) for instance. In this example Dropout will infer the first dimension (the batch size) dynamically (and also the last dimension).
=> Added support for dynamic noise_shape in Dropout

keras/backend/cntk_backend.py, keras/backend/tensorflow_backend.py, keras/backend/theano_backend.py, tests/keras/backend/backend_test.py
As of now, K.switch supports only scalar condition on TF backend. This PR makes TF backend's switch function behave more like Theano's switch; with element-wise selection and broadcasting when required.
* If rank of `condition` == 0 (scalar), call `tf.cond` like before
* If rank of `condition` == 1, call `tf.where`
* If rank of `condition` > 1, make sure shape of `condition` is same as that of the expressions by applying `expand_dims` and `tile` ops; then call `tf.where`
=> Improve TF backend's Switch function

keras/models.py
fixes #8016
Just add `shuffle` to the Model API
=> Add shuffle to the Model API

examples/README.md
File was removed in https://github.com/fchollet/keras/pull/7943
=> Remove lstm_benchmark from examples/README.md

keras/utils/layer_utils.py
As of now, the following model is being considered as a "Sequential-like":
```python
a = Input((5,))
dense = Dense(5)
b = dense(a)
c = dense(b)
model = Model(a, c)
model.summary()
```
=> Bug fix: Models with shared layers shouldn't be considered Sequential like

examples/mnist_siamese_graph.py
1. Enable accuracy reporting during training.
2. Simplify compute_accuracy()
=> Enable accuracy reporting during training in examples/mnist_siamese_graph.py

keras/utils/data_utils.py, tests/keras/utils/data_utils_test.py
During the initial implementation of Sequence, there have been some issues when using large objects inside of the Sequence like a list of paths. This PR solves these issues by caching the Sequence in each process instead of copying it everytime we need it. Between epochs, we update the Sequence since it may get modified by the `on_epoch_end`.
I could have done it in a simpler way by direction accessing `self.pool._processes`, but it would be accessing a private member.
Example :  
Let's say that we keep a list `x` inside a Sequence where `x = [('abc', 512)] * 100000`.
```
Old way : 1.8216075897216797 seconds
New way : 0.22916626930236816 seconds
```
=> Faster sequence

keras/backend/tensorflow_backend.py
Tensorflow (at least versions 1.3 and below) does not support `NCHW` computations of many ops when run on the CPU. That creates compatibility issues. These are originally mitigated in Keras, by doing a "NHWC roundtrip" and any op requested to be ran in "`channels_first`" (`NCHW`) would actually be transposed to- and from-  `NHWC`.
`NCHW` often has performance benefits; for example, cuDNN is often fastest when the largest dimension is last (favouring `NCHW` for images).
The current implementation probes if NCHW is available by checking:
1. Whether `NCHW` (`channels_first`) is requested at all
2. If `NCHW` is supported by checking (1) if a GPU is available at all and (2) if it is not explicitly set on CPU.
If the op is set explicitly on the CPU, or there is no GPU device, and if NCHW is …
=> WIP: Support NCHW (for conv2d).

keras/utils/data_utils.py, tests/keras/utils/data_utils_test.py
Reverts fchollet/keras#8039
@fchollet 
Just to go back to a stable state till we figure something out and I improve test coverage in this highly sensitive area.
=> Revert "Faster sequence"

keras/engine/training.py
Fix off-by-one bug in predict/evaluate progress bar
```
Before:
0/1 [..............................] - ETA: 0s
0/1 [..............................] - ETA: 0s
After:
1/1 [==============================] - ETA: 0s
1/1 [==============================] - ETA: 0s
```
Also sync (make identical) portions of the code in _predict_loop() and _test_loop()
=> Fix off-by-one bug in predict/evaluate progress bar

keras/models.py
...to sync it with that of Model.fit_generator(), which was there first, and modifying it would be an API change. shuffle was added to Sequential.fit_generator() only 7 days ago in https://github.com/fchollet/keras/pull/8023. The discrepancy was pointed out in https://github.com/fchollet/keras/pull/8023#discussion_r142943710
=> Change default value of shuffle parameter of Sequential.fit_generator() from True to False

keras/preprocessing/image.py, tests/keras/preprocessing/image_test.py
Otherwise, nearest neighbor interpolation is used, which produces awful results. I consider this as a bug. In any case, the old behavior can be recovered using ``load_img(..., resample=PIL.Image.NEAREST)``.
=> Add option to specify resampling method in load_img

docs/templates/constraints.md
The current code doesn't work since `maxnorm` doesn't match called name `max_norm` in the next line.
=> Fix code snippet

keras/utils/generic_utils.py
```
Before:
- 2s
After:
19600/Unknown - 2s
```
Also fixes unbounded growth of Progbar.total_width when target==None as described in https://github.com/fchollet/keras/pull/8076
```
Before:
^M - 0s
^H^H^H^H^H^M - 0s
^H^H^H^H^H^H^H^H^H^H^M - 0s
^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^M - 0s
After:
^M - 0s
^H^H^H^H^H^M - 0s
^H^H^H^H^H^M - 0s
^H^H^H^H^H^M - 0s
```
=> Print current iteration even if target is unknown

examples/README.md, examples/lstm_stateful.py
- rename file to `lstm_stateful.py` so it shows up together with the other `lstm_*.py` example files
- fix input average: the existing code is not doing any averaging because `cos[i + 1:i + lahead + 1]` is just one point. I think the purpose was for it to be a 2-point average.
- aesthetic progress fix: the progress message was 0-based, i.e. first message was `Epoch 0 / 25`.
=> Fixes to example/stateful_lstm.py

keras/callbacks.py, tests/keras/test_callbacks.py
`self.wait` should be incremented before the comparison with `self.patience`, as this comparison is made after the end of an epoch. I noticed the bug in this [StackOverflow question](https://stackoverflow.com/questions/46656948/earlystopping-callback-behaving-mysteriously-in-keras) and the test case I added is derived from that example.
=> Fix off-by-one error in EarlyStopping callback

examples/mnist_net2net.py
The style seems to be to just use range. In fact, this is the only place in the whole repository where xrange is used. With, clearly, no performance benefit for Python 2.
=> Replace xrange => range

examples/mnist_net2net.py, keras/backend/cntk_backend.py, keras/preprocessing/image.py, keras/utils/test_utils.py
Outside of tests/ directory "num_class" is used 10 times, "num_classes" is used 106 times. This makes it all consistent, and also fixes a docstring bug in test_util.get_test_data()
Inside tests/ directory, the score is 53:62 in favor of num_classes. I can do the renaming there as well, if there is interest.
=> Rename num_class => num_classes

keras/applications/inception_resnet_v2.py
This PR fixes TF-slim urls to follow recent updates in `tensorflow/models`.
=> Fix TF-slim urls

.travis.yml
To match [setup.py](https://github.com/fchollet/keras/blob/master/setup.py#L34).  There are a number of questions raised in #7297 about Python 3.6 support so let's test that version.
The Python 3.6 tests all pass.  Only one unrelated Python 2.7 test seems to be failing. 
* https://travis-ci.org/fchollet/keras/builds/288454466
=> Upgrade Travis testing from Python 3.5 to 3.6

examples/mnist_siamese.py
...and remove 4 hardcoded constants. This makes the code structure more logical. For example, after replacing mnist with cifar10 training still works (reaching 60% validation accuracy in 7 epochs), while before it was raising an exception.
=> Move Flatten layer into create_base_network()

keras/preprocessing/image.py
Hi,
I noticed that the abstract base class `keras.preprocessing.image.Iterator` was seemingly missing an abstract method definition for `_get_batches_of_transformed_samples` so I added it.
=> Add missing abstract method to keras.preprocessing.image.Iterator

keras/utils/data_utils.py, tests/keras/utils/data_utils_test.py
The GeneratorEnqueuer class is used by Keras to generate batches of data. Even though it's an internal class, it can be used for building fast training and prediction pipelines that do not use the *_generator() methods. One core assumption of the class is that the underlying generator must be able to produce infinite amount of data. This is useful when we perform training but can be limiting when we want to make predictions (especially when you combine Spark + Keras).
This PR extends GeneratorEnqueuer to handle finite generators and it was tested both with threads and processes. The main idea is that we catch the StopIteration which is raised when the underlying generator is exhausted and gracefully exit the thread. When we call get() on the enqueuer instead of sleeping directly when the …
=> Extending GeneratorEnqueuer to handle finite generators.

examples/mnist_net2net.py
examples/mnist_net2net.py was broken since transition to Keras-2, because filter layout changed, producing "AssertionError: weight and bias from same layer should have compatible shapes".
Also some of the validation losses had typos in them, made moot by the new validation losses, which are always stricter less than the old ones.
Resolves #5690, resolves #6539.
=> Fix examples/mnist_net2net.py for Keras 2

keras/callbacks.py, tests/keras/test_callbacks.py
Output from callbacks include epoch, but the epoch is index 0 format. It shows up when callbacks output information about the epoch.
Example:
```
Epoch 1/100
2300/2300 [==============================] - 462s - loss: 3.6914 - acc: 0.7710 - val_loss: 3.7383 - val_acc: 0.7681
Epoch 2/100
2300/2300 [==============================] - 457s - loss: 3.6921 - acc: 0.7709 - val_loss: 3.7442 - val_acc: 0.7677
Epoch 3/100
2299/2300 [============================>.] - ETA: 0s - loss: 3.6904 - acc: 0.7710
Epoch 00002: reducing learning rate to 9.999999747378752e-06.
```
Notice how the lr reduction is showing epoch 2 instead of the correct epoch 3.
The callback `ModelCheckpoint` will also save checkpoints with the correct epoch number in the filename.
=> Epoch is 0 indexed, add one to match from fit

keras/utils/generic_utils.py
When stdout is redirected to a pipe or a file, for example, `python examples/mnist_cnn.py |& less -U` the output is unreadable.
Before:
```
Epoch 1/12
^M  128/60000 [..............................] - ETA: 265s - loss: 2.3164 - acc: 0.0703^H^H
^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^M  768/60000 [
..............................] - ETA: 48s - loss: 2.1636 - acc: 0.2865 ^H^H^H^H^H^H^H^H^H
^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H
^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^M 1408/60000 [...............
...............] - ETA: 28s - loss: 1.9688 - acc: 0.3764^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H …
```
=> Output \b and \r only if stdout is a tty

keras/utils/training_utils.py
Just making the example in the comment runnable without errors. No functional changes.
=> Add missing imports in the multi_gpu_model() example.

keras/utils/data_utils.py, tests/keras/utils/data_utils_test.py
I spotted a race condition on my previous PR https://github.com/fchollet/keras/pull/8104. The problem affects only the case of finite generators and has no effect on the infinite ones. This PR fixes the bug and updates the test to capture similar problems. 
Please check the github comments on the code where I explain where the problem was and how I fixed it. Feedback is always welcome! :)
=> Fixing finite generator race condition

examples/mnist_acgan.py
Before:
```
Epoch 1 of 50
599/600 [============================>.] - ETA: 0s  
Testing for epoch 1:
```
After:
```
Epoch 1 of 50
600/600 [==============================] - ETA: 0s   
Testing for epoch 1:
```
Also, before, saved file had names: 
```
params_discriminator_epoch_000.hdf5
params_generator_epoch_000.hdf5
plot_epoch_000_generated.png
```
even though there is no "epoch 0".
=> Fix off-by-one display errors for batch and epoch

tests/keras/layers/cudnn_recurrent_test.py
Move `times = []` from the outer to the inner loop (because the speed-up is calculated for each inner loop)
Delete `clear_session()` which is redundant with `keras_test` (thus the outer loop should be transformed to `pytest.mark.parametrize`)
Reduce the example size under the 3x speed-up is satisfied (the sample size 10000 is too large)
=> Fix cuDNN tests

keras/legacy/layers.py
numpy is used at line 1090, but never imported
https://github.com/Danielhiversen/keras/blob/f7a150f035a2bd2a9fe419da3c2c3943fc7ed52f/keras/legacy/layers.py#L1090
=> Add missing numpy library

examples/babi_memnn.py
Turned out that renaming X=>x, etc, is easiest done by eliminating the variables altogether. Other simplifications are also included.
=> Simplify by using sparse_categorical_crossentropy

examples/lstm_text_generation.py, examples/mnist_acgan.py
All-cap identifiers are reserved for constants.
=> Rename X=>x to sync with the rest of codebase.

examples/lstm_text_generation.py
Without this change, running the lstm_text_generation.py example would cause me to get an input shape error when running the `.fit()` command during the second training iteration, since `x` had been overwritten with the text generation input in line 93.
=> Distinguish between x and x_pred in lstm text generation example to avoid overwriting training data

keras/backend/cntk_backend.py, keras/backend/tensorflow_backend.py
also use existing abstraction get_variable_shape(x), instead of using .shape attribute directly. Also improve docstrings.
I think this fixes a bug in TF backend, because int_shape(x) returns x.get_shape() only if x._keras_shape is not set, for example if x is np.ndarray, or a sparse tensor/ndarray.
=> Simplify and fix count_params()

keras/utils/generic_utils.py
This PR changes the ETA while training from printing only the number of seconds, to printing it in a more human readable format (ie. `ETA: 9:17:04` for 9 hours, 17 minutes and 4 seconds, as opposed to `ETA: 33424s`).
=> Add datetime formatting for ETA time.

keras/utils/data_utils.py
Rename random_seed => seed for consistency with the rest of the code. Maybe resolves https://github.com/fchollet/keras/issues/8227, although maybe GeneratorEnqueuer.seed should be eliminated altogether, because currently it's not used anywhere in Keras code.
=> Rename random_seed => seed

keras/utils/training_utils.py
* added _normalize_device_name function to training_utils.py --> convert "/device:GPU:0" to "/gpu:0"
* call _normalize_device_name() after obtaining available devices in multi_gpu_model() before verifying against target_devices.
* Successfully run tests in tests/keras/utils/multi_gpu_test.py
* Should work in both nightly and stable versions of tensorflow as all device names are shortened. 
Related Issues: 
fixes #8213  : converts all to "/xpu:0" representation  
fixes #8220  
fixes #8222   : This PR suggests converting to "/device:GPU:0" format for gpu and "/cpu:0" for cpu. 
Source: 
Uses code snippet suggested by @fchollet in https://github.com/fchollet/keras/pull/8222
=> Normalize device names in multi_gpu_model

docs/autogen.py, docs/templates/models/about-keras-models.md, keras/utils/__init__.py
This expose `utils.layer_utils.print_summary()` as `utils.print_summary()` and therefore document it, fixing #8105 .
This also fixes an issue with the `process_XXX_docstring` functions in `docs/autogen.py` which led to incorrect docstring formatting, making Arguments and Returns top-level markdown sections. The current doc on [keras.io](https://keras.io/models/sequential/#the-sequential-model-api) looks like this : 
This fixes it to look like this
=> Fix summary about models

keras/engine/topology.py, keras/engine/training.py, keras/utils/layer_utils.py, tests/keras/engine/test_training.py
This will raise a UserWarning when the user modifies model.trainable
and tries to print a model summary or launch a fit without having
called .compile.
Calling .compile() is necessary because trainable weights are collected
in compile (model._collected_trainable_weights).
Fixes #8121
=> Add a model.check_trainable_weights_consistency

examples/mnist_net2net.py
This PR contains no semantic changes.
1. Build teacher network only once. It's faster, clearer, produces less output.
2. Sync style and naming conventions with the rest of examples/
3. Remove unused and duplicated code.
4. Simplify and clarify logic, docs, output.
5. Remove usage of literals for epochs.
=> Simplify, clarify, sync style examples/mnist_net2net.py

docs/autogen.py
Current `post_process_signature` function generates broken signatures for some classes including a floating point in default argument such like [GRU](https://keras.io/layers/recurrent/#gru), [ELU](https://keras.io/layers/advanced-activations/#elu).
=> Fix post_process_signature for floating point

keras/backend/tensorflow_backend.py
Resolves https://github.com/fchollet/keras/issues/8232
Now in TF backend, `K.eye()` is consistent with `K.zeros()` and `K.ones()` (all returning Keras variable constructed from tf.Tensor), but still inconsistent with `K.zeros_like()` and `K.ones_like()` (returning raw `tf.Tensor`).
I didn't change `.eye()` in Theano and CNTK because `.zeros(), .ones(), .eye()` were already mutually consistent (all returning Keras variable constructed from `np.ndarray`), but inconsistent with `.zeros_like()` and `ones_like()` (returning `TH/CNTK Tensor`). 
TH/CNTK  `.zeros(), .ones(), .eye()`  (constructed from `np.ndarray`) are inconsistent with those of TF (constructed from `tf.Tensor`).
All this looks weird, but intentional.
=> Use tf.eye(), instead of np.eye()

keras/utils/data_utils.py
For example, if len(x) is 3 and the batch size is 2, 3//2 == 1 but there really is 2 batches.
=> Fix incorrect __len__ method in CIFAR10Sequence example

keras/backend/tensorflow_backend.py
Maybe _to_tensor() should be renamed and exposed (made public) as K.convert_to_tensor(), with API changed to match (will be backward compatible)?
=> Simplify _to_tensor(), reduce graph ops.

keras/preprocessing/image.py
Issue #8249 runs into a problem where the max hash size is low, resulting in files being potentially overwritten.
The behavior of this functionality is as such:
As batch size increases, the probability that any given file will have a conflict in the hash reduces. However, when the author wants to save images with a batch size of one, the probability of a conflict increases since {index} is always 1. This seems to just be an unforeseen bug because a batch size of one is uncommon.
=> Increase file save hash size

keras/datasets/cifar10.py, keras/datasets/cifar100.py
http://www.cs.toronto.edu server no longer accepts HTTP connections and requires HTTPS. Using cifar dataset then ends up with this error:
```
Exception: URL fetch failure on http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz: None -- Internal Server Error
```
This PR fixes the issue.
=> Cifar URL fixes

keras/layers/recurrent.py, tests/keras/layers/recurrent_test.py
Fixes `ValueError` for `LSTM(implementation=1, use_bias=False)` where the addition operation fails because `self.bias` is set to `None`.
Also added a test in `test_implementation_mode()` that fails before this fix and passes after this fix.
=> Fix ValueError for LSTM(implementation=1, use_bias=False)

keras/datasets/boston_housing.py
Those are the only two that have `test_split`. Syncing in that direction, because `boston_housing` is not referenced anywhere in Keras code, while `reuters` is. I think there was some discussion of datasets API in tensorflow, but can't find it now. Should `test_split` be renamed `validation_split` for consistency with the rest of codebase?
=> Sync parameter order in boston_housing with reuters

keras/datasets/boston_housing.py, keras/datasets/imdb.py, keras/datasets/reuters.py
This makes it more idiomatic, style synced with the rest of the codebase, shorter, faster.
=> Improve synchronized shuffle in datasets

keras/utils/data_utils.py
Remove duplicate logic, reduce line count, fix potential bug if reporthook is convertible to bool by checking "is not None" - i.e. what PR https://github.com/fchollet/keras/pull/8320 title promised, but didn't really do :-)
=> Simplify reporthook-related logic

keras/engine/topology.py, keras/layers/cudnn_recurrent.py, tests/keras/layers/cudnn_recurrent_test.py
This PR fixes a `ValueError` when trying to load weights from a `CuDNNLSTM` layer into an `LSTM` layer. Because `CuDNNLSTM` uses two biases, the size of `self.bias` is doubled comparing to that of an `LSTM` layer.
From the equations on the cuDNN user guide, by summing the two biases into one, the resulting bias term will be the same one used by `LSTM`.
However, there's no such relationship between `CuDNNGRU` and `GRU` (see the third equation in the image below, also from the cuDNN user guide). So this PR only deals with loading `CuDNNLSTM` weights.
Changes:
1. In `preprocess_weights_for_loading()`, check if we're loading `CuDNNLSTM` weights into `LSTM` by checking the shape of bias. If the size of bias is twice as large as `kernel.shape[1]`, then the weights are from an `CuDNNLSTM` layer. …
=> Enable loading CuDNNLSTM weights into an LSTM layer

keras/utils/generic_utils.py
#8171 checks to see if there is a tty available and if there is one update the same terminal line. This fixes when you wan't to pipe the output to a file for example. But it also breaks `fit` output in jupyter notebook. In jupyter you get a newline with a update.
This will add a check to see if `ipykernel` is loaded and output with `\b\r`. (Does not affect IPython)
=> Skip newlines in TTY AND ipykernel.

examples/mnist_acgan.py
It's compiled later as a part of the `combined` model. `generator` compilation is confusing and takes significant time.
=> mnist_acgan: generator.compile() has no effect. Remove.

examples/mnist_acgan.py
Generated image is a 10x10 grid. This cleanly separates `num_classes` (columns) and `num_rows`, while removing literal `100`.
=> Separate num_classes and num_rows

keras/backend/tensorflow_backend.py, tests/keras/backend/backend_test.py
Allow passing fetches to tf.Session.run() in K.Function() in TensorFlow backend.
- allow passing additional operations, such as StagingArea.put()
- previously (#6693) only options and run_metadata could have been passed
- note that providing `feed_dict` substitutions doesn't make much sense here since:
- they can be passed in the `input` argument
- if they're passes via kwargs in model.compile() the values would be constant
The main reason is to allow using TensorFlow StagingArea for copying input data to GPU asynchronously. A working implementation of such as pipeline is in [StagingAreaCallback](https://github.com/rossumai/keras-multi-gpu/blob/master/keras_tf_multigpu/callbacks.py#L10). [Several examples are provided](https://github.com/rossumai/keras-multi-gpu/tree/master/keras_tf_multig …
=> TensorFlow K.Function() additional ops via fetches

keras/engine/training.py
See issue #8381 - `count_params` is causing a terrible slowdown with Theano backend.
=> Replacing count_params() with len() in training.py

keras/backend/tensorflow_backend.py, keras/utils/training_utils.py
This PR tries to address the issues https://github.com/fchollet/keras/issues/8353, https://github.com/fchollet/keras/issues/8311 and https://github.com/fchollet/keras/issues/8374. Unfortunately they affect each other.
A recent PR https://github.com/fchollet/keras/pull/8021 added a check at the beginning of the [tensorflow_backend.py](https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L50) to determine the number of available GPUs. Unfortunately the `tensorflow.python.client.device_lib.list_local_devices()` method seems to create of a new TF Session and to register of all the available GPUs on the system. To resolve this I replace all the `device_lib.list_local_devices()` calls with `K.get_session().list_devices()`. 
Moreover on commit …
=> Remove unintended session initialization on TF backend

keras/utils/generic_utils.py
Add an attribute check for sys.stdout before using isatty().
In some cases, sys.stdout is replaced and may miss this attribute.
=> Fix attribute error for using isatty() by sys.stdout 

keras/datasets/cifar10.py
This makes it marginally faster, and avoids cache thrashing. 50,000*3*32*32=150 MBytes.
Also eliminates variables `data`, `labels`, which are not entirely consistent with the rest of the code, and makes logic marginally clearer (i.e. why initialize with zeros?, etc).
=> Load data directly into Nympy array

docs/templates/preprocessing/image.md
It wasn't 100% clear to me what "reflect" and "wrap" modes do exactly so I looked in scipy source for examples. The `fill_mode` is implemented using `NI_ExtendLine()` from [ni_support.c](https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/ni_support.c).
=> Added examples for fill_mode

keras/engine/training.py
The doc string is the negation of the code implementation.
=> Fix doc string for _check_trainable_weights_consistency()

examples/mnist_acgan.py
With TF 1.3 cudnn 6, this reduces time per epoch from 112 sec to 97 sec on Titan X Maxwell. This and `mnist_swwae.py` are the only examples which use `K.set_image_data_format()`
=> acgan: use default TF layout i.e. 'channels_first'

examples/mnist_acgan.py
Resolves https://github.com/fchollet/keras/issues/8373. Variability (within same epoch) is not as good as @lukedeo's https://github.com/lukedeo/keras-acgan/blob/master/acgan-analysis.ipynb
Greatest hits:
Epoch 13 =========================== Epoch 16
Epoch 40 =========================== Epoch 50
=> acgan: Fix generator producing pure black images

keras/preprocessing/image.py
Addresses: https://github.com/fchollet/keras/issues/8426
In versions prior to 2.0.9 there was no `interpolation` option so we always used the default interpolation mode of 'nearest'. With 2.0.9 `interpolation` can be specified however the default is `bilinear`, which can lead to subtly different results than in previous versions. This PR ensures that the image resizing behavior remains identical for code that doesn't specify an `interpolation` explicitly.
=> use 'nearest' rather than 'bilinear' as default interpolation method when resizing images

keras/engine/training.py, keras/losses.py, tests/keras/engine/test_training.py, tests/keras/losses_test.py
#8033 was rejected because the pinball loss function isn't widely used enough for the main keras package. Nevertheless, in order to use an externally provided class, the main keras package still needs to be able to serialise and deserialise it when saving and loading models. Currently `keras.losses.serialize` simply returns the name of the function, which doesn't allow saving any parameters or internal state.
=> Serialize loss functions with internal state using get_config

docs/autogen.py, keras/backend/cntk_backend.py, keras/backend/tensorflow_backend.py, tests/keras/backend/backend_test.py
and add `int_shape()` to tests. See https://github.com/fchollet/keras/issues/8230
Now `get_variable_shape()` is unused anywhere in Keras codebase, and could be removed. Leaving for backward compatibility only. In TF and CNTK, `get_variable_shape()` simply returns `int_shape()`.
=> Use int_shape() instead of get_variable_shape()

keras/engine/training.py, keras/models.py, tests/keras/test_callbacks.py
... and improve docstrings.
A couple of API changes, all backward compatible (additions and more permissive), except that now Model.fit(epoch=1) is the default (matching Sequential.fit(). I didn't find any example/*.py affected by this.
=>  Sync Sequential.fit() with Model.fit()

keras/models.py
Change default value verbose=1 to verbose=0 in `Sequential.predict_proba()` and `Sequential.predict_classes()` for consistency with `Sequential.predict()`, for which the same change was introduced in https://github.com/fchollet/keras/commit/f30223096eb2d16a65e0e99cb5c31b1f8dfe0980, but not for these two functions.
=> Change default value verbose=1 to verbose=0 for Sequential.predict_proba() and Sequential.predict_classes()

examples/mnist_tfrecord.py
the bug was there from the very first commit of the file.
=> Replace erroneous num_classes with batch_size in examples/mnist_tfrecord.py

keras/models.py
Very minor cleanup after https://github.com/fchollet/keras/pull/8233 and https://github.com/fchollet/keras/commit/d4a14ee54728ac8ea6c5ffbf41f559662dcfba46
=> Sync docstring of Model.fit() with Sequential.fit() iter2.

keras/engine/training.py
See https://stackoverflow.com/questions/46999519/keras-model-fit-unboundlocalerror
=> UnboundLocalError if input is a Dataframe

keras/engine/training.py, keras/preprocessing/image.py
It's 63 times faster on my box:
```
$ python -m timeit -s 'import numpy as np' 'int(np.ceil(10 / float(3)))'
1000000 loops, best of 3: 1.17 usec per loop
$ python -m timeit -s 'import numpy as np' '(10 + 3 - 1) // 3'
10000000 loops, best of 3: 0.0185 usec per loop
```
Also see https://github.com/fchollet/keras/pull/8284#issuecomment-343029412
=> Replace float ops with faster integer ops

keras/engine/training.py, tests/keras/engine/test_training.py
This PR will try to fix some pandas DataFrame related issues, including https://github.com/fchollet/keras/pull/8199 and https://github.com/fchollet/keras/pull/8290.
- Pandas DataFrame check is moved, in order to make sure that keras will check `array`/`list`/`dict` first, then `numpy.ndarray`/`pandas.DataFrame`.
- Add standalone `test_pandas_dataframe` unit test, covering `Model.fit`, `Model.predict`, `Model.predict_on_batch`, `Model.evaluate`, `Model.train_on_batch`, `Model.test_on_batch` functions, and `array`/`list`/`dict` inputs.
=> bug fix on pandas DataFrame support

keras/engine/training.py, keras/models.py, tests/keras/engine/test_training.py
`steps_per_epoch` forced to `len(generator)` causes problems to the logic of having less number of steps for special occasions, like [distributed training](https://github.com/uber/horovod/blob/master/examples/keras_mnist_advanced.py#L116), artificially smaller epochs (e.g. use 10% of data per "epoch" to get epoch-end callbacks called more frequently) or some other scenarios.
The `steps_per_epoch = len(generator)` rule was introduced by https://github.com/fchollet/keras/pull/8052, I propose that we roll it back.
=> Allow custom steps_per_epoch for sequences, default to len(generator) if unspecified

keras/utils/training_utils.py, tests/keras/utils/multi_gpu_test.py
This PR will try to add custom GPU ID support for `keras.utils.training_utils.multi_gpu_model`.
For example, such model will be trained at `/device:GPU:1` and `/device:GPU:3`.
```python
parallel_model = multi_gpu_model(model, gpus=[1, 3])
```
=> add custom gpu id support for multi_gpu_model

keras/utils/training_utils.py
This PR copies the names of the outputs to the multi_gpu_model output. This allows the use of loss dictionaries, where the name of the output is coupled with a loss function.
ps. I tried to do the same for the input, but it seems that `model.input_names` is not yet created at that time (it is created in the line with `outputs = model(inputs)`). Got any tips to fix this? My issue was with outputs, but it seems other people have the same problem with the inputs (https://github.com/fchollet/keras/issues/8339).
=> Copy name of outputs in multi_gpu_model.

docs/templates/scikit-learn-api.md, keras/wrappers/scikit_learn.py
Currently ``__call__ `` is not wrapped with backquotes, so on the webpage it's rendered in boldface (__call__).  A class that inherits `KerasClassifier` should implement `__call__()` instead of `call()`.
Also wraps all `build_fn` with backquotes.
=> Fix scikit-learn API docs

keras/engine/training.py
In response to [these](https://github.com/fchollet/keras/pull/8056#pullrequestreview-76745344) comments, this PR partly reverts the changes made in https://github.com/fchollet/keras/pull/8056 . That PR had the unintended side effect of forcing target blobs to have the same shape as output blobs for custom loss functions, which is currently frequently used as a workaround ([discussion](https://github.com/fchollet/keras/issues/7395)).
=> Allow custom losses to have mismatching target shapes.

keras/preprocessing/image.py
Hi! I was training Deep Feature Consistent Variational Autoencoder on CelebA and resized images had many artifacts. Unfortunately in DirectoryIterator there is call of load_img function with default argument and it is not parametrizable from outside.
My pull request introduces ability to change the interpolation method in two places.
=> Configurable interpolation in flow_from_directory

examples/mnist_dataset_api.py
This was the only example that relied on `from __future__ import division`. Removed. Also replace literal `128` with already existing named variable `batch_size`.
=> Sync style of calculating num_batches with rest of examples

keras/losses.py
Rely on softplus function to skip the calculus of exp(y_pred - y_true), thus preventing NaNs.
=> Improve numerical stability of logcosh

keras/engine/training.py, tests/test_multiprocessing.py
This PR enables callers of `fit_generator()`, `evaluate_generator()`, etc. to specify that they'd like the generator to be called on the main thread by passing `workers = 0`. 
The motivation is to enable use of code within generators that either requires or benefits from being on the main thread. Two concrete examples are:
1) Creating a generator that draws batches from a TF Dataset. There is an existing example of using Keras with TF datasets here (https://github.com/fchollet/keras/blob/master/examples/mnist_dataset_api.py) but it requires wiring the batch tensors directly into the graph and then saving/restoring weights for evaluation. Ideally we could write a generator like this for a dataset:
```python
def dataset_generator(dataset):
iter = dataset.make_one_shot_iterator()
batch = …
```
=>  Provide option to run generators on main thread

keras/engine/topology.py, tests/test_model_saving.py
Resolves #8541 by checking `len(weights)` before trying to do the conversion from `CuDNNLSTM` to `LSTM`.
Also added a test in test_model_saving.py for this case.
=> Fix loading LSTM weights without bias

examples/cifar10_resnet.py
... since it's reshaping to the current shape.  Also fixes a non-triggered latent bug (no effect is exactly what we want) actual changes would have had to be done with `transpose()`.
=> Remove reshape() which has no effect

keras/backend/tensorflow_backend.py
When using tensorflow as backend and the version of tensorflow is under r1.3, the list_devices() function is not available of Session instance. This may cause some issue like keras.utils.multi_gpu_model(model, gpus) function can not work under r1.3 of tensorflow. This change is a hack to fix that issue.
=> fix list_devices() function is not available issue
